### ISSUE TITLE
QUESTION: Username and search command do not work together.

### ISSUE THREAD

**Issue by sekmenli** [twintproject/twint#1006]
Version:
- [] Python version is 3.8.2;
- [] twint 2.1.20

### Command Ran

import twint
#configuration
config = twint.Config()
config.Username = "bbcturkce"
config.Search = "ekonomi"
#running search
twint.run.Search(config).

### Description of Issue
>Username and search command do not work together. I can only receive data by username. Or I can only get data with the search command. I cannot run both at the same time. When I run it I get the following error.
>No more data. finished scraping!! is it though? because sometimes twitter lie.

### Environment Details
>I am Using Windows.  This in Run  PyCarm.

**Comment by himanshudabas** [comment]
Please update your _twint_ installation using the following command:
```
pip3 install --user --upgrade git+https://github.com/twintproject/twint.git@origin/master#egg=twint
```

this problem has already been fixed.

**Comment by sekmenli** [comment]
> Please update your _twint_ installation using the following command:
> 
> ```
> pip3 install --user --upgrade git+https://github.com/twintproject/twint.git@origin/master#egg=twint
> ```
> 
> this problem has already been fixed [here](https://github.com/himanshudabas/twint/commit/b732fcbdd85b885d29ab0c28ecf3b6e2d42e0e2f).
> 
> Check #973, #947 for more info.

Thank You.

**Comment by himanshudabas** [comment]
If your problem is solved, please close this issue.
