### ISSUE TITLE
Set Lang to "en", but still got tweets in other language

### ISSUE THREAD

**Issue by yuqwang913** [twintproject/twint#1022]
# Issue Template
Please use this template!

### Initial Check
> If the issue is a request please specify that it is a request in the title (Example: [REQUEST] more features). If this is a question regarding 'twint' please specify that it's a question in the title (Example: [QUESTION] What is x?). Please **only** submit issues related to 'twint'. Thanks.

>Make sure you've checked the following:

- [] Python version is 3.6;
- [] Updated Twint with `pip3 install --user --upgrade -e git+https://github.com/twintproject/twint.git@origin/master#egg=twint`;
- [] I have searched the issues and there are no duplicates of this issue/question/request.

### Command Ran
>Please provide the _exact_ command ran including the username/search/code so I may reproduce the issue.

### Description of Issue
>Please use **as much detail as possible.**

### Environment Details
>Using Windows, Linux? What OS version? Running this in Anaconda? Jupyter Notebook? Terminal?

Hi. I have already set language to English like this:

import twint

c = twint.Config()
c.Search = "a"
c.Limit = 100
c.Store_csv = True
c.Output = "none.csv"
c.Lang = "en"

But the output still contained tweets in other languages
![image](https://user-images.githubusercontent.com/50217068/98603401-46295800-22e2-11eb-9b7f-0a4ce8f95851.png)

Could you please help me figure out what's the problem?

**Comment by himanshudabas** [comment]
Please search the existing issues before creating a new one.

#1015 is exactly the same issue as yours. Go through that thread once. Please close this issue, as it is a duplicate.
