### ISSUE TITLE
[QUESTION] How do you exclude replies? 

### ISSUE THREAD

**Issue by wed3** [twintproject/twint#1041]
I cant figure out how to exclude replies

**Comment by himanshudabas** [comment]
do something like this

from command-line
```
twint -s "from:realDonaldTrump -filter:replies" -o donal_filter_replies.csv --csv
```

or you can set
```
config.Search = "from:realDonaldTrump -filter:replies"
```
if you are using twint as a package in some other python script.

both should work fine.

**Comment by wed3** [comment]
thank you! this works perfectly!
