### ISSUE TITLE
[Bug] userlist command in CLI works only for one user?

### ISSUE THREAD

**Issue by teamdaemons** [twintproject/twint#1046]
Unable to get tweets of multiple users using the userlist command. It works for one user only. Kindly help

### Command Ran
twint --userlist user1,user2 --since 2020-11-01 -o file.csv --csv

### Description of Issue
Trying to get tweets from multiple users

- [YES] Python version is 3.6;
- [YES] Updated Twint with `pip3 install --user --upgrade -e git+https://github.com/twintproject/twint.git@origin/master#egg=twint`;
- [YES] I have searched the issues and there are no duplicates of this issue/question/request.

### Environment Details
macOS, Terminal

**Comment by himanshudabas** [comment]
Duplicate of #1012 
Patch in #1014

**Comment by teamdaemons** [comment]
Can i use the patch and check? I tried the changes from patch #1014 to see if it works and still doesnt work. Am I doing something wrong?

**Comment by himanshudabas** [comment]
You need to put the userlist in double quotes seperated by comma
```
twint --user-list "realDonaldTrump,elonmusk" -s "sad"
```
I think this should work

**Comment by teamdaemons** [comment]
Still doesnt work :( Here is what I have done. I have updated the changes from cli.py from the patch #1014 and then ran the command 
twint --userlist "realDonaldTrump" --since 2020-11-01 -o file.csv --csv
[!] No more data! Scraping will stop now.
found 0 deleted tweets in this search.
Still it fails. If i replace with just one user same command works.

**Comment by himanshudabas** [comment]
After making the changes did you uninstall and reinstall twint?
Perhaps you missed that?

**Comment by teamdaemons** [comment]
I just tried pip uninstall and install twint again. Then tried the same. Now it doesnt even work even for one user. This is frustrating. Am I doing something wrong here. 

twint --userlist "realDonaldTrump,elonmusk" --since 2020-11-01 -o file.csv --csv 
CRITICAL:root:twint.run:Twint:Feed:noDataExpecting value: line 1 column 1 (char 0)
sleeping for 15 secs
CRITICAL:root:twint.run:Twint:Feed:noDataExpecting value: line 1 column 1 (char 0)

**Comment by himanshudabas** [comment]
@teamdaemons 
what command did you use for reinstalling twint?
this looks like an old error to me, perhaps you are using the below command to install twint:
```
pip install twint
```

**Comment by teamdaemons** [comment]
> @teamdaemons
> what command did you use for reinstalling twint?
> this looks like an old error to me, perhaps you are using the below command to install twint:
> 
> ```
> pip install twint
> ```

Yes that is what I used.

**Comment by dixler** [comment]
also having this issue with a single user. I had installed via `pip install twint`

installing via git fixed the issue
`pipenv install 'git+https://github.com/twintproject/twint.git#egg=twint`

**Comment by himanshudabas** [comment]
@teamdaemons 
After you make changes to the cloned repo of twint, you need to install twint from there locally instead of using `pip install twint`, do the following:
1. Clone the latest repo from GitHub to your system.
2. Make the necessary changes in code.
3. Uninstall if there is a previous installation of twint.
4. Start you terminal and go the cloned repo directory which contains the `setup.py` file.
5. Now run this command `pip install -e .`

Now it should work for you.

**Comment by teamdaemons** [comment]
Thank you for the steps @himanshudabas Followed the steps and installed twint locally.
Regarding necessary changes in code. Could you please re-confirm if (twint/cli.py) it is the only change required for this to work?
https://github.com/twintproject/twint/pull/1014/files

Because still doesnt work
twint --userlist "realDonaldTrump,elonmusk" --since 2020-11-01 -o file.csv --csv
[!] No more data! Scraping will stop now.
found 0 deleted tweets in this search.

> also having this issue with a single user. I had installed via `pip install twint`
> 
> installing via git fixed the issue
> `pipenv install 'git+https://github.com/twintproject/twint.git#egg=twint`

So is it working for multiple users for you? Or are you saying that u are still facing the issue. I tried even this still no luck.

**Comment by himanshudabas** [comment]
@teamdaemons 
you can instead install from my [branch](https://github.com/himanshudabas/twint/tree/twint-fixes) using the following command:
 
**_Be sure to remove your previous twint installation before proceeding._**
```
pip3 install --user --upgrade git+https://github.com/himanshudabas/twint.git@origin/twint-fixes#egg=twint
```


_**Note**: this is an experimental branch and may contain a lot of new bugs, I usually use this branch for myself, but feel free to use it if it works for you._

**Comment by teamdaemons** [comment]
@himanshudabas thank you for sharing. I guess I have to just give up now:( .. Tried it as well and still doesnt work. I guess something i must be doing really wrong. maybe you could connect with me at teamdaemons@gmail.com to prevent to and fro to get your contact if you dont mind sharing your email.

**Comment by teamdaemons** [comment]
@himanshudabas Thanks a million for providing the solution offline. Posting here for others reference.
I was running in mac, using virtual env

Here are the steps that worked.
1. Create a fresh virtual environment.
2. Activate it.
3. git clone https://github.com/himanshudabas/twint.git
cd twint
git checkout twint-fixes
pip3 install -e .

Once above installations are done succesfully without any issues. Then the below command worked perfectly.
twint --userlist "realDonaldTrump,elonmusk" --since 2020-11-01 -o file.csv --csv
