### ISSUE TITLE
token.py is not included when pip3 install twint is used. 

### ISSUE THREAD

**Issue by mayankrichu** [twintproject/twint#1081]
# Issue Template
Please use this template!

### Initial Check
> I've installed twint using pip install twint, but it seems to be missing token.py file in my installed twint folder.

>Make sure you've checked the following:

- [] Python version is 3.6;
- [] Updated Twint with `pip3 install --user --upgrade -e git+https://github.com/twintproject/twint.git@origin/master#egg=twint`;
- [] I have searched the issues and there are no duplicates of this issue/question/request.

### Command Ran
>twint -u Myusername --following

### Description of Issue
>CRITICAL:root:twint.get:User:'NoneType' object is not subscriptable
CRITICAL:root:twint.feed:Follow:IndexError

### Environment Details
>Terminal

**Comment by rachmadaniHaryono** [comment]
> Updated Twint with pip3 install --user --upgrade -e git+https://github.com/twintproject/twint.git@origin/master#egg=twint

**Comment by mayankrichu** [comment]
I've already tried this and it doesn't seems to work.

**Comment by mayankrichu** [comment]
I tried using installing via GIT command, Token.py got installed. Now I'm able to retrieve tweets but unable to retrieve the followers and followings of a user.
