### ISSUE TITLE
[!] No more data! Scraping will stop now.

### ISSUE THREAD

**Issue by Vildnex** [twintproject/twint#1098]
When I'm running the following script

```
from datetime import datetime

import twint

output_file = "twint_database.csv"

config = twint.Config()
config.Search = "bitcoin btc bitcoinump #bitcoin #btc #bitcoinump"
config.Lang = "en"
config.Resume = output_file
config.Since = str(datetime(2009, 1, 3))
config.Until = str(datetime(2021, 1, 3))
config.Store_csv = True
config.Output = output_file
twint.run.Search(config)

```

I am receiving:

```
> [!] No more data! Scraping will stop now.
> found 0 deleted tweets in this search.
```

### Environment Details
Windows 10
and 
Manjaro

**Comment by innocentius** [comment]
Could you repeat the search by only using "bitcoin" as search term? If you see now result in this fashion, then maybe you actually don't get any result from this search...

**Comment by Vildnex** [comment]
But this line 
config.Search = "bitcoin btc bitcoinump #bitcoin #btc #bitcoinump"

Is not supposed to give me all the tweets with at least one of the following terms on it? For example, if a tweet contains "BTC" it should appear either way if it's not going to contain the rest of them. Or not?

**Comment by innocentius** [comment]
The search result twint gives would be the same search result as you search on twitter. I tried your search term and I couldn't find any.

**Comment by Vildnex** [comment]
Ok... Sorry about this, I think it's my confusion. But how can I search in this case for multiple terms? What is the correct why of writing?

**Comment by innocentius** [comment]
Well, I would try "bitcoin OR btc OR bitcoinump OR #bitcoin OR #btc OR #bitcoinump" first. Also, make sure to try to search on twitter yourself, it would help you get a sense of how to right queries as well.

**Comment by Vildnex** [comment]
Oh ok, I get it. Sorry for this misunderstanding.

Thanks :D
