### ISSUE TITLE
new feature: get full info of users , the same than for followers and followings

### ISSUE THREAD

**Issue by Nestor75** [twintproject/twint#123]
# Issue Template
Please use this template!

### Initial Check 
> If the issue is a request please specify that it is a request in the title (Example: [REQUEST] more features). If this is a question regarding 'twint' please specify that it's a question in the title (Example: [QUESTION] What is x?). Please **only** submit issues related to 'twint'. Thanks.

>Make sure you've checked the following:

- [x] Python version is 3.5 or higher.
- [x] Using the latest version of Twint.
- [x] I have searched the issues and there are no duplicates of this issue/question/request.

### Description of Issue

you can get full info from followers and followings of a user but you cannot get this info from the user itself. 
I have an option using the twitter api but I think your approach is better.

it could  be great if you can add an option to get the users info from a list
or maybe generate this info at the same time you get the tweets from a search and give also the user info of the users who tweet them

### Environment Details
>Using Windows, Linux? What OS version? Running this in Anaconda? Jupyter Notebook? Terminal?

**Comment by haccer** [comment]
These are great suggestions @Nestor75 !

**Comment by pielco11** [comment]
To get infos about a specific user:
`python3 Twint.py --username user1 --user-full`

To get infos about users mentioned or that target user replied to: (**requires database**)
`python3 Twint.py --username user1  --database users.db`
