### ISSUE TITLE
Picture or Video or Web Page or only Text

### ISSUE THREAD

**Issue by DavidPerea** [twintproject/twint#125]
It would be great to know that type of file attached there is to the tweet. That is, if in the tweet there is a photo or some video or some web page or nothing, it is only text.

Therefore, there are some new columns (photos / videos / web page) that have Boolean values ​​to know that they are attached to the tweet.

Could this update be possible? I did not know how to do it, but it would be very useful.

**Comment by haccer** [comment]
When there's a picture or video attached to the Tweet, in the text there's a link to it. Most often something like `pic.twitter.com/alsdjk`

**Comment by DavidPerea** [comment]
You're absolutely right. However, by this method there is no possibility to differentiate videos with images.

I do not know if there is another way of being able to indetify if it is video or picture. It may be a very difficult task. I get it. But I mention it in case there is such a possibility.

Anyway thank you very much.

**Comment by haccer** [comment]
I will consider adding this though, it's related to something else I've been wanting to add

**Comment by haccer** [comment]
Added in the dev branch, will move to master shortly
