### ISSUE TITLE
[REQUEST] Submit a Twitter URL as an input for search

### ISSUE THREAD

**Issue by hudmb** [twintproject/twint#127]
It would be really cool if you could simply enter a Twitter URL as search input, e.g. : -

[https://mobile.twitter.com/search?q=(bmw%20OR%20renault)%20filter%3Anews%20min_retweets%3A10&src=typd&f=live]

So that you can specify all the parameters within the search and Twint just has to go ahead and do the scraping part. E.g. with a -url command: -

`python3 twint.py -s -url [https://mobile.twitter.com/search?q=(bmw%20OR%20renault)%20filter%3Anews%20min_retweets%3A10&src=typd&f=live] -o file.csv --csv`

**Comment by haccer** [comment]
I don't really want to add this, seems a bit redundant.

Everything in the url (ie `(bmw%20OR%20renault)%20filter%3Anews%20min_retweets%3A10&src=typd&f=live`) can be included in the search (-s) option if needed and it'll get appended to the URL.
