### ISSUE TITLE
[QUESTION] How can i give custom index name while dumping output to ElasticSearch?

### ISSUE THREAD

**Issue by ganeshknr** [twintproject/twint#137]
I wanted to store the output into Elastic Search. I read all the documentation, apart from providing hostname for Elastic Search, i didn't find how to give custom index name while dumping data into Elastic Search. How can i provide?

**Comment by pielco11** [comment]
You have to edit the index name when you create the index, so when you are in `DevTools` and you copy&paste from `index-tweets.json` and others, change `twint` to what you prefer. You will have something like `PUT mycustomindex ...` 

Also you will have to edit `_index` in `twint/elasticsearch.py` 

I'll make this easier asap

**Comment by ganeshknr** [comment]
Thank you. 

Yeah, I think it will be better if we can provide through **command line** along with *elastic search host name*. If user doesn't give, the default can be used or else it can be overridden from command line.

**Comment by pielco11** [comment]
Sure, thank you for the hint!

**Comment by pielco11** [comment]
For the index of tweets `-it` or `--index-tweets`, for followers/following `-if` or `--index-follow` and for users profile `-iu` or `--index-users`.

If you user Twint as module:
```python
import twint
c = twint.Config()
Index_tweets = "..." # change
Index_follow = "..."  # values
Index_users = "..."  # here
...
```

About the `Elasticsearch hostname` you have just to change `-es` or `--elasticsearch` at your needs (e.g. `--elasticsearch myhostname.io:1234`) or using Twint as module `c.Elasticsearch = "myhostname.io:1234"`

**Comment by pielco11** [comment]
Ok now it should be fixed, there are default both for indexes name and essid (this one is an empty string)

Should be fixed, in case feel free to reopen and/or comment
