### ISSUE TITLE
Tor_Crawler Integration and user agent randomisation

### ISSUE THREAD

**Issue by cbjrobertson** [twintproject/twint#139]
@haccer, if you recall, I forked the project back in March when it was still a command line app and began the process of turning it into a module, see repo [here](https://github.com/cbjrobertson/pytweep). Since then, I'm happy to see that a lot of progress has been made on the package, and I'm wondering about integrating some of the things I did with the main package as it is now. The main innovation of my fork (apart from python module functionality which is now part of the twint anyway) was that it had was integrated with [Tor_Crawler](https://github.com/alex-miller-0/Tor_Crawler) so that it could route requests through tor and thereby periodically change the ip address from which an request appeared to be coming. It also randomised user agent headers to make it appear as though each request was coming from a different browser. This all because I was worried about getting blocked by twitter. I'm starting a new project now which will use twint, and I will be trying to integrate the same functionality with the master package as it stands now. I suppose my question is are these upgrades you'd be interested in integrating into twint?

Have you had any trouble getting blocked by twitter? I haven't yet but I'm worried that it might start to happen especially as the popularity of  the package increases.

**Comment by pielco11** [comment]
We did not have troubles, there are search limits imposed by Twitter: if Twitter gets too much requests from an IP address, it will stop returning search results so using a global "proxy" as Tor is not a really good idea. Anyway we have never ever reaced that limit while scraping big profiles

**Comment by cbjrobertson** [comment]
Sorry, perhaps I wasn't clear. Tor_Crawler reroutes request through a different ip address every n request, so it wouldn't function as a 'global proxy'.

**Comment by pielco11** [comment]
There are a lot of people using Tor to bypass censorship, which involves Twitter so it's reasonable to assume that there would be more requests from those IP address than your

Anyway feel free to suggest code that improves the project via PR (there would nice big code changes and discussing them in issue could be really hard) 

Ps: I'm not saying that adding Tor to route traffic is a bad idea, I also implemented that (with downsides that will be removed)

**Comment by cbjrobertson** [comment]
Hmmm. I suppose it depends on how many tor ips there are out there. Ok,
cool. I want to check with you active developers before making PRs for the
changes I was thinking of. Anyway, thanks.


Cole

**Comment by pielco11** [comment]
No problem, we are also here for that

A mandatory request is that Tor_Crawler does not change the `socket.socket` object, it that case users will not be able to index tweets and stuff to a local hosted Elasticsearch instance (I did not check this yet)

**Comment by cbjrobertson** [comment]
Hmmm. It may do. I added Tor_Crawler integration prior to elastisearch
integration.

Cole

**Comment by pielco11** [comment]
Found this [aiosocksy](https://github.com/romis2012/aiosocksy)

**Comment by hpiedcoq** [comment]
Why not simply use the torify command?

example : 
> torify python3 Twint.py -s "Vanilla OR chocolate" --csv --stats -o test.csv

works like a charm for me.
https://linux.die.net/man/1/torify

**Comment by pielco11** [comment]
@hpiedcoq there is no practical difference between using torify and setting up a "global proxy" (inside Twint)... but there is an issue with that, if one is connecting to a service that's binding on localhost (elasticsearch backend, for example), he/she will not be able to index since Twint will go through Tor to reach the destination

**Comment by pielco11** [comment]
### Example
![proxy](https://user-images.githubusercontent.com/17363750/45930946-a6c07400-bf66-11e8-8650-aaf9585a6516.png)

For custom configurations you have to specify all `c.Proxy...` options, if you want to use Tor just use `c.Proxy_host = "Tor"`
