### ISSUE TITLE
[REQUEST] Search by time interval

### ISSUE THREAD

**Issue by RicardoAlexandreMartins** [twintproject/twint#151]
If possible, it would be interesting a parameter to search by time (not date) interval.
For example: search all tweets containing the words "World Cup" in the last hour.

**Comment by pielco11** [comment]
Unfortunately it's not possible to search by time interval, so there will not be speed improvements... most probably there will be a "filtering out" feature

**Comment by pielco11** [comment]
Now as now I suggest to save the data somewhere, let it be a list, a json/csv file, whatsoever, and then operate on the saved data. Twitter does not allow searching for tweets in a specific time range, so some filtering by the user is required
