### ISSUE TITLE
Question - Filtering out replies? 

### ISSUE THREAD

**Issue by sidsathi** [twintproject/twint#156]
Is there a way to filter out tweets that replies to another tweet? I am looking to scrape original tweets if possible. 
Thank you for you help and awesome work!

**Comment by hudmb** [comment]
You can use this in your query string: -

-filter:replies

e.g.

"brexit -filter:replies"

**Comment by haccer** [comment]
If you're referring to a Twitter thread, I haven't found a way to completely collect that data properly.

If you're just trying to collect replies from a user, `--replies` (in the Dev branch for now) will do it.
