### ISSUE TITLE
issue in __init__.py

### ISSUE THREAD

**Issue by tiwaryshailesh** [twintproject/twint#161]
### Command Ran
python3 Twint.py -u xxxxxxxx --followers -o followersall-2.txt
Traceback (most recent call last):
  File "Twint.py", line 12, in <module>
    import twint
  File "/home/tiwaryshailesh/twint/twint/__init__.py", line 11, in <module>
    from . import run
  File "/home/tiwaryshailesh/twint/twint/run.py", line 9
    self.init = f"TWEET-{config.Resume}-0"
                                         ^

### Description of Issue
>Please use **as much detail as possible.**

### Environment Details
>Using Windows, Linux? What OS version? Running this in Anaconda? Jupyter Notebook? Terminal?

**Comment by haccer** [comment]
Hi @tiwaryshailesh,

are you running it with Python 3.6 ?

**Comment by tiwaryshailesh** [comment]
Yes. Thanks

**Comment by haccer** [comment]
@tiwaryshailesh is it working now? Can I close this?

**Comment by tiwaryshailesh** [comment]
Yes, Thanks a ton. Its working fine now
