### ISSUE TITLE
DependencyWarning: urllib3 (1.23) or chardet (3.0.4) doesn't match a supported version

### ISSUE THREAD

**Issue by hpiedcoq** [twintproject/twint#162]
# Issue Template
Hi, here's a little bug on the new version of Twint that I'm facing on my machine.

### Initial Check 

>Make sure you've checked the following:

- [] Python version is 3.5 or higher.
yep 3.6 installed
- [] Using the latest version of Twint.
Yep.
- [] I have searched the issues and there are no duplicates of this issue/question/request.
Also 

### Command Ran
>sudo pip3 install -r requirements.txt

gives the following result : no problem

### Description of Issue
Requirement already satisfied: aiohttp in /home/herve/.local/lib/python3.6/site-packages (from -r requirements.txt (line 1))
Requirement already satisfied: aiodns in /home/herve/.local/lib/python3.6/site-packages (from -r requirements.txt (line 2))
Requirement already satisfied: beautifulsoup4 in /home/herve/.local/lib/python3.6/site-packages (from -r requirements.txt (line 3))
Requirement already satisfied: cchardet in /home/herve/.local/lib/python3.6/site-packages (from -r requirements.txt (line 4))
Requirement already satisfied: elasticsearch in /home/herve/.local/lib/python3.6/site-packages (from -r requirements.txt (line 5))
Requirement already satisfied: pysocks in /home/herve/.local/lib/python3.6/site-packages (from -r requirements.txt (line 6))
Requirement already satisfied: pandas in /home/herve/.local/lib/python3.6/site-packages (from -r requirements.txt (line 7))
Requirement already satisfied: multidict<5.0,>=4.0 in /home/herve/.local/lib/python3.6/site-packages (from aiohttp->-r requirements.txt (line 1))
Requirement already satisfied: async-timeout<4.0,>=3.0 in /home/herve/.local/lib/python3.6/site-packages (from aiohttp->-r requirements.txt (line 1))
Requirement already satisfied: attrs>=17.3.0 in /home/herve/.local/lib/python3.6/site-packages (from aiohttp->-r requirements.txt (line 1))
Requirement already satisfied: idna-ssl>=1.0 in /home/herve/.local/lib/python3.6/site-packages (from aiohttp->-r requirements.txt (line 1))
Requirement already satisfied: yarl<2.0,>=1.0 in /home/herve/.local/lib/python3.6/site-packages (from aiohttp->-r requirements.txt (line 1))
Requirement already satisfied: chardet<4.0,>=2.0 in /home/herve/.local/lib/python3.6/site-packages (from aiohttp->-r requirements.txt (line 1))
Requirement already satisfied: pycares>=1.0.0 in /home/herve/.local/lib/python3.6/site-packages (from aiodns->-r requirements.txt (line 2))
Requirement already satisfied: urllib3>=1.21.1 in /home/herve/.local/lib/python3.6/site-packages (from elasticsearch->-r requirements.txt (line 5))
Requirement already satisfied: python-dateutil>=2.5.0 in /home/herve/.local/lib/python3.6/site-packages (from pandas->-r requirements.txt (line 7))
Requirement already satisfied: numpy>=1.9.0 in /home/herve/.local/lib/python3.6/site-packages (from pandas->-r requirements.txt (line 7))
Requirement already satisfied: pytz>=2011k in /home/herve/.local/lib/python3.6/site-packages (from pandas->-r requirements.txt (line 7))
Requirement already satisfied: idna>=2.0 in /home/herve/.local/lib/python3.6/site-packages (from idna-ssl>=1.0->aiohttp->-r requirements.txt (line 1))
Requirement already satisfied: six>=1.5 in /home/herve/.local/lib/python3.6/site-packages (from python-dateutil>=2.5.0->pandas->-r requirements.txt (line 7))

but when I start twint.py

**$ python3 twint.py -s hpiedcoq --csv -o test.csv**
**/usr/lib/python3/dist-packages/requests/__init__.py:80: RequestsDependencyWarning: urllib3 (1.23) or chardet (3.0.4) doesn't match a supported version!**
  RequestsDependencyWarning)
Traceback (most recent call last):
  File "twint.py", line 117, in <module>
    main()
  File "twint.py", line 114, in main
    twint.Search(c)
AttributeError: module 'twint' has no attribute 'Search'

### Environment Details
>Linux? Ubuntu 18.04 uptodate

**Comment by hpiedcoq** [comment]
Ok my bad. I had the old `twint.py` in the directory.

By invoking` Twint.py` it works but I still have the error

> /usr/lib/python3/dist-packages/requests/__init__.py:80: RequestsDependencyWarning: urllib3 (1.23) or chardet (3.0.4) doesn't match a supported version!
>   RequestsDependencyWarning)

**Comment by haccer** [comment]
That's a recent problem with requests it looks like: 
- [https://github.com/requests/requests/issues/4673(https://github.com/requests/requests/issues/4673)
- [https://bugs.archlinux.org/task/58878](https://bugs.archlinux.org/task/58878)

You probably need to update it again?
