### ISSUE TITLE
[Question] Searching within a Date Range (Python Module) 

### ISSUE THREAD

**Issue by saching6** [twintproject/twint#164]
### Initial Check 

>Make sure you've checked the following:

- [x] Python version is 3.6 or higher.
- [x] Using the latest version of Twint.
- [x] I have searched the issues and there are no duplicates of this issue/question/request.

### Command Ran
```python
since="2017-01-01"
until="2017-02-01"
search_str="Microsoft"

c = twint.Config()
c.Search = search_str
c.Since=since
c.Until=until
c.Lang='en'
c.Store_json =True
c.Stats=False
c.Custom = ["id", "date", "time", "timezone", "user_id", "username", "tweet", "replies", "retweets", "likes", "hashtags", "link", "retweet", "user_rt", "mentions"]
c.Output = "tweets_"+str(search_str)+'_'+str(since)+'_'+str(until)+".json"
```
### Description of Issue
Ran the above code for different months but interestingly only for months with 31 days it does not stop the search on the first day of the month (in the above case "2017-01-01") rather it starts going to December 2016. I don't face this problem with 30 day  months or February. This pattern makes me think there is a bug somewhere but I am unable to find it.  
### Environment Details
Anaconda on Linux (Windows 10 Linux subsystem)

**Comment by Nestor75** [comment]
Try using the parameter timedelta,  set it up to 2 for example and verify if it works or not

**Comment by saching6** [comment]
Can you explain the logic behind that? One more observation that I failed to mention in the last comment was that I for a 31-day month if I run the query without considering the last day for example  since=2017-08-01 and until=2017-08-30 the tweets dont overspill to the previous month.

**Comment by Nestor75** [comment]
If the query is very large result and you specify more than 30 days...  You won't get tweets for all the days but only for few days
 It's a known problem on twitter side.  If you use timedelta parameter to 2 you got all of them. 
It's just a test,  try it and see if using that parameter also helps you

**Comment by pielco11** [comment]
But `datecheck` func should work, will look into it

**Comment by pielco11** [comment]
Closing since is a known issue
