### ISSUE TITLE
How to search for tweets contain two neighbor words such as "burger king" and should I add quotation while searching about hashtags?

### ISSUE THREAD

**Issue by yemen2016** [twintproject/twint#165]
# Issue Template
Please use this template!

### Initial Check 
> If the issue is a request please specify that it is a request in the title (Example: [REQUEST] more features). If this is a question regarding 'twint' please specify that it's a question in the title (Example: [QUESTION] What is x?). Please **only** submit issues related to 'twint'. Thanks.

>Make sure you've checked the following:

- [] Python version is 3.5 or higher.
- [] Using the latest version of Twint.
- [] I have searched the issues and there are no duplicates of this issue/question/request.

### Command Ran
>Please provide the _exact_ command ran including the username/search/code so I may reproduce the issue.

### Description of Issue
>Please use **as much detail as possible.**

### Environment Details
>Using Windows, Linux? What OS version? Running this in Anaconda? Jupyter Notebook? Terminal?

**Comment by hudmb** [comment]
I use this ""burger king"" ie two double quotes.

**Comment by pielco11** [comment]
If you are interested in tweets containing "Burger" and "King" as keyword, add a `#hashtag`:
```python
import twint

c = twint.Config()
c.Search = "Burger King #Burger #King"
c.Hashtags = True
c.Format = "Tweet id: {id} | Hashtags: {hashtags} | Tweet: {tweet}"

twint.run.Search(c)
```

If you are interested in tweets containing "Burger" and "King" as keyword and you want to extract the hashtags:
```python
import twint

c = twint.Config()
c.Search = "Burger King"
c.Hashtags = True
c.Format = "Tweet id: {id} | Hashtags: {hashtags} | Tweet: {tweet}"

twint.run.Search(c)
```

So "normal" keywords as usual and "hashtags" keywords with a `#` before.

Using double quotes will rise errors, both cli and module, but yes that's how "specific phrase" to search works in Twitter. 
So if you are interested in tweets containing `"burger king"` and not `burger`and `king` around, just do:
```python
import twint

c = twint.Config()
c.Search = "\"Burger King\""
c.Hashtags = True
c.Format = "Tweet id: {id} | Hashtags: {hashtags} | Tweet: {tweet}"

twint.run.Search(c)
```

And for cli `python Twint.py --hashtags --search "\"Burger King\""`

**Comment by ManalBenchrif** [comment]
@pielco11 Thank you so much , i test the third script and it works for me .
Could you please explain difference between the 1st and  2nd script.
Thank youu!

![Search](https://user-images.githubusercontent.com/72361536/132871644-ffddef41-a610-4ced-93db-ade91f4ffc2a.PNG)
