### ISSUE TITLE
[REQUEST] Lowercase output for Author, Mentions and Hashtags

### ISSUE THREAD

**Issue by hudmb** [twintproject/twint#170]
Hi,

Would you be able to lowercase the outputs for: -

- Tweet Author
- Mentions
- Hashtags

The reason is that some people use hashtags using a mixture of case, e.g. #Brexit / #brexit / #BREXIT. Or they refer to people in tweets in the different ways, e.g. @ThisAccount / @thisaccount

When manipulating the data in e.g. Excel, it makes life just that bit harder and longer ;) So it would be great if you could include this or make it an option.

Thanks!

**Comment by pielco11** [comment]
In **dev** branch, not tested yet

**Comment by hudmb** [comment]
Thank you! A small change but a big difference ☺

**Comment by pielco11** [comment]
Works now, closing
