### ISSUE TITLE
Limits on twint.run.Profile

### ISSUE THREAD

**Issue by itstomrobinson** [twintproject/twint#175]
# Issue Template
Please use this template!

### Initial Check 
> If the issue is a request please specify that it is a request in the title (Example: [REQUEST] more features). If this is a question regarding 'twint' please specify that it's a question in the title (Example: [QUESTION] What is x?). Please **only** submit issues related to 'twint'. Thanks.

>Make sure you've checked the following:

- [x] Python version is 3.5 or higher.
- [x] Using the latest version of Twint.
- [x] I have searched the issues and there are no duplicates of this issue/question/request.

### Command Ran

import twint
c = twint.Config()
c.Username = "ferretscot"
c.Store_csv = True
c.Output = "ferretscot.csv"
twint.run.Profile(c)

***then***

import twint
c = twint.Config()
c.Username = "ferretscot"
c.Store_csv = True
c.Output = "ferretscot2.csv"
c.Profile_full = True
twint.run.Profile(c)

### Description of Issue
>Trying to get a comprehensive list of tweets and retweets for a given user. Twitters says example user given above has 7,292 tweets.

First command returns only 798 tweets and retweets (consistently). Earliest tweet returned is from 2017-10-07 (accounts first tweet was July 2013)

Second command is obviously much slower (30 minutes or so) but gets further back in time. However it also stops, this time at 2736 tweets, earliest tweet returned is from 2016-04-23.

Attempting to use Since and Until to collect earlier tweets than, for example, 2016-04-23, doesn't seem to work: it just begins returning data from present day.

### Environment Details
>MacOS High Sierra 10.13.5. Terminal. Python 3.6.5. pip twint module.

**Comment by haccer** [comment]
Hi @itstomrobinson,

I did some experimenting a while back and those are the timeline limitations imposed by Twitter. There isn't anything I can do about them, and I haven't figured out a way to bypass them... yet.

The limitations are:
- 1st option: ~25 requests
- 2nd option: ~160 requests.

I added a specification in the README.md in case someone has questions about this in the future.

**Comment by Konstantin555** [comment]
@haccer the 1st option does not work at all at the moment (windows 10, python 3.6). Tried it with several usernames.
![изображение](https://user-images.githubusercontent.com/13664826/57074908-df3ee200-6ced-11e9-96cc-98e41e64d439.png)

**Comment by pielco11** [comment]
Tried with a couple of users, it works

![immagine](https://user-images.githubusercontent.com/17363750/57091157-c98ae600-6d08-11e9-8eda-4595b38ef2c1.png)

![immagine](https://user-images.githubusercontent.com/17363750/57091214-f17a4980-6d08-11e9-95ed-071b73648e3a.png)
