### ISSUE TITLE
[REQUEST] RegEx matching

### ISSUE THREAD

**Issue by blatherdrift** [twintproject/twint#176]
Hello,

I'm trying to get this bad boy to scrape bitcoin addresses from twitter using a RegEx but I am a beginner in python. How about would I go about inserting this conditional variable into a search? 

/^[13][a-zA-Z0-9]{27,34}/

**Comment by pielco11** [comment]
You can't since Twitter search does not provide this feature. What you can do is scraping tweets and apply regular expressions to the content of tweets
