### ISSUE TITLE
How to extract followers and following of any user?

### ISSUE THREAD

**Issue by yemen2016** [twintproject/twint#182]
# Issue Template
Please use this template!

### Initial Check 
> If the issue is a request please specify that it is a request in the title (Example: [REQUEST] more features). If this is a question regarding 'twint' please specify that it's a question in the title (Example: [QUESTION] What is x?). Please **only** submit issues related to 'twint'. Thanks.

>Make sure you've checked the following:

- [] Python version is 3.5 or higher.
- [] Using the latest version of Twint.
- [] I have searched the issues and there are no duplicates of this issue/question/request.

### Command Ran
>Please provide the _exact_ command ran including the username/search/code so I may reproduce the issue.
I used this command from cmd command line:
python twint.py --followers "CNN" .......
It does not work with me. Please help.
### Description of Issue
>Please use **as much detail as possible.**

### Environment Details
>Using Windows, Linux? What OS version? Running this in Anaconda? Jupyter Notebook? Terminal?

**Comment by pielco11** [comment]
`Followers` is `boolean` and specifies that you are interested about the followers of a user, so you just need to specify what user you are addressing. Run `python twint.py -u cnn --followers`
