### ISSUE TITLE
[QUESTION] How to corectly get user info

### ISSUE THREAD

**Issue by nitanmarcel** [twintproject/twint#184]
I see in the documentation that there's a User_full option to show all of the user info. And I'm using the next code but all I get are all of the users tweets and not the profile info. Did I understand everything wrong or I'm doing something wrong?

```
def twit():
    loop = asyncio.new_event_loop()
    asyncio.set_event_loop(loop)
    c = twint.Config()
    c.Username = "banana"
    c.User_full = True
    res = twint.run.Search(c)
    print(res)
    loop.close()
```

Also, there's a way to output the info in json format in the console?
Thanks!

**Comment by pielco11** [comment]
Duplicate #123
