### ISSUE TITLE
verbose.py runs into config not defined

### ISSUE THREAD

**Issue by sshum00** [twintproject/twint#186]
# Issue Template
Please use this template!

### Initial Check 
> If the issue is a request please specify that it is a request in the title (Example: [REQUEST] more features). If this is a question regarding 'twint' please specify that it's a question in the title (Example: [QUESTION] What is x?). Please **only** submit issues related to 'twint'. Thanks.

>Make sure you've checked the following:

- [] Python version is 3.5 or higher.
- [] Using the latest version of Twint.
- [] I have searched the issues and there are no duplicates of this issue/question/request.

### Command Ran
>Please provide the _exact_ command ran including the username/search/code so I may reproduce the issue.

```import yaml
import twint
import threading
import asyncio
from datetime import datetime, timedelta

users = []
with open('config.yaml', 'r') as stream:
    users = yaml.load(stream)['Twitter_handles']

yesterday = datetime.strftime(datetime.now() - timedelta(1), '%Y-%m-%d')

def launch_query(c):
    asyncio.set_event_loop(asyncio.new_event_loop())
    twint.run.Search(c)


twint_array = []
for i in range(len(users)):
    c = twint.Config()
    c.Username = users[i]
    c.Timedelta = 2
    c.Count = True
    c.Store_json = True
    c.Output = '{}.json'.format(users[i])
    twint_array.append(c)

threads = []
for i in range(len(twint_array)):
    threads.append(threading.Thread(target=launch_query, args=(twint_array[i],)))

[t.start() for t in threads]
```

### Description of Issue
>Please use **as much detail as possible.**

Doesn't seem like config is defined within the scope of verbose.py

```Exception in thread Thread-34:
Traceback (most recent call last):
  File "/usr/lib64/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "run.py", line 16, in launch_query
    twint.run.Search(c)
  File "/opt/twint/env/lib/python3.7/site-packages/twint/run.py", line 137, in Search
    run(config)
  File "/opt/twint/env/lib/python3.7/site-packages/twint/run.py", line 117, in run
    get_event_loop().run_until_complete(Twint(config).main())
  File "/usr/lib64/python3.7/asyncio/base_events.py", line 568, in run_until_complete
    return future.result()
  File "/opt/twint/env/lib/python3.7/site-packages/twint/run.py", line 114, in main
    verbose.Count(self.count, self.config.Username)
  File "/opt/twint/env/lib/python3.7/site-packages/twint/verbose.py", line 3, in Count
    if config.Followers:
NameError: name 'config' is not defined
```

### Environment Details
>Using Windows, Linux? What OS version? Running this in Anaconda? Jupyter Notebook? Terminal?
CentOS, Python 3.7

**Comment by pielco11** [comment]
I tested and it works, in case feel free to reopen or report unexpected behavior

**Comment by mike-aungsan** [comment]
This bug came back >=1.1.4

**Comment by pielco11** [comment]
Are you using twint via pip? If so, try upgrading the package via git

If not, be sure to have updated your local repo

**Comment by mike-aungsan** [comment]
Yes I am using it via pip. Ok. Let me try.
