### ISSUE TITLE
[Question] Is it possible to have twint write only the new unique lines into the output file?

### ISSUE THREAD

**Issue by sshum00** [twintproject/twint#194]
# Issue Template
Please use this template!

### Initial Check 
> If the issue is a request please specify that it is a request in the title (Example: [REQUEST] more features). If this is a question regarding 'twint' please specify that it's a question in the title (Example: [QUESTION] What is x?). Please **only** submit issues related to 'twint'. Thanks.

>Make sure you've checked the following:

- [] Python version is 3.5 or higher.
- [] Using the latest version of Twint.
- [] I have searched the issues and there are no duplicates of this issue/question/request.

### Command Ran
>Please provide the _exact_ command ran including the username/search/code so I may reproduce the issue.

```
users = ['otojya', 'otsuichich']


while True:
    yesterday = datetime.strftime(datetime.now() - timedelta(1), '%Y-%m-%d')

    def launch_query(c):
        asyncio.set_event_loop(asyncio.new_event_loop())
        twint.run.Search(c)


    twint_array = []
    for i in range(len(users)):
        c = twint.Config()
        c.Username = users[i]
        c.Timedelta = 2
        c.Count = True
        c.Store_json = True
        c.Profile_full = True
        c.Since = yesterday
        c.Output = 'data/{}.json'.format(users[i])
        twint_array.append(c)

    threads = []
    for i in range(len(twint_array)):
        threads.append(threading.Thread(target=launch_query, args=(twint_array[i],)))

    [t.start() for t in threads]
    [t.join() for t in threads]
    for user in users:
        with open('data/{}.json'.format(user), 'r') as f:
            data = f.readlines()
        with open('data/{}.json'.format(user), 'w') as f:
            f.writelines(set(data))
    sleep(20)

```

### Description of Issue
>Please use **as much detail as possible.**

Right now I have a loop that continuously runs and pulls the date "yesterday", after it finishes getting the data it dedupes the lines in the file, and writes the chunk back into the file. Would it be possible to have twint only write new entries?

### Environment Details
>Using Windows, Linux? What OS version? Running this in Anaconda? Jupyter Notebook? Terminal?

Mac, Terminal

**Comment by sshum00** [comment]
Forgot to note that my solution doesn't actually work if tweets have interactions changes (likes, retweets, etc)

**Comment by pielco11** [comment]
Hi @sshum00,

thank you for the patience.

It seems not to be an issue with Twint, but we have a solution for it

To "automatically" save unique tweets you can store them into the db, the "do not write the same tweet twice" feature is bundle inside the database query

After the scraping session you can get unique data from tweets with this query `SELECT DISTINCT user_id,date,time,timezone,user,tweet,link FROM tweets` 

The fields between `DISTINCT` and `FROM` are the tweets' fields, the full list is available [here in the wiki](https://github.com/twintproject/twint/wiki/Module#custom-formating)

If you need some help don't hesitate to ask
