### ISSUE TITLE
[Question] Is the time zone taken from my PC location?

### ISSUE THREAD

**Issue by aslv95** [twintproject/twint#195]
Hi! When I use c.Since, I specify an exact date and time. Is this time taken with respect to my current location? Or, is it a standart US time? How can I change the time zone in my queries? Is the only way using a VPN? 

Thanks!

**Comment by haccer** [comment]
Hi @aslv95,

The timezone/time is taken from your PC location

**Comment by aslv95** [comment]
Hi @haccer ,

I appreciate your help! Then, I think there is a mismatch in the time. There are some tweets before the c.Since date. May I share the code and output here?

**Comment by aslv95** [comment]
@haccer  I mean, I specify c.Since = 2012-09-09. The earliest tweet in this case is on 09-09 at 09:59 Turkey Standard Time. But, if I say c.Since = 2012-09-08, I see that there are some tweets on 09-09 at 03:00 for example. 

There is around 10 hour difference between California and Turkey time, and the earliest tweet for me is at 09:59. Does this mean the following:
_c.Since date stands for the pacific time, and the output given to me is in my local time. So, 2012-09-09 is actually the time not for me. Instead it starts from 09-09 at 00:00 for the pacific time and gives an output time in my location which is 09:59?_ 

Thank you!

**Comment by aslv95** [comment]
PS: I have the following tweet from Twint:

2.45E+17 | 9/9/2012 | 22:56:20 | Turkey Standard Time | 1.1E+08 | FauxJohnMadden | "You guys want Kevin Kolb back?" -   Ken Whisenhunt to Andy Reid after Vick's pick six. | 1 | 161 | 14 |   |   | https://twitter.com/FauxJohnMadden/status/244886980872249345 | None |  
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --


It is at 22:56.

But on Twitter it seems like 12:56 pm. 

![image](https://user-images.githubusercontent.com/41928053/43613255-76f83d16-96b7-11e8-9452-db46d6ba635b.png)

So obviously, there is 10 hr difference and Twitter gives the tweet's local time instead of mine. The main problem is: Does c.Since start at:

1. My local time. 
2. US Twitter HQ local time (pacific)
3. the tweet's local time wherever it was sent

I think it may be the third option.

**Comment by pielco11** [comment]
It should be the Tweet's local time, so the timezone of the tweet is the same of the tweeter... and this could be a problem since that you don't have an absolute timezone

**Comment by aslv95** [comment]
Hi, 

Many thanks for the answer. I believe the answer is not correct again. Please see the following code:

```
c.Until = '2012-09-10'
c.Since = '2012-09-09'
c.Search = 'Ken Whisenhunt'
```
Here, the most recent tweet is at 2012-09-10 @4:57 pm (local tweeter time). Then it suddenly stops. However, if I make c.Until = '2012-09-11' then  I see on 2012-09-10 there are more tweets at like 5pm,6pm and so on.

I think there is a problem. Is it a problem with the Twint package, or is the time zone fixed to a certain place?

**Comment by aslv95** [comment]
No. It's not an error. Twitter takes the time as GMT

**Comment by pielco11** [comment]
It make sense now since GMT is CEST - 2
