### ISSUE TITLE
[QUESTION/REQUEST] Distinction Between Favorites/Likes and Normal Tweets/Retweets

### ISSUE THREAD

**Issue by nicolecheng** [twintproject/twint#196]
# Issue Template
Please use this template!

### Initial Check 
> If the issue is a request please specify that it is a request in the title (Example: [REQUEST] more features). If this is a question regarding 'twint' please specify that it's a question in the title (Example: [QUESTION] What is x?). Please **only** submit issues related to 'twint'. Thanks.

>Make sure you've checked the following:

- [x] Python version is 3.5 or higher.
- [x] Using the latest version of Twint.
- [x] I have searched the issues and there are no duplicates of this issue/question/request.

### Command Ran
python3.6 Twint.py -u liamcs98 --database databaseName.db --favorites

### Description of Issue
When using the --favorites tab, the user's "liked" posts get added to the tweets table, but there is no way to distinguish the difference between the posts that the user liked and what the user has retweeted or posted. Is there a field / flag that can distinguish between the types of tweets inserted? Can a "favorites" db table be created, thus separating favorited posts and "regular" posts?

### Environment Details
Tried in Linux and MacOS

**Comment by pielco11** [comment]
@haccer may help

**Comment by pielco11** [comment]
### Open the database and print the tables

![immagine](https://user-images.githubusercontent.com/17363750/57030162-2cff1000-6c44-11e9-9cae-c787d5d6e6f7.png)

### Print the id of the tweets that user liked

![immagine](https://user-images.githubusercontent.com/17363750/57030227-5a4bbe00-6c44-11e9-872c-4edb6c336e8e.png)

### Print a specific tweet from the tweets table given the liked id

![immagine](https://user-images.githubusercontent.com/17363750/57030331-98e17880-6c44-11e9-8db0-e6c136de3153.png)
