### ISSUE TITLE
[BUG] Missing favorites

### ISSUE THREAD

**Issue by nicolecheng** [twintproject/twint#197]
### Command Ran
$ python3 Twint.py -u liamcs98 --favorites

### Description of Issue
The actual count on Twitter is 741 liked posts. However this command only outputs 661 tweets. It is missing 80 favorites -- how come? A hunch is that the --favorites flag does not return the tweets that the user tweeted and favorited (i.e. if Liam favorited his own tweet)

### Environment Details
MacOS and Linux terminals

**Comment by haccer** [comment]
Hi @nicolecheng,

I have a few guesses why this is happening, it could either be:
- The favorite count on Twitter isn't accurate (This is common)
- There is a limit on retrieving favorites (Related to the limit on retrieving retweets, **likely reason**)

**Comment by Arwa200** [comment]
hi
I have the same issue, try to apply filters like
--since, --until and --year but still bring same likes every time

**Comment by pielco11** [comment]
`--since`, `--until` and `--year` are just for tweets
