### ISSUE TITLE
Is it possible to search a tweet by tweet id and get an output with the corresponding tweet?

### ISSUE THREAD

**Issue by sliceofshaun** [twintproject/twint#199]
Is it possible to search a tweet by tweet id and get an output with the corresponding tweet?

It may be trivial and I am just not getting it but this does not seem to be the case.

- Thank You

**Comment by haccer** [comment]
Hi @sliceofshaun,

Are you talking about from within Twint or in general?

If you know the username of the Tweeter, retrieving the Tweet is just:
```
https://twitter.com/<username>/status/<tweet id>
```

I don't think this is possible from within Twitter's search, I will have to double check.
