### ISSUE TITLE
[QUESTION] Can you scrape followers from a list of accounts in a file?

### ISSUE THREAD

**Issue by hudmb** [twintproject/twint#200]
E.g. Can this command: -

python3 Twint.py -u username --followers

use the --userlist argument to get followers for multiple accounts?

**Comment by pielco11** [comment]
The feature is already available, if you encounter errors don't hesitate to re-open the issue

**Comment by hudmb** [comment]
Hmm, OK. I tried 

python Twint.py --userlist userlist.txt --csv -o userlisttest.csv

But I get nothing. The userlist.txt file is in the same directory as Twint.py

**Comment by hudmb** [comment]
My bad. Working now.
