### ISSUE TITLE
[REQUEST] For --userlist arg output file with 2 columns

### ISSUE THREAD

**Issue by hudmb** [twintproject/twint#201]
Hi,

It would be SUPER useful when using the --userlist argument (with a path to the file) together with the --csv file output argument for the output file to contain 2 columns. 

The first column would be the follower (current behaviour), but the second column would be a comma separated list of those accounts from the --userlist file that is a follower of that account.  E.g.

--userlist file: -

TwitterUser01
TwitterUser02
TwitterUser03

Proposed -o --csv output file: -

TwitterUser70 --> TwitterUser01,TwitterUser02
TwitterUser82 --> TwitterUser03
TwitterUser84 --> TwitterUser02,TwitterUser03

I assume this is possible because you are having to go through the --userlist file anyway and then build a combined file output with all followers.

What I am asking for would be great for producing graph files of follower relationships that could be used with e.g. Gephi.

**Comment by hudmb** [comment]
Really hoping you can consider this :)

**Comment by pielco11** [comment]
This is really a great idea, but please consider the difference from "data harvesting" and "data analyzing", what you are asking for is something that you can achieve trough data analyzing, for example with the db

**Comment by hudmb** [comment]
OK thanks. I'm just not that experienced, that's all. No worries.

**Comment by pielco11** [comment]
I'm at a Hacker Camp in these days so I'm really really busy, I'll add this and other stuff to the wiki asap

**Comment by hudmb** [comment]
Thank you! It's very much appreciated. If I knew how to do it, I would. Would make my life a lot easier!

**Comment by pielco11** [comment]
You can use simple SQL queries like: `SELECT follows FROM following_names WHERE user = "user1"`
This will return who `user1` is following, you can also "switch" `follows` with `user` to get the *vice versa*

SQL queries return tuples so this is really easy to handle, you don't really need much more for easy elaborations like this, you can look at the db structure inside `twint/storage/db.py` and construct queries by your self

**Comment by hudmb** [comment]
Hi! Really appreciate your help here...but believe me when I say it's beyond my skills. I'm happy running a simple command from Terminal by copying some examples, but when it comes to db stuff - I've no idea. If anyone has the time to do a step by step from running Twint, to storing it in a db, to querying the db to give me what I want, to producing a CSV output I'd be eternally grateful :)

**Comment by pielco11** [comment]
I think that you should search for some basic SQL language course, this is not really the right place to talk about this

Than with a little knowledge of python you can parse the data to every format or "storage type" that you prefer
