### ISSUE TITLE
Error on first running

### ISSUE THREAD

**Issue by ClumsyCoder72** [twintproject/twint#204]
Python 3.5.3
Debian 9
Freshly cloned Twint from Github

Command I ran: python3 Twint.py -s trump

Ran the above command to test I had cloned / installed requirements properly and got the below error:
Used trump as the keyword as there is bound to be something mentioning that name happening!

Keep getting the following when running in terminal:

```
Traceback (most recent call last):
  File "Twint.py", line 12, in <module>
    import twint
  File "/home/user/twint/twint/__init__.py", line 11, in <module>
    from . import run
  File "/home/user/twint/twint/run.py", line 9
    self.init = f"TWEET-{config.Resume}-0"
                                 ^
```
 Tried a couple of times, tried on a fresh debian install incase but no go.  The ^ is positioned under the 0 in the last line of the error message (in case formatting doesn't position it correctly!)
Hopefully not something stupid I am doing

**Comment by pielco11** [comment]
Hi @ClumsyCoder72 

This is not a bug or Twint or your setup, simply Twint is not compatible with python 3.5, instead is compatible with python 3.6 

https://github.com/twintproject/twint#requirements
![immagine](https://user-images.githubusercontent.com/17363750/43958028-436dcaf8-9caa-11e8-8fb2-2ad35fae2fe7.png)

**Comment by ClumsyCoder72** [comment]
My apologies - read my version as 3.6.3. Its been a long day. Sorry again.

**Comment by pielco11** [comment]
Don't worry, no problem :+1:
