### ISSUE TITLE
[BUG] Count

### ISSUE THREAD

**Issue by mike-aungsan** [twintproject/twint#207]
[+] Finished: Successfully collected 1055 Tweets.
But only 690 tweets are written in kingsman.twint

python3.6
Ubuntu 16.04.5 LTS
4.4.0-131-generic
latest verion of twint

====
```python
import twint

twint_config = twint.Config()

twint_config.Lang = 'en'

twint_config.Since = "2017-12-02"
twint_config.Until = "2017-12-03"

twint_config.Count = True
twint_config.Search = "kingsman"

twint_config.Store_json = True
twint_config.Output = "kingsman.twint"

twint_result = twint.run.Search(twint_config)
```

**Comment by pielco11** [comment]
#### I tried and everything seems to work right, can't replicate the issue
![immagine](https://user-images.githubusercontent.com/17363750/44291843-6263f900-a281-11e8-8113-a08dd5464a6d.png)
