### ISSUE TITLE
When I run the example python module code, nothing happens.

### ISSUE THREAD

**Issue by bmferreira** [twintproject/twint#209]
### Command Ran

```
import twint

# Configure
c = twint.Config()
c.Username = "now"
c.Search = "fruit"
c.Format = "Tweet id: {id} | Tweet: {tweet}"

# Run
twint.run.Search(c)
```

### Description of Issue
Nothing is outputted to the terminal

### Environment Details
>Using Windows 10 under anaconda (python 3.6+) in the latest version of vscode

**Comment by pielco11** [comment]
Cody has a private account, try with an open one

![immagine](https://user-images.githubusercontent.com/17363750/44487576-edb10600-a656-11e8-9a37-d49a960b10b3.png)
