### ISSUE TITLE
Discord invite expired :(

### ISSUE THREAD

**Issue by realdevnullius** [twintproject/twint#211]
:) per title. The link to the Discord channel expired (github main page for twintproject).

Request: start using Telegram? :)

# Issue Template
Please use this template!

### Initial Check 
> If the issue is a request please specify that it is a request in the title (Example: [REQUEST] more features). If this is a question regarding 'twint' please specify that it's a question in the title (Example: [QUESTION] What is x?). Please **only** submit issues related to 'twint'. Thanks.

>Make sure you've checked the following:

- [] Python version is 3.5 or higher.
- [] Using the latest version of Twint.
- [] I have searched the issues and there are no duplicates of this issue/question/request.

### Command Ran
>Please provide the _exact_ command ran including the username/search/code so I may reproduce the issue.

### Description of Issue
>Please use **as much detail as possible.**

### Environment Details
>Using Windows, Linux? What OS version? Running this in Anaconda? Jupyter Notebook? Terminal?

**Comment by pielco11** [comment]
Hi @realdevnullius, we have a [Slack Workspace](https://os-int.slack.com/join/shared_invite/enQtMzc4NzY5ODI3NDI3LWRlOGNhN2U3OTUwY2Q1OTk5MDI2YjliOWQ1OTI5NzAyZjc0MDhiYTQ3NTY4MjMxY2E0MTRhOTVlN2M0ZmJhMjI) where you can reach us!

**Comment by realdevnullius** [comment]
This invite link is no longer active.
Please check with the person who shared it with you to see if there's a new link available

**Comment by pielco11** [comment]
The link expired, I'm sorry for inconvenience. [this link](https://join.slack.com/t/os-int/shared_invite/enQtNDI1MDA2OTg4MDg0LWUxYWNmMjI2MGFlMTZjZjhmOWY1ZTVhNmFiMDU2NzY1MzhiMDI2ZTZmYmEwY2MxY2YzMGFkZTY2MTcxZWI2ODM) know works
