### ISSUE TITLE
Unable to import twint due to SyntaxError in run.py

### ISSUE THREAD

**Issue by HarshVaragiya** [twintproject/twint#212]
# Unable to import twint 

### Initial Check 
> If the issue is a request please specify that it is a request in the title (Example: [REQUEST] more features). If this is a question regarding 'twint' please specify that it's a question in the title (Example: [QUESTION] What is x?). Please **only** submit issues related to 'twint'. Thanks.
>Make sure you've checked the following:
- [x] Python version is 3.5 or higher.
- [x] Using the latest version of Twint.
- [x] I have searched the issues and there are no duplicates of this issue/question/request.

### Command Ran
>import twint
### Description of Issue
>>> import twint
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/pi/Desktop/twint/twint/__init__.py", line 11, in <module>
    from . import run
  File "/home/pi/Desktop/twint/twint/run.py", line 9
    self.init = f"TWEET-{config.Resume}-0"
                                         ^
SyntaxError: invalid syntax

### Environment Details
>Using on Raspberry pi running raspian - SSH
![screenshot from 2018-08-29 19-54-45](https://user-images.githubusercontent.com/32223129/44794452-31ab8a00-abc6-11e8-89ec-b9dd9ac3a43f.png)

**Comment by pielco11** [comment]
Hi, Twint is not more compatible with Python3.5, use Python3.6 instead
