### ISSUE TITLE
Search for tweet in specific country!

### ISSUE THREAD

**Issue by yemen2016** [twintproject/twint#213]
# Issue Template
Please use this template!

### Initial Check 
> If the issue is a request please specify that it is a request in the title (Example: [REQUEST] more features). If this is a question regarding 'twint' please specify that it's a question in the title (Example: [QUESTION] What is x?). Please **only** submit issues related to 'twint'. Thanks.
**Could you please guide me how to extract tweets in a specific country. I am working on Hate Speech Detection in my country where the search using twint retrieves all tweets from different countries and dialects as well which makes the task too much difficult.** 
>Make sure you've checked the following:

- [] Python version is 3.6;
- [] Using the latest version of Twint;
- [] I have searched the issues and there are no duplicates of this issue/question/request.

### Command Ran
>Please provide the _exact_ command ran including the username/search/code so I may reproduce the issue.

### Description of Issue
>Please use **as much detail as possible.**

### Environment Details
>Using Windows, Linux? What OS version? Running this in Anaconda? Jupyter Notebook? Terminal?

**Comment by pielco11** [comment]
Hi @yemen2016,

the options that can help you achieving this are `Config.Near` (Near a certain city, eg: London) and `Config.Geo` (Geo coordinates lat,lon,km/mi). 
Currently Twitter does not offer an option to search tweets in a specific country, so Twint cannot create specific requests aimed at this purpose.
