### ISSUE TITLE
Elasticsearch type: possibility to change it

### ISSUE THREAD

**Issue by salvob41** [twintproject/twint#216]
It might be useful having the possibility to set the Elasticsearch `type` name that is by default `items`.

**Comment by pielco11** [comment]
Hi @salvob41,

you can change the `type` name as you may prefer, before creating the index.
E.g.:
```
PUT twintuser
{
  "mappings": {
    "mycustomname": {
      "properties": {
        "id": {"type": "keyword"},
        "name": {"type": "keyword"},
        "username": {"type": "keyword"},
        "bio": {"type": "text"},
        "location": {"type": "keyword"},
        "url": {"type": "text"},
        "join_datetime": {"type": "date", "format": "yyyy-MM-dd HH:mm:ss"},
        "join_date": {"type": "date", "format": "yyyy-MM-dd"},
        "join_time": {"type": "date", "format": "HH:mm:ss"},
        "tweets": {"type": "integer"},
        "following": {"type": "integer"},
        "followers": {"type": "integer"},
        "likes": {"type": "integer"},
        "media": {"type": "integer"},
        "private": {"type": "boolean"},
        "verified": {"type": "boolean"},
        "avatar": {"type": "text"},
        "session": {"type": "keyword"}
      }
    }
  }
  ,
  "settings": {
    "number_of_shards": 1
  }
}
```

**Comment by salvob41** [comment]
if you use it as module, installed with pip. There is no easy way to do it. though.

**Comment by pielco11** [comment]
Maybe I misunderstood what you are talking about, can you elaborate please?

How did you create the index?

**Comment by salvob41** [comment]
I am using the `twint` module available from `pip`

```
import twint

# Configure
c = twint.Config()
c.Search = "#gamedev"
c.Store_json = True
# CSV Fieldnames
c.Output = "twitter.json"
c.Elasticsearch = "localhost:9200"
c.Index_tweets= "tweets"
# Run
twint.run.Search(c)
```

I did something like this. I didn't put any mapping, because I want to use it in code  (because search words and index will be different ). 

The type though, is still `items`. And it seems I have no way of changing it.  It isn't extremely important but might be a good thing to have it.

**Comment by pielco11** [comment]
Now the point is more clear, I'll add the option for custom index

**Comment by pielco11** [comment]
![code](https://user-images.githubusercontent.com/17363750/45585951-44280200-b8ee-11e8-8187-5adf386fc1e2.png)

Change `c.Index_type` as you may prefer
Obviously change the index template accordingly

**Comment by jordanhimawan** [comment]
I had tried to customize the index name and type name using `c.Index_tweets` and `c.Index_type`.
![screenshot from 2019-02-19 16-19-19](https://user-images.githubusercontent.com/15666240/53003706-28f38c80-3462-11e9-8a73-62339990eb33.png)

Then, this error occured.
![screenshot from 2019-02-19 16-11-57](https://user-images.githubusercontent.com/15666240/53003323-47a55380-3461-11e9-86a9-dc6d9742478e.png)
This doesn't happen if I set them back to the default settings.
What can I do to resolve this?

**Comment by pielco11** [comment]
Because you are trying to index into an index that has a different "document type". So if you want a specific "document type" you have to create a new index, so specify a new `config.Index_tweets`.

On the other side, as you can see here
https://github.com/twintproject/twint/blob/f8c8d84cf84c5290c0cfbc06682b1509a1991598/twint/storage/elasticsearch.py#L54-L95
and below, Twint creates the index with `items` as `Index_type` by default (this is my fault)

I'm going to apply a patch soon, in the mean time you can replace `"items"` with `config.Index_type`

**Comment by pielco11** [comment]
Please consider that once an Index is created with a specific document type, it needs to be same over time
