### ISSUE TITLE
Additions to "Fruit" 

### ISSUE THREAD

**Issue by blatherdrift** [twintproject/twint#217]
Hello,

I see that you have the ability to pull phone numbers and other personal information by using the --fruit function. Is there any way we can do that but include bitcoin addresses? Or is there any way to query twitter for any bitcoin addresses that are found? 

using a regex like this maybe:

"x = re.findall('^[13][a-km-zA-HJ-NP-Z1-9]{25,34}$', line)"

**Comment by pielco11** [comment]
#176 

Hi @blatherdrift,

unfortunately this is not possible, we can't query Twitter to get tweets that match regular expression.
We can only apply regular expressions to retrieved tweets.
