### ISSUE TITLE
Possible to search with two key words?

### ISSUE THREAD

**Issue by blatherdrift** [twintproject/twint#218]
Hi again,

I tried the slack invite in the readme but the invite link is no longer working. My question is simple. How do you perform a query chaining two words? Is this possible?

**Comment by pielco11** [comment]
Hi,

the link does not expire, so I don't know what is going on.

![immagine](https://user-images.githubusercontent.com/17363750/45434757-7861af80-b6af-11e8-81c0-b5b663f497a6.png)

Anyway, yes, you can. You do `c.Search = "two words"`, a more "complex" example is with keywords: `c.Search = "\"keyword\""`

PS: about Slack, if you want you can send me an email to "francescopoldi<at>pielco11<dot>ovh" and I'll add you, if you prefer you can contact me via other ways
