### ISSUE TITLE
UnicodeEncodeError

### ISSUE THREAD

**Issue by aslv95** [twintproject/twint#221]
### Command Ran
c.Search = str(row['coach'])

### Description of Issue
I get the UnicodeEncodeError:
UnicodeEncodeError: 'UCS-2' codec can't encode characters in position 217-217: Non-BMP character not supported in Tk

I have also tried: c.Search = str(row['coach']).encode('UTF-8').decode('UTF-8')
Doesn't change anythin.

### Environment Details
Windows 10, using Python 3.6 via IDLE.

**Comment by pielco11** [comment]
Hi @aslv95 ,

it seems not to be an issue with Twint. What is `row['coach']`?

**Comment by aslv95** [comment]
Hi,
It is just a string. The problem is when I say       twint.run.Search(c)
It may be a reason with the 'emojis' at Tweets. 

Do you have any idea?
Thank you!

**Comment by pielco11** [comment]
I tried searching tweets with emojis and everything works great.

Can you provide me a your example, please? If it does not expose sensitive infos obv

**Comment by aslv95** [comment]
This is the simplified code which has a probem:

```
import csv
import twint

c = twint.Config()
c.Until = '2013-10-18'

c.Since = '2013-10-13'

c.Search = 'Arizona Cardinals'
c.Store_csv = True
c.Output = r"D:\NFLCodes\Code-for-Years\try2.csv"


twint.run.Search(c)
```

Thanks!

**Comment by pielco11** [comment]
The code is right and I don't see anything unusual, plus I tried it and it works right. It's definitely not an issue with Twint.

Closing this.

PS: you can still comment and I'll try to help you, just closing because it's not related to Twint

**Comment by aslv95** [comment]
Dear @pielco11 ,

Thank you very much for checking it for me.

I still have a problem. Can it be about my operating system, i.e., a string in csv error ?

I get this error:


```
Traceback (most recent call last):
  File "D:\NFLCodes\Code-for-Years\try.py", line 14, in <module>
    twint.run.Search(c)
  File "C:\Users\Aras Selvi\AppData\Local\Programs\Python\Python36-32\lib\site-packages\twint\run.py", line 25, in Search
    run(search.Search(config).main())
  File "C:\Users\Aras Selvi\AppData\Local\Programs\Python\Python36-32\lib\site-packages\twint\run.py", line 5, in run
    get_event_loop().run_until_complete(x)
  File "C:\Users\Aras Selvi\AppData\Local\Programs\Python\Python36-32\lib\asyncio\base_events.py", line 468, in run_until_complete
    return future.result()
  File "C:\Users\Aras Selvi\AppData\Local\Programs\Python\Python36-32\lib\site-packages\twint\search.py", line 49, in main
    await self.tweets()
  File "C:\Users\Aras Selvi\AppData\Local\Programs\Python\Python36-32\lib\site-packages\twint\search.py", line 37, in tweets
    await output.Tweets(tweet, "", self.config, self.conn)
  File "C:\Users\Aras Selvi\AppData\Local\Programs\Python\Python36-32\lib\site-packages\twint\output.py", line 48, in Tweets
    _output(tweet, output, config)
  File "C:\Users\Aras Selvi\AppData\Local\Programs\Python\Python36-32\lib\site-packages\twint\output.py", line 34, in _output
    print(output)
UnicodeEncodeError: 'UCS-2' codec can't encode characters in position 217-217: Non-BMP character not supported in Tk

```

**Comment by pielco11** [comment]
It seems that your IDLE can't handle emojis, more info [here](https://stackoverflow.com/questions/32442608/ucs-2-codec-cant-encode-characters-in-position-1050-1050#32442684)

I can search and retrieve tweets that have emojis, so it's a compatibility issue with IDLE

**Comment by aslv95** [comment]
Oh.. So, better if I ignore emojis (and how?). Or, better if I use PyCharm? Any suggestions?

**Comment by pielco11** [comment]
Ignoring emojis could be quite tedious, you should change some pieces of code. Not so hard but better not waste time. 

I suggest you to use IDEs as VSCode, Atom, PyCharm, Sublime... which one you might prefer.
Try to run the code inside the terminal (cmd). I'm not really familiar with Windows environment, hope this helps.

**Comment by aslv95** [comment]
That's fixed now. I couldnt think it was about IDLE. Thank you!
