### ISSUE TITLE
REQUEST: search tweets with several keywords

### ISSUE THREAD

**Issue by patowarheart** [twintproject/twint#222]
import twint 
c = twint.Config()
c.Search = "vanilla" or "chocolate"
c.Format = "{tweet}"
twint.run.Search(c)
 
Hello I have been using twint to webscrape tweets and I think is a great module. However, there is one feature I think is missing or might be missing from the wiki commands. I would like to search for tweets containing one or more of several keywords. Right now if you include several keywords Twint only outputs tweets containing all of the keywords. I would like to run a code like the one above and have twint output all the tweets containing the word vanilla, chocolate or both of them instead of only tweets containg both of them.

I use the latest version of twint on a jupyter notebook on module mode. I have read the wikia several times and I don't see anyway to run a code with this type of search.

**Comment by hpiedcoq** [comment]
It should be possible to retrieve these tweets like this : 

c.search = "vanilla OR chocolate"

**Comment by pielco11** [comment]
Full text search is different from keyword search. 

Example of full text search:
`c.Search = "full text search"` could return a tweet with "this is a **text**, not **full**, but useful for a **search**"

Example of keyword search:
`c.Search = "\"keyword search\""` could return a tweet with "this tweet is useful for a **keyword search**" and not return a tweet with "this tweet is useful for a **search**, but it does not have **keyword** that we want"

**Comment by pielco11** [comment]
Anyway, as @hpiedcoq correctly said, this is what you should do:

![tweets](https://user-images.githubusercontent.com/17363750/45930082-2b0cfa00-bf5b-11e8-9179-f22fc323f88f.png)

And this is an example of what you can get:
![immagine](https://user-images.githubusercontent.com/17363750/45930077-116bb280-bf5b-11e8-82a0-f4ac4b400ad0.png)

**Comment by maria-mh07** [comment]
Hi @pielco11,
Could you answer me a question? 
I want to get tweets that contain any of the following keywords: "Burger King", "Domino´s Pizza" or "Pizza Hut".

Then I need: `c.Search = "\"Burger King\""` or `c.Search = "\"Domino´s Pizza\""` or `c.Search = "\"Pizza Hut\""`.
How these three searches are joined by or? Because
`c.Search = "\"Burger King OR Domino´s Pizza OR  Pizza Hut\""` is not correct.

Thank you!

**Comment by paleboot** [comment]
> Hi @pielco11,
> Could you answer me a question?
> I want to get tweets that contain any of the following keywords: "Burger King", "Domino´s Pizza" or "Pizza Hut".
> 
> Then I need: `c.Search = "\"Burger King\""` or `c.Search = "\"Domino´s Pizza\""` or `c.Search = "\"Pizza Hut\""`.
> How these three searches are joined by or? Because
> `c.Search = "\"Burger King OR Domino´s Pizza OR Pizza Hut\""` is not correct.
> 
> Thank you!

`"\"Burger King OR Domino´s Pizza OR Pizza Hut\""` will only return tweets that literally have the string `Burger King OR Domino´s Pizza OR Pizza Hut` in them. I think what should get you going is `"Burger King OR Domino´s Pizza OR Pizza Hut"`.

**Comment by Abdelrahmanrezk** [comment]
Can it based on just language not on word ?

**Comment by Sohamk27** [comment]
is it a good method

**Comment by Amrouane** [comment]
@pielco11 Is it the same way for the "OR" operator, in case I want to have multiple keywords at a time in one single tweet ?
