### ISSUE TITLE
want to scrape all tweets from timeline in json

### ISSUE THREAD

**Issue by adityak2920** [twintproject/twint#226]
I tried this "python3 Twint.py -u karpathy -o file.json --json" to scrape all tweets but it is only providing tweets by the user not retweets so how can I scrape all tweets from timeline including retweets and save in json.

**Comment by pielco11** [comment]
You should also pass the `--profile-full` argument, but it seems that this feature is broken. Probably Twitter changed some selector. Now as now users can only scrape users' tweets

**Comment by pielco11** [comment]
@adityak2920 now this issue is fixed.

To scrape users' retweets you can pass the `--retweet`  argument, this is the fast way.
The slow but effective way to enumerate the user's Timeline is passing `--profile-full` argument instead of `--retweets`
