### ISSUE TITLE
cchardet can't install in mac OS 10.14

### ISSUE THREAD

**Issue by XiaoWuTongZhi** [twintproject/twint#227]
'pip3 install cchardet'  get some problems !

I notice the wrong-log contain '**library not found for -lstdc++**'，How should I solve the problem in mac OS 10.14 ?

here is log :

...
clang: warning: libstdc++ is deprecated; move to libc++ with a minimum deployment target of OS X 10.9 [-Wdeprecated]
    clang: warning: libstdc++ is deprecated; move to libc++ with a minimum deployment target of OS X 10.9 [-Wdeprecated]
    ld: library not found for -lstdc++
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
    error: command '/usr/bin/clang++' failed with exit status 1
    
    ----------------------------------------
Command "/Users/test/PycharmProjects/TWINT/venv/bin/python3.6 -u -c "import setuptools, tokenize;__file__='/private/var/folders/4d/xnms9dqx1hg681lyf2ht7dtr0000gp/T/pip-install-g79gn1a3/cchardet/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/var/folders/4d/xnms9dqx1hg681lyf2ht7dtr0000gp/T/pip-record-mq3ir1k2/install-record.txt --single-version-externally-managed --compile --install-headers /Users/test/PycharmProjects/TWINT/venv/bin/../include/site/python3.6/cchardet" failed with error code 1 in /private/var/folders/4d/xnms9dqx1hg681lyf2ht7dtr0000gp/T/pip-install-g79gn1a3/cchardet/

**Comment by pielco11** [comment]
Please **only** submit issues related to Twint

**Comment by pielco11** [comment]
I do not really why this is happening. Anyway, googling around I found that some users are reporting this as a solution `pip3 install cchardet==1.0.0`

**Comment by cursivemess** [comment]
> I do not really why this is happening. Anyway, googling around I found that some users are reporting this as a solution `pip3 install cchardet==1.0.0`

That did not work for me, I still get the following :

error: command 'gcc' failed with exit status 1

**Comment by isanbel** [comment]
https://github.com/TokenMarketNet/smart-contracts/issues/115 works
Command: 
MACOSX_DEPLOYMENT_TARGET=10.13 pip3 install cchardet
