### ISSUE TITLE
When trying to run a Search list index out of range [x] run.Feed

### ISSUE THREAD

**Issue by mrdeds** [twintproject/twint#228]
### Command Ran
`
>>> import twint
>>> c = twint.Config()
>>> c.Username = "elon_musk"
>>> c.limit = 20
>>> c.Pandas = True
>>> twint.run.Search(c)
list index out of range [x] run.Feed`

### Description of Issue
I'm trying to run a Search in the Mac OS terminal. Sometimes it gives me a:
`list index out of range [x] run.Feed`

### Environment Details
>Using Mac OS, Terminal, Python 3.6.5

**Comment by pielco11** [comment]
It seems not to be an issue with Twint, `elon_musk` account is suspended so Twint does not have tweets to scrape. 

Do you get the same issue with active accounts?

**Comment by mrdeds** [comment]
you are totally right, my fault. Thanks for the quick reply and all the work you are doing.

**Comment by hudmb** [comment]
Hi! I am also getting this same error when I run this from the command line: -

`python3 twint.py -s "\(#craftbeer OR \"craft beer\"\) near:\"united kingdom\" lang:en filter:mentions" -o craftbeer.csv --csv`

The query runs absolutely fine, but then eventually stops with this error: -

`list index out of range [x] run.Feed`

**Comment by pielco11** [comment]
Hi @hudmb ,

that "issue" is not so much different from the previous one. That error is printed when **no more** tweets are available, when you reach the first tweet of that query no more tweets are available (going from the last to the first) and so Twint stops. 

If you think that this is an issue with Twint and so there are more tweets available, I suggest you to try using twitter advanced search specifying the right date range, if you get more tweets feel free to let us know.

**Comment by hudmb** [comment]
OK thanks, I'll test that and report back!

**Comment by pielco11** [comment]
@hudmb I tried and yes, tweets do exist but the issue is that Twitter is not loading them. Using `since` and `until` args I  before May 30 get tweets

**Comment by Arwa200** [comment]
Hi, when I run this from the command line:
import twint
c = twint.Config()
c.Username = "USERNAME"
twint.run.Favorites(c) 

 I am also getting this same error: 
list index out of range [x] feed.Mobile

**Comment by pielco11** [comment]
@Arwa200 I have it running correctly, please be sure to have Twint updated, run `pip3 install --upgrade -e git+https://github.com/twintproject/twint.git@origin/master#egg=twint`. 

If you still have errors, I kindly ask you to open a new issue so that we do not mix conversations/issues, thank you!
