### ISSUE TITLE
scrapping by a hashtag

### ISSUE THREAD

**Issue by adityak2920** [twintproject/twint#231]
how can I scrape tweets by a hashtag for example I want to scrape tweets which include #happy how can I do it

**Comment by rpanai** [comment]
@adityak2920  Have you tried the 3rd basic example [here](https://github.com/twintproject/twint) using #happy instead of pinapple?

**Comment by adityak2920** [comment]
ya I have tried but it's scrapping tweets which contain the word for example "happy" but when I tried to pass "#happy" it's throwing an error and the error is given below

usage: python3 Twint.py [options]
Twint.py: error: argument -s/--search: expected one argument

**Comment by hudmb** [comment]
Try "happy filter:hashtags"

**Comment by pielco11** [comment]
`python3 Twint.py -s "\"#happy\""`

**Comment by Neeparte** [comment]
how can I scrap tweets with multiple twitter handels or list of twitter keywords
