### ISSUE TITLE
New lines in tweet text concatenated. Can they be split by " " or \n instead?

### ISSUE THREAD

**Issue by jnorm18** [twintproject/twint#232]
### I'm running the following:
import twint
c = twint.Config()
c.Since='2018-10-01'
c.Search= "#hashtag"
c.Store_csv = True
c.Custom = ["tweet"]
c.Output = "twitter.csv"
twint.run.Search(c)

###It works just fine. However, when my search finds tweets like this...
This tweet contains the following:
x
y
z

#hashtag

###My .csv files is formatted like so: "This tweet contains the following:xyz#hashtag"
###What would be great is more like this: "This tweet contains the following: x y z #hashtag" or "This tweet contains the following:\nx\ny\nz\n#hashtag"

Any ideas?
Cheers!!

**Comment by pielco11** [comment]
# `twint/tweet.py`
![immagine](https://user-images.githubusercontent.com/17363750/46489178-00495e00-c805-11e8-9651-2569ae0a029e.png)

The new-line char is replace with whitespace-char, can you please update your local repo?
`pip install --upgrade -e git+https://github.com/twintproject/twint.git@origin/master#egg=twint`
