### ISSUE TITLE
How to get long/lat of a tweet?

### ISSUE THREAD

**Issue by hwsamuel** [twintproject/twint#233]
I have read the Wiki and the other documentation I could find, but there's no mention of long/lat for a tweet. I also haven't been able to see it in the returned results from multiple queries.

**Comment by pielco11** [comment]
Hi @hwsamuel ,

unfortunately we can't get the long/lat of a tweet. You can just search for a specific place a get the tweets that were geo-tagged near that place, `config.Near`.
