### ISSUE TITLE
[QUESTION][REQUEST] Options for not showing tweets while searching

### ISSUE THREAD

**Issue by mrdeds** [twintproject/twint#236]
# Issue Template
Please use this template!

### Initial Check 
> 
>Make sure you've checked the following:

- [x] Python version is 3.6;
- [x] Using the latest version of Twint;
- [x] I have searched the issues and there are no duplicates of this issue/question/request.

### Command Ran
>c = twint.Config()
>c.Username = account
>c.Pandas = True
>twint.run.Search(c)

### Description of Issue
>Is there a way to tell twint to not show the tweets it's scrapping in the loggs?
I've tried changing the configuration format like:
c.format = ' '
but instead I get a bunch of white spaces. I use it just for the Pandas Dataframe, I'm not interested in watching tweets on the terminal. I'd be more interested in current tweets count or something like that.

### Environment Details
>Linux Ubuntu terminal using nohup and OSX using terminal

**Comment by pielco11** [comment]
I'll push changes in the next days, while you can comment out this line
https://github.com/twintproject/twint/blob/d0fe42d31502ce1ba9eecce6b476fb2856f7d880/twint/output.py#L76

Or simply redirect the output

**Comment by pielco11** [comment]
(reopening since I did not push changes, yet)
