### ISSUE TITLE
[QUESTION][REQUEST]Getting more tweets than the limit configured

### ISSUE THREAD

**Issue by mrdeds** [twintproject/twint#237]
### Initial Check 
>Make sure you've checked the following:

- [X] Python version is 3.6;
- [X] Using the latest version of Twint;
- [X] I have searched the issues and there are no duplicates of this issue/question/request.

### Command Ran
>c = twint.Config()
>c.Username = account
>c.Pandas = True
>c.Limit =10
>twint.run.Search(c)

And i get 20 tweets 
### Description of Issue
I'm using your awesome library but when trying to get just `n` tweets I get more than those. I usualy make debuging using a limit of the last 10 tweets but I get 20, more or less always (sometimes i get more tweets more). Am I using it wrong or is it some bug? 

### Environment Details
>Linux Ubuntu terminal using nohup and OSX using terminal

**Comment by pielco11** [comment]
It's a Twitter flaw, but I'll add the option to count every single tweet and stop when the **actual** limit is reached

**Comment by pielco11** [comment]
Honestly said, better fetch 20 tweets and extract the first one. This can be achieved really easy as explained here https://github.com/twintproject/twint/wiki/Module#save-data-tweets-users--in-lists-ram

If you store the data to json or csv, you can just do some shell scripting

**Comment by lisenkaci** [comment]
Hello, I am still having a problem with this the c.Limit does not working. I get back way more tweets than the limit. Anything new on this bug? thank you!

**Comment by Greatdane** [comment]
Same - no matter what I select, I get 100

**Comment by himanshudabas** [comment]
@Greatdane 
Hi,
In the newer implementation, you get tweets in multiple of 100.
So even when you specify the limit below 100 it will still return 100, try to specify the limit in multiples of 100.
That should work.

**Comment by Greatdane** [comment]
Thanks @himanshudabas, I didnt see that anywhere - the wiki unfortantely is very out of date on lots of things.
