### ISSUE TITLE
[QUESTION] [REQUEST]Config file explanation

### ISSUE THREAD

**Issue by mrdeds** [twintproject/twint#238]
hi guys, is there anywhere (Readme or something) to find an explanation for all the elements of the configuration?
It'd be awesome to have that. I'd love doing it but as you can see I don't understand all the elements and functionality.

**Comment by pielco11** [comment]
https://github.com/twintproject/twint/blob/d0fe42d31502ce1ba9eecce6b476fb2856f7d880/Twint.py#L111-L191

If you have specific questions don't hesitate to ask

**Comment by mrdeds** [comment]
great, thanks!
