### ISSUE TITLE
[QUESTION] Twint and Twitter ToS

### ISSUE THREAD

**Issue by hwsamuel** [twintproject/twint#241]
Just a simple question out of curiosity. Is using Twint in line with Twitter's [terms of service](https://twitter.com/en/tos), especially around scraping and rate limits? I'm doing research that I wouldn't want discredited later on because of legalese!

**Comment by pielco11** [comment]
![immagine](https://user-images.githubusercontent.com/17363750/47615111-013f7980-daab-11e8-8585-8208d8a77f4d.png)

[More here](https://help.twitter.com/en/rules-and-policies/twitter-automation)

**Comment by wuqui** [comment]
Hi,

I share this concern and this should be a crucial issue for everyone using this tool, I guess, so I'm surprised this was closed. After reading quite a few blogs and papers on the one hand, and Twitter's Terms of Service on the other, it seems to be quite clear that using `twint` for collecting Twitter data is explicitly prohibited by the ToS. 

Is there any way around this problem and any way we can still use this data for research (publications)?

Has anybody explicitly asked Twitter for using `twint` (or any other scraper) for research purposes?


Best,
Quirin

**Comment by pielco11** [comment]
@wuqui this issue has been closed because an answer has been found

Twitter does not allow you to use scrapers. So the usage of Twint is prohibited, not Twint itself. Therefore every other single scraper is forbidden. They know that people are using scrapers (and not only Twint) and they are acting pretty well (honestly) to minimize the effects of scrapers

And to be more specific, what's forbidden is that Twint automatically (here is the point) generates the url for the next query.

You could search manually for tweets via Twitter Advanced Search, scroll down, save the page and extract tweets offline. Is this legal? Idk, it depends. Is this against ToS? For sure. Is this what Twint does? Absolutely yes.

About research. In my opinion, it depends by your commission to accept this kind of data source.

I'm here for other questions and/or continue the discussion

Regards,
Francesco

(reopening since people are not satisfied by the given answer)

**Comment by wuqui** [comment]
Thanks for your reply, Francesco!

> and they are acting pretty well (honestly) to minimize the effects of scrapers

Not sure what you mean by that. Do you mean that they make it hard to scrape tweets / build scrapers?

> So the usage of Twint is prohibited, not Twint itself.

Alright, I see, that's a good point. This brings me to the next one though.

> About research. In my opinion, it depends by your commission to accept this kind of data source.

I would guess that a lot of people using `twint` use it for research. So surely many should have faced the following two issues:

1. In Twitter's ToS they mention that scraping is not allowed "without permission", which suggests that one could ask for permission and it's not ruled out that they would grant it. Has anybody tried that?

2. Assuming no permission, was use in academic circles (conferences etc.) and publications (journals, publishers) problematic?

**Comment by pielco11** [comment]
> Do you mean that they make it hard to scrape tweets / build scrapers?

For now it's pretty easy to build a scraper, but it's hard is scraping. They block connections/don't return data. It seems that with the new version of Twitter, that will come in the next month, they will use "dynamic generated" classes, with would make the developing of a scraper harder.

> Has anybody tried that?
> Assuming no permission, was use in academic circles (conferences etc.) and publications (journals, publishers) problematic? 

I don't know the answer to this question

**Comment by wuqui** [comment]
I see, thanks explaining it in more detail.

1. In Twitter's ToS they mention that scraping is not allowed "without permission", which suggests that one could ask for permission and it's not ruled out that they would grant it. Has anybody tried that?

2. Assuming no permission, was use in academic circles (conferences etc.) and publications (journals, publishers) problematic?

> I don't know the answer to this question

This is such a weird situation to me. Basically everyone who uses `twint` (or other scrapers) violates Twitter's Terms of Service, yet nobody discusses how to handle this situation? What do all these people use their data for then? ;)

**Comment by pielco11** [comment]
Scraping the web is a weird situation for everyone, I guess

What I know for sure is that companies 'buy' tweets (datasets) from Twitter to do data analysis (yes, Twitter gets money selling tweets and lets others doing analysis). So for research you should buy tweets as well

How to handle this situation is out of my scope, I mean, I don't think that I'm in the position to give legal advices

Honestly I do not know what people do with data collected by Twint and, just to be clear with everyone, we do not take any responsibilities

A few people are saying that even if Twint breaks ToS, it does not break the law and this is enough to use Twint in a legitimate way

**Comment by wuqui** [comment]
Yes, I have been in contact with the legal department of my university and scraping the web is even weird to them. Just a big gray area ;) 

Still surprised that none of your users come out and ask about it when everyone has to do something about it when he/she wants to use the data. Surely somebody must also have tried and asked Twitter for permission. But well, maybe there'll be some answers still...

**Comment by pielco11** [comment]
Well, I had a couple of discussions about this topic, but there were almost only opinions. I can't give more than my opinion

About permissions, I think it's all about the money

**Comment by AyhmRB** [comment]
Are there any legal consequences to using twint-scraped tweets commercially? from what I've seen people don't really care.
