### ISSUE TITLE
[QUESTION] Can you scrape from multiple usernames and put in the same elasticsearch index?

### ISSUE THREAD

**Issue by magamonsta** [twintproject/twint#242]
Do you need to run each username is a separate command? 
When I try and collect from multiple usernames and put in elasticsearch, it overwrites the existing index, I want to append these new tweets from a new username to the tweets in elasticsearch from a different username.

# Issue Template
Please use this template!

### Initial Check 
> If the issue is a request please specify that it is a request in the title (Example: [REQUEST] more features). If this is a question regarding 'twint' please specify that it's a question in the title (Example: [QUESTION] What is x?). Please **only** submit issues related to 'twint'. Thanks.

>Make sure you've checked the following:

- [] Python version is 3.6;
- [] Using the latest version of Twint;
- [] I have searched the issues and there are no duplicates of this issue/question/request.

### Command Ran
>Please provide the _exact_ command ran including the username/search/code so I may reproduce the issue.

### Description of Issue
>Please use **as much detail as possible.**

### Environment Details
>Using Windows, Linux? What OS version? Running this in Anaconda? Jupyter Notebook? Terminal?

**Comment by pielco11** [comment]
Seems to be a bug, but I tested and it not seems to be

**Comment by pielco11** [comment]
If the index does not exist, it's created automatically by Twint. In this case you should see something like this:
![immagine](https://user-images.githubusercontent.com/17363750/46887511-1b981700-ce5e-11e8-930c-ffc87f9d420f.png)

If the index already exists, it's not overwritten:
https://github.com/twintproject/twint/blob/d0fe42d31502ce1ba9eecce6b476fb2856f7d880/twint/storage/elasticsearch.py#L22-L37

Error `400` is returned if the index already exists.
![immagine](https://user-images.githubusercontent.com/17363750/46887682-97925f00-ce5e-11e8-8ca0-fde36a55f16a.png)

Can you elaborate and give me more infos, please?

**Comment by pielco11** [comment]
Closing since:
- no more details were provided;
- inactivity (one month from the opening);
- the issue was not reported by others that are using Elasticsearch.

In case feel free to reopen
