### ISSUE TITLE
[ISSUE] performance

### ISSUE THREAD

**Issue by mike-aungsan** [twintproject/twint#243]
>Make sure you've checked the following:

- [Y] Python version is 3.6;
- [Y] Using the latest version of Twint;
- [Y] I have searched the issues and there are no duplicates of this issue/question/request.

### Command Ran
twint_config = twint.Config()

twint_config.Database = db_obj
twint_config.Lang = 'en'

twint_config.Since = job["since"]
twint_config.Until = job["until"]

twint_config.Count = True
twint_config.Search = job["keyword"]

twint_result = twint.run.Search(twint_config)

### Description of Issue
No matter how many cores the machine has, performance does not improve.
I can see it is running on all cores.

### Environment Details
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.1 LTS
Release:        18.04
Codename:       bionic

4.15.0-36-generic

112 Core
377 G

**Comment by pielco11** [comment]
The bottleneck is on Twitter side, not your bandwidth/cores/etc.
