### ISSUE TITLE
[QUESTION] Is it possible to get a user's location without searching for tweets?

### ISSUE THREAD

**Issue by gauravsekhar** [twintproject/twint#244]
I'm going through a large list of usernames, determining the location.

![image](https://user-images.githubusercontent.com/36719517/46903132-020ec380-ce8e-11e8-91e1-86877b6c48b4.png)

This however hunts through upto 20 tweets. All I need is a single search instead of 20, since all I need is the location.

**Comment by pielco11** [comment]
User or tweet location?

Anyway, Twitter is giving us 20 tweets, we can not ask for a single tweet.

If you are looking for a location of a specific user, I'm sorry to inform you that this features is not available (yet)

**Comment by gauravsekhar** [comment]
If it's not possible to ask for a single tweet from all of the users tweets, is it possible to fetch 20 tweets, but only get the location for 1 of them? Maybe a break statement in a loop? I tried it but it returns an error at times, in case a tweet was not found (NoneType return).

**Comment by pielco11** [comment]
To get user's location you do not have to search for tweets

Doing as you would, will return only the location (if available) of the last tweet of that specific user

**Comment by gauravsekhar** [comment]
For the exact code snippet that I have provided above, I seem to be getting the same location numerous times. I'd much appreciate a solution or explanation.

Code Snippet:

![image](https://user-images.githubusercontent.com/36719517/46914240-69447a80-cf57-11e8-9b7e-9957fe657964.png)

Terminal Output (also stored into the csv file):

![image](https://user-images.githubusercontent.com/36719517/46914235-503bc980-cf57-11e8-93c4-1bfb72c356fd.png)

**Comment by pielco11** [comment]
You are getting multiple locations because, for every tweet Twint extracts the location of the user.

You could use `c.Limit` to limit the output or add an if statement in `twint/output.py` to stop Twint after one tweet is scraped.
Or, you could save the output to a temporary file and when the search is finished, open that file and extract one line, so save this one to `locations.csv`

All the three options have the same performance

**Comment by pielco11** [comment]
Better store tweets in objects, extract the first of the list and save that one

**Comment by pielco11** [comment]
![immagine](https://user-images.githubusercontent.com/17363750/46914977-93bd2480-cfa5-11e8-9bce-84a07d828484.png)

**Comment by pielco11** [comment]
`python3.6 Twint.py -u user1 --user-full` this will return every info about that specific user

```python
import twint

c = twint.Config()
c.Username = "user1"
c.Store_object = True

twint.run.Lookup(c)

users = twint.output.user_object
print(users[0].location)
```
