### ISSUE TITLE
Repeating Set of Tweets

### ISSUE THREAD

**Issue by RoiOng** [twintproject/twint#250]
### Command Ran

import twint

c = twint.Config()
c.Search = "#OmpongPH"
c.Format = "{tweet}"
c.Lang = "tl"
c.Limit = 1000

twint.run.Search(c)

### Description of Issue
>Repeated gathered tweets. Every time I use c.Search, the tweets being displayed are repeated at a set of 20. There will be 20 unique tweets but after the first 20 unique tweets the following tweets are just repeated from those 20 tweets again and again.

### Environment Details
>Using Windows. Running this in Anaconda. Spyder Python 3.6

**Comment by patowarheart** [comment]
Started happening samw thing to me just now. didnt happen yesterday that I used it. So weird maybe twitter blocked it?

**Comment by pielco11** [comment]
Could be related to #249 
Will discuss about this in that issue to avoid double comments

**Comment by SebastianMuszynski** [comment]
Possibly solved by this PR: https://github.com/twintproject/twint/pull/251

**Comment by haRpxd** [comment]
having this problem still

**Comment by pielco11** [comment]
@haRpxd be sure to use the latest version. If the problem persists, please provide us more details about your query (which username you want to scrape, date range, and so on)
