### ISSUE TITLE
Limited historical data

### ISSUE THREAD

**Issue by xxshazxx** [twintproject/twint#272]
- [X] Python version is 3.6; 
- [X] Using the latest version of Twint;
- [X] I have searched the issues and there are no duplicates of this issue/question/request.

### Command Ran
>python3 -V
Python 3.6.3 :: Anaconda, Inc.

>python3 Twint.py -u ChiaraFerragni
40090727 | Chiara Ferragni | @ChiaraFerragni | Private: 0 | Verified: 1 | Bio: Love fiercely (and don't forget to stop along the way to take photos) | Location:  | Url: http://www.theblondesalad.com/ | Joined: 14 May 2009 2:33 PM | Tweets: 44946 | Following: 77 | Followers: 394884 | Likes: 5703 | Media: 4842 | Avatar: https://pbs.twimg.com/profile_images/1016800181059276806/qQkiI2RT_400x400.jpg
Series([], dtype: object)

>python3 Twint.py -u Fedez
267138741 | Fedez | @Fedez | Private: 0 | Verified: 1 | Bio: Prima di ogni cosa. 2 Novembre. 👇🏻 | Location: Milano | Url: https://smi.lnk.to/PrimaDiOgniCosa | Joined: 16 Mar 2011 4:50 AM | Tweets: 10002 | Following: 739 | Followers: 1969799 | Likes: 30079 | Media: 2207 | Avatar: https://pbs.twimg.com/profile_images/1054375393753526273/SluDBMbU_400x400.jpg
1056950281743859718 2018-10-29 17:45:59 CET <Fedez>  https://youtu.be/Xn8Pg18giRQ 
1056510883394920448 2018-10-28 12:39:58 CET <Fedez> 3 generazioni. Presente e futuro ❤️
1056290352267698176 2018-10-27 23:03:39 CET <Fedez> Piccola riflessione. pic.twitter.com/D7qfilvUcB
1054131135687614466 2018-10-22 00:03:42 CET <Fedez> Prima di ogni cosa. 2 Novembre pic.twitter.com/tYg39Raug1
1053972892071931904 2018-10-21 13:34:53 CET <Fedez> Ci siamo... pic.twitter.com/jE3X2E8BFb
Series([], dtype: object)

### Description of Issue
I have tried to run twint in CLI and also as a Module but in both cases either I get no tweets like in the first example or I get only tweets till the 21st of October. If I search for user without recent post I only get the profile information and nothing more. It looks like the software cannot go back more than 10 days in the history.
By using other user, like CocaCola, I can get only up to the 20th of October:

1053678086661816320 2018-10-20 18:03:26 CET <CocaCola> While it’s not discontinued in the U.S., it may no longer be available in some Bottling territories.  Please PM us with your zipcode and we can help determine that for you.
1053677975273639936 2018-10-20 18:03:00 CET <CocaCola> While it’s not discontinued in the U.S., it may no longer be available in some Bottling territories.  Please PM us with your zipcode and we can help determine that for you.
Series([], dtype: object)

Is this "Series([], dtype: object)" message correct ?

### Environment Details
Linux Ubuntu 16.04
Python 3.6.3 :: Anaconda, Inc.
Terminal

Thanks a lot for the help and great job!

**Comment by Mehdzor** [comment]
Could you try it with this PR?
https://github.com/twintproject/twint/pull/271 - there's a fix for data inconsistencies.

**Comment by xxshazxx** [comment]
Yes, applying the changes it seems to work perfectly. I'll test it more, but for now, Thank you so much for the help and fast answer.

**Comment by andytnt** [comment]
@xxshazxx What commit are you on? 
`python3 Twint.py -u Fedez`
I tried with the above username and I see the tweets returned going back to 2017 without any error.
I don't see the error you mentioned `Series([], dtype: object)`

**Comment by xxshazxx** [comment]
commit 731020a22b767625648e3db8e76a8ed1afeb046d
Author: Francesco Poldi <francesco.poldi@protonmail.ch>
Date:   Mon Oct 29 19:26:17 2018 +0100

**Comment by pielco11** [comment]
`Series([], dtype: object)` this message is related to Anaconda

**Comment by pielco11** [comment]
@xxshazxx we applied some patch, feel free to try and let us know
