### ISSUE TITLE
'NoneType' object has no attribute 'find' [x] get.Tweet

### ISSUE THREAD

**Issue by LaurenDahlin** [twintproject/twint#273]
### Initial Check
- x Python version is 3.6;
- x Just updated Twint with `pip3 install --upgrade -e git+https://github.com/twintproject/twint.git@origin/master#egg=twint`;
- ? Could be a duplicate - similar errors seem to be cropping up. Sorry for initially posting this as a comment on a pull request. (Deleted, thanks for the reply.)

### Command Ran
Goal: save all tweets for user as json. Here's a simple example. 

```
c = twint.Config()
c.Profile_full = True
c.Username = 'AshfordU'
c.Store_json = True
c.Output = 'AshfordU.json'
twint.run.Profile(c)
```

### Description of Issue
For some Tweets I'm occasionally seeing the error output:
`'NoneType' object has no attribute 'find' [x] get.Tweet`

Also not sure yet if the full history will come through. Waiting on example to finish. For this particular username I was previously only able to go back to 2016-05-03 before I repulled Twint.

### Environment Details
Ubuntu Terminal

**Comment by LaurenDahlin** [comment]
Yes, so my history still isn't going back as far as expected (#272 ), which is supposed to be fixed with the latest merge. It takes a little while to run, but would someone else mind checking this out? Maybe my pull/update didn't work.

**Comment by pielco11** [comment]
It seems to not be working but, it's also True that the missing tweets do not exist (at least this is what I can say)

### Twint ouput

![2018-10-31_17-11](https://user-images.githubusercontent.com/17363750/47802435-8a1b1700-dd30-11e8-831a-3fc19d611545.png)

### Twitter screenshot

![2018-10-31_17-14](https://user-images.githubusercontent.com/17363750/47802459-969f6f80-dd30-11e8-939b-1730e606f895.png)

**Comment by pielco11** [comment]
```python
import twint

c = twint.Config()
c.Username = 'AshfordU'
c.Store_json = True
c.Output = 'AshfordU.json'
twint.run.Search(c)
```

with `twint.run.Search` instead of `twint.run.Profile`, Twint will use Twitter search, which is speeder

**Comment by LaurenDahlin** [comment]
Okay interesting. I am trying to now confirm that there should be tweets before 2016-05-03 for this user in case they deleted all their tweets before that or something. Twitter’s advanced search isnt working for me. Can you tell if the tweets actually go back to 2009 July like it says on the profile?

**Comment by pielco11** [comment]
### Twint output

![2018-10-31_17-48](https://user-images.githubusercontent.com/17363750/47804466-319a4880-dd35-11e8-839b-7f70f5530a5c.png)

### Twitter screenshot

![2018-10-31_17-48_1](https://user-images.githubusercontent.com/17363750/47804494-41199180-dd35-11e8-929d-eb8be3133d72.png)

### Conclusions

At this point I can say that Twint scraped every tweet and there are not more tweets available

**Comment by pielco11** [comment]
`UPDATE:
with the code you provided, the last tweet that I got is
> 727573444699820032 2016-05-03 21:00:01 CET RT <AshfordU> How @Forbes Distinguished Speaker Series brings the lecture experience to online students:  http://bit.ly/1TvRJ21  pic.twitter.com/WVWfvpT1oG

### error returned 
`list index out of range`

**Comment by LaurenDahlin** [comment]
So using Search instead of Profile you were able to go back to July 2010?

**Comment by pielco11** [comment]
Yes, this is what I got

**Comment by LaurenDahlin** [comment]
Update: Confirmed - the full history is coming through now. Glad search works even though profile does not. Are there features that are available through profile that are not available through search? Can you just deprecate profile? haha

**Comment by pielco11** [comment]
I can not deprecate profile, even though it's not working completely right (yet). And the reason is quite simple, there are shadow-banned accounts around, and you can scrape their tweets only with profile and not search 

In general, you can't find tweets (via search) of shadow-banned accounts, and there's where profile comes into play
