### ISSUE TITLE
Use multiprocessing.

### ISSUE THREAD

**Issue by dpffxhad** [twintproject/twint#285]
Use the multiprocessing library to spawn up to n processes.
https://github.com/taspinar/twitterscraper this library uses multiprocessing,is much faster but doesn't have the features twint has.

**Comment by pielco11** [comment]
#185

**Comment by dpffxhad** [comment]
Code was not modified to support multiprocessing since July? Is multiprocessing out of scope? Will it be added to twint ever in future?

**Comment by pielco11** [comment]
Hi @dpffxhad and thank you for the questions.

A sort for multiprocessing will be added to Twint. In the past months we focused more on features rather than speed, since for the second there already some good workarounds

**Comment by dpffxhad** [comment]
When can we expect it?

**Comment by pielco11** [comment]
At the moment it's not scheduled

**Comment by rpanai** [comment]
Have you tried to make a list of smaller queries and use yourself multiprocessing?

**Comment by pielco11** [comment]
Spawning more processes will be counterproductive since Twitter monitors your requests, and if your requests-rated is more than a threshold, Twitter suspends your IP for a while
