### ISSUE TITLE
only Last 10 days data got scraped

### ISSUE THREAD

**Issue by jayantj1j** [twintproject/twint#286]
# Issue Template
**py Twint.py -g=" 28.64386,77.12373 ,100km" -s "#airpollution" --since 2018-10-01 -o pollfile.csv --csv**
Ran this in cmd Win10(py3.6) on 7th NOV,2018.got data till 28thOCT,2018 when i use -g argument of geocode.Whats the fix I should look for?Also I cloned th erepo to my Pc on ^6th Nov,18
### Initial Check
> If the issue is a request please specify that it is a request in the title (Example: [REQUEST] more features). If this is a question regarding 'twint' please specify that it's a question in the title (Example: [QUESTION] What is x?). Please **only** submit issues related to 'twint'. Thanks.

>Make sure you've checked the following:

- [] Python version is 3.6;
- [] Updated Twint with `pip3 install --upgrade -e git+https://github.com/twintproject/twint.git@origin/master#egg=twint`;
- [] I have searched the issues and there are no duplicates of this issue/question/request.

### Command Ran
>Please provide the _exact_ command ran including the username/search/code so I may reproduce the issue.

### Description of Issue
>Please use **as much detail as possible.**

### Environment Details
>Using Windows, Linux? What OS version? Running this in Anaconda? Jupyter Notebook? Terminal?

**Comment by pielco11** [comment]
### Twitter Search Screenshot

![immagine](https://user-images.githubusercontent.com/17363750/48207307-a93d2880-e370-11e8-8a1a-5c605049d590.png)

So it seems that the Twitter search does not return other tweets, Twint is working correctly.

Do you know **for sure** that more tweets do exist?

**Comment by jayantj1j** [comment]
yes like i tested with some other hashtags too.When i use **near "NewDelhi"**  instead of geocode for delhi then so many tweets corresponding to that hashtag appear

**Comment by pielco11** [comment]
Let me re-elaborate.

Do you know for sure that more tweets with the same hashtag and with the same geocode do exist?

Also it's "strange" that using a point (New Delhi) that's in the area with center 28.64386,77.12373 and radius 100km, more tweets are returned. Anyway it's definitely an issue on Twitter side
