### ISSUE TITLE
Invalid syntax error when trying to run Twint.py

### ISSUE THREAD

**Issue by timothyjgraham** [twintproject/twint#288]
>Make sure you've checked the following:

- [x] Python version is 3.6;
- [x] Updated Twint with `pip3 install --upgrade -e git+https://github.com/twintproject/twint.git@origin/master#egg=twint`;
- [x] I have searched the issues and there are no duplicates of this issue/question/request.

### Command Ran
`python3 Twint.py -u SenatorAbetz --followers -o SenatorAbetz-followers.csv --csv`

### Description of Issue
When running the above command, I get the following error. This has happened on both my Ubuntu 16.04.4 server, and also my Macbook Pro (Mojave). 

```
Traceback (most recent call last):
  File "Twint.py", line 14, in <module>
    import twint
  File "/mnt/darren_data/src/twint/twint/__init__.py", line 11, in <module>
    from . import run
  File "/mnt/darren_data/src/twint/twint/run.py", line 13
    self.init = f"TWEET-{config.Resume}-0"
                                         ^
SyntaxError: invalid syntax
```

### Environment Details
Ubuntu 16.04.4 LTS
Terminal

**Comment by pielco11** [comment]
![immagine](https://user-images.githubusercontent.com/17363750/48232263-5041b480-e3b1-11e8-93ef-b79814ad2802.png)

Please be sure to run `Python 3.6.x`

**Comment by Chealkeo** [comment]
I met the same problem, have you solved that?

**Comment by pielco11** [comment]
@Chealkeo check your python version
