### ISSUE TITLE
[REQUEST] Get most popular tweets feature

### ISSUE THREAD

**Issue by carlosabcs** [twintproject/twint#291]
>Make sure you've checked the following:

- [x] Python version is 3.6;
- [x] Updated Twint with `pip3 install --upgrade -e git+https://github.com/twintproject/twint.git@origin/master#egg=twint`;
- [x] I have searched the issues and there are no duplicates of this issue/question/request.

### Description of Issue
I want to retrieve the most popular tweets only but I think Twint doesn't have this feature implemented yet.

**Comment by Slider-Whistle** [comment]
"Most popular" is pretty vague, unless Twitter explicitly marks some posts as being so. What you're probably looking for is filters related to favorites, "Impressions" (I think that's just views), or retweets right?

**Comment by pielco11** [comment]
The solution is present in the issue 371, I'm closing this to avoid duplicates.

Anyway, this feature is not implemented yet, but if you want to achieve it on your own code, there is the solution.
