### ISSUE TITLE
[DOCS] --users isn't recognized option even though it's in examples & docs

### ISSUE THREAD

**Issue by jvanalst** [twintproject/twint#299]
# Issue Template
Please use this template!

### Initial Check
> If the issue is a request please specify that it is a request in the title (Example: [REQUEST] more features). If this is a question regarding 'twint' please specify that it's a question in the title (Example: [QUESTION] What is x?). Please **only** submit issues related to 'twint'. Thanks.

>Make sure you've checked the following:

- [x] Python version is 3.6;
- [x] Updated Twint with `pip3 install --upgrade -e git+https://github.com/twintproject/twint.git@origin/master#egg=twint`;
- [x] I have searched the issues and there are no duplicates of this issue/question/request.

### Command Ran
>Please provide the _exact_ command ran including the username/search/code so I may reproduce the issue.

```
vanalsti@~$ twint -s "Donald Trump" --verified --users
usage: python3 twint [options]
twint: error: unrecognized arguments: --users
```

### Description of Issue
See above. --users doesn't work

### Environment Details
Mac OS X Mojave using CLI Twint

**Comment by jvanalst** [comment]
According to https://github.com/twintproject/twint/pull/287#issuecomment-440355921, this is an error in the documentation/examples.

See:
https://github.com/twintproject/twint/wiki/Commands

> --users | Display users only (Use with -s).

> python3 twint.py -s "Donald Trump" --verified --users - List verified users that Tweet about Donald Trump.

**Comment by pielco11** [comment]
Well, it's an error since to get tweets from verified users one just need to pass `--verified`

Thank you for notifying us

**Comment by pielco11** [comment]
UPDATE:

looking at the revisions of the wiki, it was added in the first review (when created the doc) and at the time `--users` did not exist, so I guess that's a typo

**Comment by pielco11** [comment]
More details:

`--users` was an argument to replace the output string with the username:
https://github.com/twintproject/twint/blob/73b33873ba49e1bb24c3db63fa76134f3f671b0e/tweep.py#L177-L178
To replicate this you have to specify `--format `, so something like `twint -s "trump" --verified --format "{username}"`
