### ISSUE TITLE
The problem is that it will bring back Twitter, which was first collected based on 20 criteria.

### ISSUE THREAD

**Issue by popohot2002** [twintproject/twint#300]
Hello, I have a problem about date.
Before I set 
c = twint.Config() 
c.Search = "topic's" 
c.Since = "yyyy-mm-dd" 
c.Until = "yyyy-mm-dd"
c.Format "{id}  {date}  {tweet}"
twint.Search(c)

and it works. but today I set for the purpose of creating a json file.

c = twint.Config() 
c.Search = "topic's" 
c.Since = "yyyy-mm-dd" 
c.Until = "yyyy-mm-dd"
c.Format "{id}  {date}  {tweet}"
c.store_json = True
c.Output = "result.json"
twint.Search(c)

The problem is that it will bring back Twitter, which was first collected based on 20 criteria.
What's wrong and how to fix it? plzzzz :(

**Comment by pielco11** [comment]
What the specific issue about date?
