### ISSUE TITLE
[BUG] list print's  <twint.tweet.tweet object at 0x000002164650AB70>

### ISSUE THREAD

**Issue by newpaulssmith** [twintproject/twint#301]
import twint

c = twint.Config()
c.Username = "twitter"
c.Limit = 10
c.Store_object = True
twint.run.Search(c)
tweets_as_objects = twint.output.tweets_object 
print (tweets_as_objects[1])

list print's

<twint.tweet.tweet object at 0x000002164650AB70>

no text

**Comment by pielco11** [comment]
A tweet is an objects, you have to access to its attributes like this `tweets_as_object[0].id` and this will return the id of the first scraped tweet.

https://github.com/twintproject/twint/blob/bab569029772d919b8a8fc162c70a1c2d279586b/twint/tweet.py#L62-L93
