### ISSUE TITLE
[ISSUE] Config.Since not working on Profile function

### ISSUE THREAD

**Issue by carlosabcs** [twintproject/twint#302]
- [x] Python version is 3.6;
- [x] Updated Twint with `pip3 install --upgrade -e git+https://github.com/twintproject/twint.git@origin/master#egg=twint`;
- [x] I have searched the issues and there are no duplicates of this issue/question/request.

### Command Ran
```python
  config = twint.Config()
  config.Username = "HuaweiMobilePE"
  config.Since = "2018-01-01"
  twint.run.Profile(config)
```

### Description of Issue
When running `twint.run.Profile()` the configuration parameter `Since` is not working, the tweets fetched are older than specified in the `Since` option.

### Environment Details
Fedora 29. Python 3.6.3.

**Comment by pielco11** [comment]
Now as now `Since` is a parameter of the query for fetching data from Twitter Advanced Search, I think that the solution could be quite hard to implement since Twint is scraping the user timeline
