### ISSUE TITLE
[REQUEST] Tweet Threads

### ISSUE THREAD

**Issue by DanilKonon** [twintproject/twint#303]
Is is possible to extract whole twitter threads? Or at least know to what tweet a reply was made?

**Comment by pielco11** [comment]
In red you see the single tweet, in cyan you see the twitter thread (a.k.a. conversation).

![immagine](https://user-images.githubusercontent.com/17363750/49141268-80b4a880-f2f6-11e8-9fd8-f9734c16badb.png)

At the moment we can't extract entire threads

**Comment by DanilKonon** [comment]
Thank you!
