### ISSUE TITLE
[BUG] cli missing in 1.2.0.0?

### ISSUE THREAD

**Issue by edsu** [twintproject/twint#304]
When installing with pipenv the CLI is not available.

    % pipenv install twint
    % twint -u barackobama
    bash: twint: command not found

However when installing directly from GitHub the command is installed:

    % pipenv install -e git+https://github.com/twintproject/twint.git#egg=twint

Perhaps the latest code needs to be released to PyPI?

**Comment by kanihal** [comment]
What is the expected release date for the next release?
