### ISSUE TITLE
Loop 

### ISSUE THREAD

**Issue by SeanMcElwee** [twintproject/twint#305]
### Initial Check
> If the issue is a request please specify that it is a request in the title (Example: [REQUEST] more features). If this is a question regarding 'twint' please specify that it's a question in the title (Example: [QUESTION] What is x?). Please **only** submit issues related to 'twint'. Thanks.

>Make sure you've checked the following:

- [] Python version is 3.6; done
- [] Updated Twint with `pip3 install --upgrade -e git+https://github.com/twintproject/twint.git@origin/master#egg=twint`; done
- [] I have searched the issues and there are no duplicates of this issue/question/request. done

### Command Ran
```python
from __future__ import print_function
import os
import sys
import subprocess
import datetime
import twint 
import pandas as pd
usernames = ["chrislhayes"]
colrn     ={0:"id",1:"date",2:"time",3:"username",4:"tweet",5:"replies",6:"retweets",7:"likes",8:"user_rt",9:"hashtags"}

for u in usernames:
    c = twint.Config()
    c.Username = u
    c.Store_csv = True
    c.Timedelta = 1
    c.Since = "2016-01-01"
    c.Store_csv = True
    c.Custom = ["id","date","time","username","tweet","replies","retweets","likes","user_rt","hashtags"]
    c.Output = u+".csv"

    # Run
    twint.run.Search(c)
    df = pd.read_csv(u+".csv")
    df["accountName"] = u
    df.to_csv(u+".csv",index=False)
    print(out)
```
### Description of Issue
> I get stuck in an endless loop (I posted a video in the Slack, wasn't sure if I was supposed to). 

### Environment Details
> ubuntu 16.04

**Comment by pielco11** [comment]
Hi @SeanMcElwee ,

I do not find your video on Slack, may you provide me a link to it?

**Comment by SeanMcElwee** [comment]
Yes. Apologies for the delay. @pielco11 Does this work? https://drive.google.com/file/d/1j6NSqu_S591Ks5Qxn0mw7CPpUmIjNz_X/view?usp=sharing

**Comment by pielco11** [comment]
Hello,

the video is not loading and I know for sure that my end is ok. May you share somewhere else?

**Comment by NoSuck** [comment]
The video did not load for me, either, but I was able to download and view it locally by clicking the download button.  The video seems to show terminal output of a series of eight or so tweets being downloaded endlessly.  Not much else is discernible.

**Comment by pielco11** [comment]
I tried the query and Twint does not replicate the issue. I suppose that's not related to Twint, so I'm closing this
