### ISSUE TITLE
Tweets.csv doesn't contain media information (gif, video)

### ISSUE THREAD

**Issue by filletofish** [twintproject/twint#306]
Hi!

Thank you for your work. I have just found out that parsed data in `tweets.csv` doesn't contain any information about such media as GIF or Video. There is nothing in field `photos` and `links`. As far I got from `tweet.py` file this feature is not implemented yet.  I find it quite useful.
Is there any workaround?

As for example I used this tweet https://twitter.com/redbullracing/status/1054097253860818944

My script:
```python
import twint
c = twint.Config()
c.Username = "redbullracing"
c.Store_csv = True
c.Since = "2018-10-12"
c.Until = "2018-11-18" 
c.Format = "Tweet id: {id} | Date: {date} | Time: {time} | Username: {username} | User_id: {user_id} | Tweet: {tweet} | Hashtags: {hashtags} | Replies: {replies} | Retweets: {retweets} | Likes: {likes} "
c.Output = c.Username + ".csv"
twint.run.Search(c)
```

**Comment by andytnt** [comment]
Hi!
It is not possible to scrape video information. In order to get tweet video information you have to use Twitter API.

**Comment by filletofish** [comment]
@andytnt even the fact that the video or gif exists?

**Comment by andytnt** [comment]
Twitter API provides so much information that twint doesn't, if you definitely need video information you  have to use Twitter API. Also if you're making API requests just to get video information of a tweet you would be wasting your API calls and the rest of information which Twitter API provides. 
Maybe Twitter Streaming API is what you're looking for? 
Just curious, why do you need video information?

**Comment by filletofish** [comment]
@andytnt Thank you. I will take a look.

My plan was to analyse if a picture, video or gif has impact on number of likes / mentions / retweets the tweet gets. So, in my case I don't need all video information, just the fact that video or gif is used.

**Comment by andytnt** [comment]
I thought you were looking for video information. 
If you just need to know video or GIF is used, you can check for those specific selectors, if it is present return 1 else 0. https://github.com/twintproject/twint/blob/master/twint/tweet.py#L62
You wanna make a PR?

**Comment by filletofish** [comment]
Thank you! I will take a look and come back if I have any solution or PR.

**Comment by andytnt** [comment]
4a16ca1
