### ISSUE TITLE
Twitter´s Copyright

### ISSUE THREAD

**Issue by DavidPerea** [twintproject/twint#313]
In these days, I have a doubt, that I would like, if possible, that you solve me.

It's about the the tweets´s copyrights. Can a tweet be protected by copyright? Are the tweets´s data open data? Is it legal to scraper the tweets, as we are doing through Twint?

I would also like to know if this tool, Twint, tracks tweets directly from Twitter, right?

**Comment by pielco11** [comment]
![immagine](https://user-images.githubusercontent.com/17363750/49931604-8948d980-fec7-11e8-8802-0013dabd2dbd.png)

Twint does not scrape copyrighted tweets

As you may see in the code, Twint gets tweets from Twitter

**Comment by DavidPerea** [comment]
Okay!!, I understand it. So not all tweets are copyrighted, right?. that doubt has arisen me. To whom does the tweets belong? Are they open data?

**Comment by pielco11** [comment]
You should check tweet by tweet (not from the output or something provided by Twint) and see who they belong to.
