### ISSUE TITLE
Rate Limit

### ISSUE THREAD

**Issue by jewl123** [twintproject/twint#315]
Every time I run twint it stops at about 800 tweets !
Or if I use Profile_full it stops at about 3,000 tweets !
Please Help

Thanks :)

**Comment by pielco11** [comment]
Probably Twitter temporarily suspends your IP

About `Profile_full`:
![immagine](https://user-images.githubusercontent.com/17363750/50106237-93543a80-022f-11e9-80bb-16f6c37a2313.png)

**Comment by jewl123** [comment]
Do you think using a vpn would help solve this issue ?

**Comment by pielco11** [comment]
No problem, if you want we have Slack to discuss in a back-and-forth way. Just in case you could need it

**Comment by jewl123** [comment]
Thanks, ill try the proxies and get back to you
