### ISSUE TITLE
twint.run.Followers() returns "list index out of range [x] feed.Follow" errors before terminating

### ISSUE THREAD

**Issue by IvanTrendafilov** [twintproject/twint#316]
### Initial Check
> If the issue is a request please specify that it is a request in the title (Example: [REQUEST] more features). If this is a question regarding 'twint' please specify that it's a question in the title (Example: [QUESTION] What is x?). Please **only** submit issues related to 'twint'. Thanks.

>Make sure you've checked the following:

- [x] Python version is 3.6;
- [x] Updated Twint with `pip3 install --upgrade -e git+https://github.com/twintproject/twint.git@origin/master#egg=twint`;
- [x] I have searched the issues and there are no duplicates of this issue/question/request.

### Command Ran
>Please provide the _exact_ command ran including the username/search/code so I may reproduce the issue.

```
import twint
c = twint.Config()
c.Username = "mseiler1"
twint.run.Followers(c)
```

### Description of Issue

Running the above, a bunch of followers are dispayed, before the program terminates with this:

```
BickersKnickers
soldiagrl269
list index out of range [x] feed.Follow
ndouthat
hirecube
ScrimpleCoupons
Zoudini
idanbeck
CROTTY
CrottyFarmRepor
cowinkidink
maui2010
kellyhotta
ms_shuangmeng
entryboard
nycbonnie
wiggio
anrahman
BobbyKen
list index out of range [x] feed.Follow
```

### Environment Details
Ubuntu 16.04 LTS

**Comment by pielco11** [comment]
## Please check before reporting an issue, thank you for your cooperation! 
![immagine](https://user-images.githubusercontent.com/17363750/50171718-7f720c80-02f3-11e9-9f0d-c23091807d17.png)

**Comment by IvanTrendafilov** [comment]
so, you're saying throwing `list index out of range [x] feed.Follow` twice is the expected mode of operation?

**Comment by IvanTrendafilov** [comment]
it sounds like: a) you should not display this error b) you should display a message for successful completion c) you should at least not display it 2 times or some combination of (a), (b), (c).

**Comment by pielco11** [comment]
Every follower has been successfully scraped so, I guess, that there are not "concrete" errors. 
Hiding exceptions is not a practice that I think should be implemented (at least not everywhere).

In details, this issue is happening because Twitter is returning 20 users at a time and less are returned when, instead, the same quantity is expected (not on Twint side)
