### ISSUE TITLE
[REQUEST] Fetch over Tor

### ISSUE THREAD

**Issue by nsuchy** [twintproject/twint#322]
This is a feature request. I would like to see a `--tor` flag which connects to the system's tor daemon and fetches data over Tor for additional privacy and anonymity. Is this something the developers would consider adding?

**Comment by pielco11** [comment]
https://github.com/twintproject/twint/blob/653de504f7a7d65ec1dabf0cc67b141555780009/twint/get.py#L23-L28

**Comment by nsuchy** [comment]
@pielco11 Can you use that by tying `--tor` into the command line as you run your command or do you have to edit the config?

**Comment by pielco11** [comment]
@nsuchy `twint --proxy-host tor -u username`

**Comment by nsuchy** [comment]
I think that works for me, I still think a `--tor` flag would still be nice and a bit faster to type (more consistent with other scripts I've used) but I am closing this issue as it's already possible to fetch over Tor.

**Comment by pielco11** [comment]
I understand but adding this option could be a replica of something already implemented. If other users will report our solution confusing or something, I'll edit this. For now I would like to keep code as is
