### ISSUE TITLE
Pandas version compatible issue  

### ISSUE THREAD

**Issue by makcedward** [twintproject/twint#330]
Thank you providing this great library. It may our life easier. 

Since I installed pandas for a long time, I noticed that the latest version of twint have to work with pandas >=0.23. "Sort" feature in concat is new in version 0.23. If pandas version is < 0.23, error will be thrown. 

https://github.com/twintproject/twint/blob/653de504f7a7d65ec1dabf0cc67b141555780009/twint/storage/panda.py#L34

[Pandas Concat API](https://pandas.pydata.org/pandas-docs/version/0.23.4/generated/pandas.concat.html)

**Comment by pielco11** [comment]
Hi @makcedward 

and thank you for reporting, for now I'm going to specify the version that needs to be used

**Comment by pielco11** [comment]
I specified `pandas>=0.23.0`, should be fine!

If anyone gets issues about this, just reopen and comment!
