### ISSUE TITLE
How much time does the compiling / installation process require? pip3 has been building for an hour now on raspbian.

### ISSUE THREAD

**Issue by github-userx** [twintproject/twint#331]
# Issue Template
Please use this template!

### Initial Check
> If the issue is a request please specify that it is a request in the title (Example: [REQUEST] more features). If this is a question regarding 'twint' please specify that it's a question in the title (Example: [QUESTION] What is x?). Please **only** submit issues related to 'twint'. Thanks.

>Make sure you've checked the following:

- [X] Python version is 3.6;
- [] Updated Twint with `pip3 install --upgrade -e git+https://github.com/twintproject/twint.git@origin/master#egg=twint`;
- [] I have searched the issues and there are no duplicates of this issue/question/request.

### Command Ran
>Please provide the _exact_ command ran including the username/search/code so I may reproduce the issue.

    virtualenv --python=python3.6 twint
    cd twint
    .activate/bin
    pip install twint

### Description of Issue
>Please use **as much detail as possible.**

### Environment Details
>Using Windows, Linux? What OS version? Running this in Anaconda? Jupyter Notebook? Terminal?

**Comment by github-userx** [comment]
Edit: after four hours the installation and compiling finished 'successfully' but when having the virtual python environment activated, it doesn't find the command *twint* at all.

When I try a
    pip install twint

Again in the environment, then it will tell be that all the requirements are already satisfied and installed.

**Comment by pielco11** [comment]
Instead of `pip install twint` do `pip3 install --upgrade -e git+https://github.com/twintproject/twint.git@origin/master#egg=twint`

**Comment by github-userx** [comment]
@pielco11

Will do and try that.

But when activating the virtual environment that we specified before should use python3, this will automatically lead to the pip command using pip3/python3 in my experience. No?

**Comment by pielco11** [comment]
@github-userx that's correct
