### ISSUE TITLE
c.Since not working

### ISSUE THREAD

**Issue by arasselvi** [twintproject/twint#334]
### Initial Check
- [] Python version is 3.6;
- [] Updated Twint with `pip3 install --upgrade -e git+https://github.com/twintproject/twint.git@origin/master#egg=twint`;
- [] I have searched the issues and there are no duplicates of this issue/question/request.

### Command Ran
c = twint.Config()
c.Username = 'elonmusk'
c.Since = "2019-01-01"
twint.run.Search(c)

### Description of Issue
Same tweets between 13-17 January '19 are given forever. It does not stop. I just want to have all the tweets of a given username.  Until, Since commands are not working. Also, once it gave random tweets from Twitter which are not relevant to the username I gave (at all). I think there is some bug going on.

Also, if I try twint.run.Lookup(c), I get "AttributeError: module 'twint.run' has no attribute 'Lookup'"

### Environment Details
>Windows 10. Ran in PyCharm. Same problem arises in Jupyter notebook.

**Comment by arasselvi** [comment]
Updated twint. It works now.

**Comment by xxshazxx** [comment]
Hi,
I've pulled the latest version yesterday and if I use the following code:
`
            c = twint.Config()
            c.To = u_twitter
            c.Search_name = u_id
            c.Elasticsearch = "192.168.1.118:9200"
            c.Index_tweets = db_tweets
            c.Index_users = db_tweets_users
            c.User_full = False
            c.Since = "2018-10-01"
            #c.Until = until_date
            try:
                twint.run.Search(c)
`
I get tweets before the date set, for example I have entries for 2018-01-01.
Am I doing something wrong here?

Thanks

**Comment by pielco11** [comment]
Hi @xxshazxx 
your code is correct, it seems to be something wrong with Twitter. I have it working correctly so I guess that it's not an issue with Twint

![image](https://user-images.githubusercontent.com/17363750/51800534-92e88f80-2230-11e9-904c-78e367d71ddc.png)

**Comment by xxshazxx** [comment]
Thanks a lot for checking. Would you mind in trying with a different user?
I've tried with "realDonaldTrump" and it doesn't seem to stop, while using "noneprivacy", it stops.

Thank you
