### ISSUE TITLE
[QUESTION] Is there a proper way to cite Twint for research purposes?

### ISSUE THREAD

**Issue by CarbuncleOrigin** [twintproject/twint#335]

**Comment by pielco11** [comment]
Honestly I do not know. Twitter does not allow automated scraping processes, on the other side what Twint automates is just scrolling down, which is like keeping the arrow-down held down. So for Twitter scrolling down with arrow-down held down, violates the TOS.

If you search tweets, manually with your browser, via Twitter Advanced Search and keep "automatically" scrolling down, Twitter says that you are violating TOS

It's up to you decide if this _modus operandi_ is "ethical" and respects the academics rules
