### ISSUE TITLE
[ QUESTION ] Many parameters

### ISSUE THREAD

**Issue by xxshazxx** [twintproject/twint#339]
Hello,

what happens if I run the following code ?

> d = twint.Config()
> d.Username = "noneprivacy"
> d.Search_name = "1234567"
> d.User_full = False
> d.Since = "2019-01-01"
> try:
>     twint.run.Search(d)

Is the parameter Search_name used or only Username is taken as parameter?

Thanks

**Comment by pielco11** [comment]
Hi,

what do you mean with `Search_name`? If you want tweets of a specific user, just specify `c.Username`
