### ISSUE TITLE
[Question] - problems when running module example for Followers

### ISSUE THREAD

**Issue by five0h302** [twintproject/twint#343]
All pre-checks have been done and TWINT is updated.

**Command Ran**: 
import twint
c = twint.Config()
c.Username = "twitter"
c.User_full = True
c.Format = "Username: {username} | Bio: {bio} | Url: {url}"
twint.run.Followers(c)

**Description of Issue**
I've been able to use many of the other module features without  problems, but when I try to pull data using the Followers moules I don't have as much luck.  I've tried to research the problem, but so far I've hit a wall.  Welcome your help since clearing I am doing something wrong.  When I run the above I get the following:

(base) C:\Users\Computer\Desktop\twint-master\twint>python testing.py
'NoneType' object is not subscriptable [x] get.User
'NoneType' object is not subscriptable [x] get.User
'NoneType' object is not subscriptable [x] get.User
'NoneType' object is not subscriptable [x] get.User
'NoneType' object is not subscriptable [x] get.User
'NoneType' object is not subscriptable [x] get.User
'NoneType' object is not subscriptable [x] get.User
'NoneType' object is not subscriptable [x] get.User
'NoneType' object is not subscriptable [x] get.User
'NoneType' object is not subscriptable [x] get.User
replace() argument 2 must be str, not None [x] get.User
'NoneType' object is not subscriptable [x] get.User
replace() argument 2 must be str, not None [x] get.User
'NoneType' object is not subscriptable [x] get.User
'NoneType' object is not subscriptable [x] get.User
'NoneType' object is not subscriptable [x] get.User
'NoneType' object is not subscriptable [x] get.User
'NoneType' object is not subscriptable [x] get.User
'NoneType' object is not subscriptable [x] get.User
'NoneType' object is not subscriptable [x] get.User
'NoneType' object is not subscriptable [x] get.User
'NoneType' object is not subscriptable [x] get.User
'NoneType' object is not subscriptable [x] get.User
'NoneType' object is not subscriptable [x] get.User

However, sometimes it will work and the formatted output just repeats itself, such as: 

 Bio: 702346349161754624Username: mimippiii | Bio: 702346349161754624Username: mimippiii | Bio: 702346349161754624Username: {username} | Bio: 702346349161754624Username: {username} | Bio: 702346349161754624Username: mimippiii | Bio: 702346349161754624Username: mimippiii | Bio: 702346349161754624Username: {username} | Bio: 702346349161754624Username: {username} | Bio: 702346349161754624Username: mimippiii | Bio: 702346349161754624Username: mimippiii | Bio: 702346349161754624Username: {username} | Bio: 702346349161754624Username: {username} | Bio: 702346349161754624Username: mimippiii | Bio: 702346349161754624Username: mimippiii | Bio: 702346349161754624Username: {username} | Bio: 702346349161754624Username: {username} | Bio: 702346349161754624Username: mimippiii | Bio: 702346349161754624Username: mimippiii | Bio: 702346349161754624Username: {username} | Bio: 702346349161754624Username: {username} | Bio: 702346349161754624...…………...
>Using Windows 10 on the Anaconda prompt.

**Comment by pielco11** [comment]
I guess that the issue is caused by the `c.Format` line. If I exclude it, Twint works correctly. Fortunately the issue is not in the selectors and this makes the fix "easier".

For now I suggest you to remove that line, until I do not fix it.

Thank you for patience!

**Comment by five0h302** [comment]
Thank you for taking the time to look into this.  I will work around the c.Format line. 

Thanks again.

**Comment by adnanmig** [comment]
I hve a similar issue when using the command: 
twint -u uname -o output.csv --csv
the username has an underscore at the end of the name.

**Comment by pielco11** [comment]
@adnanmig what's you actual issue? If it's not related to this, please open a new issue

**Comment by adnanmig** [comment]
I receive the same error as mentioned in the original post when running the command:
twint -u uname -o output.csv --csv
with the latest TWINT ona fresh install.

**Comment by pielco11** [comment]
@adnanmig 

![immagine](https://user-images.githubusercontent.com/17363750/57091409-68174700-6d09-11e9-9823-67aa275179b0.png)

**Comment by ervlh** [comment]
Same problem, 
I remove c.Format line, but it still not work.
`'NoneType' object is not subscriptable [x] get.User` err

**Comment by pielco11** [comment]
With every username?
-------- Messaggio originale --------
On 6 Giu 2019, 08:13, ervlh ha scritto:

**Comment by ervlh** [comment]
@hpiedcoq pei
some username work well, other Non.
Have you implement any method to fetch infos for a list of users?

**Comment by pielco11** [comment]
You can iterate over a list with Twint as module, or do some shell scripting via CLI

I'm going to try with some users and see what happens when it crashes
-------- Messaggio originale --------
On 6 Giu 2019, 11:05, ervlh ha scritto:

**Comment by ervlh** [comment]
Thank for your answer. 
I tried iterate the list with `Lookup` method, and see other problem with output data.
I config c.Pandas = True, then try to get twint.storage.panda.User_df as the output for each item. 
May we use twint.storage.panda.clean() inside the loop?

**Comment by pielco11** [comment]
This should do what you need
```python
import twint

c =twint.Config()
c.Username = "username1"
c.Pandas = True
twint.run.Lookup(c)

twint.storage.panda.User_df = None
c.Username = "username2"
twint.run.Lookup(c)
df = twint.storage.panda.User_df
print(df)
```

So for every username which you want iterate over, you have to reset the `User_df`

**Comment by ervlh** [comment]
@pielco11 
Thanks very much,
I tried `twint.storage.panda.clean()` and it work well.
