### ISSUE TITLE
Cant fetch user profile

### ISSUE THREAD

**Issue by tiwaryshailesh** [twintproject/twint#348]
- [CHECKED] Python version is 3.6;
- [DONE] Updated Twint with `pip3 install --upgrade -e git+https://github.com/twintproject/twint.git@origin/master#egg=twint`;
- [NO] I have searched the issues and there are no duplicates of this issue/question/request.

### Command Ran
>twint -u iamsrk --user-full

### Description of Issue
doesnt give any output.
rest twint commands running fine

### Environment Details
Linux 4.15.0-38-generic #41-Ubuntu SMP Wed Oct 10 10:59:38 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

Distributor ID: Ubuntu
Description:    Ubuntu 18.04.1 LTS
Release:        18.04
Codename:       bionic

Python 3.6.7

**Comment by pielco11** [comment]
I tested and I can confirm that's not working
