### ISSUE TITLE
[QUESTION] is there a way to get the number of likes and retweets for given tweet within a given period?

### ISSUE THREAD

**Issue by lmonninger** [twintproject/twint#349]
Just had a quick question here: Is there a way, using twint, to get the number of likes and retweets for given tweet within a given period?

**Comment by pielco11** [comment]
The `get-retweets` feature is currently broken

Anyway you should get the tweets first, and then filter them out

Currently a solution where you specify the date range and get the tweets that match that request, it's not available

We could do no more than filter them out while scraping, so something like automating the filtering-out process. In this case, if you would be interested in the retweets of a specific user in the year 2016, you  would still have to get every-single-tweet until that year.
