### ISSUE TITLE
Cannot create csv file

### ISSUE THREAD

**Issue by j1wonkim** [twintproject/twint#353]
# Issue Template
Please use this template!

### Initial Check
> If the issue is a request please specify that it is a request in the title (Example: [REQUEST] more features). If this is a question regarding 'twint' please specify that it's a question in the title (Example: [QUESTION] What is x?). Please **only** submit issues related to 'twint'. Thanks.

>Make sure you've checked the following:

- [V] Python version is 3.6;
- [V] Updated Twint with `pip3 install --upgrade -e git+https://github.com/twintproject/twint.git@origin/master#egg=twint`;
- [V] I have searched the issues and there are no duplicates of this issue/question/request.

### Command Ran
>Please provide the _exact_ command ran including the username/search/code so I may reproduce the issue.
>>> import twint, os, sys
>>> os.environ['TWINT_DEBUG']='debug'
>>> c=twint.Config()
>>> c.Username="user_name"
>>> c.Search="#hashtag"
>>> c.Store_csv=True
>>>c.Output="user_name_#hashtag.csv"
>>> c.Since="2014-01-01"
>>> c.Until="2016-12-31"
>>> twint.run.Search(c)

### Description of Issue
>Please use **as much detail as possible.**
1) The code runs.
2) When i put the following, it gives me the path.
>>>os.path.abspath("user_name_#hashtag.csv")
3) However, when I go to the location, there is no such file.
4) I have tried the same code multiple times, and it succeeded in some times (created the csv after 4 hours) and failed in some times.

### Environment Details
>Using Windows, Linux? What OS version? Running this in Anaconda? Jupyter Notebook? Terminal?
Windows, IDLE, ver.3.6.6.
Thank you very much in advance.
- [ ]

**Comment by pielco11** [comment]
That's not an issue with Twint

In python comments are started by a `#`. Just change `c.Output="user_name_#hashtag.csv"` to `c.Output="user_name_hashtag.csv"` and it will work

**Comment by j1wonkim** [comment]
Hi, thanks for the prompt response! I really appreciate it.
I wonder why that would be a matter, when it is in "quote".
However, I tried your suggestion, but it is still not working. Do you have any other insight on this?

**Comment by pielco11** [comment]
Wait, I do have to correct what I said.

I retried it now and your code is correct (I tested with different users). So placing `#` inside quotes is syntactically **correct**.

So I guess that the issue resides in the query. Did you try a manual search with Twitter Advanced Search to be sure that there are tweets to get?

**Comment by j1wonkim** [comment]
Thanks a lot for your comment! I am grateful for your responsiveness and goodwill for the community.

To my best knowledge, if I run Twitter Advanced Search with the above conditions, it will not return me anything, because the timeframe I am looking within exceeds the most recent 3200 tweets of the account (the accounts are government municipalities' official accounts, so they tweet very often.)
Consistent with the assumption, the Twitter Advanced Search did not give me any output. However, I am still unsure whether this is because there are no tweets out there because 1) I tried with different IDs and different keywords and all of them gives output of zero, and it is impossible that none of them has no tweet match; 2) More specifically about why I think it's impossible to have no match- when I scraped with R with the same conditions but within their most recent 3200 tweets (API limit), it rendered a ton.

I am confused about how the Advanced Search works though. Even when I search without the time filter but only usernames and keywords, it does not give any result (when R scraped a ton, altho within the most recent 3200, with the same filter). Why...?

To give you a better context, I am looking at municipalities of Brazil: @Profeitura_Rio @PrefGru_Oficial @prefdeteresina, from 2014-01-01 to 2016-12-31, with a bag of keywords like mcmv, Minha Casa Minha Vida, casas, entregas, chaves.

Thanks a lot!!

**Comment by pielco11** [comment]
I tried your queries and fortunately it's not an issue with Twint

The first user, Profeitura_Rio, does not exist.

The second, PrefGru_Oficial, exists but joined in May 2017

The third, prefdeteresina, joined in April 2018

**Comment by j1wonkim** [comment]
Oh, I am sorry. That was a typo. It's @Prefeitura_Rio.
Thanks for the insights about PrefGru_Oficial and prefdeteresina!

**Comment by pielco11** [comment]
With the username `Prefeitura_Rio` I get tweets in the specified date range

**Comment by j1wonkim** [comment]
I'm assuming that you mean you can save it in a csv file also.
It must not be the package then... thanks!
