### ISSUE TITLE
CSV turns the tweet id into a floating-point number

### ISSUE THREAD

**Issue by NewCTwo** [twintproject/twint#355]
# Issue Template
Please use this template!

### Initial Check
> If the issue is a request please specify that it is a request in the title (Example: [REQUEST] more features). If this is a question regarding 'twint' please specify that it's a question in the title (Example: [QUESTION] What is x?). Please **only** submit issues related to 'twint'. Thanks.

>Make sure you've checked the following:

- [V] Python version is 3.6;
- [V] Updated Twint with `pip3 install --upgrade -e git+https://github.com/twintproject/twint.git@origin/master#egg=twint`;
- [V I have searched the issues and there are no duplicates of this issue/question/request.

### Command Ran
>Please provide the _exact_ command ran including the username/search/code so I may reproduce the issue.

 twint -u redacted --videos -o AT_redacted_video.csv --csv

### Description of Issue
I saved some media tweets as csv, and when I opened the file it had turned the twitter IDs:

    791557233689870338 2016-10-25 19:21:56 EST 
    761762492475842560 2016-08-04 20:45:38 EST 
    753254411990736897 2016-07-14 20:53:50 EST 
    692703645437677568 2016-01-26 10:18:20 EST 

into weird scientific floats:

    7.9155723368987E+017	7.9105723368986E+017	1477437710000	2016-10-25	19:21:56	EST
    7.61762492475843E+017	7.61361592436943E+017	1470357930000	2016-08-04	20:45:38	EST
    7.53254411990737E+017	7.53754411990735E+017	1468544130000	2016-07-14	20:53:50	EST
    6.92703645437678E+017	6.91993044153970E+017	1453821000000	2016-01-26	10:18:20	EST

### Environment Details

Ubuntu 18.04 Terminal

**Comment by pielco11** [comment]
Which software did you use to open the csv file?

**Comment by NewCTwo** [comment]
LibreOffice

**Comment by pielco11** [comment]
You need to change the way that LibreOffice handles csv files
