### ISSUE TITLE
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host mobile.twitter.com:443 ssl:True [Connect call failed

### ISSUE THREAD

**Issue by mysstyle** [twintproject/twint#356]
code:
import twint
import aiohttp
c = twint.Config()
c.Username = "twitter"
c.User_full = True
c.Format = "Username: {username}"
c.Output = "users.csv"
twint.run.Followers(c)

error:
CRITICAL:root:twint.get:User:Cannot connect to host twitter.com:80 ssl:True [Connect call failed ('', 80)]
Cannot connect to host twitter.com:80 ssl:True [Connect call failed ('', 80)] [x] get.User
Traceback (most recent call last):
 
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host mobile.twitter.com:443 ssl:True [Connect call failed ('', 443)]

**Comment by pielco11** [comment]
It seems that there are connections issue between you and Twitter. The code works correctly

**Comment by R6Six** [comment]
Hi，have you solved it? 
I have a same problem with you. I've used a VPN and it can reach Twitter's website. But Twink just can't work. I  don't know how to solve it.
