### ISSUE TITLE
[QUESTION] Cannot create index pattern

### ISSUE THREAD

**Issue by jordanhimawan** [twintproject/twint#357]
Hello,
I've encountered some problems when setting up Kibana:
I've done the steps to setup Kibana as shown in this link https://github.com/twintproject/twint/wiki/Elasticsearch. On the third step, when I want to create index pattern, I cannot find the "Index Pattern: twint" stuff. How can I solve this problem?
Thanks.

I'm using Ubuntu 18.04

**Comment by pielco11** [comment]
Hello,

with the latest updates of Twint everything is made easier. I suggest you to delete the created index:
![immagine](https://user-images.githubusercontent.com/17363750/52845548-b1db9280-3107-11e9-9020-2b94f95994af.png)

And proceed with the updated Wiki (which I updated a couple of minutes ago).
The old way was causing issues with a couple users, now it's made simpler

Please be sure to have installed Twint with `pip3 install --upgrade -e git+https://github.com/twintproject/twint.git@origin/master#egg=twint`

**Comment by jordanhimawan** [comment]
I've done the new steps described in the wiki.
A new problem comes, however.

It seems that the result doesn't take place as it is supposed to be.

![screenshot from 2019-02-16 00-35-15](https://user-images.githubusercontent.com/15666240/52873991-e80a2800-3182-11e9-8d64-3d21cf4898bc.png)
 
Is there anything to do?

**Comment by pielco11** [comment]
Top right corner, change "last 15 minutes" to a different time-range

**Comment by jordanhimawan** [comment]
It works!

Thank you for your support. I really appreciate it.

**Comment by pielco11** [comment]
Great, for other questions just open a new issue or contact me via Slack or Twitter!
