### ISSUE TITLE
[Question] Connection timeout 

### ISSUE THREAD

**Issue by Aassifh** [twintproject/twint#358]
Im having this error at each time i run the script that scraps tweets for a username given : 

elasticsearch.exceptions.ConnectionTimeout: ConnectionTimeout caused by - ReadTimeoutError(HTTPConnectionPool(host='localhost', port=9200): Read timed out. (read timeout=200))

can i have some clarification for what can be the source of the error ! thanks

**Comment by pielco11** [comment]
Did you specify `config.Elasticsearch` somewhere?

**Comment by Aassifh** [comment]
I just wrote  (c.Elasticsearch = "localhost")  is there any config needed in order to make it work ?

**Comment by pielco11** [comment]
Elasticsearch needs both the `host` and the `port`. Use, for example, `config.Elasticsearch = "localhost:9200"`

**Comment by Aassifh** [comment]
``for hit in res['hits']['hits']:
        print(hit['_source']['username'])
        c = twint.Config()
        c.Username = hit['_source']['username']
        # c.Debug = True
        c.Since = (datetime.now() - timedelta(days=365)).date().__str__()
        # c.Store_json = True
        # c.Output = "output"
        c.Limit = 100
        c.Location = False            
        c.Elasticsearch = "localhost:9200"
        twint.run.Search(c)``

**Comment by Aassifh** [comment]
```python 
for hit in res['hits']['hits']:
        c = twint.Config()
        c.Username = hit['_source']['username']
        # c.Debug = True
        c.Since = (datetime.now() - timedelta(days=365)).date().__str__()
        # c.Store_json = True
        # c.Output = "output"
        c.Limit = 100
        c.Location = False            
        c.Elasticsearch = "localhost:9200"
        twint.run.Search(c)``

So this the code that im runinng in a scrolling loop that fetchs data from another index to get tweets by username. I changed the chunk_size in the bulk function also request_timeout and my heapspace configuration but i always get the Read time out, is there any possible solution please ?

**Comment by pielco11** [comment]
I think that this issue is not related to Twint, your code works on my end
