### ISSUE TITLE
[Question] Scrapping tweets for a large amount of users

### ISSUE THREAD

**Issue by Jordan9675** [twintproject/twint#360]
# Issue Template
Please use this template!

### Initial Check
> If the issue is a request please specify that it is a request in the title (Example: [REQUEST] more features). If this is a question regarding 'twint' please specify that it's a question in the title (Example: [QUESTION] What is x?). Please **only** submit issues related to 'twint'. Thanks.

>Make sure you've checked the following:

- [x] Python version is 3.6;
- [x] Updated Twint with `pip3 install --upgrade -e git+https://github.com/twintproject/twint.git@origin/master#egg=twint`;
- [x] I have searched the issues and there are no duplicates of this issue/question/request.

Hi everyone, I'm a newbie to Twint and I honestly don't exactly get how to use it.
I'm doing an academic research and for this purpose, I need to scrap the tweets from a large number of users (around 1400), but I didn't find a way to do this.

I've been trying to run the following command on my Mac's terminal :

twint -userlist user1,user2,user3...user1400 -o filename.csv --csv

However, I get a "CRITICAL:root:twint.run:Twint:Feed:noData'items_html'" error which is not the case when I'm running the same command with a reduced amount of users.

Hence, I'd like to know if there was any way to scrap tweets for a high amount of users.

Ideally, I'd love to find a way to implement a loop on Python (Anaconda) so that the datas obtained would immediately be stored in my MongoDB database instead of being written on a csv file.

Thanks by advance !

**Comment by pielco11** [comment]
Hi @Jordan9675 

I got issues while scraping tweets from more than ~20 selected users, you can check this manually playing with the Twitter Advanced Search. Just fill the "from user" field and when you will not get more tweets, that will be the limit.

About MongoDB, currently that storing option is not handled, but Pull Requests are open. You could just create a file in `twint/storage/` that contains every function needed to save tweets into a MongoDB database. Then in `twint/output.py` you will have just to import that file and call the functions as done for the other storing options. If this second part sounds hard to you, I can handle it.

**Comment by Jordan9675** [comment]
Sorry for responding that late @pielco11 but I finally found a way to do what I wanted. I simply had to made a loop on python using the Twint Module to scrap all the tweets' id from the desired users, to store them in a csv file and to use Twitter API to collect all the tweets I need.

Thanks for your answer though !

**Comment by antoinecomp** [comment]
Ok, I'm trying to take care of it. At least for the Tweets.

In `twint/storage/` I created a file which looks like `elasticsearch.py`, where replaced:

```
    es = Elasticsearch(config.Elasticsearch, verify_certs=config.Skip_certs)
    if not _index_tweet_status:
        _index_tweet_status = createIndex(config, es, scope="tweet")
    with nostdout():
        helpers.bulk(es, actions, chunk_size=2000, request_timeout=200)
    actions = []
```

by:

```
    client = MongoClient(url)
    db = client[config.MongoDB.db]
    collection = db[config.MongoDB.collection]
    collection.insert_one(actions)
    client.close()
```

Yet I need to know where I can access config to create this MongoDB property.
