### ISSUE TITLE
[Question] Long-running continuous scraping?

### ISSUE THREAD

**Issue by rgrunbla** [twintproject/twint#362]
Hello everyone,

I was wondering if there was a « workflow » to do long-running scraping using twint.

Goal would be scraping tweets (that tends to not appearing in the past, so there is an easy way to avoid making duplicate requests) continuously, to be able to add tweets to elastic search (for example) without having twint recrawling the whole set of data.
Having this continuous crawl would mean being able to get « everything », in particular stuff that is deleted before it gets deleted (it would be nice to be able to re-crawl everything and points out which tweets have been deleted, because their deletion might be a good indicator of importance).

Thanks for the project :)
R

**Comment by pielco11** [comment]
What you are looking for is a stream API, Twitter offers a solution of that kind but Twint does not.

You could check if a tweet every 100 (for example) already exists and if so, stop the scraping process, otherwise continue. Then wait a while and rescan

**Comment by im-n1** [comment]
Is there a possibility how to add "callback" once the scrapping is done by set up Config object? The thing is I would like to read my scrapped CSV and process it futher but first I need to know the scrapping is done.

**Comment by pielco11** [comment]
Basically the scrape is done when it finishes

If you want to use the store-object feature you have to set `config.Store_object = True` first, and then call `tweet = twint.output.tweets_object` after `twint.run.Search` or similar

**Comment by im-n1** [comment]
Sorry for the delay. I've tried what you suggest but the thing is the `tweet` list is growing as the tweets are being scraped. I want to get all scraped tweets at once. How can I know scrapping has finished?

**Comment by pielco11** [comment]
If you want all scraped tweets at once you have just to wait the end of `twint.run.Search` and then call `tweets = twint.output.tweets_object`

Probably I'm not getting the point but you know that a scraping process is finished when it finishes. If you want to be notified, just add a call to a function that plays an audio file (for example)
