### ISSUE TITLE
[Question] Can i do case sensitive string search in Twint?

### ISSUE THREAD

**Issue by SundareshPrasanna** [twintproject/twint#363]
Hi I'm trying to do a case sensitive string search in Twint & so far I was not very successful. Can someone guide me if its possible to do case sensitive string search here?

Ex: difference between Marble as a name & marble as in a rock is because of the first capital letter. If this is possible, the number of records extracted will reduce & also no need for string search or matching post getting all the tweets for filtering out the relevant tweets

**Comment by pielco11** [comment]
It should be
> twint --search "\"Marble\""

And
```python
import twint

c = twint.Config()
c.Search = "\"Marble\""

twint.run.Search(c)
```

But I tried with the Twitter Advanced Search and it seems that Twitter itself is not returning correct results (specifying `Marble` in the keyword field, as it has to be)

**Comment by SundareshPrasanna** [comment]
thanks @pielco11 .  I tried running the "\"Marble\"" in the module & it doesn't work. As you mentioned, twitter advanced search does not offer this feature. So it is a limitation of Twitter ? This problem can only be handled locally?

**Comment by SundareshPrasanna** [comment]
Thanks pieclo11. so is it a limitation of Twitter ? It can only be handled locally?. I tried your codes but they returned both lower & upper case scenarios as u mentioned with advanced twitter search

**Comment by pielco11** [comment]
For what I tested I think that it can only be handled locally
