### ISSUE TITLE
Scraping user profile do not return retweets.

### ISSUE THREAD

**Issue by dusadvarshit** [twintproject/twint#364]
# Issue Template
Please use this template!

### Initial Check
> If the issue is a request please specify that it is a request in the title (Example: [REQUEST] more features). If this is a question regarding 'twint' please specify that it's a question in the title (Example: [QUESTION] What is x?). Please **only** submit issues related to 'twint'. Thanks.

>Make sure you've checked the following:

- [] Python version is 3.6;
- [] Updated Twint with `pip3 install --upgrade -e git+https://github.com/twintproject/twint.git@origin/master#egg=twint`;
- [] I have searched the issues and there are no duplicates of this issue/question/request.

### Command Ran
c = twint.Config()
c.Username = "hugoford"
c.Store_json = True
c.Output = "tweets.json"
c.Retweets = True
twint.run.Profile(c)

### Description of Issue
I wanted to scrape a given users profile and extract all of their tweets, and retweets. However, the above commands only provide the tweets written by the user and not the retweets done by him. I would like to request some help regarding this. 
Thank you!

### Environment Details
>Running from terminal both Windows 10 and Ubuntu 18.04

**Comment by gabrielacaesar** [comment]
Hello. I am using Twint to scrape the presidential tweets in Brazil. I couldn't get the retweets of the username, but only the tweets and replies. Is there a way to get the retweets?

**Comment by pielco11** [comment]
@gabrielacaesar get retweets feature is currently broken

**Comment by pielco11** [comment]
Fixed #404

**Comment by zhixideyu** [comment]
Aren't you going to fix it
