### ISSUE TITLE
Twint keeps running despite "since" tag, how to restrict to one month?

### ISSUE THREAD

**Issue by NewCTwo** [twintproject/twint#368]
### Initial Check

- [X] Python version is 3.6;
- [X] Updated Twint with `pip3 install --upgrade -e git+https://github.com/twintproject/twint.git@origin/master#egg=twint`;
- [X] I have searched the issues and there are no duplicates of this issue/question/request.

### Command Ran

`twint -u nytimes --since 2019-01-01 --until 2019-02-01`

### Description of Issue

I'm trying to scrape tweets from just January with a combination of since and until. Despite this, twint keeps running into last year:
```
1079981566305202181 2019-01-01 01:04:05 EST <nytimes> As Migrants Cross English Channel, Numbers Are Small but Worry Is Big https://nyti.ms/2CJPQhD 
1079974042256502786 2019-01-01 00:34:11 EST <nytimes> Pete Davidson Back on Stage for First Time Since Suicide Scare https://nyti.ms/2EYFfAR 
1079970878954356737 2019-01-01 00:21:37 EST <nytimes> Paula Martiesian and Ken Carpenter were together for more than 4 decades before getting married https://nyti.ms/2F31BS3 
1079966586449088512 2019-01-01 00:04:33 EST <nytimes> ‘I Have Seen Many Crises’: Steel Magnate Stands Firm as Turmoil Hits Turkey https://nyti.ms/2CH48PV 
1079965501059665920 2019-01-01 00:00:14 EST <nytimes> The Democrats’ midterms sweep in California’s Orange County signals a political shift, and serves as a warning for national Republicans https://nyti.ms/2CIrK6U 
1079959264272285696 2018-12-31 23:35:27 EST <nytimes> "These days, winter means an excuse to stay in. It means — unbelievably — comfort." https://nyti.ms/2CGN0d8 
1079954841194151936 2018-12-31 23:17:53 EST <nytimes> More vegetables. Gut health. Cocktails with less alcohol. A look at the food trends for 2019. https://nyti.ms/2EWQmKK 
1079950385832493056 2018-12-31 23:00:11 EST <nytimes> One native New Yorker feels the power of the Times Square crowd on New Year's Eve for the first time https://nyti.ms/2CHpSLO 
1079944031499702273 2018-12-31 22:34:56 EST <nytimes> President Trump issued an executive order on Friday freezing pay for federal civilian workers in 2019 https://nyti.ms/2CIA1rq 
1079939652327493634 2018-12-31 22:17:32 EST <nytimes> Between 1981 and 1998, Robert Rauschenberg created a self-portrait a quarter of a mile long. Now 2 curators interpret its meanings. https://nyti.ms/2EYvu5I 

```

### Environment Details
>Terminal, Python3.6, Ubuntu 18.04

**Comment by pielco11** [comment]
Twint uses `since` and `until` to formulate the query, so after query is created, it's passed to Twitter. Then it's Twitter that elaborates the request. So I guess that you are getting those tweets because Twitter is returning them

On the other side, we have a `datecheck` function to properly filter data even if Twitter does not respond properly
https://github.com/twintproject/twint/blob/b5338e47a5ed55d001d6d48860cd249cadb0293e/twint/output.py#L24-L33

I tried your query and I did not get errors
![immagine](https://user-images.githubusercontent.com/17363750/53689170-c5b20600-3d4f-11e9-83c6-c094ec19d606.png)

**Comment by cbjrobertson** [comment]
> Twint uses `since` and `until` to formulate the query, so after query is created, it's passed to Twitter. Then it's Twitter that elaborates the request. So I guess that you are getting those tweets because Twitter is returning them
> 
> On the other side, we have a `datecheck` function to properly filter data even if Twitter does not respond properly
> [twint/twint/output.py](https://github.com/twintproject/twint/blob/b5338e47a5ed55d001d6d48860cd249cadb0293e/twint/output.py#L24-L33)
> 
> Lines 24 to 33 in [b5338e4](/twintproject/twint/commit/b5338e47a5ed55d001d6d48860cd249cadb0293e)
> 
>  def datecheck(datestamp, config): 
>      logme.debug(__name__+':datecheck') 
>      if config.Since and config.Until: 
>          logme.debug(__name__+':datecheck:dateRangeTrue') 
>          d = int(datestamp.replace("-", "")) 
>          s = int(config.Since.replace("-", "")) 
>          if d < s: 
>              return False 
>      logme.debug(__name__+':datecheck:dateRangeFalse') 
>      return True 
> I tried your query and I did not get errors
> ![immagine](https://user-images.githubusercontent.com/17363750/53689170-c5b20600-3d4f-11e9-83c6-c094ec19d606.png)
> 
> I also tried different queries

Yes... I can vouch that twitter will 'fill up' especially low volume requests to complete a page. You'll tend to get 'overages' at the end of a request.
