### ISSUE TITLE
Lookup command is returning incorrect results when User_id is provided in config

### ISSUE THREAD

**Issue by AyeshaAbid** [twintproject/twint#369]
I'm trying to fetch user details by providing User__id and doing a lookup. My code snippet looks like below:

```python
import twint
c = twint.Config()
c.User_id = "122453931"
c.User_full = True
twint.run.Lookup(c)

```
Expected Result:

`122453931 | Imran Khan | @ImranKhanPTI | Private: 0 | Verified: 1 | Bio: Prime Minister of Pakistan | Location: Pakistan | Url: http://insaf.pk | Joined: 12 Mar 2010 11:28 AM | Tweets: 5792 | Following: 19 | Followers: 9320104 | Likes: 0 | Media: 930 | Avatar: https://pbs.twimg.com/profile_images/1034759395622756352/G3QDI4pv_400x400.jpg
`

Actual Result:
`1977321 | Tagwisa | @none | Private: 1 | Verified: 0 | Bio:  | Location: South Africa | Url: None | Joined: 22 Mar 2007 9:26 PM | Tweets: 197 | Following: 32 | Followers: 2 | Likes: 0 | Media: 0 | Avatar: https://abs.twimg.com/sticky/default_profile_images/default_profile_400x400.png
`

>Make sure you've checked the following:

- [] Python version is ~~3.6~~ 3.7.1;
- [] Updated Twint with `pip3 install --upgrade -e git+https://github.com/twintproject/twint.git@origin/master#egg=twint`;
- [] I have searched the issues and there are no duplicates of this issue/question/request.

### Command Ran
```python
import twint
c = twint.Config()
c.User_id = "122453931"
c.User_full = True
twint.run.Lookup(c)

```
### Environment Details
>Using Windows 10.  running this with anaconda and pycharm.

**Comment by pielco11** [comment]
Thank you for reporting this!

Now it's fixed and the results are as expected

**Comment by AyeshaAbid** [comment]
I tried the fix but I'm getting another error now. The error is:
```
 'NoneType' object is not subscriptable [x] get.User
CRITICAL:root:twint.get:User:'NoneType' object is not subscriptable
```
The same error occours in both CLI and Module (via Pycharm). Even the simplest of code is not working now i.e Lookup using username. 
<img width="585" alt="git" src="https://user-images.githubusercontent.com/20228701/53970530-c1edfd00-411c-11e9-8d2a-baaea18f0223.PNG">

**Comment by pielco11** [comment]
![immagine](https://user-images.githubusercontent.com/17363750/54019715-24caad00-418c-11e9-8d85-098875009737.png)

Please be sure to have updated the package
