### ISSUE TITLE
asyncio.TimeoutError (there must be another solution)

### ISSUE THREAD

**Issue by UmutCan06** [twintproject/twint#370]
The main Error of my code is that one:

raise asyncio.TimeoutError
concurrent.futures._base.TimeoutError

I increased the timeout 30 to 60 in get.py file where i get the error at 94. However this didnt solve the error. I still get the error coz 60 sec is not enouh for it i assume.  I checked the other issues and that one solve nothing. I check the connection between me and twitter mostly the problem it seems not only the connection but also something else.  I wonder any one got this kind of error and how to solve ? I upgrade and update all kind of lib. which is used on this script including twint. 

In config i used language,key and "since/until". I am running the twint like ; 

"twint.run.Search(config=c)"

Maybe this one is bind somewhere i didn t understand yet. 

Python version is 3.6;
Ubuntu linux 16.04

**Comment by pielco11** [comment]
The timeout errors means that Twitter is not returning you data

**Comment by Meera2512** [comment]
I am also facing the same time timeout error, is there any solution? or it is just a  network 
connectivity issue?
