### ISSUE TITLE
Scrapping date range doesn't work

### ISSUE THREAD

**Issue by im-n1** [twintproject/twint#374]
I use the following config:

```python
c = twint.Config()
c.Search = "bitcoin"
c.Lang = "en"
c.Store_object = True
c.Hide_output = True
c.Since = "2019-02-01"
```

Then I run:

```python
twint.run.Search(c)
```

But I get only tweets from past 2 days (it's 10th March today). How do I know? I stuff the data into pandas and then I ask (`date` is renamed `tweet.timestamp / 1000` column).

```python
df["date"].unique()
```

Output:
```python
array([datetime.date(2019, 3, 10), datetime.date(2019, 3, 9)], dtype=object)
```

**Comment by pielco11** [comment]
Did you check with the output of a search done with Twitter Advanced Search? I used to get Tweets prior the "since date" specified

**Comment by im-n1** [comment]
No I didnt. Sorry. Actually I'm messing with another libraries but this is still a thing.

**Comment by pielco11** [comment]
#368
