### ISSUE TITLE
NoneType exception using both c.Username and c.User_id

### ISSUE THREAD

**Issue by mattiacampana** [twintproject/twint#376]
- [x] Python version is 3.6;
- [x] Updated Twint with `pip3 install --upgrade -e git+https://github.com/twintproject/twint.git@origin/master#egg=twint`;
- [x] I have searched the issues and there are no duplicates of this issue/question/request.

### Command Ran
```python

import twint

c = twint.Config()
c.User_id ='2550600458'
# or c.Username = 'noneprivacy'
c.Store_json = True
c.Limit = 10
twint.run.Search(c)
```

### Description of Issue
If I specify the **User_id** or **Username**, I receive the following exception:

> 'NoneType' object is not subscriptable [x] get.User
Traceback (most recent call last):
  File "test.py", line 11, in <module>
    twint.run.Search(c)
  File "/home/mattia/Development/socialContext/venv3.6/lib/python3.6/site-packages/twint/run.py", line 201, in Search
    run(config)
  File "/home/mattia/Development/socialContext/venv3.6/lib/python3.6/site-packages/twint/run.py", line 153, in run
    get_event_loop().run_until_complete(Twint(config).main())
  File "/usr/lib/python3.6/asyncio/base_events.py", line 473, in run_until_complete
    return future.result()
  File "/home/mattia/Development/socialContext/venv3.6/lib/python3.6/site-packages/twint/run.py", line 113, in main
    self.config.User_id = await get.User(url, self.config, self.conn, True)
  File "/home/mattia/Development/socialContext/venv3.6/lib/python3.6/site-packages/twint/get.py", line 133, in User
    return int(inf(soup, "id"))
  File "/home/mattia/Development/socialContext/venv3.6/lib/python3.6/site-packages/twint/user.py", line 16, in inf
    ret = group["data-user-id"]
TypeError: 'NoneType' object is not subscriptable

It works only if I use **c.Search = 'noneprivacy'**. 

### Environment Details
>Linux Ubuntu 16.04 shell

**Comment by carlosabcs** [comment]
I'm receiving the same error. However, in my case the script keeps running anyway.

**Comment by pielco11** [comment]
Strange, I'm not having this error

**Comment by pielco11** [comment]
![immagine](https://user-images.githubusercontent.com/17363750/54607829-a30e3580-4a4f-11e9-9ff1-d15523ef1e2c.png)
 
![immagine](https://user-images.githubusercontent.com/17363750/54607864-b3261500-4a4f-11e9-8e48-fbf8324549bb.png)

**Comment by carlosabcs** [comment]
Hmmm, looks like it's a problem with `twint.run.Lookup()`
When we search all tweets by a certain user, automatically the user's profile is fetched too, so that log:
```
CRITICAL:root:twint.get:User:'NoneType' object is not subscriptable
'NoneType' object is not subscriptable [x] get.User
```
is part of the _lookUp_ function.

I ran `twint -u carlosabcs18 --user-full` and received the same error.

**Comment by pielco11** [comment]
Did you run pip+git? You should not be able to automatically get the user's profile because I removed this feature
-------- Messaggio originale --------
On 24 Mar 2019, 00:05, Carlos Córdova Sáenz ha scritto:

**Comment by carlosabcs** [comment]
I ran this: `pip3 install --upgrade -e git+https://github.com/twintproject/twint.git@origin/master#egg=twint`

Anyway, right now I do want to get all the user's profile information using `twint.run.Lookup()` and I'm also getting that error. I was reading about that log, and it usually happens when the method `__getitem__` is not implemented on an object.

**Comment by pielco11** [comment]
The command is correct. I tried a query and everything is fine, no errors displayed

![immagine](https://user-images.githubusercontent.com/17363750/54877885-fc49e080-4e24-11e9-8b73-3b76d6ff5ad1.png)

May you share me an username such that Twint returns errors?

**Comment by carlosabcs** [comment]
Try this: `carlosabcs18`

**Comment by pielco11** [comment]
Here you are!
![immagine](https://user-images.githubusercontent.com/17363750/54951205-580a8b80-4f43-11e9-9e0a-3c27ac0edb1b.png)

**Comment by carlosabcs** [comment]
Well, idk what else could be 😢

**Comment by pielco11** [comment]
I would suggest you to be sure that you are importing the right Twint. I mean, to be sure that you have only one Twint pip package installed and that's updated. If you cloned the Twint repo, be sure to have your local branch up-to-date

Since it seems that the issue does not exist, I'll close this.

We can obviously continue the discussion, if there something that I can help you with, I'm here!
