### ISSUE TITLE
[REQUEST] Allow arbitrary post limits

### ISSUE THREAD

**Issue by Slider-Whistle** [twintproject/twint#381]
As the help output says, Twint's --limit option only deals with multiples of 20.
My use case is probably pretty bizarre, but I think it'd be nice if there were an option to make it grab a specific number of posts, or to be more particular, just one post. I basically intend to use it for random xscreensaver text without having to pipe the output through `head`, which I don't imagine anyone else in the world will ever really want to do. There might be a use in grabbing, say, 511 posts to fill some kind of  quota though.
This might not align with Twint's objective of being a data analysis tool, so I understand if it isn't implemented.

**Comment by pielco11** [comment]
You could scrape 20 tweets and then play just with one of them

```python
import twint

c = twint.Config()
c.Limit = 10
c.Search = "something"
c.Store_object = True
twint.run.Search(c)
tweets = twint.output.tweets_object
single_tweet = tweets[0]
text = single_tweet.tweet
```

**Comment by Slider-Whistle** [comment]
My main concern is the amount of time it takes to finish. Piping the results through `head` in itself isn't too bad.
I might want to have a closer look at twint's usage as a python module though, looks like there might be some functionality I'm missing out on.
