### ISSUE TITLE
CRITICAL:root:twint.get:User:'NoneType' object is not subscriptable + Unicode issues

### ISSUE THREAD

**Issue by lozgarrido** [twintproject/twint#384]
# Issue Template
Please use this template!

### Initial Check
> If the issue is a request please specify that it is a request in the title (Example: [REQUEST] more features). If this is a question regarding 'twint' please specify that it's a question in the title (Example: [QUESTION] What is x?). Please **only** submit issues related to 'twint'. Thanks.

>Make sure you've checked the following:

- [x] Python version is 3.6;
- [x] Updated Twint with `pip3 install --upgrade -e git+https://github.com/twintproject/twint.git@origin/master#egg=twint`;
- [x] I have searched the issues and there are no duplicates of this issue/question/request.

### Command Ran
>Please provide the _exact_ command ran including the username/search/code so I may reproduce the issue.

`$ twint -u lozgarrido -s hola`

### Description of Issue
>Please use **as much detail as possible.**

First of all, thank you for your work developing and supporting the tool. That's my first issue —I'm newbie at this—, so I'm sorry too if I'm doing something too obvious wrong.

My problem is similar to this, but I've not been able to know what's happening: https://github.com/twintproject/twint/issues/352#issue-408486834

This is the complete output of previous command with Git:

![imagen](https://user-images.githubusercontent.com/15851286/54865680-669d4b00-4d69-11e9-84fb-b08f2cab6e55.png)

As you can see, I have two types of error:

1. It is repeated once for every missing character inside the scraped tweets. I've changed Git's encoding options, but nothing happens. I guess it could be Python or Anaconda's problem, maybe? A colleague uses Twint on Mac without any problem with emojis or special characters.

> `CRITICAL:root:twint.output:_output:UnicodeEncodeError`
> `unicode error [x] output._output`

2. Which I don't understand at all and happens with all queries.

> `CRITICAL:root:twint.get:User:'NoneType' object is not subscriptable`
> `'NoneType' object is not subscriptable [x] get.User`

Thank you so much for your help and patience.

#### Update 1:

Tried with Win Command Prompt. Unicode errors disappear (it just doesn't show emojis), but NoneType remains. Where I had `unicode error [x] output._output`, I can see the tweet. I guess codification problems are related to Git. I will look for more info on that.

![imagen](https://user-images.githubusercontent.com/15851286/54867205-d289ae80-4d7d-11e9-843c-c0b9985df0a9.png)

#### Update 2:

NoneType is everywhere when I make other queries. Next screenshot with `$ twint -u lozgarrido --following --user-full`:

![imagen](https://user-images.githubusercontent.com/15851286/54869502-ae3bcb00-4d99-11e9-97a7-2169b57246d2.png)

### Environment Details
>Using Windows, Linux? What OS version? Running this in Anaconda? Jupyter Notebook? Terminal?

Clean installation of Windows 10. Working on Git+Anaconda up to date.

**Comment by pielco11** [comment]
I tried your query and this is what I get 
![immagine](https://user-images.githubusercontent.com/17363750/54866040-7c157380-4d6f-11e9-8942-749e12a41aca.png)

I do not know where those `CRITICAL:root:twint.get:User:'NoneType' object is not subscriptable` are coming from

**Comment by lozgarrido** [comment]
Thanks for your reply, @pielco11. That seems perfect.

The truth is, I'm pretty lost. Are you on Windows? Maybe I could try with different tools...

**Comment by pielco11** [comment]
Currently I'm on Ubuntu

**Comment by lozgarrido** [comment]
Updated main post. 

I'm going to keep looking for a solution in the next few days. If I don't get it I will end up installing Ubuntu.

Anyway, thanks again for your time.

**Comment by NaRuecker** [comment]
@lozgarrido did you end up installing ubuntu? I have exactly the same problem.

**Comment by lozgarrido** [comment]
@NaRuecker I was able to avoid NoneType errors with [Windows Subsystem for Linux](https://docs.microsoft.com/en-us/windows/wsl/install-win10). Unfortunately, pure Windows+Twint still doesn't work properly for me.

**Comment by pielco11** [comment]
@lozgarrido thank you for letting us know that Windows+Twint does not work properly

Added Compatibility label

**Comment by Konstantin555** [comment]
Tried to run the code below on both Windows and Ubuntu (both python 3.6) for a random account with 93 followers. Got the NoneType error for all followers except two. 

`#!/usr/bin/python3

import twint
c = twint.Config()
c.Username = "hannegraat"
c.Store_csv = True
c.User_full = True
c.Output = "users.csv"
twint.run.Followers(c)`

![изображение](https://user-images.githubusercontent.com/13664826/57069621-cc241600-6cdd-11e9-9f1e-64ae2339ce12.png)

**Comment by Konstantin555** [comment]
Tried it with another username: RocioMV2 (312 followers). Only 13 as a result. All of them private btw.
![изображение](https://user-images.githubusercontent.com/13664826/57076313-04cdea80-6cf2-11e9-85b8-25d6b3c504ab.png)

**Comment by hpiedcoq** [comment]
same error now on ubuntu.
CRITICAL:root:twint.get:User:'NoneType' object is not subscriptable
This error happen on "twint -u " not on "twint -s".

Twint is up to date (I redid pip3 install --upgrade -e git+https://github.com/twintproject/twint.git@origin/master#egg=twint)

**Comment by pielco11** [comment]
Fresh install of Twint

![immagine](https://user-images.githubusercontent.com/17363750/57092381-9dbd2f80-6d0b-11e9-8fd5-4cc5e187355f.png)

Trying the @Konstantin555 query

![immagine](https://user-images.githubusercontent.com/17363750/57092492-d6f59f80-6d0b-11e9-843c-c6837c83d1fd.png)

Trying something with "twint -u"

![immagine](https://user-images.githubusercontent.com/17363750/57092710-49667f80-6d0c-11e9-8f0a-de2a58dfb9d2.png)

![immagine](https://user-images.githubusercontent.com/17363750/57092725-51beba80-6d0c-11e9-8b6c-c29b7d2a1b6b.png)


If we look closer, nothing "wrong" happens

![immagine](https://user-images.githubusercontent.com/17363750/57092871-b67a1500-6d0c-11e9-8aa3-41ff4d229317.png)

Since the supposed missing tweet, is missing, so nothing is missed

![immagine](https://user-images.githubusercontent.com/17363750/57092911-d14c8980-6d0c-11e9-83e5-478baec650d8.png)

So maybe when Twint makes a new request to get other tweets, it's not properly handling the response, but it's still working

**Comment by AntonioNieto92** [comment]
Sorry I get this now:

CRITICAL:root:twint.get:User:'NoneType' object is not subscriptable

And afterwards, the tweets:
1126462919963705344 2019-05-09 14:24:23 Hora de verano romance @atleti pongan los 80M de Lucas https://twitter.com/rubenuria/status/1126445234769014784 …
1126403330123665408 2019-05-09 10:27:36 Hora de verano romance Este tío es un hijo de la gran puta. No convoca a ninguna jugadora del Barça pero si a las del Atleti qu
e también tienen una final este sábado. https://twitter.com/SeFutbolFem/status/1126161332598919170 …

And with this:

import twint

c = twint.Config()
c.Username = "RobertoEntio"
c.Since = "2019-05-01"
c.Until = "2019-05-10"

twint.run.Lookup(c)

CRITICAL:root:twint.get:User:'NoneType' object is not subscriptable

Process finished with exit code 0

**Comment by pielco11** [comment]
@AntonioNieto92 please don't crosspost. There's already an issue where you did post the same comment

We can continue the discussion here, or there #414. Not both

**Comment by AntonioNieto92** [comment]
So sorry 😔. Do you recommend any VPN or something in order not to be banned by Twitter?

**Comment by pielco11** [comment]
@AntonioNieto92 no problem

I do not have any VPN to recommend, I guess that a random one should be enough

**Comment by karimkohel** [comment]
> pip3 install --upgrade -e git+https://github.com/twintproject/twint.git@origin/master#egg=twint

yup, that did it

**Comment by antoinecomp** [comment]
Damn, damn, damn. I have this issue too on Colaboratory notebook.

**Comment by netotz** [comment]
> 
> 
> @lozgarrido thank you for letting us know that Windows+Twint does not work properly
> 
> Added Compatibility label
> 
> Edit:
> just to be sure, may you run `pip3 install --upgrade -e git+https://github.com/twintproject/twint.git@origin/master#egg=twint` and then re-try? It seems that you are having errors related to an old and already patched issue

this solved it for me, using Windows 10 and Python 3.8.8

**Comment by KavehSons** [comment]
I use the   simple command line in windows 10 but only get the following return for any username 
```
twint -u EasyE_Coli --following
CRITICAL:root:twint.feed:Follow:IndexError
```

**Comment by KyroAtelerix** [comment]
> > pip3 install --upgrade -e git+https://github.com/twintproject/twint.git@origin/master#egg=twint
> 
> yup, that did it


Executing this I had this error:

WARNING: Discarding git+https://github.com/twintproject/twint.git@origin/master#egg=twint. Command errored out with exit status 1: git clone -q https://github.com/twintproject/twint.git /Users/'''''''''/Desktop/Twint/src/twint Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement twint (unavailable)
ERROR: No matching distribution found for twint (unavailable)

How to resolve it?

**Comment by ahmedshahriar** [comment]
> 

solved for me, thanks
on windows 10, python 3.9
