### ISSUE TITLE
[Question] How does twint retreive hidden information like followers/following?

### ISSUE THREAD

**Issue by thojest** [twintproject/twint#385]
How does Twint manage to do this, because when not logged in, this information is not displayed by Twitter. I really tried to dig into this with logging-level debug and replaying the requests, but I could not manage to understand how it is done. Has it something to do with the requests being sent to twitter-mobil (http://mobile.twitter.com/...) ?

**Comment by pielco11** [comment]
Twint basically makes a request to mobile.twitter.com, asking for followers of a specific user.

Twitter via desktop does not allow this feature
