### ISSUE TITLE
Problem with users

### ISSUE THREAD

**Issue by DavidPerea** [twintproject/twint#387]
I want to perform the scraping of three Twitter users, but the problem is that I don't get all their tweets, only about 2500 tweets. I don't know what the problem might be.
I'm using the following command:
`twint -u username -o file.csv --csv`

For these three users:

- **AytoGuadix**

- **AytoCoin**

- **losbarriosmejor**

I only get these tweets for each user: 
- **AytoGuadix** --> 4626 tweets (last date: _2016-08-08_)

- **AytoCoin**  --> 2594 tweets (last date: _2017-01-09_)

- **losbarriosmejor** --> 2344 tweets (last date: _2016-05-01_)

Someone would know why it doesn't allow me to get more tweets?

**Comment by pielco11** [comment]
Would you do a manual search in the browser to see if the latest tweet that you find is the latest tweet that you scrape?

**Comment by DavidPerea** [comment]
They are not the last tweets. They have older tweets. For that reason I do not understand why it does not scraped more.

**Comment by pielco11** [comment]
Twitter usually blocks IPs that make too many requests, this happens even when I scroll the feed with the native app
