### ISSUE TITLE
[QUESTION] Is it possible to search for only a part of a word/affix

### ISSUE THREAD

**Issue by ElizabethCappon** [twintproject/twint#388]
Is it possible to use c.Search (or Twint in any other way) to search for only a part of a word or an affix? For example I would use c.Search = 'foo', and Twint would return tweets containing 'foo', but also tweets containing 'foobar', 'foot', fool', 'food', etc. Or I would search for 'cat' and Twint would return tweets containing 'cat', 'catlady', 'autocat', etc. 
If I'm not mistaking, you can't use regex in Twint?

Thanks in advance for the answer

**Comment by pielco11** [comment]
Hi @ElizabethCappon 

you can't use regex in Twint because it uses the search field of the Twitter Advanced Search and Twitter does not allow regex search
