### ISSUE TITLE
Search twint in a for loop not working after first pass

### ISSUE THREAD

**Issue by julen-0002** [twintproject/twint#389]
### Initial Check
> If the issue is a request please specify that it is a request in the title (Example: [REQUEST] more features). If this is a question regarding 'twint' please specify that it's a question in the title (Example: [QUESTION] What is x?). Please **only** submit issues related to 'twint'. Thanks.

>Make sure you've checked the following:

- [] Python version is 3.6;
- [] Updated Twint with `pip3 install --upgrade -e git+https://github.com/twintproject/twint.git@origin/master#egg=twint`;
- [] I have searched the issues and there are no duplicates of this issue/question/request.

### Command Ran

import twint
from datetime import datetime
from datetime import timedelta

days = [1,2,3]

for n in days:
    c = twint.Config()
    c.Search = 'Potro'
    c.Count = True
    c.Format = 'Username: {username} | Date: {date}'
    c.Output = str(n)+'.csv'
    
    st = datetime.strptime('2019-04-03','%Y-%m-%d')
    end = datetime.strptime('2019-04-04','%Y-%m-%d')
    
    stdt = st + timedelta(days=n)
    enddt = end + timedelta(days=n)
    
    ststr = stdt.strftime('%Y-%m-%d')
    endstr = enddt.strftime('%Y-%m-%d')
    
    c.Since = ststr
    c.Until = endstr
    c.Hide_output = True
        
    twint.run.Search(c)

### Description of Issue
I want to search and storage tweets of three different days but the problem is that the loop only 
runs once, then stops.
I tried to run the loop without using twint and it works.

### Environment Details
Windows

**Comment by pielco11** [comment]
![immagine](https://user-images.githubusercontent.com/17363750/55673644-f0d9c900-58aa-11e9-80ba-ccd4d1dbaf24.png)

![immagine](https://user-images.githubusercontent.com/17363750/55673656-22529480-58ab-11e9-8fc2-258fc3adb8ae.png)

Twint works well with iterators.

Plus your query works for me
![immagine](https://user-images.githubusercontent.com/17363750/55673727-e3710e80-58ab-11e9-99d3-05f9313f819b.png)

Please be sure that you formatted correctly your code

**Comment by julen-0002** [comment]
Thank you for your quick reply.

With different users works OK but I am trying to do the loop with different days and I only reach the first day search. 


<img width="614" alt="script" src="https://user-images.githubusercontent.com/49346511/55674696-45d00c00-58b8-11e9-8113-eeccc939545c.PNG">


<img width="274" alt="command_console" src="https://user-images.githubusercontent.com/49346511/55674699-4ec0dd80-58b8-11e9-820c-dd8ec4a95f60.PNG">

The loop stops in the first iteration, as you can see above.

<img width="439" alt="variables" src="https://user-images.githubusercontent.com/49346511/55674700-51233780-58b8-11e9-97ac-f78f71198b22.PNG">

The last value of the "n" variable is 1 and there is only one file saved.

**Comment by pielco11** [comment]
Hmmm, strange, because I saved in 3 different files as wanted (showed in the last screenshot)
