### ISSUE TITLE
I can't identify if a tweet is original or if it's a retweet

### ISSUE THREAD

**Issue by Zeykit-Dev** [twintproject/twint#390]
### Initial Check
> If the issue is a request please specify that it is a request in the title (Example: [REQUEST] more features). If this is a question regarding 'twint' please specify that it's a question in the title (Example: [QUESTION] What is x?). Please **only** submit issues related to 'twint'. Thanks.

>Make sure you've checked the following:

- [] Python version is 3.6;
- [] Updated Twint with `pip3 install --upgrade -e git+https://github.com/twintproject/twint.git@origin/master#egg=twint`;
- [] I have searched the issues and there are no duplicates of this issue/question/request.

### Command Ran
c = twint.Config()
c.Retweets = True
c.Store_object = True
c.Username = 'btc'
c.Format = 'It\'s retweet: {is_retweet} | Tweet: {tweet}'
twint.run.Search(c)

### Description of Issue
I want to identify if the tweet is original or if it's a retweet. It seems that twint already can identify the tweet origin, but from my side it always return None. 

### Environment Details
Windows, VS Code

**Comment by pielco11** [comment]
![immagine](https://user-images.githubusercontent.com/17363750/57029680-b7df0b00-6c42-11e9-809f-369a38df33e1.png)

Now it's fixed

#404

**Comment by Zeykit-Dev** [comment]
Awesome, thank you !
