### ISSUE TITLE
Unable to install twint

### ISSUE THREAD

**Issue by reesiecup** [twintproject/twint#391]
>Make sure you've checked the following:

- [v] Python version is 3.6;
```
(python36) Reeses-Air:~ reesetou$ python --version
Python 3.6.8 :: Anaconda, Inc.
```
- [v] Updated Twint with `pip3 install --upgrade -e git+https://github.com/twintproject/twint.git@origin/master#egg=twint`;

  I got the following warnings and errors:
```
clang: warning: libstdc++ is deprecated; move to libc++ with a minimum deployment target of OS X 10.9 [-Wdeprecated]
    clang: warning: libstdc++ is deprecated; move to libc++ with a minimum deployment target of OS X 10.9 [-Wdeprecated]
    ld: library not found for -lstdc++
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
    error: command '/usr/bin/clang++' failed with exit status 1
```
- [v] I have searched the issues and there are no duplicates of this issue/question/request.

### Command Ran
>Please provide the _exact_ command ran including the username/search/code so I may reproduce the issue.

```
(python36) Reeses-Air:~ reesetou$ pip3 install --upgrade -e git+https://github.com/twintproject/twint.git@origin/master#egg=twint
```
### Description of Issue
>Please use **as much detail as possible.**

 I got several message like this:
```
Cache entry deserialization failed, entry ignored
```
At the end, I got message like the following:
```
clang: warning: libstdc++ is deprecated; move to libc++ with a minimum deployment target of OS X 10.9 [-Wdeprecated]
    clang: warning: libstdc++ is deprecated; move to libc++ with a minimum deployment target of OS X 10.9 [-Wdeprecated]
    ld: library not found for -lstdc++
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
    error: command '/usr/bin/clang++' failed with exit status 1
    
    ----------------------------------------
Command "/Library/Frameworks/Python.framework/Versions/3.6/bin/python3.6 -u -c "import setuptools, tokenize;__file__='/private/var/folders/0c/0gfwnsh13ml8x1w5b33scjgc0000gn/T/pip-build-7ufk657x/cchardet/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /var/folders/0c/0gfwnsh13ml8x1w5b33scjgc0000gn/T/pip-zest2dsr-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/0c/0gfwnsh13ml8x1w5b33scjgc0000gn/T/pip-build-7ufk657x/cchardet/
```

### Environment Details
>Using Windows, Linux? What OS version? Running this in Anaconda? Jupyter Notebook? Terminal?
```
OS Mojave Version 10.14.2
Using the terminal to run in Anaconda3 virtual environment
```

**Comment by pielco11** [comment]
I have reasons to believe that's not related to Twint, `ld: library not found for -lstdc++`

Maybe it's a compatibility issue with Anaconda environment

**Comment by reesiecup** [comment]
I have tried to uninstall Anaconda entirely and install twint but I always got the same error message.

I also tried to use git to install it but I got this error when I ran `pip3 install -r requirements.txt` in terminal:
```
Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'
```

Any suggestions?

**Comment by pielco11** [comment]
`requirements.txt` is a file in the repo. You have to clone the repo first

**Comment by reesiecup** [comment]
I did clone the repo first, but the terminal showed me the error in the previous comment when I ran the requirement command.

I later found out that the problem came from Xcode 10.1, and I followed this post (https://stackoverflow.com/questions/52509602/cant-compile-c-program-on-a-mac-after-upgrade-to-mojave) to fix it. 

Now twint is installed and running. Thanks!

**Comment by pielco11** [comment]
Great to know!

I'm going to close this issue since it has been solved

Enjoy Twint as much as possible!
