### ISSUE TITLE
Runtime Error

### ISSUE THREAD

**Issue by chrisseiler96** [twintproject/twint#393]
# Issue Template
Please use this template!

### Initial Check
> If the issue is a request please specify that it is a request in the title (Example: [REQUEST] more features). If this is a question regarding 'twint' please specify that it's a question in the title (Example: [QUESTION] What is x?). Please **only** submit issues related to 'twint'. Thanks.

>Make sure you've checked the following:

- [X] Python version is 3.6;
- [X] Updated Twint with `pip3 install --upgrade -e git+https://github.com/twintproject/twint.git@origin/master#egg=twint`;
- [X] I have searched the issues and there are no duplicates of this issue/question/request.

### Command Ran
>Please provide the _exact_ command ran including the username/search/code so I may reproduce the issue.

```
c = twint.Config()

c.Username = 'noneprivacy'
c.Limit = 1000
c.Store_object = True

twint.run.Followers(c)
followers = twint.output.follow_object
```

### Description of Issue
>Please use **as much detail as possible.**

This returns a runtime error:

```
RuntimeError: This event loop is already running

CRITICAL:root:twint.get:User:'NoneType' object is not subscriptable
```

The followers actually show up in the output after the error, but it will not allow me to store it inside a variable

### Environment Details
>Using Windows, Linux? What OS version? Running this in Anaconda? Jupyter Notebook? Terminal?

I'm running this on a Jupyter Notebook. OS is Ubuntu 18.04. This is running on a 3.6 anaconda environment with all the proper requirements.

**Comment by pielco11** [comment]
It seems that Twint is not compatible with Jupyter Notebooks

**Comment by chrisseiler96** [comment]
It gives me the same error when I try to run in terminal

**Comment by chrisseiler96** [comment]
I'd be willing to try to make a patch, any idea where I might start looking?

**Comment by pielco11** [comment]
I tried your query without using Anaconda, just pure Python and I do not get errors

I kindly ask you to update your package and retry

Alternatively, you have to debug a bit and see what makes get.User break (file `twint/get.py`, function `User`, line 166)

**Comment by pielco11** [comment]
[This](https://www.kdnuggets.com/2019/05/analyzing-tweets-nlp-spark-optimus-twint.html) might help you.

**Comment by edsu** [comment]
Yep, this makes the error message go away. FWIW twint still seemed to do data collection even after the error message. But it's nicer to get rid of the message that clutters up my Jupyter notebook!

```python
import nest_asyncio
nest_asyncio.apply()
```
