### ISSUE TITLE
[Question] Difference between Geo command/module pulls

### ISSUE THREAD

**Issue by five0h302** [twintproject/twint#399]
- [x] Python version is 3.6;
- [x] Updated Twint with `pip3 install --upgrade -e git+https://github.com/twintproject/twint.git@origin/master#egg=twint`;
- [x] I have searched the issues and there are no duplicates of this issue/question/request.

I'm creating a project that pulls Tweets based on geodata, and I was wondering if someone could explain the difference between the following lines and whether or not they would pull the same data back?  Both lines of code work when I run them, but the amounts of data pulled back  is vastly different between 1 (less data) and 2 (more data).

1)	 twint -g="48.880048,2.385939,1km"
 
2)	c = twint.Config()
        c.Geo = "48.880048,2.385939,1km"
        twint.run. search(c)

**Comment by pielco11** [comment]
https://github.com/twintproject/twint/blob/b85d18a1676756e16a461282a413a8340c90ddb5/twint/cli.py#L120

https://github.com/twintproject/twint/blob/b85d18a1676756e16a461282a413a8340c90ddb5/twint/cli.py#L65

Twint handles the data in the same way

You can run Twint via module adding `config.Debug = True` and see in the logs the single request urls

**Comment by five0h302** [comment]
Thank you for the helpful response.

**Comment by pielco11** [comment]
@five0h302  May you compare the request urls and let me know if you see any difference? (which is not expected, since Twint should generate the same url in both cases)

If the urls are the same, it means that Twitter is returning different tweets with the same request, so it would be an issue with Twitter and not Twint.

**Comment by five0h302** [comment]
Hi, was able to debug and both were the same.  I ran each of the above mentioned and the results were the same.  Thanks for answering my question.
