### ISSUE TITLE
[BREAKING UPDATE] Breaking changes for Elasticsearch 7.0.0

### ISSUE THREAD

**Issue by pielco11** [twintproject/twint#400]
# What happened?

Since the new release of Elasticsearch 7.0.0, `types` have been removed. This caused errors while creating the index (#397), to fix this I had to remove `types` both from index creating and documents indexing.

This means that if you used Elasticsearch before, you can re-index tweets and users in a new index for Elasticsearch 7.0.0, or keep the previous version (like 6.5.4) make a backup of `twint/elasticsearch.py`, update your local repo, substitute the "new" `twint/elasticsearch.py` with the backup

**Comment by pielco11** [comment]
If you "accidentally" upgraded Twint but you are still using Elasticsearch 6.x, you have just to download the previous version of `twint/storage/elasticsearch.py` https://github.com/twintproject/twint/blob/e824e0b36ca9130150979f870ac8a5183c7fe7f6/twint/storage/elasticsearch.py and the previous version of `twint/config.py` https://github.com/twintproject/twint/blob/c55ac0b2e03e8e2c88f0efd4e12220947aedeef5/twint/config.py

**Comment by Prichard407** [comment]
Welcome to the great illuminati Age of new dawns of fame, wealth, knowledge and power. Are you a business man or an Artist,Politicians or pastor and you want to become big, Powerful and famous in the world, join us to become one of our official member today. you shall be given an ideal chance to visit the illuminati and his representative after registrations is completed by you, no sacrifice, or human life needed, Illuminati brotherhood brings along wealth and famous in life, you have a full access to eradicate poverty away from your life now. it only a member who is been initiated into the church of illuminati have the authority to bring any member to the church, so before you contact any body you must be link by who is already a member, Join us today and realize your dreams. we also help out our member in protection of drugs pushing, once you become a member you will be rich and famous for the rest of your life, illuminati make there member happy so i will want you all to also be a member of the illuminati and get a tangible support of (£700,000 pounds) contact me on WhatsApp +447852680916 or mail me on Prichardmark407@outlook.com

**Comment by pielco11** [comment]
@Prichard407 thank you for your offer, but here people are interested in Twint, not in Illuminati. Please don't spam

I kindly ask you to respect the rules, feel free to open/comment issues about Twint and don't spam. Thank you
