### ISSUE TITLE
Elasticsearch calculation for HOUR and Day

### ISSUE THREAD

**Issue by sebastienhouzet** [twintproject/twint#401]
>Make sure you've checked the following:

- [X] Python version is 3.6;
- [X] Updated Twint with `pip3 install --upgrade -e git+https://github.com/twintproject/twint.git@origin/master#egg=twint`;
- [X] I have searched the issues and there are no duplicates of this issue/question/request.

### Command Ran
twint -u username - es localhost:92000 -it test

### Description of Issue
<img width="441" alt="Capture d’écran 2019-04-25 à 10 53 00" src="https://user-images.githubusercontent.com/2550639/56722996-661d1900-6748-11e9-9ba8-2110d86d02fe.png">

HOUR is normaly 9
DAY is normaly 4 (thursday)

Other example
<img width="402" alt="Capture d’écran 2019-04-25 à 10 56 02" src="https://user-images.githubusercontent.com/2550639/56723174-c14f0b80-6748-11e9-9f83-0598f4dc3ace.png">

HOUR is normaly 9
DAY is normaly 4 (thursday)

### Environment Details
Docker + Ubuntu 18.04 + Master of twint

**Comment by pielco11** [comment]
The cause of the error is that `tweet.datetime` returned by Twitter is in milliseconds

Honestly I do not know how this went unnoticed

**Comment by sebastienhouzet** [comment]
Thx :)

Only other remarks, when you calculate HOUR and DAY, you use timestamp without localtime.

date | Apr 25, 2019 @ 18:48:40.000
  | # day | 4
  | # hour | 16

My timezone is UCT+2

date is OK with correct timezone
but day and hour use only UTC.

I think for good graphic, it is better to have HOUR and DAY with localtime like date :)

Seb

**Comment by pielco11** [comment]
Maybe I'm missing the point, but, Elasticsearch displays date with a different timezone

## Table
![immagine](https://user-images.githubusercontent.com/17363750/56756884-1adc2800-6793-11e9-9469-a268d28fed7b.png)

## JSON
![immagine](https://user-images.githubusercontent.com/17363750/56757049-91792580-6793-11e9-8ea2-dbfe5f204e3c.png)

Plus Twint uses `time.localtime`
https://github.com/twintproject/twint/blob/3b07559381e701bdb0808bd8c37fd2fb6afd8583/twint/storage/elasticsearch.py#L168-L169

https://github.com/twintproject/twint/blob/3b07559381e701bdb0808bd8c37fd2fb6afd8583/twint/storage/elasticsearch.py#L183

Currently I'm not aware on how to "fix" the "Elasticsearch's timezone"
