### ISSUE TITLE
[REQUEST] Automatically resume from most recent tweet if output.json exists

### ISSUE THREAD

**Issue by briatte** [twintproject/twint#406]
This request builds on what has been briefly discussed in #73 and #367.

Suppose I run

```
twint -u twitter_user --favorites -o twitter_user_favourites.json
```

and then wish to update that JSON file two weeks later.

If I run exactly the same command in two weeks, would it be possible for twint to find the most recent tweet in that JSON file, and automatically append the corresponding `--resume 0123..789` "most recent tweet" argument?

-----

- [x] Python version is 3.6;
- [x] Updated Twint with `pip3 install --upgrade -e git+https://github.com/twintproject/twint.git@origin/master#egg=twint`;
- [x] I have searched the issues and there are no duplicates of this issue/question/request.

**Comment by pielco11** [comment]
Sometimes scripting is still a good solution. You should be able to do the same with Windows, simply print the last line, split with "space" as separator, from the second element remove the last char

```
twint -u noneprivacy -o file.json --json --resume `awk 'END{print substr($2, 1, length($2)-1)}' file.json`
```

**Comment by briatte** [comment]
Thanks. I'm on Mac, so should be able to use that straight away :)
