### ISSUE TITLE
[QUESTION]CRITICAL:root:twint.output:_output:UnicodeEncodeError

### ISSUE THREAD

**Issue by MarcusCS** [twintproject/twint#407]
- [] Python version is 3.6;
- [] Updated Twint with `pip3 install --upgrade -e git+https://github.com/twintproject/twint.git@origin/master#egg=twint`;

### Command Ran
>twint -u herrcore -s unpacking > results.txt

### Description of Issue
>As soon as I run the above command I see this error 
![issue](https://user-images.githubusercontent.com/44235326/57120583-f504e380-6d8f-11e9-8b65-8d63867e29aa.png)

### Environment Details
>I'm running Windows 7 SP1 on my machine.

**Comment by pielco11** [comment]
It seems that the error is not caused by Twint, at least with my system configuration. I see that some tweets have emojis, are you able to print them? The error could be caused by this

![immagine](https://user-images.githubusercontent.com/17363750/57145429-7c1f7f00-6dc3-11e9-97b2-4a6b54a499a7.png)

**Comment by MarcusCS** [comment]
exactly, I see question marks everywhere instead of emojis. How to get rid of this now?

**Comment by pielco11** [comment]
You should install a font that supports emojis

**Comment by david115896** [comment]
Hello, any suggestion for the font to install ?
I installed "pip install emoji" but even if I import it, it doesn't change.

Thanks in advance.

**Comment by pielco11** [comment]
@david115896 I use https://github.com/ryanoasis/nerd-fonts
