### ISSUE TITLE
[REQUEST] Docker project

### ISSUE THREAD

**Issue by sebastienhouzet** [twintproject/twint#408]
Hello

I have created a Docker projet for Twint

https://github.com/sebastienhouzet/twint-docker

With it, all people can use twint just with docker.

Seb

**Comment by pielco11** [comment]
Hi Sebastien,

that's awesome!

I added you as member of the Twint Project, so you will be able to move from your private repo to the one of the organization. Obviously if you want to do so.
In any case you will have every single credit for your work

**Comment by badele** [comment]
Hum ... @sebastienhouzet Why you not create a PR into the main twint project ?

You can commit 3 files `Dockerfile`, `docker-compose.yml` and `entrypoint.sh` ?

**Comment by sebastienhouzet** [comment]
Hello

THX :)

I have accepted request and i push my project on your organization.

Seb
