### ISSUE TITLE
CRITICAL:root:twint.feed:Follow:IndexError

### ISSUE THREAD

**Issue by 0xSnipe** [twintproject/twint#409]
# Issue Template
Please use this template!

### Initial Check
> If the issue is a request please specify that it is a request in the title (Example: [REQUEST] more features). If this is a question regarding 'twint' please specify that it's a question in the title (Example: [QUESTION] What is x?). Please **only** submit issues related to 'twint'. Thanks.

>Make sure you've checked the following:

- [X] Python version is 3.6;
- [X] Updated Twint with `pip3 install --upgrade -e git+https://github.com/twintproject/twint.git@origin/master#egg=twint`;
- [X] I have searched the issues and there are no duplicates of this issue/question/request.

### Command Ran
>Please provide the _exact_ command ran including the username/search/code so I may reproduce the issue.

twint -u coindesk --followers --elasticsearch localhost:9200

### Description of Issue
>Please use **as much detail as possible.**

Got 30k results afterwards error:
CRITICAL:root:twint.feed:Follow:IndexError

Rerunning command doesn't give any immediate issues, just starts from 0 again

### Environment Details
>Using Windows, Linux? What OS version? Running this in Anaconda? Jupyter Notebook? Terminal?

Ubuntu 18.04, Python 3.6, ES 7, kibana 7

**Comment by pielco11** [comment]
Hi @0xSnipe and thanks for reaching us out,

That error message appears because Twitter does not return more followers, and so in the newly returned bunch of data, no followers found.

You could wait a while until Twitter does not "unsuspend" your IP, and then resume the scraping

#340

**Comment by 0xSnipe** [comment]
Very interesting thread, thanks for your quick reply.
Perhaps it would benefit from something like this, instead of the fixed sleep?
https://github.com/litl/backoff

I'll see what I can do to make that happen, if it's not beyond my python knowledge

**Comment by pielco11** [comment]
That's a really interesting library! Thanks for sharing

Feel free to provide any kind of patch, either by code or concept!

**Comment by KayHS** [comment]
Has anyone found a solution for this?

I get this error after fetching just 20 usernames.

**Comment by pielco11** [comment]
@KayHS not yet

I suggest you to apply a workaround as explained in #340 or use the Twitter API

**Comment by edwardqianofficial** [comment]
Hi, just wondering if I resume the scrape, am i able start from where I stop? Since When I tried to resume the program, the scraped results would start over again.

**Comment by pielco11** [comment]
You have to specify `config.Resume = "session_number_123.session"` (or whatever fits your needs) first, and then you can resume that session from where you stopped

**Comment by ahaseeb7838** [comment]
I'm facing same issue, I'm getting this error,

CRITICAL:root:twint.get:User:'NoneType' object is not subscriptable
CRITICAL:root:twint.feed:Follow:IndexError

I'm running this command
`twint -u paulchuckle2 --followers -o PaulChuckle.csv --csv --resume username_followers_resume.txt`

I'm getting above error after running the command with out getting any follower.
Can anyone help me about the issue ?

**Comment by ahaseeb7838** [comment]
I'm running the script on AWS EC2 Instance so I have also changes my IP but still getting this error,

`CRITICAL:root:twint.get:User:'NoneType' object is not subscriptable
CRITICAL:root:twint.feed:Follow:IndexError`

`c = twint.Config()
c.Username = "KatiePrice"
c.Followers = True
c.Resume = "resume.txt"
c.Output = "KatiePrice.csv"
twint.run.Followers(c)`

I'm running above code. Total Followers are 1.9M but I'm receiving this error after 6 Lac followers.

**Comment by theshouryagupta** [comment]
I am trying to extract the followers from a twitter account. I am getting the following error, it was working fine yesterday.
CRITICAL:root:twint.feed:Follow:IndexError

**Comment by himanshudabas** [comment]
That's because twitter killed the no js (mobile version) version of twitter on 15th December. Followers were scraped using that version.

**Comment by mayankrichu** [comment]
is there a new update?

**Comment by drumstick90** [comment]
Same problem. Other twint features are working fine but I need this one

**Comment by itsnotashes** [comment]
The problem persists...

**Comment by brenorb** [comment]
> That's because twitter killed the no js (mobile version) version of twitter on 15th December. Followers were scraped using that version.

So the whole lib is now useless? Nothing I try is working at the moment.
