### ISSUE TITLE
Could not load 

### ISSUE THREAD

**Issue by Artook10** [twintproject/twint#411]
Downloaded Twint and followed instructions to the letter but when I get to the pip3 install -r requirements.txt I receive this error " Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-2a74a6k2/pysocks/ Need help with this issue.

### Initial Check
> If the issue is a request please specify that it is a request in the title (Example: [REQUEST] more features). If this is a question regarding 'twint' please specify that it's a question in the title (Example: [QUESTION] What is x?). Please **only** submit issues related to 'twint'. Thanks.

>Make sure you've checked the following:

- [] Python version is 3.6;
- [] Updated Twint with `pip3 install --upgrade -e git+https://github.com/twintproject/twint.git@origin/master#egg=twint`;
- [] I have searched the issues and there are no duplicates of this issue/question/request.

### Command Ran
>Please provide the _exact_ command ran including the username/search/code so I may reproduce the issue.

### Description of Issue
>Please use **as much detail as possible.**

### Environment Details
>Using Windows, Linux? What OS version? Running this in Anaconda? Jupyter Notebook? Terminal?

**Comment by Artook10** [comment]
Forgot to add my OS which is Linux mint 18

**Comment by Artook10** [comment]
And Forgot more of the error message saying No module named 'setuptools'

**Comment by pielco11** [comment]
@Artook10 as the error messages says, you need to install setuptools

Usually this package is already shipped
