### ISSUE TITLE
'missing authentication credentials for REST request [/twinttweets]'

### ISSUE THREAD

**Issue by 0vert1m3** [twintproject/twint#412]
Where can I set the password for the elastisearch user?

**Comment by pielco11** [comment]
That depends on your setup. By default Elasticsearch is not authenticated, you need to install external plugins

**Comment by 0vert1m3** [comment]
Yes I know that but I don't want to leave my Kibana open so is there a way to add the data to the url string ?

**Comment by 0vert1m3** [comment]
> That depends on your setup. By default Elasticsearch is not authenticated, you need to install external plugins

Yes I know that but I don't want to leave my Kibana open so is there a way to add the data to the url string ?

**Comment by pielco11** [comment]
OK I guess I got your point

https://github.com/twintproject/twint/blob/77ec23f76d2bee011aa5e53d529e504761281a27/twint/storage/elasticsearch.py#L248

in your script place `c.Elasticsearch = "https://admin:admin@elastichost:port". If you use Twint via CLI, --elasticsearch "https://admin:admin@elastichost:port"

This works for basic auth

**Comment by 0vert1m3** [comment]
Thank you very much now it works without any problems., btw great project keep it up.
