### ISSUE TITLE
c.Username doesnt work

### ISSUE THREAD

**Issue by AntonioNieto92** [twintproject/twint#414]
# [QUESTION] c.UserName doesnt work

### Initial Check
> If the issue is a request please specify that it is a request in the title (Example: [REQUEST] more features). If this is a question regarding 'twint' please specify that it's a question in the title (Example: [QUESTION] What is x?). Please **only** submit issues related to 'twint'. Thanks.

>Make sure you've checked the following:

- [] Python version is 3.6;
- [] Updated Twint with `pip3 install --upgrade -e git+https://github.com/twintproject/twint.git@origin/master#egg=twint`;
- [] I have searched the issues and there are no duplicates of this issue/question/request.

### Command Ran
# Import
import twint

# Configure
c = twint.Config()
c.Username = "RobertoEntio"
#c.Search = "RobertoEntio”

# Run
twint.run.Search(c)

### Description of Issue
>c.UserName = "RobertoEntio" doesn't work, only when I put c.Search = "RobertoEntio" too. If I put only the c.UserName field, I get the following  --> 

'NoneType' object is not subscriptable [x] get.User
...............
...............
...............
TypeError: 'NoneType' object is not subscriptable

I downloaded manually the last version from git to local and install with pip

Any help plz?

### Environment Details
>Using Windows 10

**Comment by pielco11** [comment]
Not sure if you are using `c.UserName` or `c.Username`

Anyway, I tried your query and I have it working correctly
![immagine](https://user-images.githubusercontent.com/17363750/57450001-980ca000-725d-11e9-941d-8df9657143e9.png)

**Comment by AntonioNieto92** [comment]
This is what I get:

import twint
c = twint.Config()
c.Username = "RobertoEntio"
twint.run.Search(c)
'NoneType' object is not subscriptable [x] get.User
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "C:\Users\aniegarc\TFM\venv\lib\site-packages\twint\run.py", line 201, in Search
    run(config)
  File "C:\Users\aniegarc\TFM\venv\lib\site-packages\twint\run.py", line 153, in run
    get_event_loop().run_until_complete(Twint(config).main())
  File "C:\Program Files\Python37\lib\asyncio\base_events.py", line 584, in run_until_complete
    return future.result()
  File "C:\Users\aniegarc\TFM\venv\lib\site-packages\twint\run.py", line 113, in main
    self.config.User_id = await get.User(url, self.config, self.conn, True)
  File "C:\Users\aniegarc\TFM\venv\lib\site-packages\twint\get.py", line 133, in User
    return int(inf(soup, "id"))
  File "C:\Users\aniegarc\TFM\venv\lib\site-packages\twint\user.py", line 16, in inf
    ret = group["data-user-id"]
TypeError: 'NoneType' object is not subscriptable

**Comment by pielco11** [comment]
Please be sure to have Twint updated. I'm unable to replicate your issue with every username that I try

**Comment by AntonioNieto92** [comment]
I have installed again:

C:\Users\aniegarc\TFM>pip3 install C:\Users\aniegarc\TFM\src\twint-master.zip --user
Processing c:\users\aniegarc\tfm\src\twint-master.zip
Requirement already satisfied: aiohttp in c:\users\aniegarc\appdata\roaming\python\python37\site-packages (from twint==1.2.1) (3.5.4)
Requirement already satisfied: aiodns in c:\users\aniegarc\appdata\roaming\python\python37\site-packages (from twint==1.2.1) (2.0.0)
Requirement already satisfied: beautifulsoup4 in c:\users\aniegarc\appdata\roaming\python\python37\site-packages (from twint==1.2.1) (4.7.1)
Requirement already satisfied: cchardet in c:\users\aniegarc\appdata\roaming\python\python37\site-packages (from twint==1.2.1) (2.1.4)
Requirement already satisfied: elasticsearch in c:\users\aniegarc\appdata\roaming\python\python37\site-packages (from twint==1.2.1) (7.0.0)
Requirement already satisfied: pysocks in c:\users\aniegarc\appdata\roaming\python\python37\site-packages (from twint==1.2.1) (1.6.8)
Requirement already satisfied: pandas in c:\users\aniegarc\appdata\roaming\python\python37\site-packages (from twint==1.2.1) (0.24.2)
Requirement already satisfied: aiohttp_socks in c:\users\aniegarc\appdata\roaming\python\python37\site-packages (from twint==1.2.1) (0.2.2)
Requirement already satisfied: schedule in c:\users\aniegarc\appdata\roaming\python\python37\site-packages (from twint==1.2.1) (0.6.0)
Requirement already satisfied: geopy in c:\users\aniegarc\appdata\roaming\python\python37\site-packages (from twint==1.2.1) (1.19.0)
Requirement already satisfied: async-timeout<4.0,>=3.0 in c:\users\aniegarc\appdata\roaming\python\python37\site-packages (from aiohttp->twint==1.2.1) (3.0.1)
Requirement already satisfied: yarl<2.0,>=1.0 in c:\users\aniegarc\appdata\roaming\python\python37\site-packages (from aiohttp->twint==1.2.1) (1.3.0)
Requirement already satisfied: chardet<4.0,>=2.0 in c:\users\aniegarc\appdata\roaming\python\python37\site-packages (from aiohttp->twint==1.2.1) (3.0.4)
Requirement already satisfied: attrs>=17.3.0 in c:\users\aniegarc\appdata\roaming\python\python37\site-packages (from aiohttp->twint==1.2.1) (19.1.0)
Requirement already satisfied: multidict<5.0,>=4.0 in c:\users\aniegarc\appdata\roaming\python\python37\site-packages (from aiohttp->twint==1.2.1) (4.5.2)
Requirement already satisfied: pycares>=3.0.0 in c:\users\aniegarc\appdata\roaming\python\python37\site-packages (from aiodns->twint==1.2.1) (3.0.0)
Requirement already satisfied: soupsieve>=1.2 in c:\users\aniegarc\appdata\roaming\python\python37\site-packages (from beautifulsoup4->twint==1.2.1) (1.9.1)
Requirement already satisfied: urllib3>=1.21.1 in c:\users\aniegarc\appdata\roaming\python\python37\site-packages (from elasticsearch->twint==1.2.1) (1.24.3)
Requirement already satisfied: python-dateutil>=2.5.0 in c:\users\aniegarc\appdata\roaming\python\python37\site-packages (from pandas->twint==1.2.1) (2.8.0)
Requirement already satisfied: pytz>=2011k in c:\users\aniegarc\appdata\roaming\python\python37\site-packages (from pandas->twint==1.2.1) (2019.1)
Requirement already satisfied: numpy>=1.12.0 in c:\users\aniegarc\appdata\roaming\python\python37\site-packages (from pandas->twint==1.2.1) (1.16.2)
Requirement already satisfied: geographiclib<2,>=1.49 in c:\users\aniegarc\appdata\roaming\python\python37\site-packages (from geopy->twint==1.2.1) (1.49)
Requirement already satisfied: idna>=2.0 in c:\users\aniegarc\appdata\roaming\python\python37\site-packages (from yarl<2.0,>=1.0->aiohttp->twint==1.2.1) (2.8)
Requirement already satisfied: cffi>=1.5.0 in c:\users\aniegarc\appdata\roaming\python\python37\site-packages (from pycares>=3.0.0->aiodns->twint==1.2.1) (1.12.3)
Requirement already satisfied: six>=1.5 in c:\users\aniegarc\appdata\roaming\python\python37\site-packages (from python-dateutil>=2.5.0->pandas->twint==1.2.1) (1.12.0)
Requirement already satisfied: pycparser in c:\users\aniegarc\appdata\roaming\python\python37\site-packages (from cffi>=1.5.0->pycares>=3.0.0->aiodns->twint==1.2.1) (2.19)
Installing collected packages: twint
  Found existing installation: twint 1.2.1
    Uninstalling twint-1.2.1:
      Successfully uninstalled twint-1.2.1
  Running setup.py install for twint ... done
Successfully installed twint-1.2.1

**Comment by pielco11** [comment]
The log is correct

**Comment by AntonioNieto92** [comment]
But I get the same problem, after running the script :(

**Comment by pielco11** [comment]
It seems that the twint package that's loaded is wrong. For example one of your log lines is

> File "C:\Users\aniegarc\TFM\venv\lib\site-packages\twint\get.py", line 133, in User
return int(inf(soup, "id"))

But that line is different from this https://github.com/twintproject/twint/blob/49fe573293977fbea1519d828ae8ed7780eea28c/twint/get.py#L133

Your line 133 is, actually, line 172 https://github.com/twintproject/twint/blob/49fe573293977fbea1519d828ae8ed7780eea28c/twint/get.py#L172

**Comment by AntonioNieto92** [comment]
so what can I do?

**Comment by pielco11** [comment]
No worries, now enjoy Twint!

**Comment by AntonioNieto92** [comment]
Sorry I get this now:

**CRITICAL:root:twint.get:User:'NoneType' object is not subscriptable**

And afterwards, the tweets:
1126462919963705344 2019-05-09 14:24:23 Hora de verano romance <RobertoEntio> @Atleti pongan los 80M de Lucas https://twitter.com/rubenuria/status/1126445234769014784 …
1126403330123665408 2019-05-09 10:27:36 Hora de verano romance <RobertoEntio> Este tío es un hijo de la gran puta. No convoca a ninguna jugadora del Barça pero si a las del Atleti qu
e también tienen una final este sábado. https://twitter.com/SeFutbolFem/status/1126161332598919170 …

**Comment by pielco11** [comment]
I'm not getting your error message

FYI, c.Since and c.Until is used only with run.Search

**Comment by shepan6** [comment]
I am running into the same errors. I am currently getting grips with the package and used this script, using one of the examples provided in the Wiki:

SCRIPT:
`import twint
import pandas as pd
import nest_asyncio
nest_asyncio.apply()

username = "@Record_Politics"

c = twint.Config()
c.Limit = 20
c.Username = username
c.Store_pandas = True
c.Pandas = True
c.Debug = True
c.Store_csv = True
c.Output = "test_twint_df.csv"

twint.run.Search(c)

Tweets_df = twint.storage.panda.Tweets_df`

TRACEBACK: 
`CRITICAL:root:twint.get:User:'NoneType' object is not subscriptable
CRITICAL:root:twint.run:Twint:Feed:noDataExpecting value: line 1 column 1 (char 0)
sleeping for 1.0 secs
CRITICAL:root:twint.run:Twint:Feed:noDataExpecting value: line 1 column 1 (char 0)
sleeping for 8.0 secs`

OPERATING SYSTEM:
MacOS
