### ISSUE TITLE
How to read tweets one by one from list?

### ISSUE THREAD

**Issue by yemen2016** [twintproject/twint#416]
# Issue Template
Please use this template!

### Initial Check
> If the issue is a request please specify that it is a request in the title (Example: [REQUEST] more features). If this is a question regarding 'twint' please specify that it's a question in the title (Example: [QUESTION] What is x?). Please **only** submit issues related to 'twint'. Thanks.

>Make sure you've checked the following:

- [] Python version is 3.6;
- [] Updated Twint with `pip3 install --upgrade -e git+https://github.com/twintproject/twint.git@origin/master#egg=twint`;
- [] I have searched the issues and there are no duplicates of this issue/question/request.

### Command Ran
>Please provide the _exact_ command ran including the username/search/code so I may reproduce the issue.
import twint

c = twint.Config()

c.Username = 'noneprivacy'
c.Limit = 10
c.Store_object = True

twint.run.Search(c)
tweets = twint.output.tweets_object
for tweet in tweets:
	print (tweet)
### Description of Issue
>Please use **as much detail as possible.**
I have run the above code in order to obtain tweets one by one and I got the following output:
Size of List is:  20
<twint.tweet.tweet object at 0x7f8e81a55eb8>
<twint.tweet.tweet object at 0x7f8e81a55e48>
<twint.tweet.tweet object at 0x7f8e81a55e80>
<twint.tweet.tweet object at 0x7f8e81a55f60>
<twint.tweet.tweet object at 0x7f8e81a55fd0>
<twint.tweet.tweet object at 0x7f8e81a64080>
<twint.tweet.tweet object at 0x7f8e81a640f0>
<twint.tweet.tweet object at 0x7f8e81a64160>
<twint.tweet.tweet object at 0x7f8e81a641d0>
<twint.tweet.tweet object at 0x7f8e81a64240>
<twint.tweet.tweet object at 0x7f8e81a642b0>
<twint.tweet.tweet object at 0x7f8e81a64320>
<twint.tweet.tweet object at 0x7f8e81a64390>
<twint.tweet.tweet object at 0x7f8e81a64400>
<twint.tweet.tweet object at 0x7f8e81a64470>
<twint.tweet.tweet object at 0x7f8e81a644e0>
<twint.tweet.tweet object at 0x7f8e81a64550>
<twint.tweet.tweet object at 0x7f8e81a645c0>
<twint.tweet.tweet object at 0x7f8e81a64630>
<twint.tweet.tweet object at 0x7f8e81a646a0>

Kindly guide me how to print tweets one by one from tweets list.

Thanks
### Environment Details
>Using Windows, Linux? What OS version? Running this in Anaconda? Jupyter Notebook? Terminal?
I am running my code from Ubuntu 16 OS and Python 3.6.

**Comment by pielco11** [comment]
> Please only submit issues related to 'twint'

Basically you have to iterate over the list and access to the members via dot notation. 

```python
import twint
c = twint.Config()

c.Username = 'noneprivacy'
c.Limit = 10
c.Store_object = True

twint.run.Search(c)
tweets = twint.output.tweets_object
for tweet in tweets:
    print ('ID: {}'.format(tweet.id))
```

https://github.com/twintproject/twint/blob/49fe573293977fbea1519d828ae8ed7780eea28c/twint/tweet.py#L64-L96
