### ISSUE TITLE
_CRITICAL:root:twint.get:User:'NoneType' object is not subscriptable_

### ISSUE THREAD

**Issue by AdamRid** [twintproject/twint#417]
- [] Python version is 3.6.6;
- [] Installed by '**python setup.py install**' after cloning the repository (twint version 1.2.1)

### Command Ran
I'm working with tweet as a module in my code.

### Description of Issue
Possible bug in the code:
In module **twint.user**, line 12, there's extra blank space in the end of the pattern passed to **ur.find** method that cause getting the next error during the execution:
**_CRITICAL:root:twint.get:User:'NoneType' object is not subscriptable_**
The error has been captured on line 19 (in the same module) when trying to access '_group ["data-user-id"]_'. But because the _ur.find_ method fails to look for the div object with the class "user-actions btn-group not-following ", it returns a None object that is not _subscriptable_ by definition.
Converting "user actions btn-group not-following " to "user actions btn-group not-following" (without the last extra blank space) solved the problem.

### Environment Details
Linux, Centos 6 distro

**Comment by pielco11** [comment]
Honestly I do not know why you are getting the div without the extra space

![immagine](https://user-images.githubusercontent.com/17363750/57573548-955ea600-7429-11e9-9a2b-3db013cd96e8.png)

I'll try to fix this trying the second if the first fails

**Comment by pielco11** [comment]
With the patch Twint tries a couple of selectors, seems to work fine
