### ISSUE TITLE
AttributeError: module 'twint' has no attribute 'Config'

### ISSUE THREAD

**Issue by kiwamizamurai** [twintproject/twint#422]
### Issue

     c = twint.Config()
     AttributeError: module 'twint' has no attribute 'Config'

### Script

nikkei.py

    import twint
    # Configure
    c = twint.Config()
    c.Search = "日経"
    c.Format = " Tweet: {tweet}"
    c.Output = 'nikkei'
    c.Store_csv = True
    c.Since = 2016-6-25
    c.Until = 2017-6-27
    # Run
    twint.run.Search(c)

### Command Ran

Just Run on the IntelliJ

### Description of Issue

Could not run `nikkei.py`

- https://github.com/twintproject/twint/issues/92

It is similar to this issue, but it is not.

### Environment Details

IntelliJ

**Comment by pielco11** [comment]
How did you install Twint? Went everything ok? Are you able to use Twint outside IntelliJ?

**Comment by kiwamizamurai** [comment]
```
git clone https://github.com/twintproject/twint.git
pip3 install -r requirements.txt
```

At first, everything was fine, but it suddenly did not work.
No, I cannot use Twint from Terminal either.

**Comment by kiwamizamurai** [comment]
Once I moved nikkei.py file to directly under the Twint folder, it worked. Thanks.
