### ISSUE TITLE
JSON error

### ISSUE THREAD

**Issue by EmanueleCozzo** [twintproject/twint#430]
Under Ubuntu 18 I'm now getting the following error whatever the command (everything work since today):

line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by AtrusHB** [comment]
Same under Windows 7.

**Comment by pielco11** [comment]
Might be related to #426

Please be sure to have Twint updated and retry

**Comment by EmanueleCozzo** [comment]
Now it's working again without updating

**Comment by pielco11** [comment]
@EmanueleCozzo initially it was not working because the server was offline. I highly suggest you to update so that when the website will be offline again, Twint will automatically pick an UA from a given list

**Comment by pielco11** [comment]
I'm going to close this issue since a solution has been found.

For any question I kindly ask you to post it in #426 to avoid duplicates
