### ISSUE TITLE
--retweet error (index out of range)

### ISSUE THREAD

**Issue by nothx2** [twintproject/twint#431]
### Command Ran
twint -u realdonaldtrump --retweet
### Description of Issue
copy-paste from the terminal output:

`1115412261273841669 2019-04-09 02:33:01 CEST RT <WhiteHouse> The newly constructed 30-foot wall in Calexico, CA, replaces a barrier made of surplus corrugated steel landing mats from the Vietnam War—and border officials tell President @realDonaldTrump it's making a crucial difference.  1600 Daily:  http://45.wh.gov/5yKBD8  pic.twitter.com/FGHwZeBlgG
1115475412606496768 2019-04-09 06:43:57 CEST <realDonaldTrump> Congratulations to Virginia - Great game!
CRITICAL:root:twint.run:Twint:Feed:noDatalist index out of range
CRITICAL:root:twint.run:Twint:Feed:noDatalist index out of range
CRITICAL:root:twint.run:Twint:Feed:noDatalist index out of range
CRITICAL:root:twint.run:Twint:Feed:noDatalist index out of range
CRITICAL:root:twint.run:Twint:Feed:noDatalist index out of range
CRITICAL:root:twint.run:Twint:Feed:noDatalist index out of range
CRITICAL:root:twint.run:Twint:Feed:noDatalist index out of range
CRITICAL:root:twint.run:Twint:Feed:noDatalist index out of range
CRITICAL:root:twint.run:Twint:Feed:noDatalist index out of range
CRITICAL:root:twint.run:Twint:Feed:noDatalist index out of range
CRITICAL:root:twint.run:Twint:Feed:Tweets_known_error:list index out of range
list index out of range [x] run.Feed
[!] if get this error but you know for sure that more tweets exist, please open an issue and we will investigate it!
`

### Environment Details
ubuntu 18.04

**Comment by pielco11** [comment]
I tested that query and others, I can't reproduce your error. Maybe it's just an isolated even, please retry later and/or with other users

**Comment by nothx2** [comment]
Unfortunately, I get the exact same error. Even tried as root.

**Comment by pielco11** [comment]
Twitter does not allow Twint to get more than a few 100s of retweets
