### ISSUE TITLE
[QUESTION] Hide result

### ISSUE THREAD

**Issue by AntonioNieto92** [twintproject/twint#433]
### Description of Issue
>Hi, how can I hide the log: "CRITICAL:root:twint.get:User:'NoneType' object is not subscriptable"?

![image](https://user-images.githubusercontent.com/23341043/58245058-3ae01680-7d54-11e9-8049-9fabd4e7fe5c.png)

Thanks in advance!

### Environment Details
>Using Windows

**Comment by pielco11** [comment]
https://github.com/twintproject/twint/blob/f124a2789c8ae98a6765b67b49fefbc30a67e43b/twint/get.py#L193-L203

Replace `logme.critical(__name__+':User:' + str(e))` with `pass`
