### ISSUE TITLE
[ERROR] CRITICAL:root:twint.get:Multi:'NoneType' object is not callable / getting user's Retweets

### ISSUE THREAD

**Issue by AntonioNieto92** [twintproject/twint#434]
### Command Ran
>c.Retweets = True
c.Profile_full = True
twint.run.Profile(c)

### Description of Issue
>Hi, when I include user's retweets, I get the following:

![image](https://user-images.githubusercontent.com/23341043/58248420-5f3ff100-7d5c-11e9-82cb-d6c4a343d91c.png)

And aftwerwards (more than 30 min), I get an error like out of range or something like that

### Environment Details
>Using Windows

**Comment by pielco11** [comment]
Hmmm, quite strange. But it seems that you still get all the data

For example, with my profile:

![immagine](https://user-images.githubusercontent.com/17363750/58284287-950bc680-7daa-11e9-8756-0e6b139cad2a.png)

![immagine](https://user-images.githubusercontent.com/17363750/58284336-afde3b00-7daa-11e9-9c2e-0916b0bbf00d.png)

As you may see, the error does not represent a tweet that's not being scraped for some reasons (at least in this case)

I kindly ask you to do the same and let me know what you get

**Comment by pielco11** [comment]
With `retweets` you can get a few 100s of tweets, then Twitter does not return more data so an empty list. Then Twint retries the request since Twitter sometimes lies, if Twitter does not return more data too many times, Twint stops.
