### ISSUE TITLE
[Request] Too many options can be defined, but some do not work

### ISSUE THREAD

**Issue by badele** [twintproject/twint#437]
For example, i trying to get all tweets and retweets (it's important). I try some functions, it seems the best practice, that use `Profile` function (for get retweets). And i also see we can use the `Resume` option.

But after analysing the code (why i must analysing it) i see the `Resume` option seem only work with `Search` function .

I think the best pratice, if we use some options does not working with main function(Ex: `Profile`), raise exception, because too options, too confusions.

The second solutions. ex:

For some functions that we want call

```
twint.run.Search() 
twint.run.Followers() 
twint.run.Following() 
twint.run.Favorites() 
twint.run.Profile() 
twint.run.Lookup() 
```

We can use configuration like this

```
# We can see, we use search options for Profile function (that eliminate confusion)
c = twint.Config()
c.search.resume = 12345
c.global.limit = 50
twint.run.Search() 

# We can see, we use search options for Profile function (that eliminate confusion)
c = twint.Config()
c.search.resume = 12345
c.global.limit = 50
twint.run.Profile() 
```

Also the code, can raise excaption if some options have setted for other function we want call

**Comment by 0xSnipe** [comment]
![image](https://user-images.githubusercontent.com/42121860/58824240-ea15cb00-863b-11e9-83ad-8f48d3cbc704.png)

Perhaps something like this in the wiki to make it clear which flags are for which data gathering type
I have ran into this issue too

**Comment by pielco11** [comment]
@0xSnipe that structure is not clear to me, may be elaborate please?
