### ISSUE TITLE
Fake-useragent library error

### ISSUE THREAD

**Issue by fatihhcelik** [twintproject/twint#443]
>Make sure you've checked the following:

- [+] Python version is 3.6;
- [+] Updated Twint with `pip3 install --upgrade -e git+https://github.com/twintproject/twint.git@origin/master#egg=twint`;
- [+] I have searched the issues and there are no duplicates of this issue/question/request.

### Description of Issue
I'm working on linux enviroment with python and twint and I use twint as a python module. Today, I realized twint module gives me an error, I updated everyting and double-check but gave me nothing. Output of the error is below, [Django,Gunicorn,Nginx these are that I used in my project.]
```
WARNING:fake_useragent:Error occurred during loading data. Trying to use cache server https://fake-useragent.herokuapp.com/browsers/0.1.11
Traceback (most recent call last):
  File "/usr/lib/python3.6/urllib/request.py", line 1318, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/usr/lib/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/usr/lib/python3.6/http/client.py", line 964, in send
    self.connect()
  File "/usr/lib/python3.6/http/client.py", line 1400, in connect
    server_hostname=server_hostname)
  File "/usr/lib/python3.6/ssl.py", line 407, in wrap_socket
    _context=self, _session=session)
  File "/usr/lib/python3.6/ssl.py", line 817, in __init__
    self.do_handshake()
  File "/usr/lib/python3.6/ssl.py", line 1077, in do_handshake
    self._sslobj.do_handshake()
  File "/usr/lib/python3.6/ssl.py", line 689, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:847)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.6/site-packages/fake_useragent/utils.py", line 67, in get
    context=context,
  File "/usr/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.6/urllib/request.py", line 526, in open
    response = self._open(req, data)
  File "/usr/lib/python3.6/urllib/request.py", line 544, in _open
    '_open', req)
  File "/usr/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 1361, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/usr/lib/python3.6/urllib/request.py", line 1320, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:847)>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.6/site-packages/fake_useragent/utils.py", line 154, in load
    for item in get_browsers(verify_ssl=verify_ssl):
  File "/home/ubuntu/.local/lib/python3.6/site-packages/fake_useragent/utils.py", line 97, in get_browsers
    html = get(settings.BROWSERS_STATS_PAGE, verify_ssl=verify_ssl)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/fake_useragent/utils.py", line 84, in get
    raise FakeUserAgentError('Maximum amount of retries reached')
fake_useragent.errors.FakeUserAgentError: Maximum amount of retries reached
```

**Comment by louisgregg** [comment]
fake-useragent gets a list of user-agent strings from w3schools, specifically the url https://www.w3schools.com/browsers/default.asp 
This url still works and it seems this error happens only part of the time, when 2 requests to w3schools fails - hence 'Maximum amount of retries reached'.
Perhaps a quick fix is to allow more retries before raising the error? say, 5? This could be achieved by increasing the HTTP_RETRIES variable in the settings.py file for fake-useragent. I'm going to try this fix and see if it helps. Will post back.

**Comment by fatihhcelik** [comment]
Firstly,thanks for your comment. Maybe we can get the list of user-agent strings to our local thus we can eliminate this error? Am I missing something? Why are we keeping request to live website to fetch user-agents every time?

**Comment by fatihhcelik** [comment]
> Perhaps a quick fix is to allow more retries before raising the error? say, 5? This could be achieved by increasing the HTTP_RETRIES variable in the settings.py file for fake-useragent.
I updated HTTP_RETRIES variable's value as a 10 but error is still exist my local. I can't do any query right now using twint module.

**Comment by louisgregg** [comment]
>  Why we are keeping request to live website to fetch user-agents every time?
I would guess we do this to get an up-to-date set of user strings (including their usage statistics) to better mimic a non-automated request. 
> Maybe we can get the list of user-agent strings to our local thus we can eliminate this error?
We do have a list of user-agent strings stored locally, and indeed fake-useragent can obtain a list from a cache server maintained by the author instead of going to the w3schools website. So there's a couple ways we could avoid this error. 
If you need quick fix **now**  then you can edit the twint file get.py and replace:
`
async def RandomUserAgent():
    logme.debug(__name__+':RandomUserAgent')
    try:
        ua = UserAgent()
        return ua.random
    except:
        return random.choice(user_agent_list)
`
with the following code:
`
async def RandomUserAgent():
    logme.debug(__name__+':RandomUserAgent')
    return random.choice(user_agent_list)
`
This will avoid querying a website to obtain a list of user-agent strings. However, this list is not updated frequently and makes it more likely for your traffic to be flagged as automated and blocked. So use with caution. 
Better fixes are possible. I'll play with the fake-useragent and twint modules today and try to find a better fix.

**Comment by fatihhcelik** [comment]
Thanks for your effort and quick response. I modify the code as you said but it seems doesn't work for me.

**Comment by louisgregg** [comment]
One possible reason for this is that you need to install twint as a editable install. So re-install twint using the command 
```
pip3 install --upgrade -e git+https://github.com/twintproject/twint.git@origin/master#egg=twint
```
This will probably be most easily achieved using a virtual environment for the editable install.
```
python3 -m venv twint-env
. /twint-env/bin/activate
# then install from github as editable
pip3 install --upgrade -e git+https://github.com/twintproject/twint.git@origin/master#egg=twint 
```
Then, you implement the quick-fix I suggested above. In my virtual-env example in this post you'll need to replace the code in the file ./twint-env/src/twiint/twint/get.py

Then, twint will only generate user agent strings from the local list, skipping fake-useragent altogether.

**Comment by pielco11** [comment]
https://github.com/twintproject/twint/blob/4e1347257f8b8b1d6c3946a88b7817339a8d5e0b/twint/get.py#L22-L46

https://github.com/twintproject/twint/blob/4e1347257f8b8b1d6c3946a88b7817339a8d5e0b/twint/get.py#L165-L171

This is issue has already been addressed. Please be sure to run the up-to-date repo

**Comment by pielco11** [comment]
I guess that's the error message to be annoying, so I'm going to handle it in a cleaner way and print a short error message if the server is unreachable
