### ISSUE TITLE
Saving Tweets in pandas DF return TypeError: 'DataFrame' object is not callable// savong in json is impossible

### ISSUE THREAD

**Issue by hokusai-tristan** [twintproject/twint#444]
Hello!

And thank you so much for your hardwork... I encountered recently many mistakes with this slice of test code (in the past i used a lot twint and it worked well):
```python
import twint
import time
c =twint.Config()
c.Username="0xdefec7edcafe"
c.Resume = "history_ids.txt"
Pandas=True
#c.Format = "{id}\001{date}\001{user_id}\001{timezone}\001{tweet}\001{location}\001{hashtags}\001{replies}\001{retweets}\001{likes}\001{link}\001{is_retweet}\001{mentions}"
c.Since = "2019-06-01"
c.Until = "2019-06-04"
twint.run.Search(c)
tweets_df= twint.storage.panda.Tweets_df()
print(tweets_df)
```

Returned error code is:
'Traceback (most recent call last):
  File "test_twint.py", line 28, in <module>
    tweets_df= twint.storage.panda.Tweets_df()
TypeError: 'DataFrame' object is not callable'
The console returned well all tweets of the user for the period desired.
Twint is uptodate, it turns on raspberry with python 3.6

Thanks for all!!!!

**Comment by hokusai-tristan** [comment]
Ok So let me correct something. I have tested in json in my laptop and it's working. Issue concerning json seems to come from raspberry configuration. Any idea? 
Thanks again

**Comment by pielco11** [comment]
`Tweets_df` is a variable, not a function https://github.com/twintproject/twint/blob/master/twint/storage/panda.py#L6

So you have just use `tweets_df= twint.storage.panda.Tweets_df`
Plus, you have to specify `c.Pandas = True` as well

**Comment by hokusai-tristan** [comment]
....Thanks you Pielco11.... so silly am i... so obvious.... i will tell with some changes if it s ok. Still does not understand why on rasp json don't work well. It must be from my side but i have no clue...i have to find tint users workin with rasp
