### ISSUE TITLE
CRITICAL:root:twint.output:_output:CSV:Error:'tweet' object has no attribute 'near'

### ISSUE THREAD

**Issue by edmundlim2806** [twintproject/twint#445]
# Issue Template
Please use this template!

### Initial Check
> If the issue is a request please specify that it is a request in the title (Example: [REQUEST] more features). If this is a question regarding 'twint' please specify that it's a question in the title (Example: [QUESTION] What is x?). Please **only** submit issues related to 'twint'. Thanks.

>Make sure you've checked the following:

- [x] Python version is 3.6;
- [x] Updated Twint with `pip3 install --upgrade -e git+https://github.com/twintproject/twint.git@origin/master#egg=twint`;
- [x] I have searched the issues and there are no duplicates of this issue/question/request.

### Command Ran
>Please provide the _exact_ command ran including the username/search/code so I may reproduce the issue.

twint -g="48.880048,2.385939,1km" -o file.csv --csv

### Description of Issue
>Please use **as much detail as possible.**

Sorry for any inconvenience as I'm still very new to Python and coding in general. I've been trying to get this code to run for a while now and output to csv/json, but every time I do so, I'll get an error message:
csv: 'tweet' object has no attribute 'near' [x] output._output
json: AttributeError: 'tweet' object has no attribute 'near'
![image](https://user-images.githubusercontent.com/35293196/58852962-73ef8380-8690-11e9-83a3-ca95ebd41f07.png)

And nothing ends up getting outputted. Any idea what's going wrong here?

### Environment Details
>Using Windows, Linux? What OS version? Running this in Anaconda? Jupyter Notebook? Terminal?

Windows 10.0.17763. Running this in Visual Studio Code. Python 3.6 installed. 

### Update 1:
Quick update, removing line 30/31
>     if t.near:
>        data.update({"near": t.near})

 and line 60
>             "near"

from the write_meta.py file seems to work.

**Comment by pielco11** [comment]
Fixed
