### ISSUE TITLE
ISSUE: 'tweet' object has no attribute 'profile_image_url'

### ISSUE THREAD

**Issue by CriclyticsDBDA** [twintproject/twint#446]
Python version is 3.6;
Updated Twint with `pip3 install --upgrade -e git+https://github.com/twintproject/twint.git@origin/master#egg=twint`;
I have searched the issues and there are no duplicates of this issue/question/request.

### Command Ran
c = twint.Config()
c.Search = "data science"
c.Format = "Username: {username} |  Tweet: {tweet}"
c.Limit = 1
c.Pandas = True

twint.run.Search(c)

### Description of Issue
'tweet' object has no attribute 'profile_image_url'

Using Linux, Running this in Anaconda Spyder.

**Comment by pielco11** [comment]
Please update and retry

Plus, Twitter returns data in chunks of 20 tweets so `c.Limit` should be a multiple of 20. If you set `c.Limit` to something in between 20 and 39, you will still get 20 tweets because with the next chunk of 20 tweets (so for a total of 40) will exceed your limit
