### ISSUE TITLE
twint.feed:Mobile:list index out of range

### ISSUE THREAD

**Issue by betasm** [twintproject/twint#447]
### Error message
twint.feed:Mobile:list index out of range

### Command Ran

twint -u srvmshr --favorites -o output.csv

### Description of Issue
The feed of favorites stops at 3237 (out of a possible ~4200 favorited tweets) after the last scraped tweet (i.e. after 3237th oldest tweet the Error message is displayed) The account being scraped is mine @srvmshr

### Environment Details
Using Linux 18.04 with a environment on Anaconda (Py3.6 + pip installed requirements) . The environment is up to date and `git-pull` done for build as of 2019-06-5

### Additional notes:
Issue reported on #twint in OS-INT Slack channel

### Object details
The offending tweet at two simultaenous runs is 
> https://twitter.com/fhuszar/status/875462826105552896

I have unfavorited the tweet to see if TWINT is making an isolated error on this particular status message.

**Comment by betasm** [comment]
### Update: 
The list still stops at the particular tweet (3236th tweet)

**Comment by pielco11** [comment]
`since` and `until` can't be used with following/followers/profile/favorites, only with search

Favorites and Profile are subjected to restrictions by Twitter, which means that you can get about 3200 tweets

**Comment by betasm** [comment]
I think there is still some bug which is not understood well.

I pruned my own "Likes" down to 2148. Yet, the parsing and collection stops repeatedly before list runs out.  Still shows list `index out of range.` Technically, this should not happen as the number is now well below 3200.

**Comment by pielco11** [comment]
@betasm Twitter might stop before for unknown reasons
