### ISSUE TITLE
Unable to intall twint - ModuleNotFoundError: No module named 'twint'

### ISSUE THREAD

**Issue by fareid-32** [twintproject/twint#451]
So I am having difficulty installing Twint package.
I am using Anaconda and Spyder for my environment.

Having downloaded Git, I the use pip to install the relevant packages using the following command:
pip3 install --upgrade -e git+https://github.com/twintproject/twint.git@origin/master#egg=twint

the installation works fine in the anaconda prompt window, and I get following message returned: "Successfully installed aiodns-2.0.0 aiohttp-3.5.4 aiohttp-socks-0.2.2 async-timeout-3.0.1 cchardet-2.1.4 elasticsearch-7.0.2 fake-useragent-0.1.11 geographiclib-1.49 geopy-1.20.0 idna-ssl-1.1.0 multidict-4.5.2 pycares-3.0.0 schedule-0.6.0 twint typing-3.6.6 typing-extensions-3.7.2 yarl-1.3.0"

however, when I open Spyder and running the command "import twint", I get the following error message: ModuleNotFoundError: No module named 'twint'.

I am wondering if anyone has any idea why this might be the case?

**Comment by pielco11** [comment]
Strange, using `pip3 ...` will install Twint as globally accessible, so running that command in a directory or another, nothing change.

Could be that you have a directory with the same name (Twint) in the directory which you are running Anaconda

![immagine](https://user-images.githubusercontent.com/17363750/59504378-1da9ee00-8ea3-11e9-8fff-c04cad198399.png)

In yellow the wrong module is loaded, in cyan the correct module is loaded

**Comment by fareid-32** [comment]
@pielco11 thanks for getting back to me. it seems like this was the exact reason for the error. 

Having sorted out the directories, twint appears to be running fine. Thank you for the solution, much appreciated!
