### ISSUE TITLE
When running as a module twint dosn't get all videos, but when running from the command line it dosn't

### ISSUE THREAD

**Issue by NewCTwo** [twintproject/twint#452]
>Make sure you've checked the following:

- [X] Python version is 3.6;
- [X] Updated Twint with `pip3 install --upgrade -e git+https://github.com/twintproject/twint.git@origin/master#egg=twint`;
- [X] I have searched the issues and there are no duplicates of this issue/question/request.

### Command Ran
Not applicable.

### Description of Issue

There are two types of possible videos: Videos _posted_ to twitter and videos _linked_ to twitter from some other source like youtube or periscope. 

When I use the python module,

	c = twint.Config()
	c.Username = usn
	c.Store_csv = True
	c.Output = directory
	c.Limit = 999999999

 it gives me a csv with a 'video' column, but it only gets videos posted to twitter.  But when I use the command line:

       twint -u username --videos

It gets videos no matter what site. Why don't these return identical results?

### Environment Details
Linux 18.04 and Python 3.6

**Comment by pielco11** [comment]
Using `--videos` via CLI is the same as using `c.Videos = True` with Twint as module

The `video` column is used to indicate if the tweet has a video, if I share a link to a Youtube video there's no video

**Comment by NewCTwo** [comment]
Then why can't I do: 

     c.Media = True

To get video links?

**Comment by pielco11** [comment]
`c.Media = True` filters for `media` (images, gifs, videos) and (quite surprisingly) I find links to YouTube as well. That's quite confusing because if you share a link to a video, you are not sharing the video itself

That said, I'll correct my previous statement: searching for videos means searching for link to videos as well
