### ISSUE TITLE
[BUG] Tweet has no location field but Pandas expects it

### ISSUE THREAD

**Issue by danielblignaut** [twintproject/twint#454]
# Issue Template
Please use this template!

### Initial Check
> If the issue is a request please specify that it is a request in the title (Example: [REQUEST] more features). If this is a question regarding 'twint' please specify that it's a question in the title (Example: [QUESTION] What is x?). Please **only** submit issues related to 'twint'. Thanks.

>Make sure you've checked the following:

- [] Python version is 3.6;
- [] Updated Twint with `pip3 install --upgrade -e git+https://github.com/twintproject/twint.git@origin/master#egg=twint`;
- [] I have searched the issues and there are no duplicates of this issue/question/request.

### Command Ran
>Please provide the _exact_ command ran including the username/search/code so I may reproduce the issue.

### Description of Issue
Hi, I can see in a commit 9 days ago you removed the "location" attribute of the tweet. This is still being referenced in the Pandas storage object class and throws the below error:

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-39-0f903a7b0a7a> in <module>
      4 output_file_name="data/output_south_african_economy-2019_01_01-2019_01_09.csv"
      5 max_workers=8
----> 6 tweets = save_tweets(topic,start_date,end_date, output_file_name,max_workers)

<ipython-input-38-697248a6f078> in save_tweets(topic, start_date, end_date, output_file, max_workers)
     92     with open(output_file, 'a') as f:
     93         f.write(header_string)
---> 94     save_tweets_in_parallel(topic, start_date,end_date, output_file, max_workers=max_workers)
     95     #tweets_df = convert_tweets_to_dataframe(tweets)
     96     #tweets_df.to_csv(output_file_name, index = None, header=True)

<ipython-input-38-697248a6f078> in save_tweets_in_parallel(topic, start_date, end_date, output_file, max_workers)
     42         requests.append(asyncio.ensure_future(get_tweets_worker(topic, date_range[i],date_range[i+1], output_file)))
     43 
---> 44     tweet_results = loop.run_until_complete(asyncio.gather(*requests))
     45 
     46     return tweet_results

~/anaconda3/envs/twint/lib/python3.6/site-packages/nest_asyncio.py in run_until_complete(self, future)
     59             while not f.done():
     60                 run_once(self)
---> 61             return f.result()
     62         else:
     63             return self._run_until_complete_orig(future)

~/anaconda3/envs/twint/lib/python3.6/asyncio/tasks.py in _step(***failed resolving arguments***)
    178                 # We use the `send` method directly, because coroutines
    179                 # don't have `__iter__` and `__next__` methods.
--> 180                 result = coro.send(None)
    181             else:
    182                 result = coro.throw(exc)

<ipython-input-38-697248a6f078> in get_tweets_worker(topic, start_date, end_date, output_file)
     12     c.Custom["location"] = ["id"]
     13 
---> 14     twint.run.Search(c)
     15     tweets_df= twint.storage.panda.Tweets_df()
     16     tweets_df = convert_tweet_objects_to_dataframe(tweets_df)

~/Documents/Development/machine-learning/src/twint/twint/run.py in Search(config, callback)

~/Documents/Development/machine-learning/src/twint/twint/run.py in run(config, callback)

~/anaconda3/envs/twint/lib/python3.6/site-packages/nest_asyncio.py in run_until_complete(self, future)
     59             while not f.done():
     60                 run_once(self)
---> 61             return f.result()
     62         else:
     63             return self._run_until_complete_orig(future)

~/anaconda3/envs/twint/lib/python3.6/asyncio/tasks.py in _step(***failed resolving arguments***)
    180                 result = coro.send(None)
    181             else:
--> 182                 result = coro.throw(exc)
    183         except StopIteration as exc:
    184             if self._must_cancel:

~/Documents/Development/machine-learning/src/twint/twint/run.py in main(self, callback)

~/anaconda3/envs/twint/lib/python3.6/asyncio/tasks.py in _wakeup(self, future)
    248     def _wakeup(self, future):
    249         try:
--> 250             future.result()
    251         except Exception as exc:
    252             # This may also be a cancellation.

~/anaconda3/envs/twint/lib/python3.6/asyncio/tasks.py in _step(***failed resolving arguments***)
    178                 # We use the `send` method directly, because coroutines
    179                 # don't have `__iter__` and `__next__` methods.
--> 180                 result = coro.send(None)
    181             else:
    182                 result = coro.throw(exc)

~/Documents/Development/machine-learning/src/twint/twint/run.py in run(self)

~/Documents/Development/machine-learning/src/twint/twint/run.py in tweets(self)

~/Documents/Development/machine-learning/src/twint/twint/output.py in Tweets(tweets, config, conn, url)

~/Documents/Development/machine-learning/src/twint/twint/output.py in checkData(tweet, config, conn)

~/Documents/Development/machine-learning/src/twint/twint/storage/panda.py in update(object, config)

AttributeError: 'tweet' object has no attribute 'location'

### Environment Details
>Using Windows, Linux? What OS version? Running this in Anaconda? Jupyter Notebook? Terminal?

MacOS

**Comment by danielblignaut** [comment]
I haven't checked other storage types if this a potential issue there as well.

**Comment by danielblignaut** [comment]
https://github.com/twintproject/twint/pull/455

**Comment by pielco11** [comment]
Whops! My bad, I'm going to merge your PR right now. Thanks for the fix and for your patience
