### ISSUE TITLE
Ran Command "Twint" But Says  bash: twint: command not found

### ISSUE THREAD

**Issue by thalfpant** [twintproject/twint#456]
# Issue Template
Please use this template!

### Initial Check

>Make sure you've checked the following:

- [] Python version is 3.6;
- [] Updated Twint with `pip3 install --upgrade -e git+https://github.com/twintproject/twint.git@origin/master#egg=twint`;
- [] I have searched the issues and there are no duplicates of this issue/question/request.

### Command Ran
> Twint
### Description of Issue
>Installed Twint Using Pip3. Ran Twint Command. And Says This " bash: twint: command not found" What TO Do?

### Environment Details
>Using Kali Linux.

**Comment by Matiusco** [comment]
I using bash terminal virtualenvs  

pipenv shell
Launching subshell in virtual environment…
 . /home/matiusco/.local/share/virtualenvs/twint-BwUoZn5H/bin/activate
matiusco@dev-py:twint$> . /home/matiusco/.local/share/virtualenvs/twint-BwUoZn5H/bin/activate
(twint) matiusco@dev-py:twint$> 

(twint) matiusco@dev-py:twint$>  [-] Error: Please use at least -u, -s, -g or --near. 

my install with pipenv 
https://github.com/twintproject/twint/blob/master/README.md

If I did not understand your question, sorry.

**Comment by pielco11** [comment]
@thalfpant please add more information, thank you

**Comment by pielco11** [comment]
![immagine](https://user-images.githubusercontent.com/17363750/60204497-42ad4200-984f-11e9-97d3-6f0eb56c1a3e.png)

**Comment by walter-grace** [comment]
https://pypi.org/project/twint/
pip3 install twint **
Should fix it
