### ISSUE TITLE
how to use OR AND operators in search

### ISSUE THREAD

**Issue by jamestch** [twintproject/twint#458]
### Initial Check

>Make sure you've checked the following:

- [checked] Python version is 3.6.8;
- [checked] Updated Twint with `pip3 install --upgrade -e git+https://github.com/twintproject/twint.git@origin/master#egg=twint`;
- [checked] I have searched the issues and there are no duplicates of this issue/question/request.

### python3 test.py

import twint

c = twint.Config()
c.Search = "basketball OR football OR badminton OR volleyball"
c.Resume = "history_ids.txt"
c.Store_json = True
c.Output = "sports.json"
c.Lang = "en"
c.Count = True
twint.run.Search(c)

### Description of Issue
>I  want to use "OR" operator  to search tweets which contain "basketball" or "football" or "badminton" or "volleyball", anyone of them. But it seem does not work, is this usage correct?

### Environment Details

Package           Version  Location
----------------- -------- ---------------------------------------------
aiodns            2.0.0
aiohttp           3.5.4
aiohttp-socks     0.2.2
async-timeout     3.0.1
attrs             19.1.0
beautifulsoup4    4.7.1
cchardet          2.1.4
certifi           2019.3.9
cffi              1.12.3
chardet           3.0.4
elasticsearch     7.0.0
fake-useragent    0.1.11
geographiclib     1.49
geopy             1.19.0
idna              2.8
idna-ssl          1.1.0
multidict         4.5.2
numpy             1.16.3
oauthlib          3.0.1
pandas            0.24.2
pip               19.1
pycares           3.0.0
pycparser         2.19
PySocks           1.6.8
python-dateutil   2.8.0
pytz              2019.1
requests          2.22.0
requests-oauthlib 1.2.0
schedule          0.6.0
setuptools        41.0.1
six               1.12.0
soupsieve         1.9.1
tweepy            3.7.0
twint             1.2.3    /home/james/app/twitter_crawler/src/twint
typing            3.6.6
typing-extensions 3.7.2
urllib3           1.25.2
wheel             0.33.1
yarl              1.3.0

**Comment by pielco11** [comment]
I tried your query and it works, matches the results of the simple search with Twitter

![immagine](https://user-images.githubusercontent.com/17363750/59917687-e13a3d00-9422-11e9-8512-a9779ba908fa.png)

![immagine](https://user-images.githubusercontent.com/17363750/59917715-f31be000-9422-11e9-8e6c-a7ea35170799.png)

**Comment by michael-ziedalski** [comment]
How would one chain together logical operators? Like, say one wanted to search "thing1 AND (thing2 OR thing3)"?

Is something like that possible?

**Comment by pielco11** [comment]
@michael-ziedalski you can try with something like `crypto security OR privacy`, which returns every tweet that contains `crypto` for sure. and `security` or `privacy`

It still seems that an `AND` operator does not exist like exists `OR`. But it seems that, operator or scope specifier (`from:`, `to:`, ...) a part, Twitter splits the query and automatically adds the `AND` operator between the pieces. This is what makes sense to me
