### ISSUE TITLE
Kibana: Index Pattern Conflicts

### ISSUE THREAD

**Issue by ParkerShamblin** [twintproject/twint#459]
Guide I was following: https://github.com/twintproject/twint/wiki/Elasticsearch

I received the following error while "go to Management tab (the gear), Saved Objects, **Import and then select visualizations.json**, repeat the process for dashboard.json. After this just to go Dashboard tab and click on Twint Dashboard."

When I tried importing visualizations I received the following error:
![index_pattern_conflicts](https://user-images.githubusercontent.com/48718776/59959787-f8f9db80-948b-11e9-9d29-22e8278ee97f.PNG)

My dashboard still seems to work fine. I'm just curious if anyone knows why this is happens and what the implications are?

**Comment by pielco11** [comment]
@ParkerShamblin this happens because the ID of your index, is different from the one which I made the visualizations/dashboards with

Solving the conflicts should work as expected. Basically you are changing the ID of the visualizations/dashboards from mine to your
