### ISSUE TITLE
Resume does not seem to work

### ISSUE THREAD

**Issue by mattrocklage** [twintproject/twint#460]
- [x] Python version is 3.7.3;
- [X] Updated Twint with `pip3 install --upgrade -e git+https://github.com/twintproject/twint.git@origin/master#egg=twint`;
- [X] I have searched the issues and there are no duplicates of this issue/question/request.

### Command Ran
>twint -s nike -l en --since 2018-09-04 --until 2018-09-05 -o nike.csv --csv --debug --resume nike_resume.txt

### Description of Issue
>Twint stops after getting partially through September 4. I know there are more tweets, though, and so I am trying to resume from where Twint left off. However, Twint seems to be ignoring the "resume" text file and just starts from the beginning of September 4 again. The stored position in the nike_resume.txt file is "thGAVUV0VFVBaAwLXhqKr84xwWgICjif-kz-QcEjUAFQAlAFUAFQAA"

>Another solution would be to ask Twint to retry the same request after a brief pause (instead of stopping when it doesn't find more tweets at that moment), but I'm not sure how to modify the code myself to do that.

### Environment Details
>Linux 4.14.121 terminal ("Amazon Linux")

**Comment by pielco11** [comment]
Confirmed that's not working. For now a workaround would be using `since` and `until`

**Comment by pielco11** [comment]
I'm going to link this issue to an older one and reopen it, just to avoid duplicates #440

**Comment by pushshift** [comment]
I just want to chime in here and offer a workaround for the time being. If you are doing a search on a term and it stops prematurely, you can then do a search for that term and another term that is similar in frequency and you should be able to push past the problem time period.

In this instance, searching for Nike OR Shoe should work. The downside is you will need to do more post-processing by throwing out comments only related to shoe and not Nike -- but it does help in these situations.
