### ISSUE TITLE
[Question] Is Get_replies not working?

### ISSUE THREAD

**Issue by DenseLance** [twintproject/twint#464]
- [x] Python version is 3.6; 
- [x] Updated Twint with `pip3 install --upgrade -e git+https://github.com/twintproject/twint.git@origin/master#egg=twint`;
- [x] I have searched the issues and there are no duplicates of this issue/question/request.

### Command Ran
```
import twint

c = twint.Config()

c.Username = "Resister_Charli"
c.Since = "2019-05-01"
c.Retweets = False
c.Get_replies= False
c.Format = "Tweet id: {id} | Username: {username} | Date: {date} | Likes: {likes}"

#To bypass twint.run.Profile(c)'s limitation --> cannot use config.Since, and it cannot scrape tweets that are beyond approx. 90 posts
twint.run.Search(c)
```

### Description of Issue
I was running the earlier code for my project, and from what I received as the results, some of those are replies made by this particular user I'm searching for (which I do not want). 
I tried it with  `c.Replies = False` , but nothing has changed.
Is there a way to only get the posts made by the user with the exclusion of Retweets and Replies?
Thanks once again!

### Environment Details
Windows, Python.

**Comment by pielco11** [comment]
`config.Replies` is `False` by default, but can't search for tweets that are not replies. What you should do getting the tweets and, after that, filter them thus keeping only the ones which `id` is the same as `conversation_id`

**Comment by DenseLance** [comment]
There seems to be some problem with conversation_id, but it could be a problem on my side.

### Command Ran:
```
import twint

c = twint.Config()

c.Username = "Resister_Charli"
c.Since = "2019-05-01"
c.Format = "Tweet id: {id} | Conversation ID: {conversation_id} | Date: {date} | Likes: {likes} | Username: {username}"

twint.run.Search(c)
```

### An example of a result obtained:
`Tweet id: 1145177847222325248 | Conversation ID: {conversation_id} | Date: 2019-06-30 | Likes: 0 | Username: Resister_Charli`
