### ISSUE TITLE
Search command loops the first few results

### ISSUE THREAD

**Issue by HydroHydro** [twintproject/twint#465]
>Make sure you've checked the following:

- [x] Python version is 3.6;
- [x] Updated Twint with `pip3 install --upgrade -e git+https://github.com/twintproject/twint.git@origin/master#egg=twint`;
- [x] I have searched the issues and there are no duplicates of this issue/question/request.

### Description of Issue
I wanted to get all mentions of a user, but it keeps looping the same first few tweets without stopping. Worth noting is the same thing happens if I try to download a users tweets (-u pewdiepie). The only time I don't get looped is when I use --profile-full, which I'm not able to use with -s.

### Command Ran
twint -s pewdiepie

### Environment Details
Windows 10

**Comment by DenseLance** [comment]
To find the posts that mentions a particular user:
```
import twint

# Configure
c = twint.Config()
c.Format = "Post ID: {id} | Mentions: {mentions} | Date: {date}"
c.Search = "@pewdiepie"

# Run
twint.run.Search(c)
```

To find the posts that a user sends and who he mentions (inclusive of replies):
```
import twint

# Configure
c = twint.Config()
c.Username = "pewdiepie"
c.Format = "Post ID: {id} | Mentions: {mentions} | Date: {date}"

# Run
twint.run.Search(c)
```

**Comment by HydroHydro** [comment]
@DenseLance Neither of those modules worked. Got an error about 'NoneType' object being unscriptable.

**Comment by DenseLance** [comment]
@HydroHydro Mine worked. Did you update Twint to the latest version?

**Comment by HydroHydro** [comment]
Nevermind. I got it working! Thank you!
