### ISSUE TITLE
Unable to install __main__ module not found

### ISSUE THREAD

**Issue by ChocolateSaucisson** [twintproject/twint#467]
# Issue Template
Please use this template!

### Initial Check
> If the issue is a request please specify that it is a request in the title (Example: [REQUEST] more features). If this is a question regarding 'twint' please specify that it's a question in the title (Example: [QUESTION] What is x?). Please **only** submit issues related to 'twint'. Thanks.

>Make sure you've checked the following:

- 

- [] Python version is 3.6;
**Python version 3.6.8**
- [] Updated Twint with `pip3 install --upgrade -e git+https://github.com/twintproject/twint.git@origin/master#egg=twint`;
**Used this command to install the first time**
- [] I have searched the issues and there are no duplicates of this issue/question/request.
**Similar issues but not this one**
### Command Ran
>Please provide the _exact_ command ran including the username/search/code so I may reproduce the issue.
**git clone https://github.com/twintproject/twint.git
pip3 install -r requirements.txt**

### Description of Issue
> I previously had a Debian OS until yesterday and on that when I tried to install Twint, it gave me the can't find __main__ module in twint error. I had installed with the command above and so tried by cloning the Git and installing that way; still the same error. I did have issues trying to get Python 3.7 working on that and so gave up in the end. 
I have just installed Ubuntu 18.04 and tried the command above and again the same error. I also tried the Git clone method again and still the same error. I did however run the test.py with Python3 and that scraped twitter albeit with an error to do with urllib and chardet.
I checked both of these and they are up to date.

### The error from test.py
python3 test.py
/usr/lib/python3/dist-packages/requests/__init__.py:80: RequestsDependencyWarning: urllib3 (1.25.3) or chardet (3.0.4) doesn't match a supported version!

Something to note is that everytime I've tried installing, I've never been able to call it from the command line nor can I call it from within the folder.

### Environment Details
>Using Windows, Linux? What OS version? Running this in Anaconda? Jupyter Notebook? Terminal?
**Currently Ubuntu 18.04 and in terminal**

**Comment by pielco11** [comment]
Not sure what's your issue.

About `RequestsDependencyWarning: urllib3 (1.25.3) or chardet (3.0.4) doesn't match a supported version!`, this issue is not related to Twint but to `requests` lib. You can simply ignore this

**Comment by ChocolateSaucisson** [comment]
Yes that's fine, the main issue I'm having is that I'm unable to run twint at all due to main module not being found in twint. 
It doesn't run from the command line or from inside the folder.

**Comment by pielco11** [comment]
If you just clone the repository (and install the dependencies, obviously) you can't use Twint via CLI but only as module. So you have to create your scripts

If you want to use Twint via CLI you have to install Twint with pip `pip3 install --upgrade -e git+https://github.com/twintproject/twint.git@origin/master#egg=twint`

**Comment by ChocolateSaucisson** [comment]
Ok I see the difference now however when I install using the command above which I've just copied and pasted I get "Command 'twint' not found" 
It doesn't have to be run as sudo does it?

**Comment by pielco11** [comment]
It really depends on your setup. You have to install Twint in a directory which you have access too, usually you should be able to run Twint with the same user which you installed it

Anyway I tried the command above, and it's not working on my side. Which is really strange. You can fix this issue with `pip3 install --user --upgrade -e git+https://github.com/twintproject/twint.git@origin/master#egg=twint`

Thank you for reporting this

**Comment by pielco11** [comment]
#481

**Comment by RamziManalao** [comment]
julian@DESKTOP-HFJFMH1:~/twint$ twint -u username --since 2019-4-17
/usr/lib/python3/dist-packages/requests/__init__.py:80: RequestsDependencyWarning: urllib3 (1.25.3) or chardet (3.0.4) doesn't match a supported version!
  RequestsDependencyWarning)
julian@DESKTOP-HFJFMH1:~/twint$

**Comment by pielco11** [comment]
@RamziManalao 
![immagine](https://user-images.githubusercontent.com/17363750/61805428-0eb94280-ae36-11e9-8c1f-e903c2dc798d.png)

About the `RequestsDependencyWarning` message, you have just to install the correct version of `urllib` #162

**Comment by RamziManalao** [comment]
> @RamziManalao
> ![immagine](https://user-images.githubusercontent.com/17363750/61805428-0eb94280-ae36-11e9-8c1f-e903c2dc798d.png)
> 
> About the `RequestsDependencyWarning` message, you have just to install the correct version of `urllib` #162, or just ignore the message

I tried ignoring it but it doesn't take me anywhere.
I updated the urllib using `pip install urllib3`

**Comment by pielco11** [comment]
@RamziManalao you don't have update `urllib3`, you have to install a compatible version (such as `1.22`)

Anyway, you should see an output like mine. If not try with different users (an user might be shadow banned and his/her tweets unsearchable)

**Comment by RamziManalao** [comment]
> @RamziManalao you don't have update `urllib3`, you have to install a compatible version (such as `1.22`)
> 
> Anyway, you should see an output like mine. If not try with different users (an user might be shadow banned and his/her tweets unsearchable)

Please tell me how to downgrade urllib3 to 1.22. I have tried apt-get install urllib3 1.22 but didn't work

`Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package urllib3`
