### ISSUE TITLE
[ERROR] Can't put tweets in an array.

### ISSUE THREAD

**Issue by NewCTwo** [twintproject/twint#470]
### Initial Check

- [X] Python version is 3.6;
- [X] Updated Twint with `pip3 install --user --upgrade -e git+https://github.com/twintproject/twint.git@origin/master#egg=twint`;
- [X] I have searched the issues and there are no duplicates of this issue/question/request.

### Command Ran
	tweets = []

	c = twint.Config()

	c.Username = usn
	c.Limit = 40
	c.Store_object = True
	c.Store_object_tweets_list = tweets
	try:
		twint.run.Search(c)

		print("Completed")
		return tweets

### Description of Issue

All the tweets still just print to the terminal, and the array that should have the tweets in them either has pointers:
`[<twint.tweet.tweet object at 0x7f4e44728eb8>, <twint.tweet.tweet object at 0x7f4e44728e80>, <twint.tweet.tweet object at 0x7f4e44728f60>, <twint.tweet.tweet object at 0x7f4e44728fd0>],` or is just empty.

### Environment Details
Ubuntu 18.04 & Python 3.6

**Comment by pielco11** [comment]
What's the issue then?

If you'll get tweets, they'll be in the list

**Comment by NewCTwo** [comment]
I _did_ get tweets, the 40 most recent one, the person I'm trying to scrape has thousand of tweets - but the returned array is empty: `len(tweets) = 0`. I thought this: `tweets = twint.output.tweets_object` saves them in RAM?

**Comment by NewCTwo** [comment]
I keep getting `<twint.tweet.tweet object at 0x7f91a84fe3c8>` which I can't use.

**Comment by pielco11** [comment]
`c.Store_object_tweets_list = tweets` saves correctly the tweets in the list (in RAM), to access the `<twint.tweet.tweet object at 0x7f91a84fe3c8>` as `Tweet` objects, here you can see the properties

https://github.com/twintproject/twint/blob/ad27650fbc0bf8c3f2c78449088a5ede7239f53a/twint/tweet.py#L68-L101

**Comment by pielco11** [comment]
`tweets` is a list, so you access to the information via an index (a number). Lists start at zero

**Comment by nonstop99** [comment]
Hi,

I have the same issue, I ran this code from the example:

`import twint
import pprint

tweets = []

c = twint.Config()

c.Username = 'realDonaldTrump'
c.Limit = 10
c.Store_object = True
c.Store_object_tweets_list = tweets

twint.run.Search(c)
# now 'tweets' contains the tweets
# twint.output.tweets_list` is empty
a = len(tweets)
print(a)
pprint.pprint(tweets)

#outout of tweets is:
#0
#[]
`

but the tweets list is always empty

**Comment by nonstop99** [comment]
Hi,

I have the same issue, I ran this code from the example:

    import twint
    import pprint
    
    tweets = []
    
    c = twint.Config()
    
    c.Username = 'realDonaldTrump'
    c.Limit = 10
    c.Store_object = True
    c.Store_object_tweets_list = tweets
    
    twint.run.Search(c)
    # now 'tweets' contains the tweets
    # twint.output.tweets_list` is empty
    a = len(tweets)
    print(a)
    pprint.pprint(tweets)
    
    #outout of tweets is:
    #0
    #[]
    

but tweets is always empty

**Comment by pielco11** [comment]
@nonstop99 that's quite strange, I'm getting tweets. Do you see them in the output while scraping?

**Comment by nonstop99** [comment]
@pielco11 yes there was output while scraping, after reading your comment I managed to get it working by reinstalling Twint, sorry to have bothered you, great program!

**Comment by nonstop99** [comment]
hmm my issue has come back again,

https://ibb.co/wLnpkL3

I tried rebooting and turning off anti virus but that didn't fix it

**Comment by pielco11** [comment]
(next time post the code and the screenshot, not only the screenshot, please)

I tried your query and I can still get tweets

**Comment by pielco11** [comment]
So maybe you are importing the wrong Twint version

**Comment by nonstop99** [comment]
Hi,
this is the code, although it's pretty much the same as above

    import twint
    import pprint
    
    tweets = []
    
    c = twint.Config()
    
    c.Username = 'realDonaldTrump'
    c.Limit = 1
    c.Retweets = True
    c.Store_object = True
    c.Store_object_tweets_list = tweets

    twint.run.Profile(c)
    # now 'tweets' contains the tweets
    # twint.output.tweets_list` is empty
    a = len(tweets)
    print(a)
    pprint.pprint(tweets)
    
    #outout of tweets is:
    #0
    #[]
    print(tweets[1].username)
    print(tweets[1].tweet)


I tried running this command

    pip3 install --user --upgrade -e git+https://github.com/twintproject/twint.git@origin/master#egg=twint

output:

	Obtaining twint from git+https://github.com/twintproject/twint.git@origin/master#egg=twint
	  Updating c:\users\qwerty\src\twint clone (to revision origin/master)
	  Running command git fetch -q --tags
	  WARNING: Did not find branch or tag 'origin/master', assuming revision or ref.
	  Running command git reset --hard -q origin/master
	Requirement already satisfied, skipping upgrade: aiohttp in c:\users\qwerty\appdata\local\programs\python\python37\lib\site-packages (from twint) (3.5.4)
	Requirement already satisfied, skipping upgrade: aiodns in c:\users\qwerty\appdata\local\programs\python\python37\lib\site-packages (from twint) (2.0.0)
	Requirement already satisfied, skipping upgrade: beautifulsoup4 in c:\users\qwerty\appdata\local\programs\python\python37\lib\site-packages (from twint) (4.7.1)
	Requirement already satisfied, skipping upgrade: cchardet in c:\users\qwerty\appdata\local\programs\python\python37\lib\site-packages (from twint) (2.1.4)
	Requirement already satisfied, skipping upgrade: elasticsearch in c:\users\qwerty\appdata\local\programs\python\python37\lib\site-packages (from twint) (7.0.2)
	Requirement already satisfied, skipping upgrade: pysocks in c:\users\qwerty\appdata\local\programs\python\python37\lib\site-packages (from twint) (1.7.0)
	Requirement already satisfied, skipping upgrade: pandas in c:\users\qwerty\appdata\local\programs\python\python37\lib\site-packages (from twint) (0.24.2)
	Requirement already satisfied, skipping upgrade: aiohttp_socks in c:\users\qwerty\appdata\local\programs\python\python37\lib\site-packages (from twint) (0.2.2)
	Requirement already satisfied, skipping upgrade: schedule in c:\users\qwerty\appdata\local\programs\python\python37\lib\site-packages (from twint) (0.6.0)
	Requirement already satisfied, skipping upgrade: geopy in c:\users\qwerty\appdata\local\programs\python\python37\lib\site-packages (from twint) (1.20.0)
	Requirement already satisfied, skipping upgrade: fake-useragent in c:\users\qwerty\appdata\local\programs\python\python37\lib\site-packages (from twint) (0.1.11)
	Requirement already satisfied, skipping upgrade: yarl<2.0,>=1.0 in c:\users\qwerty\appdata\local\programs\python\python37\lib\site-packages (from aiohttp->twint) (1.3.0)
	Requirement already satisfied, skipping upgrade: attrs>=17.3.0 in c:\users\qwerty\appdata\local\programs\python\python37\lib\site-packages (from aiohttp->twint) (19.1.0)
	Requirement already satisfied, skipping upgrade: chardet<4.0,>=2.0 in c:\users\qwerty\appdata\local\programs\python\python37\lib\site-packages (from aiohttp->twint) (3.0.4)
	Requirement already satisfied, skipping upgrade: multidict<5.0,>=4.0 in c:\users\qwerty\appdata\local\programs\python\python37\lib\site-packages (from aiohttp->twint) (4.5.2)
	Requirement already satisfied, skipping upgrade: async-timeout<4.0,>=3.0 in c:\users\qwerty\appdata\local\programs\python\python37\lib\site-packages (from aiohttp->twint) (3.0.1)
	Requirement already satisfied, skipping upgrade: pycares>=3.0.0 in c:\users\qwerty\appdata\local\programs\python\python37\lib\site-packages (from aiodns->twint) (3.0.0)
	Requirement already satisfied, skipping upgrade: soupsieve>=1.2 in c:\users\qwerty\appdata\local\programs\python\python37\lib\site-packages (from beautifulsoup4->twint) (1.9.1)
	Requirement already satisfied, skipping upgrade: urllib3>=1.21.1 in c:\users\qwerty\appdata\local\programs\python\python37\lib\site-packages (from elasticsearch->twint) (1.24.3)
	Requirement already satisfied, skipping upgrade: numpy>=1.12.0 in c:\users\qwerty\appdata\local\programs\python\python37\lib\site-packages (from pandas->twint) (1.16.3)
	Requirement already satisfied, skipping upgrade: python-dateutil>=2.5.0 in c:\users\qwerty\appdata\local\programs\python\python37\lib\site-packages (from pandas->twint) (2.8.0)
	Requirement already satisfied, skipping upgrade: pytz>=2011k in c:\users\qwerty\appdata\local\programs\python\python37\lib\site-packages (from pandas->twint) (2019.1)
	Requirement already satisfied, skipping upgrade: geographiclib<2,>=1.49 in c:\users\qwerty\appdata\local\programs\python\python37\lib\site-packages (from geopy->twint) (1.49)
	Requirement already satisfied, skipping upgrade: idna>=2.0 in c:\users\qwerty\appdata\local\programs\python\python37\lib\site-packages (from yarl<2.0,>=1.0->aiohttp->twint) (2.8)
	Requirement already satisfied, skipping upgrade: cffi>=1.5.0 in c:\users\qwerty\appdata\local\programs\python\python37\lib\site-packages (from pycares>=3.0.0->aiodns->twint) (1.12.3)
	Requirement already satisfied, skipping upgrade: six>=1.5 in c:\users\qwerty\appdata\local\programs\python\python37\lib\site-packages (from python-dateutil>=2.5.0->pandas->twint) (1.12.0)
	Requirement already satisfied, skipping upgrade: pycparser in c:\users\qwerty\appdata\local\programs\python\python37\lib\site-packages (from cffi>=1.5.0->pycares>=3.0.0->aiodns->twint) (2.19)
	Installing collected packages: twint
	  Found existing installation: twint 1.2.5
		Uninstalling twint-1.2.5:
		  Successfully uninstalled twint-1.2.5
	  Running setup.py develop for twint
	Successfully installed twint
	WARNING: You are using pip version 19.1.1, however version 19.2.1 is available.
	You should consider upgrading via the 'python -m pip install --upgrade pip' command.

but that didn't fix it

**Comment by pielco11** [comment]
I'm unable to reproduce your issue

**Comment by nonstop99** [comment]
I think i've found the problem, 

I was saving my python program here:

C:/temp/tweet scrape/twint-master/twint-master/twint_search_test.py

it doesn't seem to work when the python program is saved in this directory:

C:/temp/tweet scrape/twint-master/twint-master/

If I save it anywhere else it works fine.

**Comment by HongLWang** [comment]
@nonstop99 Hi I think I found a workaround.

```
import twint
c = twint.Config()
c.Username = 'NASA'
c.Limit = 3
c.Store_object = True
twint.run.Search(c)
tweets = twint.output.tweets_list
for tweet in tweets:
    print ('ID: {}'.format(tweet.id))
```

This works perfectly for me, the tweets will be stored in 'tweets'.
This solution comes from the source code in 'twint/twint/output.py', line 144-149. 

![solution](https://user-images.githubusercontent.com/40385804/103866989-974aa200-5101-11eb-9218-56258eecd7e5.png)
