### ISSUE TITLE
[REQUEST] Twitter Source Labels

### ISSUE THREAD

**Issue by GLiMPSEiNATOR-reddit** [twintproject/twint#471]
Is it possible to also gather Tweet Source Labels with the current collection methods? 

This would be a helpful data point for dashboarding in ELK if it's exposed.

**Comment by pielco11** [comment]
That would really slow down the process since Twint would have to get the information from every single tweet

But it's possible and something that I want to work on

**Comment by GLiMPSEiNATOR-reddit** [comment]
Browser seems to expose it if you use the "New Twitter"

I gotcha on the performance concerns just wasn't sure if it was already exposed in the DOM or object you're getting, I'm very new to Python so I haven't gone digging for my own answers here :-)

**Comment by pielco11** [comment]
For now I'm unable to use "New Twitter" so when it'll come out to me as well, I'll check that out
