### ISSUE TITLE
Run silently

### ISSUE THREAD

**Issue by miguelwon** [twintproject/twint#473]
Hi,
I'm running Twint as module. Is there a flag configuration to make ir run silently? I'm collection tweets from a user and I don't need the printout, since I'm saving them to a json file. 
Thanks

**Comment by pielco11** [comment]
Sure, you have just to set `Hide_output = True`, for example:

```python
import twint

c = twint.Config()
c.Username = target
c.Hide_output = True

twint.run.Search(c)
```
