### ISSUE TITLE
config.Store_object update, please read here

### ISSUE THREAD

**Issue by pielco11** [twintproject/twint#476]
## What happened?

I just renamed:
- `twint.output.tweets_object` to `twint.output.tweets_list`
- `twint.output.follow_object` to `twint.output.follows_list`
-  `twint.output.user_object` to `twint.output.users_list`

to make it more clear that's a list and what's its scope

## Examples of usage

```python
import twint

c = twint.Config()

c.Username = 'noneprivacy'
c.Limit = 10
c.Store_object = True

twint.run.Search(c)
tweets = twint.output.tweets_list
```

```python
import twint

c = twint.Config()

c.Username = 'noneprivacy'
c.Limit = 10
c.Store_object = True

twint.run.Followers(c)
followers = twint.output.follows_list
```

```python
import twint

c = twint.Config()

c.Username = 'noneprivacy'
c.Limit = 10
c.Store_object = True
c.User_full = True

twint.run.Followers(c)
users = twint.output.users_list
```

**Comment by temitope** [comment]
cant readily serialize this it seems. trying to figure out what im missing. wrapping this output in jsonify from Flask to return from end point.

**Comment by pielco11** [comment]
@temitope `twint.output.tweets_list`, `twint.output.follows_list` and `twint.output.users_list` are lists

I'm not familiar with Flash so I might not be able to help you

**Comment by temitope** [comment]
@pielco11 thanks for the response. for others following the thread, I think that the object was too complex/deep to easily `jsonify` so I mapped it to a shallower/simpler object and it seemed to work. 
e.g.

```
def convertTweet(x):
    return {'link':x.link, 'tweet': x.tweet, 'urls': x.urls, 'photos': x.photos, 'video': x.video, 'username': x.username}

@app.route('/twint-data')
def hello_twint():
    c = twint.Config()
    lat = request.args.get('lat')
    lng = request.args.get('lng')
    c.Geo =" {}, {},2km".format(lat, lng)
    c.Limit = 5
    c.Store_object = True
    c.Images = True
    twint.run.Search(c)
    tweets = twint.output.tweets_list
    tweetsMap = list(map(convertTweet, tweets))
    return jsonify(tweetsMap)
```

**Comment by pielco11** [comment]
#240
