### ISSUE TITLE
Twint command line documentation update

### ISSUE THREAD

**Issue by raspberrypie2** [twintproject/twint#480]
[Yes] Python version is 3.6;
[Yes] Updated Twint with `pip3 install --user --upgrade -e git+https://github.com/twintproject/twint.git@origin/master#egg=twint`;
[Yes] I have searched the issues and there are no duplicates of this issue/question/request.

### Command Ran
>twint -u POTUS

### Description of Issue
> The terminal spits out **bash: twint: command not found...** 
I needed to run
python setup.py install

and then the command would work. This command is not mentioned anywhere in the documentation, I only found it thanks to the recommendation of a user on a video about how to use Twint. 

### Environment Details
>Gnome Terminal 3.28.2 on Fedora 28 virtual machine.

**Comment by pielco11** [comment]
> [Yes] Updated Twint with pip3 install --user --upgrade -e git+https://github.com/twintproject/twint.git@origin/master#egg=twint

I guess your installation process did not end well

![immagine](https://user-images.githubusercontent.com/17363750/61707743-747cd000-ad4b-11e9-8f04-0644bbebdc66.png)
