### ISSUE TITLE
DependancyWarning

### ISSUE THREAD

**Issue by RamziManalao** [twintproject/twint#481]
> /usr/lib/python3/dist-packages/requests/__init__.py:80: RequestsDependencyWarning: urllib3 (1.25.3) or chardet (3.0.4) doesn't match a supported version!

- [X] Python version is 3.6;
- [X] Updated Twint with `pip3 install --user --upgrade -e git+https://github.com/twintproject/twint.git@origin/master#egg=twint`;
- [x] I have searched the issues and there are no duplicates of this issue/question/request.

### Command Ran
sudo twint -u USERNAME --since 2019-07-21

### Description of Issue
> It shows an error.

### Environment Details
Windows 10

**Comment by pielco11** [comment]
Closing, duplicate
