### ISSUE TITLE
how to get comments of all tweets with twint?

### ISSUE THREAD

**Issue by mbutler-79** [twintproject/twint#482]
Hey Guys!
please let me know how can i scrape the comments of all tweets with twint package?
i could get all tweets of a user but without its comments!

Thanks a lot

**Comment by pielco11** [comment]
You have to search for tweets "to" that user, and then filter by conversation ID

**Comment by mbutler-79** [comment]
unfortunately this way does not work,  may I please write correct syntax of the command?
I tested the switch --get-replies , but not working!!!!!
twint -u username --get-replies --json -o username.json

**Comment by pielco11** [comment]
I apologize for `--get-replies` not working as expected. That feature has been removed

To get the replies to a specific tweet you have still to search for tweets sent to your target, and filter them by conversation id. This is the only one working solution

**Comment by frank-chris** [comment]
@pielco11 Please consider removing the **--get-replies** option from the Wiki if it does not work anymore.
