### ISSUE TITLE
Install on android with termux

### ISSUE THREAD

**Issue by Bunplugged** [twintproject/twint#483]
Install problem
In android in termux terminal with

I get 
    ERROR: Complete output from command python setup.py egg_info:
    ERROR: /data/data/com.termux/files/usr/bin/sh: 1: svnversion: not found
    non-existing path in 'numpy/distutils': 'site.cfg'
    non-existing path in 'numpy/random': 'src/splitmix64/splitmix.h'
    Could not locate executable gfortran
    Could not locate executable f95
    Could not locate executable ifort
    Could not locate executable ifc
    Could not locate executable lf95
    Could not locate executable pgfortran
    Could not locate executable f90
    Could not locate executable f77
    Could not locate executable fort
    Could not locate executable efort
    Could not locate executable efc
    Could not locate executable g77
    Could not locate executable g95
    Could not locate executable pathf95
    Could not locate executable nagfor
    don't know how to compile Fortran code on platform 'posix'
    Running from numpy source directory.
    /data/data/com.termux/files/usr/tmp/easy_install-22i91e9d/numpy-1.17.0rc2/setup.py:418: UserWarning: Unrecognized setuptools command, proceeding with generating Cython sources and expanding templates
      run_build = parse_setuppy_commands()
    /data/data/com.termux/files/usr/tmp/easy_install-22i91e9d/numpy-1.17.0rc2/numpy/distutils/system_info.py:690: UserWarning:
        Optimized (vendor) Blas libraries are not found.
        Falls back to netlib Blas library which has worse performance.
        A better performance should be easily gained by switching
        Blas library.
      self.calc_info()
    /data/data/com.termux/files/usr/tmp/easy_install-22i91e9d/numpy-1.17.0rc2/numpy/distutils/system_info.py:690: UserWarning:
        Blas (http://www.netlib.org/blas/) libraries not found.
        Directories to search for the libraries can be specified in the
        numpy/distutils/site.cfg file (section [blas]) or by setting
        the BLAS environment variable.
      self.calc_info()
    /data/data/com.termux/files/usr/tmp/easy_inst
It seems that it is not set up for termux and with pip3 update also produces errors. Using py 3.7

**Comment by pielco11** [comment]
Issue not related to Twint, closing

**Comment by pielco11** [comment]
You should start to investigate starting from the first two errors
