### ISSUE TITLE
[QUESTION] Is it possible to have since until option with profile-full?

### ISSUE THREAD

**Issue by hongtaicao** [twintproject/twint#487]
# Issue Template
Please use this template!

### Initial Check
> If the issue is a request please specify that it is a request in the title (Example: [REQUEST] more features). If this is a question regarding 'twint' please specify that it's a question in the title (Example: [QUESTION] What is x?). Please **only** submit issues related to 'twint'. Thanks.

>Make sure you've checked the following:

- [x] Python version is 3.6;
- [x] Updated Twint with `pip3 install --user --upgrade -e git+https://github.com/twintproject/twint.git@origin/master#egg=twint`;
- [x] I have searched the issues and there are no duplicates of this issue/question/request.

### Command Ran
>Please provide the _exact_ command ran including the username/search/code so I may reproduce the issue.

### Description of Issue
>Please use **as much detail as possible.**

I searched closed issue and I know ``--since`` and ``--until`` only work with ``search``, but not ``--profile``. However, I need to study retweets and the only way to obtain retweet is from users' profiles. The limitation of ``--profile`` is that it is really slow and it crawls large amount of tweets that I am not interested, e.g. very old tweets. I crawled 3000 user profiles, which already contain around 30M tweets.

Is there any way to early stop the crawling based on ``--since`` and ``--until`` and start the profile crawling for the next user?

### Environment Details
>Using Windows, Linux? What OS version? Running this in Anaconda? Jupyter Notebook? Terminal?

**Comment by pielco11** [comment]
@hongtaicao not yet

**Comment by hongtaicao** [comment]
@pielco11 
I ran into the following situation"[!] Twitter does not return more data, scrape stops here." when using ``--profile-full``. I checked the crawled results, most of them are less than 400 tweets, which I believe that it is a very small fraction of tweets of the username timeline.

How to obtain more tweets from the timeline?

**Comment by pielco11** [comment]
@hongtaicao honestly I don't think that's possible to return more tweets. In every case I got that message, I scrolled down with my browser and stopped at the same point, It sounds like a limit imposed by Twitter

**Comment by hongtaicao** [comment]
Yes. I agree.
Since profile full is not a search, it might not be beneficial to have ``since`` and ``until``.
I will close this.
