### ISSUE TITLE
User_full   Error as "CRITICAL:root:twint.get:Multi:'name'"

### ISSUE THREAD

**Issue by shangyuan232** [twintproject/twint#488]
Hi, 
it shows the error "CRITICAL:root:twint.get:Multi:'name'" after I add "c.User_full = True".
It run well before I add this.

My codes are as follows.
```python
c = twint.Config()
c.Search = "Trump"
c.Lang = "en"
c.User_full = True
c.Location = True
c.Since = "2019-06-19"
c.Until = "2019-06-20"
c.Limit = 3000
```

**Comment by pielco11** [comment]
`c.User_full` is used to get all the info about an user (bio, user ID, full name, etc), it should be used with functions like `.Followers` and `.Following`

If you want to get all the infos about an user, you can do as showed here https://github.com/twintproject/twint/wiki/Module#fetch-informations-from-a-users-profile
