### ISSUE TITLE
Test.py - Build fails

### ISSUE THREAD

**Issue by haccer** [twintproject/twint#490]
Need to update this so it can build in travis-ci and deploy the new package to PyPI.

**Comment by pielco11** [comment]
`config.Custom` structure changed, now `ŧest.py` exits correctly

**Comment by pielco11** [comment]
![immagine](https://user-images.githubusercontent.com/17363750/62365878-8cabd680-b525-11e9-8bba-c5686033f691.png)

Got this error message

**Comment by pielco11** [comment]
Finally fixed

**Comment by haccer** [comment]
Sweet https://pypi.org/project/twint/
