### ISSUE TITLE
I can't index to ES with username and password (HTTPS)

### ISSUE THREAD

**Issue by recepkabatas** [twintproject/twint#491]
# I'm using elasticsearch with Opendistro for elasticsearch developed by Amazon 
https://opendistro.github.io/for-elasticsearch/

### My Problem here i cannot write into ES 
 because of my Es server is not valid (so when i'm using curl command i add --insecure)
> curl -XGET --insecure -u username:password "https://172.18.0.5:9200/_cat/indices"
or curl -XGET --insecure "https://username:password@172.18.0.5:9200/_cat/indices"

for twint tweets i don't know which command should i use for indexing the tweets

if Someone knows how i can get rid of this please help me !

**Comment by pielco11** [comment]
So I guess you want to not check if the certificate is valid or not. For this, `--skip-certs` and `config.Skip_certs` were added.

Examples:
`twint -u "username" -es "https://user:pass@localhost:9200" --skip-certs`

```python
import twint

c = twint.Config()
c.Username = "username"
c.Elasticsearch = "https://user:pass@localhost:9200"
c.Skip_certs = True

twint.run.Search(c)
```
```
