### ISSUE TITLE
[QUESTION] apply "filter:nativeretweets" to search function

### ISSUE THREAD

**Issue by hongtaicao** [twintproject/twint#492]
# Issue Template
Please use this template!

### Initial Check
> If the issue is a request please specify that it is a request in the title (Example: [REQUEST] more features). If this is a question regarding 'twint' please specify that it's a question in the title (Example: [QUESTION] What is x?). Please **only** submit issues related to 'twint'. Thanks.

>Make sure you've checked the following:

- [x] Python version is 3.6;
- [x] Updated Twint with `pip3 install --user --upgrade -e git+https://github.com/twintproject/twint.git@origin/master#egg=twint`;
- [x] I have searched the issues and there are no duplicates of this issue/question/request.

### Command Ran
>Please provide the _exact_ command ran including the username/search/code so I may reproduce the issue.

```
twint -s "cancer%20filter%3Anativeretweets" --since 2019-01-01 --until 2019-02-01 --lang en -o rt_20190101-20190201.csv
```

### Description of Issue
>Please use **as much detail as possible.**

The above command prints nothing in the terminal command line. There is also no output file.

I am trying to obtain the retweets from twitter. Profile is slow and it does not work with ``--since`` and ``--until``. I am wondering if this operator can be used with Twint search since this operator is available with twitter advanced search.

Our group need the retweet data. We are also considering modifying this tool to achieve retweet crawling. Do you have any suggestions where we should start from?

### Environment Details
>Using Windows, Linux? What OS version? Running this in Anaconda? Jupyter Notebook? Terminal?

Ubuntu 16.04 command line.

**Comment by pielco11** [comment]
Hi @hongtaicao 

You are getting nothing because Twitter does not return retweets.
![immagine](https://user-images.githubusercontent.com/17363750/62599022-6a320880-b8eb-11e9-9b59-91ceb31f62e7.png)

Please try with something different like `security`:
![immagine](https://user-images.githubusercontent.com/17363750/62599106-9cdc0100-b8eb-11e9-88d3-ea466f2e6f61.png)

In general, your command is correct!

I'll add this feature as soon as possible since it's really important, thank you so much for the tip!

**Comment by hongtaicao** [comment]
The interesting part is that ``since`` and ``until`` still works, but twitter somehow refuses to return old tweets. See this example.
``https://twitter.com/search?l=en&q=cancer%20since%3A2019-08-01%20until%3A2019-08-08%20filter:nativeretweets&src=typd&lang=en``

![image](https://user-images.githubusercontent.com/14984936/62677489-1e777180-b974-11e9-9797-92b75ccc80de.png)

I checked the retweets collected, using
``twint -s "cancer filter:nativeretweets" --lang en --csv``
One of results
```
id,conversation_id,created_at,date,time,timezone,user_id,username,name,place,tweet,mentions,urls,photos,replies_count,retweets_count,likes_count,hashtags,cashtags,link,retweet,quote_url,video,user_rt_id,near,geo
1158836350335868928,1158836350335868928,1565123090000,2019-08-06,15:24:50,CDT,2234871020,nappy_techie,Zoracon,,A Black woman with 3 PhDs just purchased a condo. The doorman tells her to smile more on the day her husband runs away with a 20 yr old.  Then somehow falls in love with the doorman after he asks her to do laundry at her place & robs her. She gets cancer tolearn humility.  https://twitter.com/IAmBumblebee/status/1158825808804372488 …,[],['https://twitter.com/IAmBumblebee/status/1158825808804372488'],[],145,2346,4662,[],[],https://twitter.com/nappy_techie/status/1158836350335868928,,https://twitter.com/IAmBumblebee/status/1158825808804372488,0,,,
```
and the web page of ``https://twitter.com/search?l=en&q=cancer%20since%3A2019-08-01%20until%3A2019-08-08%20filter:nativeretweets&src=typd&lang=en``

![image](https://user-images.githubusercontent.com/14984936/62677729-f0def800-b974-11e9-82cb-11311c228197.png)

@pielco11  Retweet user is missing in the crawled  results. Is this easy to add?

**Comment by pielco11** [comment]
@hongtaicao it seems that in some searches you can't go back. If I search for retweets made by users I can't go too back in time

**Comment by pielco11** [comment]
Since Twint extracts the data from Twitter, we can't workaound the problem. For example if you search retweets sent by users (add `from:username`) you can't go back even using `since` and `until` parameters

**Comment by hongtaicao** [comment]
@pielco11 Sorry but I believe I did not explain my points clearly.

I believe ``since`` and ``util`` work correctly in Twint at this point and they can work with ``filter:nativeretweets``. The reason that we can't go back time is caused by Twitter.  We can go back for a very short time. We can't go back for more than months otherwise Twitter just returns nothing.

However, the missing part is that ``retweet`` and ``user_rt_id`` in the crawling results are wrong. They did not reflect the tweet is a retweet made by ``user_rt_id``. I am wondering if these two fields in the crawled results can be added or corrected. See the following example using this query
``
twint -s "cancer filter:nativeretweets" --lang en --csv
``
```
id,conversation_id,created_at,date,time,timezone,user_id,username,name,place,tweet,mentions,urls,photos,replies_count,retweets_count,likes_count,hashtags,cashtags,link,retweet,quote_url,video,user_rt_id,near,geo
1158836350335868928,1158836350335868928,1565123090000,2019-08-06,15:24:50,CDT,2234871020,nappy_techie,Zoracon,,A Black woman with 3 PhDs just purchased a condo. The doorman tells her to smile more on the day her husband runs away with a 20 yr old.  Then somehow falls in love with the doorman after he asks her to do laundry at her place & robs her. She gets cancer tolearn humility.  https://twitter.com/IAmBumblebee/status/1158825808804372488 …,[],['https://twitter.com/IAmBumblebee/status/1158825808804372488'],[],145,2346,4662,[],[],https://twitter.com/nappy_techie/status/1158836350335868928,,https://twitter.com/IAmBumblebee/status/1158825808804372488,0,,,
```

**Comment by pielco11** [comment]
Working on it right now

**Comment by pielco11** [comment]
`twint -s "keyword" --native-retweets`

**Comment by hongtaicao** [comment]
Version of Twint
```python
from twint import __version__
print(__version__.VERSION)
(2, 0, 1)
```

@pielco11 I am sorry but I found two errors.

I tried ``-nt`` based on the wiki [here](https://github.com/twintproject/twint/wiki/Basic-usage) but it says option is not available. I tried ``-nr`` then bingo!

I used this command ```twint -s "cancer" --native-retweets --since 2019-01-01 --lang en --csv -o rt_20190101.csv```.

I checked the first two lines as following and I believe the results are still wrong.
```
id,conversation_id,created_at,date,time,timezone,user_id,username,name,place,tweet,mentions,urls,photos,replies_count,retweets_count,likes_count,hashtags,cashtags,link,retweet,quote_url,video,user_rt_id,near,geo,source
1160345205196972032,1160345205196972032,1565482829000,2019-08-10,19:20:29,CDT,1046813298715451392,peryiat,⨾,,what the signs need:  aries - money  taurus - success  gemini - a movie night cancer - meditation  leo - to shut the fuck up virgo - a hug/cuddle libra - friends  scorpio - a bitch slap sagittarius - water  capricorn - self love  aquarius - motivation  pisces- sex,[],[],[],1239,21161,88056,[],[],https://twitter.com/peryiat/status/1160345205196972032,True,,0,,,,
```

**Comment by pielco11** [comment]
@hongtaicao fixed the typo, thanks for spotting it out

What's wrong in your results?

**Comment by hongtaicao** [comment]
@pielco11 It looks like the ``user_rt_id`` is still missing.

**Comment by pielco11** [comment]
@hongtaicao may you be sure to be running the latest version of Twint?

![immagine](https://user-images.githubusercontent.com/17363750/62877627-c059de00-bd27-11e9-9287-852518b56bc8.png)

**Comment by hongtaicao** [comment]
@pielco11 
Thank you. I upgraded to 2.1.0 and everything looks good. Close.
