### ISSUE TITLE
[QUESTION] How to run?

### ISSUE THREAD

**Issue by nvi123** [twintproject/twint#493]
Hi, total newbie to python here and have no idea what I'm doing. 

Installed the latest version of python, and git then did 
git clone https://github.com/twintproject/twint.git
pip3 install -r requirements.txt

my twint folder seems to be username\twint\

I have no idea what I do now? Opening python and trying "twint -u username" just results in "Name error: name 'twint' is not defined"
Using command prompt I can seemingly run the .py scripts just by changing to that directory and typing in their name. (Both automate.py/test.py seem to work to an extent but error "list indices must be integers..." but looking at another post about the same issue it seems just outddated? https://github.com/twintproject/twint/issues/394 ) 
setup.py doesn't seem to do much.

How do I run the examples in the wiki? example:
twint -u username

opening python and typing twint results in:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'twint' is not defined

I tried adding the twint folder (and the subfolder also called twint?) to the windows namespace thing but no luck, obviously I have no idea what I'm doing here.
Or do I need to create a module to run commands? As opposed to just doing "twint -u username" or similar?

Many thanks for any help with this!

**Comment by pielco11** [comment]
Hi @nvi123 

the easiest way to run Twint is installing it via pip3 and running commands, please run `pip3 install twint`, after that, if everything went OK, run `twint -u username --csv -o output.csv` where `username` is the username of the user which you want to get tweets (for example if you want mine just do `-u noneprivacy`). `--csv` specifies that you want to save the tweets in a CSV format, `-o` specifies in which file save them. Basically with that command you get every tweet sent by that user and save into a CSV file
