### ISSUE TITLE
[Question] Suppress Terminal Output when running search

### ISSUE THREAD

**Issue by VasuBhog** [twintproject/twint#494]
# Issue Template
Please use this template!

### Initial Check
> If the issue is a request please specify that it is a request in the title (Example: [REQUEST] more features). If this is a question regarding 'twint' please specify that it's a question in the title (Example: [QUESTION] What is x?). Please **only** submit issues related to 'twint'. Thanks.

>Make sure you've checked the following:

- [] Python version is 3.6;
- [] Updated Twint with `pip3 install --user --upgrade -e git+https://github.com/twintproject/twint.git@origin/master#egg=twint`;
- [] I have searched the issues and there are no duplicates of this issue/question/request.

*Up to date* 

### Command Ran

python3 .\twitterADS.py

### Description of Issue

Python Script running twint on search string, gets outputted to the terminal when I run it. Is it possible to suppress the output to the terminal as I save my data to a **csv** so I do not need to see the terminal window but just the end of the compilation.

### Environment Details
*Windows 10, VSCode*

**Comment by pielco11** [comment]
Hi @VasuBhog 

yes, just add `config.Hide_output = True`

#473

**Comment by rsewell97** [comment]
Unfortunately, this doesn't seem to work for all searches. When doing `twint.run.Search`, `.Profile` and others, these lines always print to the terminal. 

```
list index out of range [x] feed.MobileFav
[!] Twitter does not return more data, scrape stops here.
```

This is frustrating because for large jobs, it is useful to use tqdm or other progress tracker.
