### ISSUE TITLE
Flag for quiet output when running?

### ISSUE THREAD

**Issue by nickian** [twintproject/twint#496]
I don't see a flag in the CLI for not running in verbose mode. Is this possible or can it be added? 

When I'm scraping tweets to a file, I don't need all of the tweet data output in the terminal. The scrape results are making my log files too large and polluted.

Thanks.

**Comment by pielco11** [comment]
`twint -u username --hide-output`

**Comment by jrosen48** [comment]
Is there also an option for `twint.Config()` to quiet output when not running through the CLI?

**Comment by pielco11** [comment]
`c.Hide_output = True`

**Comment by jrosen48** [comment]
thanks!
