### ISSUE TITLE
aiohttp error after collecting some tweets

### ISSUE THREAD

**Issue by michael-ziedalski** [twintproject/twint#497]
- [X] Python version is 3.6;
- [X] Updated Twint with `pip3 install --user --upgrade -e git+https://github.com/twintproject/twint.git@origin/master#egg=twint`;
- [x] I have searched the issues and there are no duplicates of this issue/question/request.

### Command Ran
```
import twint

## Saving to csv now
c = twint.Config()

c.Store_csv = True

c.Lang = "en"

c.Search = "UberEats OR Uber Eats"

c.Since = "2017-03-31"
c.Until = "2019-05-15"

# CSV Fieldnames
c.Custom["id"] = ["id"]
c.Custom["Date"] = ["date"]
c.Custom["Username"] = ["username"]
c.Custom["Text"] = ["tweet"]
c.Custom["Replies"] = ["replies_count"]
c.Custom["Retweets"] = ["retweets_count"]
c.Custom["Likes"] = ["likes_count"]

# Printing date to terminal to show progress is occurring
c.Format = "{date}"

# Name of the directory
c.Output = "twint_UberEats_scrape_1"

twint.run.Search(c)
```

### Description of Issue
So, I have been using twint for a couple weeks now, primarily on my own computer, but recently when I started running one script from my google compute VM, it worked fine a few times (with one script having successfully run for 20+ hours), but recently I've been getting a weird `aiohttp` error after the script runs and collects a few tweets.

The traceback is below. I would appreciate anyone helping me understand and get around this error.

### Environment Details
VM is an Ubuntu 16.04, with Python 3.7.

### Error Traceback
This is what the error says:
```
Traceback (most recent call last):
  File "twint_scraping_script.py", line 29, in <module>
    twint.run.Search(c)
  File "/home/furthermltesting/src/twint/twint/run.py", line 292, in Search
    run(config, callback)
  File "/home/furthermltesting/src/twint/twint/run.py", line 213, in run
    get_event_loop().run_until_complete(Twint(config).main(callback))
  File "/home/furthermltesting/anaconda3/lib/python3.7/asyncio/base_events.py", line 584, in run_until_complete
    return future.result()
  File "/home/furthermltesting/src/twint/twint/run.py", line 154, in main
    await task
  File "/home/furthermltesting/src/twint/twint/run.py", line 174, in run
    await self.tweets()
  File "/home/furthermltesting/src/twint/twint/run.py", line 137, in tweets
    await self.Feed()
  File "/home/furthermltesting/src/twint/twint/run.py", line 57, in Feed
    response = await get.RequestUrl(self.config, self.init, headers=[("User-Agent", self.user_agent)])
  File "/home/furthermltesting/src/twint/twint/get.py", line 107, in RequestUrl
    response = await Request(_url, params=params, connector=_connector, headers=headers)
  File "/home/furthermltesting/src/twint/twint/get.py", line 157, in Request
    return await Response(session, url, params)
  File "/home/furthermltesting/src/twint/twint/get.py", line 163, in Response
    return await response.text()
  File "/home/furthermltesting/anaconda3/lib/python3.7/site-packages/aiohttp/client_reqrep.py", line 1005, in text
    await self.read()
  File "/home/furthermltesting/anaconda3/lib/python3.7/site-packages/aiohttp/client_reqrep.py", line 969, in read
    self._body = await self.content.read()
  File "/home/furthermltesting/anaconda3/lib/python3.7/site-packages/aiohttp/streams.py", line 359, in read
    block = await self.readany()
  File "/home/furthermltesting/anaconda3/lib/python3.7/site-packages/aiohttp/streams.py", line 381, in readany
    await self._wait('readany')
  File "/home/furthermltesting/anaconda3/lib/python3.7/site-packages/aiohttp/streams.py", line 297, in _wait
    await waiter
aiohttp.client_exceptions.ClientPayloadError: Response payload is not completed
```

**Comment by pielco11** [comment]
@michael-ziedalski that issue seems to not be related to Twint, rather a network issue

Please note that you are not using `c.Custom` correctly. Twint can return either `Tweet` objects or `User` objects. Those two have different attributes.

In your case you need to do something like:
```python
c.Custom["tweet"] = ["id", "date", "username", "tweet", "replies_count", "retweets_count", "likes_count"]
```

As of now, I suggest you to create a new script and restart with `c.Since` as the date of the latest scraped tweet. I also suggest you to use a resume file, just add `c.Resume = "resume_UberEats.txt"` (please don't use different resume files for different searches)

In my opinion it would be better to create a directory named like `twitter_UberEats` and save files in it as `scrape_1.csv`. In such case, create the directory first, and then `c.Output = "twitter_UberEats/scrape_1.csv"`

**Comment by michael-ziedalski** [comment]
This being a network issue would be plausible, as the networking of the VM might not be the best. Thanks for checking that and confirming it's not some deeper problem that needs to be taken care of!

As for the correct synax, I was not aware of my mistake, so thanks also for spotting it; however, when I use the wrong syntax, the script also scrapes additional interesting info about each tweet in the form of extra columns like `user_rt_id`, `cashtags`, and `geo` (to name some), that I cannot get by specifying them in the way you said. How could I save tweets' secondary info in the correct way then?

**Comment by pielco11** [comment]
@michael-ziedalski

- `cashtags` are like `hashtags`, them are returned only if found
- `user_rt_id` is returned only if the tweet is a retweet, returns the ID of the user that retweeted
- `geo` is returned only if specified in the query

`user_rt_id` is returned only if you are specifying which user you are searching tweet of. So you need to add `--username "target"` argument, or `config.Username = "target"`

You might search for retweets without specifying the target, in such case `user_rt_id` will not be filled. This needs a new feature to get the ID regardless of the username is specified or not. Anyway we have to consider that searching for retweets is a very limited (by Twitter itself) feature, so it's not a high priority thing.

I still plan to add it in the next days
