### ISSUE TITLE
Question, Can i use the Twint OSINT Explorer on a WSL

### ISSUE THREAD

**Issue by dundundunnn** [twintproject/twint#498]
# Issue Template
Please use this template!

### Initial Check
> If the issue is a request please specify that it is a request in the title (Example: [REQUEST] more features). If this is a question regarding 'twint' please specify that it's a question in the title (Example: [QUESTION] What is x?). Please **only** submit issues related to 'twint'. Thanks.

>Make sure you've checked the following:

- [X] Python version is 3.6;
- [X] Updated Twint with `pip3 install --user --upgrade -e git+https://github.com/twintproject/twint.git@origin/master#egg=twint`;
- [X] I have searched the issues and there are no duplicates of this issue/question/request.

### Command Ran
>Please provide the _exact_ command ran including the username/search/code so I may reproduce the issue.

### Description of Issue
>Is there a way to use Twint osint tool in a wsl or cmd, smh i cant get it working though

### Environment Details
>Windows

**Comment by pielco11** [comment]
The graph explorer is quite outdated (if not deprecated). I guess you can get it running on WSL

**Comment by dundundunnn** [comment]
any tips how though

**Comment by pielco11** [comment]
I don't use Windows so I guess that I can't help you

I highly suggest you to create something from scratch
