### ISSUE TITLE
Scrape less/faster, not just save, with --since?

### ISSUE THREAD

**Issue by nickian** [twintproject/twint#499]
It appears that when using the `--since` parameter that Twint is only using this parameter to save data up until that date. But is it possible to simply scrape only up until that date? Twint appears to still over scrape as much as it can until it hits the `[!] Twitter does not return more data, scrape stops here.` point. Then it limits what it saves. Is there a way to simply scrape less, so the command will complete faster? Or does it have to scrape everything, then discern the results?

**Comment by pielco11** [comment]
In my experience Twint is working good with `--since`. That parameter is passed to Twitter in the search query, it could be possible that Twitter returns more data but it's rare

![immagine](https://user-images.githubusercontent.com/17363750/62855580-f335af00-bcf2-11e9-93c0-edc958882d1a.png)

If that's not working right in your case, may you post a screenshot and your query so that I can dig a bit?

**Comment by nickian** [comment]
Here's an exampe:

`twint -u joerogan --database tweets.db --since 2019-08-11 --retweets`

You can see it's scraping way before 2019-08-11. Is the date format off maybe?

<img width="1468" alt="Screen Shot 2019-08-12 at 5 01 09 PM" src="https://user-images.githubusercontent.com/590678/62904274-e4ff8700-bd22-11e9-8b9d-c0d6a7888822.png">

Scrolled to the bottom...

<img width="1468" alt="Screen Shot 2019-08-12 at 5 01 15 PM" src="https://user-images.githubusercontent.com/590678/62904285-ea5cd180-bd22-11e9-9047-bf301a1f9eb5.png">

**Comment by pielco11** [comment]
OK, spotted the issue.

The fact is that `--retweets` scrapes the user's timeline, while `--since` is a parameter that's given to the search query. `--retweets` calls `.Profile` while `--since` is used for `.Search`. Those two work differently.

**Comment by nickian** [comment]
Oh, I see. So is there a way to include retweets in a profile search? Also, I noticed the date created value of a retweet is that of the original tweet. I would really like to get the value of when it was retweeted, not created by the original user.

**Comment by pielco11** [comment]
Getting retweets is quite hard, getting all the retweets from an user can be considered impossible. I'm not sure if you can get them via API, but, if possible, I highly suggest you to use it

Added `retweet_date` field

**Comment by nickian** [comment]
Ok, thanks!
