### ISSUE TITLE
Twint not found when using with cron

### ISSUE THREAD

**Issue by nickian** [twintproject/twint#501]
I'm far from a Python expert, so this might be a basic question... 

I'm trying to use cron to run a PHP script that calls Twint using PHP's `popen` function, but I get an error saying the Twint command was not found:

```php
$cmd = 'twint -u username --database tweets.db --since 2019-08-12';

while ( @ ob_end_flush() );

$proc = popen($cmd, 'r');

while ( !feof($proc) ) {
    echo fread($proc, 4096);
    @ flush();
}
```
And I have a cron job set up like this:

`* * * * * php /path/to/script.php >> /path/to/file.log 2>&1`

The log file just shows: `sh: 1: twint: not found` every time it tries to run.

Is this a Python path problem? I can run Twint fine as root and this is a root cron job. I'm not sure how to make Twint available from my script/cron. Thanks!

**Comment by nickian** [comment]
I was able to get it to work with an absolute path to Twint, but that still doesn't explain why the original alias doesn't work:

`$cmd = '/usr/local/bin/twint -u username --database tweets.db --since 2019-08-12';`

**Comment by pielco11** [comment]
Usually when installing Python packages (or maybe even software in general), them are installed for the specific user which asked to install it
