### ISSUE TITLE
 [REQUEST]

### ISSUE THREAD

**Issue by noPremiumDI** [twintproject/twint#505]
# Issue Template
Please use this template!

### Initial Check
> If the issue is a request please specify that it is a request in the title (Example: [REQUEST] more features). If this is a question regarding 'twint' please specify that it's a question in the title (Example: [QUESTION] What is x?). Please **only** submit issues related to 'twint'. Thanks.

>Make sure you've checked the following:

- [] Python version is 3.6;
- [] Updated Twint with `pip3 install --user --upgrade -e git+https://github.com/twintproject/twint.git@origin/master#egg=twint`;
- [] I have searched the issues and there are no duplicates of this issue/question/request.

### Command Ran
twint -u username --followers
twint -u username --followers --user-full

### Description of Issue
Would be nice to have option of id output instead of username, --user-full option makes it unnecessary slow

### Environment Details
Using Windows 10

**Comment by pielco11** [comment]
`--user-full` fetches data from the user's profile page. Bio, id, and etc. can't get fetched otherwise. So for every user that you get, you have to lookup at his/her own page for more information.
