### ISSUE TITLE
ImportError: No module named twint

### ISSUE THREAD

**Issue by Mustafallica** [twintproject/twint#507]
Im running in error when importing twint in python file. 
> ImportError: No module named twint

i used pip3 install twint

**Comment by pielco11** [comment]
Maybe you are not running the correct version of Python, and so not importing Twint from the directory which it's installed in.

This is what I see on my end 
![immagine](https://user-images.githubusercontent.com/17363750/64075735-64e29680-ccbc-11e9-8e35-c97a217e22d1.png)
