### ISSUE TITLE
[QUESTION] How could I automate Twint to update a Google Spreadsheet with Tweets / Favorites from a specific user everytime a new tweet shows up?

### ISSUE THREAD

**Issue by massimosclaw** [twintproject/twint#517]
### Environment Details
- Python version is 3.7.2; Using MacOS Mojave Version 10.14 on Macbook Pro Retina 2013 15 inch
- I have searched the issues and there are no duplicates of this issue/question/request.

### Description

Currently, I use the command line tool to download a csv of tweets from a user, as well as favorites. 

I then upload this csv to a sheet in Google Sheets. 

Right underneath the first row, I add a row below that with some information in certain cells (for certain columns) that connects Google Sheets to AwesomeTable for data visualization. 

Every week or month or so, I update the data by downloading tweets using the same approach, then I upload the data to a second sheet in Google Sheets, then I add say 50 rows (if there are 50 tweets _below_ the second row (which has important information for Awesome Table to work the way I want it to work when it reads this particular Google sheet). 

I'd like to completely automate this process. 

Most preferably, I'd like it to do something like this: "Every time a new tweet shows up, immediately download it to the Sheet in Google Sheets after the second row and don't include a header" 

I don't prefer something that updates every hour or month because sometimes tweets (or favorites) are deleted, but if that's my only option (or the easiest) I might take it until I learn how to do what's more desirable but harder. 

Note: I'm a beginner in Python, I watched a few beginner tutorials, and courses, and can very very roughly understand what's going on. Any recommendations for specific tutorials related to this specific goal would be much appreciated. 

I'd like suggestions on easiest / fastest processes to implement this, preferably with as much pre-built tools as possible, and if not available, with easiest approaches. 

The goal isn't necessarily to learn more Python but to achieve this specific goal so I'm open to any means whatsoever.

**Comment by pielco11** [comment]
### Theory
You should download a bunch of tweets (let's say 60, but it could be whatever), save them to a temporary file, check if the latest scraped tweet has an ID which is equal to/lower than the first scraped tweet of the previous session and if so, concatenate the old file with the new one except the first `n+1` rows, where `n` is the id of the row which the duplicated tweet resides

### Example
##### `old.csv`
```
row,id
1,12345
2,12344
3,12343
4,12342
```
##### `new.csv`
```
row,id
1,12347
2,12346
3,12345
4,12344
```
(some fields have been excluded to not make more confusion; `row` field does not exist, added it to make it easier to follow the process)

Now we have that `row4` of `new.csv` has id `12344` which is lower than `row1` of `old.csv` which has id `12345`. So we don't need to double `row1` and `row2` of `old.csv`.
So we have to skip `row0` (the header), `row1` and `row2` of `old.csv`, and add `row3` and `row4` to `new.csv`

```
row,id
1,12347 <-- from new.csv
2,12346 <-- from new.csv
3,12345 <-- from new.csv
4,12344 <-- from new.csv
3,12343 <-- from old.csv
4,12342 <-- from old.csv
```

**Comment by massimosclaw** [comment]
Thank you so much! Super useful. Will try to work out how to do this in python.
