### ISSUE TITLE
[Question] How to get Tweets over a range of dates?

### ISSUE THREAD

**Issue by jensentanlo** [twintproject/twint#518]
### Command Ran
I am running this directly in a python environment and here are my two attempts.

import twint
c = twint.Config()
c.Limit = 10000
c.Lang = 'ja'
c.Store_csv = True
c.Output = 'Overnight.csv'
c.Since = "2014-12-31"
c.Until = "2019-1-1"
twint.run.Search(c)

This just gives me a whole bunch of tweets from 2015-1-1, which is the first date that meets this condition. I also tried this with c.Timedelta = 1 and that didn't change anything.

My second attempt was just making a loop and trying to force twint to search each individual day. I tried initializing twint.Config both inside and outside the loop, but the result is the same.

After the loop runs once, the program terminates, giving me 100 tweets from 2015-1-1. I suspect that this is because there is some sort of break in the twint search itself, but I'm not positive on that.

import twint
import datetime

current_date = datetime.datetime(2014,12,31)
current_end_date = current_date + datetime.timedelta(days=1)
end_date = datetime.datetime(2019,1,1)
while (current_date != end_date):
    c = twint.Config()
    c.Limit = 100
    c.Lang = 'ja'
    c.Store_csv = True
    c.Output = 'Overnight.csv'
    c.Since = current_date.strftime("%Y-%m-%d")
    c.Until = current_end_date.strftime("%Y-%m-%d")
    twint.run.Search(c)
    current_date = current_end_date
    current_end_date += datetime.timedelta(days=1)
    print(current_date != end_date)
### Description of Issue
I am trying to get an even distribution of tweets over a timespan. For example, I want ten tweets from each day from 2017-1-1 to 2018-1-1,

### Environment Details
>Windows 10 in Jupyter Notebook

**Comment by pielco11** [comment]
If you want an even distribution in a given range, get all the tweets in the range of interest, chose the lowest number of tweets per day, iterate over the tweets and for every day save in a new list the first n tweets (or the latest, or pick-up random tweets, as you may prefer)

**Comment by jensentanlo** [comment]
Thanks for the reply.

The problem with this method is that there are millions of tweets per day over the timeframe that I'm looking at, since I'm not looking for a particular type of tweet.

**Comment by jensentanlo** [comment]
I tested the loop (second set of code) in Eclipse IDE and it seems like it works perfectly now, so there could be some strange interaction with jupyter notebook. I'll keep investigating if there's some strange interaction between the notebook and the event loop, but for now, this particular issue is resolved.

Thanks again

**Comment by Gelso22** [comment]
Hi, I am trying to use a loop over single data range(one step is one day ) in order to keep the connection. It works for the first 3/4 days then it downloads only 20, 40 and often 0 tweets for a specific date. How can I address this? and why it does this thing ?
