### ISSUE TITLE
[QUESTION] Is there some way to make Twint check if a list of users in a CSV is verified?

### ISSUE THREAD

**Issue by massimosclaw** [twintproject/twint#519]
- Python version is 3.7.2; Macbook Pro Retina 15 inch 2013 model running MacOS Mojave 10.14
- I have searched the issues and there are no duplicates of this issue/question/request.

### Description  

I downloaded a list of followers of a user in a CSV. Now I'd like Twint to check which of those users is verified and perhaps export a CSV with only verified users. Is this possible to do?

**Comment by pielco11** [comment]
As you may see [here in the Wiki](https://github.com/twintproject/twint/wiki/User-attributes#attributes), the `user` object (not the `follower` object) has an attribute called `user.verified`. So you should iterate over your CSV file and for each username run a script like [this](https://github.com/twintproject/twint/wiki/Scraping-functions#targets-information). I suggest you to save the output in a list (check in the wiki how to), iterate over it and save in another file the usernames (plus other information, if needed) the users which have `user.verified = True`.

**Comment by massimosclaw** [comment]
`import twint
import csv

csvfile = open('users.csv')

#print([x[0] for x in csv.reader(csvfile)])

userx = [x[0] for x in csv.reader(csvfile)]

c = twint.Config()
c.Username = userx
c.Limit = 20
c.Store_object = True
c.User_full = True
c.Output = "verified.csv"
c.Store_csv = True

twint.run.Lookup(c)

users = twint.output.users_list
`

Here's my first messy try at that, will keep trying to improve, but I'm struggling with the area of having to iterate over each user and check if they're verified 

I don't know if it should look like so: 

`if user.verified = True: 
    print(c.Username)`

**Comment by massimosclaw** [comment]
Okay, here's a better version that actually gave me a result: 

```
import twint
import csv

csvfile = open('users.csv')

#print([x[0] for x in csv.reader(csvfile)])

#userx = [x[0] for x in csv.reader(csvfile)]




c = twint.Config()
for x in csv.reader(csvfile):
    c.Username = x[0]
c.Limit = 20
c.Store_object = True
c.User_full = True
c.Output = "verified.csv"
c.Store_csv = True

twint.run.Lookup(c)

users = twint.output.users_list
```

**Comment by massimosclaw** [comment]
Slightly better, it seems, but getting a "line 17, in <module>
    if User.verified:
NameError: name 'User' is not defined" error: 

```
import twint
import csv

csvfile = open('users.csv')

#print([x[0] for x in csv.reader(csvfile)])

#userx = [x[0] for x in csv.reader(csvfile)]




c = twint.Config()
for x in csv.reader(csvfile):
    c.Username = x[0]
    twint.run.Lookup(c)
    if User.verified:
        print(c.Username)


c.User_full = True
c.Output = "verified.csv"
c.Store_csv = True



users = twint.output.users_list
```

**Comment by massimosclaw** [comment]
I believe this is now printing the user objects. My aim here is to try to check if every user in the userlist is verified, will keep trying: 

```
import twint
import csv

csvfile = open('users.csv')

#print([x[0] for x in csv.reader(csvfile)])

#userx = [x[0] for x in csv.reader(csvfile)]




c = twint.Config()
for x in csv.reader(csvfile):
    c.Username = x[0]
    c.Limit = 20
    c.Store_object = True
    c.User_full = True
    twint.run.Lookup(c)
    userlist = twint.output.users_list
    for u in userlist:
        print(u)


c.User_full = True
c.Output = "verified.csv"
c.Store_csv = True



users = twint.output.users_list
```

**Comment by massimosclaw** [comment]
This version: 

```
import twint
import csv

csvfile = open('users.csv')

#print([x[0] for x in csv.reader(csvfile)])

#userx = [x[0] for x in csv.reader(csvfile)]




c = twint.Config()
for x in csv.reader(csvfile):
    c.Username = x[0]
    c.Limit = 20
    c.Store_object = True
    c.User_full = True
    twint.run.Lookup(c)
    userlist = twint.output.users_list
    for u in userlist:
        if u.verified:
            print(u)


c.User_full = True
c.Output = "verified.csv"
c.Store_csv = True

```

Gives me this error: "line 22, in <module>
    if u.verified:
AttributeError: 'user' object has no attribute 'verified'"

**Comment by massimosclaw** [comment]
Do you think downloading a list of Full User profiles (as in info such as: followers, following, Verified: 1/0, etc.) read from a csv file of usernames might be easier to code? That would be just as useful I think.

**Comment by pielco11** [comment]
If you have an user which you want to get the followers/following, you can get them with full info, see [here](https://github.com/twintproject/twint/wiki/Scraping-functions#followers-and-their-information), and then filter them by `verified-or-not` condition iterating over the list of users

**Comment by adnanmig** [comment]
for u in userlist:
        if u.verified:
            print(u)

Change if u.verified: to if u.is_verified:

and try.
