### ISSUE TITLE
Download tweet responses

### ISSUE THREAD

**Issue by DavidPerea** [twintproject/twint#520]
Is there a possibility to get the tweets that are responses from other tweets?

Because I would like to download the responses of specific tweets.

**Comment by pielco11** [comment]
There's already an issue about this; closing since duplicate

**Comment by DavidPerea** [comment]
Can you tell me what the problem number is about this, to see it? Thank you very much in advance.

**Comment by pielco11** [comment]
https://github.com/twintproject/twint/issues/513
https://github.com/twintproject/twint/issues/482
