### ISSUE TITLE
[Question] Can you download users who liked tweets mentioning 'x'?

### ISSUE THREAD

**Issue by massimosclaw** [twintproject/twint#525]
### Description 

I'd like to download a list of users who have _liked_ tweets that have, say, mentioned "Brad Pitt" as opposed to users who simply mentioned "Brad Pitt" (along with a link and the tweet they liked)

Is this possible?

**Comment by pielco11** [comment]
There's a limitation imposed by Twitter will allows you to see only the first 25 users that liked a given tweet. This is not suitable in many cases
