### ISSUE TITLE
min retweets not recognized

### ISSUE THREAD

**Issue by buzzo-pfinder** [twintproject/twint#527]
# Issue Template
Please use this template!

### Initial Check
> If the issue is a request please specify that it is a request in the title (Example: [REQUEST] more features). If this is a question regarding 'twint' please specify that it's a question in the title (Example: [QUESTION] What is x?). Please **only** submit issues related to 'twint'. Thanks.

>Make sure you've checked the following:

- [ok] Python version is 3.6;
- [ok] Updated Twint with `pip3 install --user --upgrade -e git+https://github.com/twintproject/twint.git@origin/master#egg=twint`;
- [ok] I have searched the issues and there are no duplicates of this issue/question/request.

### Command Ran
>Please provide the _exact_ command ran including the username/search/code so I may reproduce the issue.

twint -s pineapple --min-retweets 100 --until 2019-09-25 --hashtags --count --stats --csv -o ove3.cvs

### Description of Issue
>Please use **as much detail as possible.**

When I run the code I get this message twint: error: unrecognized arguments: --min-retweets 100. I tried it with --min-favorites as well and got the same error message. I may be doing something wrong as I am really new to this.

### Environment Details
>Using Windows, Linux? What OS version? Running this in Anaconda? Jupyter Notebook? Terminal?

Win 8.1

**Comment by pielco11** [comment]
You should see https://github.com/twintproject/twint/blob/ba467445cf334b0631e6b0d665bfa27c033c6616/twint/cli.py#L212-L214

May you be sure to be running the latest version of Twint, please?

**Comment by buzzo-pfinder** [comment]
I'm really sorry I suck at this, could you walk me through as to how I can use the help argument?

**Comment by pielco11** [comment]
Are you sure to have installed twint with `pip3 install --user --upgrade -e git+https://github.com/twintproject/twint.git@origin/master#egg=twint` ?

If so, please post here the output of `pip3 show twint`

**Comment by buzzo-pfinder** [comment]
>If so, please post here the output of pip3 show twint
>>You are using pip version 10.0.1, however version 19.2.3 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.

And when I run that command, I get 
>Requirement already up-to-date

**Comment by buzzo-pfinder** [comment]
Ok it was just a lack of upgrades it works perfectly now! Thanks for your time
