### ISSUE TITLE
[QUESTION] What happened to avatars?

### ISSUE THREAD

**Issue by 1taa** [twintproject/twint#529]
I am using Twint to make RSS feed from twitter search results.
After upgrade to twint2 I lost twitter authors avatars.
I checked ["Tweet attributes"](https://github.com/twintproject/twint/wiki/Tweet-attributes) in new wiki and there is no "{avatar}" but I think it is possible to catch it when scrapping.

**Comment by pielco11** [comment]
Hi @1taa 

I moved that attribute to `twint.User` object https://github.com/twintproject/twint/wiki/User-attributes

To get the avatar URL of an user, you have to use the `.Lookup` function

**Comment by 1taa** [comment]
Thank you.
I saw it but I think in this way I have to make a new request for every tweet.
Am I right?
It is 20th slower than first version!
By every request I catch 20 tweets, It is not logical to make new request for each of them only for avatar.
I don't need the whole user information, I just need the tweet author avatar which is accessible by the first request from search result page like other tweet object information.

**Comment by pielco11** [comment]
Not knowing what you do and how you do, I suggest you to edit some code in your local Twint repo. Basically you have to add just a row in the `Tweet` class in `twint/tweet.py` (plus two for the output)

In other words you have to revert this commit https://github.com/twintproject/twint/commit/66aef13e4e9114786509bac443eeeaf30df7ad4c#diff-9960ab7f5799ba17735bc965c8394ca9
Just add the deleted stuff, which is highlighted in red

**Comment by 1taa** [comment]
Thank you.
