### ISSUE TITLE
[QUESTION] For --userlist arg output file

### ISSUE THREAD

**Issue by carlosabun** [twintproject/twint#533]
Hi,

I'm currently typing the below to extract followers from several accounts. However, the way the data is collected, I cannot distinguish to which user the follower belongs. Is there a away of running it so that the data appears as proposed or similar?

Command:
twint --userlist user1,user2 –-followers --user-full -o file.csv -–csv

Current file.csv:
- TwitterUser01, etc
- TwitterUser02, etc
- TwitterUser03, etc
- TwitterUser04, etc
- TwitterUser05, etc

Proposed -o --csv output file: -
- User1, TwitterUser01, etc
- User1, TwitterUser02, etc
- User1, TwitterUser03, etc
- User2, TwitterUser04, etc
- User2, TwitterUser05, etc

Apologies if this is a stupid question. I'm new with Twint and exploring all possibilities.

Thanks!

**Comment by pielco11** [comment]
Hi @carlosabun 

you can simply run one single twint command for every user which you want to get followers. Technically speaking there are not differences between using `--userlist` or running different twint commands

**Comment by carlosabun** [comment]
Hi @pielco11,

Thank you for the response.

I'm doing that at the moment. I was jut wondering whether there was a way of automating it so that I only have to run one command (that allows me to see to which user the follower belongs).

Thanks!
