### ISSUE TITLE
Scrape single tweet by id or url

### ISSUE THREAD

**Issue by bstoilov** [twintproject/twint#538]
# Issue Template
Please use this template!

### Initial Check
> If the issue is a request please specify that it is a request in the title (Example: [REQUEST] more features). If this is a question regarding 'twint' please specify that it's a question in the title (Example: [QUESTION] What is x?). Please **only** submit issues related to 'twint'. Thanks.

>Make sure you've checked the following:

- [] Python version is 3.6;
- [] Updated Twint with `pip3 install --user --upgrade -e git+https://github.com/twintproject/twint.git@origin/master#egg=twint`;
- [] I have searched the issues and there are no duplicates of this issue/question/request.

### Command Ran
>N/A

### Description of Issue
> Is there a way to scrape a specific tweet by id. Yes I can make my own simple requests but I would like to keep things nice and clean

### Environment Details
>All

**Comment by pielco11** [comment]
As of now, this feature is not available. But you could search for tweets with the same test, the same user, and so on, to filter-out all the possible out-of-interest tweets

**Comment by Qriist** [comment]
You could make a function that scrapes just ahead of it so it should be one of the first you encounter.

**Comment by bstoilov** [comment]
Thank you for the information I will try this out.

**Comment by jdawahare** [comment]
commenting to add that I would also love to see this feature added.

**Comment by am-h** [comment]
Have you solved this issue? 
can I get tweet by url?

**Comment by playfulpachyderm** [comment]
I would also like this feature
