### ISSUE TITLE
[QUESTION] Format for following > pandas

### ISSUE THREAD

**Issue by EmmiBevensee** [twintproject/twint#539]
### Command Ran
twint.run.Following(c)
Followers_df = twint.storage.panda.Following_df
 list_of_following = Following_df['following'][username]

### Description of Issue
Hey I'm writing a little mutual following detection function (that I will submit to Twint later) I was just wondering if there is a parallel to this code for following instead of followers:
twint.run.Followers(c)
Followers_df = twint.storage.panda.Follow_df
list_of_followers = Followers_df['followers'][username]

It doesn't recognize a Following_df property.

Thanks!

### Environment Details
Running it all in a google colab instance for now.

**Comment by pielco11** [comment]
Hi @EmmiBevensee 

Please try the example reported in the Wiki and let me know, it works on my end https://github.com/twintproject/twint/wiki/Pandas-integration#followers

**Comment by EmmiBevensee** [comment]
Yes that one works, what I'm asking about is FOLLOWING though which does not have a documented example.
This is what I would expect it to look like based on the Followers usage but there's no Following_df property:
twint.run.Following(c)
Followers_df = twint.storage.panda.Following_df
list_of_following = Following_df['following'][username]

**Comment by pielco11** [comment]
It follows the same logic
```python
import twint

c = twint.Config()
c.Limit = 20
c.Username = username
c.Pandas = True

twint.run.Following(c)

Following_df = twint.storage.panda.Follow_df
list_of_followers = Following_df['following'][username]
```

**Comment by EmmiBevensee** [comment]
Great thank you! That works perfect. Might be worth adding to the examples so other people don't ask?

If you're interested here is the MuFo detector I wrote using this code. I could make a branch and pull request if you all are interested in incorporating it in some form (though I might need a little guidance on how your code is structured). The only thing I don't like about it is that it is too verbose. Even with c.Output = "none" it still spits out every follower and following but it works fine as best I can tell.
```
def mutuals(username):
  c = twint.Config()
  c.Output = "none"
  c.Username = username
  c.Pandas = True

  twint.run.Followers(c)

  Followers_df = twint.storage.panda.Follow_df
  list_of_followers = Followers_df['followers'][username]


  c.Pandas = True
  twint.run.Following(c)

  Following_df = twint.storage.panda.Follow_df
  list_of_following = Following_df['following'][username]

  def intersection(lst1, lst2):
    return list(set(lst1) & set(lst2))

  mufos = intersection(list_of_followers, list_of_following)
  return mufos
```

**Comment by EmmiBevensee** [comment]
perfect thank you again.

**Comment by pielco11** [comment]
@EmmiBevensee we are working on a [twint-utils](https://github.com/twintproject/twint-utils) repo to add some snippets, and other little implementations of twint (like your function) I think that it would be really cool to have your MuFo detector there

**Comment by EmmiBevensee** [comment]
Cool! Yeah I guess just let me know when you all are ready and I can add it. it looks like everything is empty there right now? I plan on making some other things too. Such as Do they like? Do they follow? A "reply guy" calculator. Etc. All in the service of eventually building larger network analysis pipelines utilizing TWINT. I think I remember there being another issue about TWINT to GEPHI. That's something I plan on working on too.

**Comment by pielco11** [comment]
@EmmiBevensee you can create custom .py files and push them anytime. If you feel skilled enough I can add you as collaborator to the repo so that you can add your scripts without asking me to review them. If you plan to add something more than just a simple snippet, I can add you as member (most suitable solution, imho)

Sounds good?
