### ISSUE TITLE
[FEATURE REQUEST] Add Since and Until configs to Profile_full

### ISSUE THREAD

**Issue by afterdelight** [twintproject/twint#541]
Problem:
Since Retweets and Native_retweets configs are tend to miss some tweets.

How about add since and until configs to Profile_full? So users can scrape retweets quickly for tweet updates.

Problem reference:
https://github.com/twintproject/twint/issues/487

Thank you.

**Comment by pielco11** [comment]
It has been already answered

> Since profile full is not a search, it might not be beneficial to have since and until.

Profile_full does not support Since and Until filters, unfortunately

**Comment by afterdelight** [comment]
Any work around to limit Profile_full to scrape only last few tweets?

**Comment by pielco11** [comment]
Not that I'm aware of
