### ISSUE TITLE
Stop/Resume when using twint from command line

### ISSUE THREAD

**Issue by deerhunter91** [twintproject/twint#544]
I am using twint from the command line to pull user profile information for a large number of users (users which follow certain accounts).

twint --user-full --userlist inputlist.txt --database profiles.db

My question is if it is possible to resume from where it left off if for whatever reason the scraping stops?

If I run it again it just starts at the top regardless of what is in the profiles.db database.

I can see there is a  --resume function but as far as I can tell it is not applicable in this type of usage.

**Comment by pielco11** [comment]
You could just pull the list out off the database, remove those users from `inputlist.txt` and then re-run the script

**Comment by deerhunter91** [comment]
@pielco11 Good idea. Thank you for your help and for your software. That will do it. I should have thought of that. It would be nice to have an option in twint to resume where it left off for these type of crawls.
