### ISSUE TITLE
[ISSUE] Search not working with python 3.7.3

### ISSUE THREAD

**Issue by jalperin** [twintproject/twint#545]
- [x] Python version is 3.7.3;
- [x] Updated Twint with `pip3 install --user --upgrade -e git+https://github.com/twintproject/twint.git@origin/master#egg=twint`;
- [x] I have searched the issues and there are no duplicates of this issue/question/request.

### Command Ran
>Please provide the _exact_ command ran including the username/search/code so I may reproduce the issue.
```
import twint
# Configure
c = twint.Config()
c.Username = "noneprivate"
c.Search = "#FORCE2019"
c.Format = "Tweet id: {id} | Tweet: {tweet}"
c.Limit = 20

twint.run.Search(c)
```

### Description of Issue
When running the above code it does not return anything. It just returns with no error, but also no output. This happens regardless of the Username or Search set up in the Cofig object. 

### Environment Details
MacOS 10.13.6

**Comment by jalperin** [comment]
Replicated on Ubuntu 16.04 and Python 3.6.6

**Comment by pielco11** [comment]
Please check your query via Twitter Search first

**Comment by jalperin** [comment]
What do you mean? [The search](https://twitter.com/search?q=%23FORCE2019&src=typd) returns results

**Comment by pielco11** [comment]
You specified `c.Username = "noneprivate"`, [this](https://twitter.com/search?src=typd&q=from%3Anoneprivate%20%23FORCE2019) is the actual results page

**Comment by jalperin** [comment]
Thank you. Understood. The documentation was not clear—to me or my colleague—that this Username would be used in the query.
