### ISSUE TITLE
Question: twint cli not working

### ISSUE THREAD

**Issue by antman1p** [twintproject/twint#547]
# Issue Template
Please use this template!

### Initial Check
> If the issue is a request please specify that it is a request in the title (Example: [REQUEST] more features). If this is a question regarding 'twint' please specify that it's a question in the title (Example: [QUESTION] What is x?). Please **only** submit issues related to 'twint'. Thanks.

>Make sure you've checked the following:

- [] Python version is 3.6;
- [] Updated Twint with `pip3 install --user --upgrade -e git+https://github.com/twintproject/twint.git@origin/master#egg=twint`;
- [] I have searched the issues and there are no duplicates of this issue/question/request.

### Command Ran
>Please provide the _exact_ command ran including the username/search/code so I may reproduce the issue.

### Description of Issue
>Please use **as much detail as possible.**

### Environment Details
>Using Windows, Linux? What OS version? Running this in Anaconda? Jupyter Notebook? Terminal?
I installed twint by cloning the git repo and running `pip3 install -r requirments.txt`
I am trying to run twint commands and I am getting `twint
bash: twint: command not found`
I've also tried `python twint`
This does not work either.  Are there steps in your install instructions that are missing?

**Comment by antman1p** [comment]
Kali Linux
Python 3.7.3
Updated twint

**Comment by pielco11** [comment]
You cloned the repo, not installed via pip3. If you want to run `twint` via CLI you have to install twint via pip3

**Comment by razu14396** [comment]
how do I remove the twint from Kali Linux. I used setup.py to install twint.

**Comment by ashutoshsoni891** [comment]
@razu14396 
use **whereis twint** in terminal and copy the path
use **rm -r path/to/twint**

**Comment by razu14396** [comment]
will this remove the installed requirements files

**Comment by ashutoshsoni891** [comment]
I would recommend to create a virtualEnv and install the dependencies.Above Commands help you to remove twint from **BIN/BASH**
