### ISSUE TITLE
CRITICAL:root:twint.feed:Follow:IndexError

### ISSUE THREAD

**Issue by asu01928** [twintproject/twint#548]
Scraping follower's donald trump
I got 16MB 
Im star this tools.
Thankyou

**Comment by asu01928** [comment]
He had 65.8M Followers 
But i just got 1.209.092 and critical index error

**Comment by asu01928** [comment]
Hello dev i hope you can fix this. Using api or something. My dream just scape all of donal trump follower.. Thats all XD sorry for poor english

**Comment by pielco11** [comment]
> just got 1.209.092

Well, my dude, that's way more than expected.

You get that error when Twitter stops you from further scraping.

Plus this is a duplicate
