### ISSUE TITLE
[BUG] setup.py cleared out in PR #537

### ISSUE THREAD

**Issue by learnitall** [twintproject/twint#549]
# setup.py cleared out in PR #537 (Commit 42c963adf7b4a436fe838dfb4fd6843af7ca9cad)

### Initial Check

>Make sure you've checked the following:

- [Y] Python version is 3.6;
- [Y] Updated Twint with `pip3 install --user --upgrade -e git+https://github.com/twintproject/twint.git@origin/master#egg=twint`;
- [Y] I have searched the issues and there are no duplicates of this issue/question/request.

### Command Ran
>Please provide the _exact_ command ran including the username/search/code so I may reproduce the issue.

Tried building the twint docker image found in [twint-search](https://github.com/twintproject/twint-search/blob/master/twint/Dockerfile)

### Description of Issue
Just tried building the twint docker image for twint-search and received the following error:

```
Traceback (most recent call last):
     File "<string>", line 1, in <module>
     File "/src/twint/setup.py", line 1, in <module>
        setup(
   NameError: name 'setup' is not defined
```

In commit 42c963adf7b4a436fe838dfb4fd6843af7ca9cad as a part of PR #537, the entire beginning of setup.py is cleared out, so now the file just contains a plain 'ol call to `setup`. Since it wasn't imported from `setuptools`, nor defined anywhere prior, python complains that `setup` cannot be found. Was this done by accident?

### Environment Details
Running on Docker for Mac

Thanks!

**Comment by pielco11** [comment]
My fault, quite embarrassing

Thanks for reporting!
