### ISSUE TITLE
[QUESTION] ValueError: time data '2019-01-01' does not match format '%Y-%m-%d %H:%M:%S'

### ISSUE THREAD

**Issue by tharrisoniii** [twintproject/twint#552]
# Issue Template
About two weeks ago twint started returning the 'VauleError' for any query requiring a date:
query:  twint -u potus --since 2019-01-01 -o potus2019.csv --csv 
error:  ValueError: time data '2019-01-01' does not match format '%Y-%m-%d %H:%M:%S'

I am on a Windows 10 machine, running PowerShell
Does anyone have an idea of what is causing the error and how to fix it?

- [] Python version is 3.6;
- [] Updated Twint with `pip3 install --user --upgrade -e git+https://github.com/twintproject/twint.git@origin/master#egg=twint`;
- [] I have searched the issues and there are no duplicates of this issue/question/request.

**Comment by pielco11** [comment]
![immagine](https://user-images.githubusercontent.com/17363750/67139522-be892b00-f240-11e9-9e6f-f80dc7b1b8f3.png)

**Comment by tharrisoniii** [comment]
If I add any type of time 'argument' I get the following error(s)

query1: twint -u potus --since 2019-01-01 00:00:01 CEST -o potus2019.csv --csv
twint: error: unrecognized arguments: 00:00:01 CEST

query2: twint -u potus --since 2019-01-01 00:00:01 -o potus2019.csv --csv
twint: error: unrecognized arguments: 00:00:01

**Comment by pielco11** [comment]
@tharrisoniii 
query 1 : ` twint -u potus --since "2019-01-01 00:00:01" -o potus2019.csv --csv`

the same for query 2
As of now timezone conversion is not handled

**Comment by mariomineiro** [comment]
Hi @pielco11 
I bumped in this error 
It doesn't works for -s parameter 
example: twint -s potus --since "2019-01-01 00:00:01" -o potus2019.csv --csv
