### ISSUE TITLE
Will it be blocked by Twitter in the future?

### ISSUE THREAD

**Issue by sonictl** [twintproject/twint#554]
I'm newbee of Twint but I love it so much.
Twint can crawl twitter messages without logging in. It's already pretty powerful. Now twitter's API adds a lot of restrictions. Obviously, twint's features are something twitter is not happy to see. 
**I'm worried that twint will be blocked by twitter. Technically, is it possible? Will it happen in the future?**

**Comment by pielco11** [comment]
Twint does not actually crawl Twitter since the webpage requires JS to be rendered.

Anyway, as you may guess, I don't have the answer to your question. We'll see what will happen
