### ISSUE TITLE
【 question】i cannot search CVEnew account's tweets

### ISSUE THREAD

**Issue by xsser** [twintproject/twint#557]
### Description of Issue
- [] Python version is 3.8;
- [] I had ran command "**twint -u CVEnew --since 2019-10-24**",but return nothing, and i checked the log with command --debug 
At last ,  i changed my python version to Python 3.6.8 but still didn't get work.

Here's the request url from my log :
http://twitter.com/i/search/timeline?vertical=default&src=unkn&include_available_features=1&include_entities=1&max_position=-1&reset_error_state=false&f=tweets&q=%20from%3ACVEnew%20since%3A2019-10-24

### More details:
I could run this command before 2019-10-24 morning,but soon it didn't work til now.
I tried to get more details , i had looked up the codes. And i wonder,something wrong with the http://twitter.com/i  api, i didn't check much about further work after request to api, but i think the problem is in this line 
https://github.com/twintproject/twint/blob/master/twint/get.py
>tweets = soup.find_all("div", "tweet")

I used proxy tool to check the request ,as following
<img width="587" alt="图片" src="https://user-images.githubusercontent.com/1850771/67467552-86884a80-f67b-11e9-9a67-5b259e1f1297.png">
<img width="661" alt="图片" src="https://user-images.githubusercontent.com/1850771/67467831-17f7bc80-f67c-11e9-8110-b4a399d2ffb3.png">
i request the url with burpsuite(a proxy ),and got the response with following 
<img width="1186" alt="图片" src="https://user-images.githubusercontent.com/1850771/67470666-b84fe000-f680-11e9-8265-7d2b2aa1e43e.png">
I guess, twitter updates his rules? so ... the bug appears...  :(

### Command Ran
twint -u CVEnew --since 2019-10-24

### Environment Details
>centos 7
>Python 3.8.0  ,Python 3.6.8
>twint 2.1.6

**Comment by pielco11** [comment]
![image](https://user-images.githubusercontent.com/17363750/67478647-fa126380-f64b-11e9-9a5d-8ee3017d48c5.png)

CVEnew is shadowbanned, meaning that the account exists but its tweets can't be found
