### ISSUE TITLE
[QUESTION] Troubles fetching tweets with a keyword

### ISSUE THREAD

**Issue by ColinPeppler** [twintproject/twint#558]
### Context
I'm trying to fetch a list of tweets with contain a keyword, so I specify the keyword using the `-s` command. Although I can get a list of tweets, not all the time will each tweet contain the specified keyword. So I'm wondering if I'm incorrectly specifying a keyword to search for.

### Command Ran
`twint --search "jellybeans" --since 2019-10-22 --until 2019-10-24 --limit 20`

### Description of Issue
Although tweets are fetched without any issue, the tweets themselves don't contain the keyword.

### Environment Details
>Using Windows, Linux? What OS version? Running this in Anaconda? Jupyter Notebook? Terminal?

Ubuntu 18.04.3 LTS and MacOS Mojave 10.14.16
Twint 2.1.6
Python 3.7.3

Thank you, please let me know if you would like more information.

**Comment by pielco11** [comment]
https://twitter.com/search?f=tweets&q=jellybeans%20since%3A2019-10-22%20until%3A2019-10-24

scroll down a bit and check for matches in the output from where you see "Oct 23", you'll confirm to me (I guess, I hope) that Twitter matches for that word even in the username and the handle of the user which sent the tweet, plus it will check in the "reply to user" handle

![immagine](https://user-images.githubusercontent.com/17363750/67624290-4dd4a680-f81e-11e9-88fb-804e35fef2ed.png)

![immagine](https://user-images.githubusercontent.com/17363750/67624295-5a58ff00-f81e-11e9-9d04-fab9974ff5b4.png)

**Comment by pielco11** [comment]
Also if you "force" `jellybeans` to be interpreted as keyword (-s "\"jellybeans\"") you'll see the same behaviur

![immagine](https://user-images.githubusercontent.com/17363750/67624316-9ee49a80-f81e-11e9-8af3-0c92fbe90a82.png)

So as of now I'm unable to find a solution to search only for tweets containing a given keyword. I suggest you to do some "post-processing" to filter-out false positives

**Comment by ColinPeppler** [comment]
@pielco11 Ahh, thank you for pointing this out. I wasn't aware how the keyword search were grabbing tweets.
