### ISSUE TITLE
 [QUESTION] How to stop Twint from printing on the terminal while crawling tweets/followings/followers ?

### ISSUE THREAD

**Issue by hassanbest** [twintproject/twint#559]
### Environment Details
>Ubuntu, Python 3.6

import twint
c = twint.Config()
c.Username = "abc"
c.Limit = 5
c.Store_object = True

twint.run.Following(c)
ls_follow = twint.output.follows_list
print(ls_follow)

**Comment by pielco11** [comment]
Add
`c.Hide_output = True`
https://github.com/twintproject/twint/wiki/Configuration
