### ISSUE TITLE
Cannot format user lookup

### ISSUE THREAD

**Issue by x0rzkov** [twintproject/twint#562]
Hi guys,

Hope you are all well !

I cannot format the output while doing a lookup on a user.

Any ideas about how to solve this problem ?

```python
import twint

account_id = "953155617098694656"

def getUsername(target):
  c = twint.Config()
  c.User_id = target
  c.Store_object = True
  c.Hide_output = False
  c.Debug = True
  c.Format = "ID {id} | Username {username}"
  twint.run.Lookup(c)
  return twint.output.users_list

if __name__ == "__main__":
  getUsername(account_id)

```

error triggered
```$ python3 test.py
CRITICAL:root:twint.get:User:replace() argument 2 must be str, not None
```

Best,
X.

**Comment by erlendstromsvik** [comment]
You have verified that you get the user details without the format? 
I'm asking because I just discovered that I'm only getting `Username - 'NoneType' object is not subscriptable` on all User searches.

**Comment by x0rzkov** [comment]
if I comment c.Format, I have
```bash
953155617098694656 | MO7EP | @MO7EPMASRY | Private: 0 | Verified: 0 | Bio:  | Location:  | Url: None | Joined: 15 Jan 2018 10:43 PM | Tweets: 107 | Following: 1986 | Followers: 56 | Likes: 2 | Media: 2 | Avatar: https://abs.twimg.com/sticky/default_profile_images/default_profile_400x400.png
```

so there is a problem in formatting the outpout

**Comment by pielco11** [comment]
![immagine](https://user-images.githubusercontent.com/17363750/68018882-281e2600-fc92-11e9-81f7-c6fc7db1fe44.png)

**Comment by x0rzkov** [comment]
works for that but not for csv output... ^^

**Comment by pielco11** [comment]
@x0rzkov for CSV/JSON output you have to set `c.Custom['user']`

![immagine](https://user-images.githubusercontent.com/17363750/68026896-dfbe3280-fca8-11e9-9063-5b23109cc731.png)

**Comment by x0rzkov** [comment]
it works, thanks a lot !
