### ISSUE TITLE
twint -u username return small number of tweets 

### ISSUE THREAD

**Issue by Arwa200** [twintproject/twint#566]
#264 Initial Check
> twint -u username return small number of tweets 
[QUESTION] how to get all tweets 

>Make sure you've checked the following:

- [] Python version is 3.6;
- [] Updated Twint with `pip3 install --user --upgrade -e git+https://github.com/twintproject/twint.git@origin/master#egg=twint`;
- [] I have searched the issues and there are no duplicates of this issue/question/request.

### Command Ran
>twint -u username 

### Environment Details
>Using mac terminal

**Comment by Qriist** [comment]
try the --profile-full option

or try formatting a manual search: -s "from:username"

see what you get

**Comment by pielco11** [comment]
I also suggest you to do your search via browser and see how far back it goes

**Comment by Arwa200** [comment]
--profile-full option: it's gather approximately 3000 tweets 
the user had 52 K of tweets 
I'm trying now with -s

**Comment by Arwa200** [comment]
-s return same small number

**Comment by pielco11** [comment]
What do you see if you scroll manually with your browser?

**Comment by Arwa200** [comment]
sorry,  lost the track.. why do i have to scroll the browser?

**Comment by pielco11** [comment]
So that we know if it's Twitter is acting in a strange way, or just because "that's it" the situation

**Comment by pielco11** [comment]
Scrolling down with the browser is the same thing as running Twint until it stops by itself, we'd be cool to know if the results are the same

**Comment by Arwa200** [comment]
just want to update you about an automatic scrolling for both tweets and likes  from twitter.com and mobile.twitter.com and goth the following:
**- tweets:** 
result in terminal: it returns until 16/07/2017  
twitter.com result from auto scrolling: returns until 26/10/2017  
mobile.twitter.com: returns until 26/10/2017  

**likes:** 
result in terminal: it returns until 29/04/2013
twitter.com result from auto scrolling: returns until Mar 2012  
mobile.twitter.com: returns until November 2012 
and both mobile and normal web are crashed while it is not while running auto scrolling in tweets  

![Screen Shot 2019-11-04 at 7 04 54 PM](https://user-images.githubusercontent.com/42224049/68145154-35fbd180-ff46-11e9-9672-475bd9658321.png)
![Screen Shot 2019-11-04 at 8 39 35 PM](https://user-images.githubusercontent.com/42224049/68145158-372cfe80-ff46-11e9-9127-75c6d7b8adba.png)

**Comment by pielco11** [comment]
### tweets

So you got more results than via browser, awesome

### likes

you should consider that scraping followers/following/favorites is a bit more limited than just searching for tweets. Those are not intended to get all the awaited results

**Comment by Arwa200** [comment]
yes, I got the idea.. 
Do you think would  be possible to get get all the awaited results somehow I mean by scraping not "Paid API"?

**Comment by pielco11** [comment]
I don't know, there limits with every tool (more or less)

**Comment by Arwa200** [comment]
Thank you
