### ISSUE TITLE
Use HTTPS to access Twitter whenever possible

### ISSUE THREAD

**Issue by ralphje** [twintproject/twint#567]
When retrieving tweets, Twint uses HTTP URLs which gets redirected almost exclusively by Twitter to its HTTPS site. To improve the privacy of Twint users, it should be using HTTPS wherever possible, or at least be an option.

**Comment by pielco11** [comment]
Honestly I don't remember why Twint was fetching via HTTP, thank you for pointing it out!

**Comment by ralphje** [comment]
Thanks for fixing :D

Probably the URL in run.py should also be updated :)

**Comment by pielco11** [comment]
@ralphje it turns out that disabling HTTPS reduces the errors returned, and that's a bit strange. This is basically the reason why I've moved to HTTP

Ideas?

**Comment by ralphje** [comment]
Do we have any clue what's the root cause of this issue? As in, what's the data returned and in what sense is it different? 

Perhaps this is some kind of timing issue, as the HTTP redirects to HTTPS we have more time to do some stuff. Just guessing here, I have no clue what's the root cause of those errors. Can you debug them further?

**Comment by bushjavier** [comment]
I have problems with twint i cannot scrape for long period of time using search

CRITICAL:root:twint.run:Twint:Feed:noDataExpecting

I am thinking that twitter is limiting the scraping session or perhaps something in the way the website work changed and twint make the request differently so is not working correctly anymore. Please help to debug this problem

**Comment by sup97** [comment]
I have the same problem. I ran
twint -s "children's home volunteer" --year 2020 -o -children_home_volunteer.csv --csv
It stopped once in 2018-09-27 and again in 2017-02-25.
It seems to be a problem with a certain number of blank pages?

**Comment by pielco11** [comment]
Added a workaround for this @sup97 @bushjavier 
https://github.com/twintproject/twint/commit/162d6d34fa6f8f5bcc0b3cd04db5f0a803b66862
