### ISSUE TITLE
How to use twint if there are some firewalls?

### ISSUE THREAD

**Issue by wangyun1996** [twintproject/twint#568]
# Question
How to use twint if there is a firewall?

### Initial Check
There is a firewall in my country,  I need to set up a proxy, but I don't know how to operate, is there a detailed case? Thank you.

**Comment by wangyun1996** [comment]
If I use a VPN software, and I do not set the proxy in twint, then when I tried to run it, there is something wrong.

The note is:
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host twitter.com:443 ssl:False [Connect call failed ('75.126.115.192', 443)]

**Comment by pielco11** [comment]
If you need to use a VPN, you have just to activate it and run twint as usual

That error means that Twitter is blocking your connection, probably due to VPN

**Comment by wangyun1996** [comment]
> If you need to use a VPN, you have just to activate it and run twint as usual
> 
> That error means that Twitter is blocking your connection, probably due to VPN

Thanks, I'll try it again with another VPN
Thanks again, sincerely.

**Comment by pielco11** [comment]
Anytime!

Since this issue is not strictly related to Twint, I'm gonna close this. Please feel free to keep me updated commenting here and I'll do my best to help you!
