### ISSUE TITLE
Is it working properly?

### ISSUE THREAD

**Issue by wangyun1996** [twintproject/twint#573]
# Is it working properly?

Dear developer, hello. Does the project work normally?

May be my country's reason, the project can not run. If it works, I plan to ask my friends abroad to download the data for me.

The function I want to achieve is: all the content about a certain keyword for a user from one moment to another. Can I download the relevant data if it is running correctly?

Thank you for your patience.

**Comment by pielco11** [comment]
Hi @wangyun1996 , Twint works correctly on my end and, so far, nobody else reported me strange behaviors
