### ISSUE TITLE
just got only a few tweets

### ISSUE THREAD

**Issue by Nixitsumi** [twintproject/twint#576]
# Issue Template
Please use this template!

### Initial Check
> If the issue is a request please specify that it is a request in the title (Example: [REQUEST] more features). If this is a question regarding 'twint' please specify that it's a question in the title (Example: [QUESTION] What is x?). Please **only** submit issues related to 'twint'. Thanks.

>Make sure you've checked the following:

- [] Python version is 3.6;
- [] Updated Twint with `pip3 install --user --upgrade -e git+https://github.com/twintproject/twint.git@origin/master#egg=twint`;
- [] I have searched the issues and there are no duplicates of this issue/question/request.

### Command Ran
>Please provide the _exact_ command ran including the username/search/code so I may reproduce the issue.

### Description of Issue
>Please use **as much detail as possible.**

### Environment Details
>Using Windows, Linux? What OS version? Running this in Anaconda? Jupyter Notebook? Terminal?

#1
c.Username = '676176407fy'
twint.run.Search(c)

i can get just only one tweet
![image](https://user-images.githubusercontent.com/33337786/68588895-90a4a880-04c5-11ea-81c5-5e22dfd5ed68.png)

#2
c.Username = '676176407fy'
twint.run.Profile(c)

i can get all the tweets of this user
![image](https://user-images.githubusercontent.com/33337786/68589151-2b04ec00-04c6-11ea-9ec6-b24b8ed7e99c.png)

So ,how can i get this user's more tweets by using function Search()?
please help me,thank you very mach

**Comment by pielco11** [comment]
As you may see, Twitter search returns only one tweet

![immagine](https://user-images.githubusercontent.com/17363750/68589452-cf197380-0483-11ea-8795-8e924bed1fe9.png)

Probably the user is partially shadow-banned or something

There's nothing that Twint can do

**Comment by Nixitsumi** [comment]
thanks for your help, i'll try something else,Twint is a very nice project,thank you

**Comment by pielco11** [comment]
You used Twint at its best and unfortunately there's nothing more that we can do

If you find another solution, please feel free to share! Other users might be in your same situation!
