### ISSUE TITLE
[QUESTION]--retweets --favorites doesn't work on --since

### ISSUE THREAD

**Issue by xsser** [twintproject/twint#577]
### Command Ran
>command i ran " twint --all xsser_w --since 2019-11-11 --favorites --retweets --proxy-type http --proxy-port 1087 --proxy-host 127.0.0.1 "
but i got all retweets or all favorites,i just wanna get retweets and favorites data since 2019/11/11 

### Description of Issue
i just wanna get retweets and favorites data since 2019/11/11 

### Environment Details
>mac

**Comment by pielco11** [comment]
Hi @xsser 

`--since` argument is available only for `--search`, also you can use `--retweets` (which scrapes the user's timeline) with `--favorites` since this scrapes the `favorites` section of the user's timeline
