### ISSUE TITLE
Generation for following Graph

### ISSUE THREAD

**Issue by DonaldTsang** [twintproject/twint#578]
### Description of Issue
The Wiki and the manual does not specify how to use Twint as a "following graph browser" i.e. Given a list of users find all the users that are followed by them and draw a graph, and can flexibly add users to the list in order to expand the graph.
Might want to clarify this a bit since the CLI is seperate from the GUI.

**Comment by pielco11** [comment]
There's a "Twint Graph Explorer" and [here](https://github.com/twintproject/twint-explorer#graph) is explained how to use it.

It needs to be considered as deprecated. Also you can't manually add nodes or links.

The library that I used for that project might not be the best one, there are others around that might fit your needs.
