### ISSUE TITLE
lengthy scrapes having issues with resuming past a certain point

### ISSUE THREAD

**Issue by Qriist** [twintproject/twint#581]
Latest twint, python 3.7
There's a strange issue when using twint to scrape hashtags past a certain exploration point into the past.

as far as twint goes, it just stops. I've confirmed that sometimes it can be resumed by inserting the oldest id (max_id) into the search query but even then there's a hard limit. It's also not a database issue because the failures occur without any disk output.

This occurs on many hashtags but I've selected these three to test with.
#Coup: 41894 tweets, back to 2019-06-03 01:56:12
#Impeachment: 62580 tweets, back to 2019-10-31 11:12:28
#Qanon: 67393 tweets, back to 2019-10-29 13:48:19
All three were started yesterday at around 1700 Eastern and left to run until complete.

Convenient CLI to those points:
twint -s "#Coup max_id:1135440027171917825" --database "#Coup.db"
twint -s "#Impeachment max_id:1189938194084704256" --database "#Impeachment.db"
twint -s "#Qanon max_id:1189252639965532165" --database "#Qanon.db"

As you can see, the error is inconsistent, too; somewhere between 0 and ~10 of these error lines. (Always the same error if present.)
![image](https://user-images.githubusercontent.com/26832022/68873825-3460a500-06ce-11ea-84ae-2bb0db2e7483.png)

For all 3 searches (and others) there is clearly more to scrape:
![image](https://user-images.githubusercontent.com/26832022/68873359-80f7b080-06cd-11ea-84d2-7a41634c7281.png)

If you need any more data please let me know!

EDIT: Actually, strangely, searching #Coup seems to be suppressed in some way and only gives further results when manually rolling down the date by one day: `#Coup until:2019-06-02`). Very strange behavior. There's a gap of around 7 hours between the two tweets. No idea if there's anything between them!

EDIT 2: With some more testing I can see that not even rolling the date back always works.

**Comment by pielco11** [comment]
`CRITICAL:root:twint.run:Twint:Feed:noDataExpecting value: line 1 column 1 (char 0)` is strongly related to #567 

I solved this moving from HTTPS to HTTP, which is not a great idea. So if we use HTTPS we get a few errors, and if we don't someone could see what we are doing. I'm open to ideas

About the strange behavior of those hashtags, what I can suggest you is to split the datetime intervals in smaller ones

**Comment by stormstricker** [comment]
> `CRITICAL:root:twint.run:Twint:Feed:noDataExpecting value: line 1 column 1 (char 0)` is strongly related to #567
> 
> I solved this moving from HTTPS to HTTP, which is not a great idea. So if we use HTTPS we get a few errors, and if we don't someone could see what we are doing. I'm open to ideas
> 
> About the strange behavior of those hashtags, what I can suggest you is to split the datetime intervals in smaller ones

What do you mean by moving to HTTP? Is it a OS setup? Could you point me to guides how to do it on Linux/Ubuntu.

**Comment by pielco11** [comment]
@stormstricker I'm sorry but here we discuss only about issues related to Twint. There are a lot of great resources out there! DuckDuckGo is your friend!
