### ISSUE TITLE
Cant read follows_list when User_full is enabled

### ISSUE THREAD

**Issue by adnanmig** [twintproject/twint#582]
- [x] Python version is 3.6;
- [x] Updated Twint with `pip3 install --user --upgrade -e git+https://github.com/twintproject/twint.git@origin/master#egg=twint`;
- [x] I have searched the issues and there are no duplicates of this issue/question/request.

### Command Ran
import twint
c = twint.Config()
startnode = 'UbwuCKwD0eIrLDr'
c.Username = startnode
c.Store_object = True
c.User_full = True
twint.run.Followers(c)
print(twint.output.follows_list)

### Description of Issue
When "c.User_full = True" is used, print command outputs empty list. If "c.User_full" is removed, the print command prints user ids.

### Environment Details
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.3 LTS
Release:        18.04
Codename:       bionic
Python 3.6.8 (default, Oct  7 2019, 12:59:55)
[GCC 8.3.0] on linux

**Comment by pielco11** [comment]
You have to use `users = twint.output.users_list`

**Comment by adnanmig** [comment]
Thanks, did I miss this in the Wiki somewhere? If yes, please refer me to it. If no, never mind.

**Comment by pielco11** [comment]
There you go! https://github.com/twintproject/twint/wiki/Storing-objects-in-RAM#users-info
