### ISSUE TITLE
Getting Error while scraping tweets

### ISSUE THREAD

**Issue by taha786** [twintproject/twint#583]
### Initial Check
Getting Error while scraping tweets

>I am using follwing packages 

- [] Python version is 3.6;
- [] Updated Twint with `pip3 install --user --upgrade -e git+https://github.com/twintproject/twint.git@origin/master#egg=twint`;
- [] I have searched the issues and there are no duplicates of this issue/question/request.

### Command Ran
twint  -s "apple,#APPL,#apple,#iphone,#macbookpro,#applefinance,#applestocks,#AppleInc" --lang "en" --since 2019-9-1 --until 2019-11-16 --count -o apple_tweets_sep-19-nov-19-16-file2.csv --csv

### Description of Issue
I am facing following problem 
 CRITICAL:root:twint.run:Twint:Feed:noDataExpecting value: line 1 column 1 (char 0)
CRITICAL:root:twint.run:Twint:Feed:noDataExpecting value: line 1 column 1 (char 0)
CRITICAL:root:twint.run:Twint:Feed:noDataExpecting value: line 1 column 1 (char 0)
CRITICAL:root:twint.run:Twint:Feed:noDataExpecting value: line 1 column 1 (char 0)
CRITICAL:root:twint.run:Twint:Feed:noDataExpecting value: line 1 column 1 (char 0)
CRITICAL:root:twint.run:Twint:Feed:Tweets_known_error:Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0) [x] run.Feed
[!] if get this error but you know for sure that more tweets exist, please open an issue and we will investigate it!
CRITICAL:root:twint.run:Twint:Feed:noDataExpecting value: line 1 column 1 (char 0)
CRITICAL:root:twint.run:Twint:Feed:noDataExpecting value: line 1 column 1 (char 0)
CRITICAL:root:twint.run:Twint:Feed:noDataExpecting value: line 1 column 1 (char 0)
CRITICAL:root:twint.run:Twint:Feed:noDataExpecting value: line 1 column 1 (char 0)
[+] Finished: Successfully collected 0 Tweets.

please help me on this.

### Environment Details
>Using Terminal

**Comment by pielco11** [comment]
`since` arguments should be as follows `2019-09-01`, anyway trying your search query it returns nothing!

![immagine](https://user-images.githubusercontent.com/17363750/69013644-7746a500-097a-11ea-8d80-440c9dd721a5.png)

What are you trying to collect? If you want to search for tweets that contain at least one of those keywords, do as follows `-s "apple OR #APPL OR #apple OR #iphone OR #macbookpro OR #applefinance OR #applestocks OR #AppleInc"`

**Comment by taha786** [comment]
Thanks for your help.Can you please help me to use custom query argument on command line

**Comment by pielco11** [comment]
Got to Twitter Advanced Search page, fill the fields, click on "search" then copy what's after `q=` into custom query
