### ISSUE TITLE
Hi, is there a way to customize mapping from configuration in python script ?

### ISSUE THREAD

**Issue by Aassifh** [twintproject/twint#584]
Hi, is there a way to customize mapping(Elasticsearch) from configuration in python script ?

**Comment by pielco11** [comment]
https://github.com/twintproject/twint/blob/94d34dd33abc493384fbbe3f43ccda26a19163f3/twint/storage/elasticsearch.py#L54-L135

There you go!

**Comment by Aassifh** [comment]
Thanks!
