### ISSUE TITLE
[QUESTION]emojis scrapted in tweets can be displayed successfully in the terminal, but not in the csv file. What should I do?

### ISSUE THREAD

**Issue by xiaowei-xw** [twintproject/twint#585]
# Issue Template
Please use this template!

### Initial Check
> If the issue is a request please specify that it is a request in the title (Example: [REQUEST] more features). If this is a question regarding 'twint' please specify that it's a question in the title (Example: [QUESTION] What is x?). Please **only** submit issues related to 'twint'. Thanks.

>Make sure you've checked the following:

- [1] Python version is 3.7;
- [2] Updated Twint with `pip3 install --user --upgrade -e git+https://github.com/twintproject/twint.git@origin/master#egg=twint`;
- [3] I have searched the issues and there are no duplicates of this issue/question/request.

### Command Ran
import twint

c = twint.Config()
c.Username = "Airbnb"
c.Custom["tweet"]=["tweet"]
c.Output="Airbnb.csv"
c.Store_csv=True

twint.run.Search(c)

### Description of Issue
emojis scrapted in tweets can be displayed successfully in the terminal, and they are as nomal as the user's tweet in twitter account.But they are displayed as messy code in the csv file. What should I do?

### Environment Details
Using Windows, Running this in Anaconda--Jupyter Notebook

**Comment by pielco11** [comment]
I'm able to see the emojis (I use gedit) so I guess it depends by the software that you use to read the CSV file

**Comment by xiaowei-xw** [comment]
> I'm able to see the emojis (I use gedit) so I guess it depends by the software that you use to read the CSV file

Thanks a lot. Can you copy your code?

**Comment by pielco11** [comment]
There's no code, I just opened the CSV file with Gedit

**Comment by xiaowei-xw** [comment]
Can you tell me that which version of Gedit you use? and the emojies are not successfully displayed the CSV file opened with the Gedit.

![捕获](https://user-images.githubusercontent.com/57753444/69476524-ef4b1a00-0e15-11ea-8f83-70dc65f410bc.JPG)

**Comment by xiaowei-xw** [comment]
Can you tell me that which version of Gedit you use? and the emojies are not successfully displayed the CSV file opened with the Gedit.

![捕获](https://user-images.githubusercontent.com/57753444/69476533-0e49ac00-0e16-11ea-8866-f23ade563fc2.JPG)

**Comment by pielco11** [comment]
Hmm, maybe you are missing the right font since the system can't recognize them? Here is a font that quite complete https://github.com/ryanoasis/nerd-fonts

**Comment by xiaowei-xw** [comment]
> Hmm, maybe you are missing the right font since the system can't recognize them? Here is a font that quite complete https://github.com/ryanoasis/nerd-fonts

Thank you very much. I scan the link, but I don't understand. Can you tell me what I should do next?

**Comment by pielco11** [comment]
@xiaowei-xw I'm sorry but here we discuss only about Twint related issues

I suggest you to check their instructions and, if needed, contact them

**Comment by pielco11** [comment]
You have just to clone the repo, install the font(s) that you want to use, and then change the settings to let your system use the new font
