### ISSUE TITLE
Does this project overcome the limits about the length of a tweet?

### ISSUE THREAD

**Issue by ConeyYan** [twintproject/twint#586]
1. With the twitter API, each tweet is limited to 140 chars. I want to know whether this project overcome this limit? If I can only get 140 chars about a tweet, many messages are lost.
2. For a user, it is limited to gather 3200 Tweets. How about scrape 3200 during a period of time, then scrape another 3200 tweets?

Thanks!

**Comment by pielco11** [comment]
With Twint you get all the content of the tweet and has not been proven otherwise ever before.

Get the set the limit of the tweets to scrape, you can set the datetime interval as well
