### ISSUE TITLE
CRITICAL:root:twint.run:Twint:Feed:noDataExpecting

### ISSUE THREAD

**Issue by stormstricker** [twintproject/twint#587]
I keep getting this error! It has something to do with Twitter ratelimiting the scraper, I presume? Was it really *that* hard to build in a queue of requests and only allow N requests per minute?

**Comment by pielco11** [comment]
Maybe you add your query or at least describe what you're trying to achieve, please?

**Comment by azraelmdfk** [comment]
On a similar note, i keep getting this error on my linux/debian 10 distribution when im using twint to collect tweets. In contrast, this error have never appeared in my Windows 10 machine, even when looking for the same hashtag/user/keyword/etc. Is there a reason why this keep happening?

p.s. excuse the broken english, not a native speaker

**Comment by pielco11** [comment]
I think that's related to #567

**Comment by o7n** [comment]
When fixating the user agent to 

`Mozilla/5.0 (Windows NT 5.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2224.3 Safari/537.36`

or 

`Mozilla/5.0 (Windows NT 6.4; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2225.0 Safari/537.36`

this error seems to go away.

**Comment by pielco11** [comment]
@o7n thank you for sharing your findings, I'll give it a run asap!

**Comment by AldebaranNapoli** [comment]
I tried 4 installation with 

Debian Mint e Kali

always the same error of critical root

I did installations with 

Pip3
Python3 build and install setup.py
Pipenv

On the older isntallations no problems, it works. Why this?

**Comment by pielco11** [comment]
How much old?

**Comment by AldebaranNapoli** [comment]
september?

**Comment by sup97** [comment]
I have the same problem. I ran
twint -s "children's home volunteer" --year 2020 -o -children_home_volunteer.csv --csv
It stopped once in 2018-09-27 and again in 2017-02-25.
It seems to be a problem with a certain number of blank pages?

<img width="616" alt="Screen Shot 2019-12-16 at 9 51 25 AM" src="https://user-images.githubusercontent.com/36643753/70916700-1d251800-1fea-11ea-8619-21d1bc758d51.png">

**Comment by pielco11** [comment]
#604
