### ISSUE TITLE
twint add new field to elasticsearch twintgraph index

### ISSUE THREAD

**Issue by sorgan191** [twintproject/twint#592]
I need help with adding new fields to twint follow result
I use python3.6 twint -u "username" --followers -es localhost:9200
after creating twintgraph index i get :
_id
_index
_score
_type
essid
follow
user
i want to add new field with name : "name" contain the user name (user)
best regards

**Comment by pielco11** [comment]
You can just change the field name here

https://github.com/twintproject/twint/blob/7ea55b2aa0dd1c5c2fe991347e2dfce7fbdb2d43/twint/storage/elasticsearch.py#L298-L324

Also remember to change the schema before creating the index

https://github.com/twintproject/twint/blob/7ea55b2aa0dd1c5c2fe991347e2dfce7fbdb2d43/twint/storage/elasticsearch.py#L123-L138

**Comment by sorgan191** [comment]
#pielco11 thank you for your help it's work :+1: +1:
