### ISSUE TITLE
[ERROR] Getting "DLL load failed: The specified procedure could not be found" when running in a .py file

### ISSUE THREAD

**Issue by jharrychapman** [twintproject/twint#593]
# Issue Template
Please use this template!

### Initial Check
> If the issue is a request please specify that it is a request in the title (Example: [REQUEST] more features). If this is a question regarding 'twint' please specify that it's a question in the title (Example: [QUESTION] What is x?). Please **only** submit issues related to 'twint'. Thanks.

>Make sure you've checked the following:

- [x] Python version is 3.7.3;
- [x] Updated Twint with `pip3 install --user --upgrade -e git+https://github.com/twintproject/twint.git@origin/master#egg=twint`;
- [x] I have searched the issues and there are no duplicates of this issue/question/request.

### Command Ran
>Please provide the _exact_ command ran including the username/search/code so I may reproduce the issue.

>import twint
>import asyncio
>import matplotlib.pyplot as plt
>import numpy as np
>import pandas as pd

># Prevents error: no current event loop in thread
>asyncio.set_event_loop(asyncio.new_event_loop())

># Configuring Twint to search for the subject in the first specified city
c> = twint.Config()

># Hiding the print output of tweets scraped
>c.Hide_output = True

># The amount of tweets to return sorted by most recent
>c.Limit = 10

># Input parameters
>c.Search = 'pizza'

># Removing retweets
>c.Filter_retweets = True

># No pictures or video
>c.Media = False

># English only
>c.Lang ='en'

># Excluding tweets with links
>c.Links ='exclude'

>twint.run.Search(c)

### Description of Issue
Hello, I receive an ImportError "DLL load failed: The specified procedure could not be found." when I run the above code. The code works in Jupyter Notebook just fine. Do you know how to solve this issue?

Thanks

### Environment Details
I am running this in Python via VSCode.

**Comment by jharrychapman** [comment]
This may be an issue with my OS if you can't see a simple solution. It works when I save it as a csv and then read in back into a dataframe.

**Comment by pielco11** [comment]
I think it's more a compatibility issue rather than an issue with Twint itself
