### ISSUE TITLE
Elasticsearch. Could not locate that index-pattern-field (id: user_id)

### ISSUE THREAD

**Issue by dieguszgz** [twintproject/twint#594]
### Description of Issue
When I am importing visualizations.json and dashboard.json, after creating the index pattern called 'twinttweets', it appears to me the following error:

'The following saved objects use index patterns that do not exist. Please select the index patterns you'd like re-associated with them. You can create a new index pattern if necessary. After this just to go Dashboard tab and click on Twint Dashboard'

Finally, after importing 'successfully', the error on tittle mentioned ('Could not locate that index-pattern-field (id: user_id)') appers on Dashborad and Visualization tab.

### Environment Details
> Linux (Ubuntu 18)

**Comment by dieguszgz** [comment]
I have just added this line in elasticsearch.py file.
"user_id": {"type": "long"},
Is there anything needed?

**Comment by pielco11** [comment]
Hmm so I guess visualizations.json and dashboard.json are broken now
