### ISSUE TITLE
Cannot extract Farsi tweets

### ISSUE THREAD

**Issue by sinagh72** [twintproject/twint#598]
I cannot retrieve data with the following command:
twint -s منزل  --year 2019  -o file.csv --csv --email --phone

I mean, is it possible to retrieve data by Farsi or Arabic words, hashtags and so on?

**Comment by pielco11** [comment]
Hi @sinagh72 

yes, that's possible to get tweets is almost any language I guess. I tried your query and I got a couple of tweets

**Comment by sinagh72** [comment]
It seems working, but why the time interval does not working?
this is my code:

c = twint.Config()
c.Search = "ایران"
c.Since = "2019-01-01"
c.Untill = "2019-12-08"
c.Index_tweets ="irantweets"
c.Elasticsearch = "http://localhost:9200"
twint.run.Search(c)

![image](https://user-images.githubusercontent.com/49681797/70432193-fa8d7f00-1a7e-11ea-9104-fbddbfdb81f9.png)

**Comment by pielco11** [comment]
May you expand a result and show me the raw json part? (just expand one and click on `json`)

**Comment by sinagh72** [comment]
my problem is solved. thanks
