### ISSUE TITLE
[ERROR] AttributeError in twint.output module

### ISSUE THREAD

**Issue by davidgithub14** [twintproject/twint#602]
Hi,

I recently installed Twint (python 3.6.9 ; Linux OS ; installation by "pip3 install . -r requirements.txt" after dowloading twint.git).
I tried the first simple example of https://pielco11.ovh/posts/twint-osint/ and I have an error when I ran this one :
import twint
# get the followers first
c = twint.Config()
c.Username = "target"
c.Store_object = True
c.User_full = True
twint.run.Followers(c)
# save them in a list
target_followers = twint.output.user_object

My "target" has only 50 followers which are correctly printed in the prompt but at the end I have : 
"target_followers = twint.output.user_object
AttributeError: module 'twint.output' has no attribute 'user_object'"

What can I do ?
What can I provide to you ?
Thanks

# Issue Template
Please use this template!

### Initial Check
> If the issue is a request please specify that it is a request in the title (Example: [REQUEST] more features). If this is a question regarding 'twint' please specify that it's a question in the title (Example: [QUESTION] What is x?). Please **only** submit issues related to 'twint'. Thanks.

>Make sure you've checked the following:

- [] Python version is 3.6;
- [] Updated Twint with `pip3 install --user --upgrade -e git+https://github.com/twintproject/twint.git@origin/master#egg=twint`;
- [] I have searched the issues and there are no duplicates of this issue/question/request.

### Command Ran
>Please provide the _exact_ command ran including the username/search/code so I may reproduce the issue.

### Description of Issue
>Please use **as much detail as possible.**

### Environment Details
>Using Windows, Linux? What OS version? Running this in Anaconda? Jupyter Notebook? Terminal?

**Comment by pielco11** [comment]
Hi @davidgithub14 and thanks for pointing it out, I've to update the article. The correct variable is `twint.output.users_list`, https://github.com/twintproject/twint/wiki/Storing-objects-in-RAM#users-info

**Comment by davidgithub14** [comment]
Thanks ! Quick and precise.
It works.
