### ISSUE TITLE
CRITICAL:root:twint.run:Twint:Feed:noDataExpecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by AldebaranNapoli** [twintproject/twint#603]
(twint-uxlpSofB) xxxxxxx@xxxxxx:~/Software/twint$ twint --index-tweets ancelotti -s ancelotti --since 2017-03-01 --stats --count -es localhost:9200 -o '/home/xxxxxx/Documenti/Ricerche/ancelotti1.json' 
[+] Indexing to Elasticsearch @ localhost:9200
CRITICAL:root:twint.run:Twint:Feed:noDataExpecting value: line 1 column 1 (char 0)
CRITICAL:root:twint.run:Twint:Feed:noDataExpecting value: line 1 column 1 (char 0)
CRITICAL:root:twint.run:Twint:Feed:noDataExpecting value: line 1 column 1 (char 0)
CRITICAL:root:twint.run:Twint:Feed:noDataExpecting value: line 1 column 1 (char 0)
CRITICAL:root:twint.run:Twint:Feed:noDataExpecting value: line 1 column 1 (char 0)
CRITICAL:root:twint.run:Twint:Feed:noDataExpecting value: line 1 column 1 (char 0)
CRITICAL:root:twint.run:Twint:Feed:noDataExpecting value: line 1 column 1 (char 0)
CRITICAL:root:twint.run:Twint:Feed:noDataExpecting value: line 1 column 1 (char 0)
CRITICAL:root:twint.run:Twint:Feed:noDataExpecting value: line 1 column 1 (char 0)
CRITICAL:root:twint.run:Twint:Feed:noDataExpecting value: line 1 column 1 (char 0)
CRITICAL:root:twint.run:Twint:Feed:Tweets_known_error:Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0) [x] run.Feed
[!] if get this error but you know for sure that more tweets exist, please open an issue and we will investigate it!
[+] Finished: Successfully collected 0 Tweets.

**Comment by pielco11** [comment]
Closing due to duplicate

**Comment by pielco11** [comment]
https://github.com/twintproject/twint/search?q=CRITICAL%3Aroot%3Atwint.run%3ATwint%3AFeed%3AnoDataExpecting+value%3A+line+1+column+1+%28char+0%29&type=Issues
