### ISSUE TITLE
[QUESTION] Is it possible to have only choosen field in output file?

### ISSUE THREAD

**Issue by Kryhowsky** [twintproject/twint#606]
# Question

When I use a twint as a module in python script, is it possible to do not extract some fileds from post? For example I don't need "id" in output file, is there any parameter I can add to script to don't have this in final file?

**Comment by pielco11** [comment]
There you go https://github.com/twintproject/twint/wiki/Tweet-attributes#customizing

**Comment by Kryhowsky** [comment]
Great!
So, I would like to say thank you for your work.
That's so helpful :)
