### ISSUE TITLE
Installation issue (Dependency not found googletransx)

### ISSUE THREAD

**Issue by existme** [twintproject/twint#607]
# Issue Template
Please use this template!

### Initial Check
> If the issue is a request please specify that it is a request in the title (Example: [REQUEST] more features). If this is a question regarding 'twint' please specify that it's a question in the title (Example: [QUESTION] What is x?). Please **only** submit issues related to 'twint'. Thanks.

>Make sure you've checked the following:

- [x] Python version is 3.6;
- [x] Updated Twint with `pip3 install --user --upgrade -e git+https://github.com/twintproject/twint.git@origin/master#egg=twint`;
- [x] I have searched the issues and there are no duplicates of this issue/question/request.

### Command Ran
>Please provide the _exact_ command ran including the username/search/code so I may reproduce the issue.
`pip3 install . -r requirements.txt`

### Description of Issue
Either trying to install twint with:
`pip3 install . -r requirements.txt `
or
`pip3 install --user --upgrade -e git+https://github.com/twintproject/twint.git@origin/master#egg=twint`

Will result is:
```
Collecting googletransx (from twint)
Could not install packages due to an EnvironmentError: 404 Client Error: Not Found for url: https://pypi.org/simple/googletransx/
```
### Environment Details
Ubuntu 19.04

**Comment by pielco11** [comment]
@x0rzkov

**Comment by x0rzkov** [comment]
did you try to upgrade pip ?

```bash
pip3 install --upgrade pip
```

**Comment by existme** [comment]
Hi, Thanks a lot that solved the issue.
