### ISSUE TITLE
[REQUEST] Another installation of twint and another problem

### ISSUE THREAD

**Issue by AldebaranNapoli** [twintproject/twint#609]
Python version is 3.7.3

### Command Ran
1) by root : twint -s koulibaly --stats --count -es localhost:9200
2) sudo twint -s gattuso --stats --count -es localhost:9200            

### Description of Issue

1
/usr/local/lib/python3.7/dist-packages/aiohttp-4.0.0a1-py3.7-linux-x86_64.egg/aiohttp/client.py:977: RuntimeWarning: coroutine 'noop' was never awaited
  self._resp.release()
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
/usr/local/lib/python3.7/dist-packages/aiohttp-4.0.0a1-py3.7-linux-x86_64.egg/aiohttp/client.py:541: RuntimeWarning: coroutine 'noop' was never awaited
  resp.release()
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
CRITICAL:root:twint.run:Twint:Feed:noDataExpecting value: line 1 column 1 (char 0)
CRITICAL:root:twint.run:Twint:Feed:noDataExpecting value: line 1 column 1 (char 0)
CRITICAL:root:twint.run:Twint:Feed:noDataExpecting value: line 1 column 1 (char 0)
CRITICAL:root:twint.run:Twint:Feed:noDataExpecting value: line 1 column 1 (char 0)
CRITICAL:root:twint.run:Twint:Feed:noDataExpecting value: line 1 column 1 (char 0)
CRITICAL:root:twint.run:Twint:Feed:noDataExpecting value: line 1 column 1 (char 0)
CRITICAL:root:twint.run:Twint:Feed:noDataExpecting value: line 1 column 1 (char 0)
CRITICAL:root:twint.run:Twint:Feed:noDataExpecting value: line 1 column 1 (char 0)
CRITICAL:root:twint.run:Twint:Feed:noDataExpecting value: line 1 column 1 (char 0)
CRITICAL:root:twint.run:Twint:Feed:Tweets_known_error:Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0) [x] run.Feed
[!] if get this error but you know for sure that more tweets exist, please open an issue and we will investigate it!
[+] Finished: Successfully collected 200 Tweets.

2
[+] Indexing to Elasticsearch @ localhost:9200
/usr/local/lib/python3.7/dist-packages/aiohttp-4.0.0a1-py3.7-linux-x86_64.egg/aiohttp/client.py:518: RuntimeWarning: coroutine 'noop' was never awaited
  resp.release()
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
/usr/local/lib/python3.7/dist-packages/aiohttp-4.0.0a1-py3.7-linux-x86_64.egg/aiohttp/client.py:541: RuntimeWarning: coroutine 'noop' was never awaited
  resp.release()
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
/usr/local/lib/python3.7/dist-packages/aiohttp-4.0.0a1-py3.7-linux-x86_64.egg/aiohttp/client.py:977: RuntimeWarning: coroutine 'noop' was never awaited
  self._resp.release()
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
CRITICAL:root:twint.run:Twint:Feed:noDataExpecting value: line 1 column 1 (char 0)
........................................................................................................................................................................................................................................................................................

### Environment Details
linux debian 10 - i7 first generation 16 GB ram

**Comment by pielco11** [comment]
#604

**Comment by AldebaranNapoli** [comment]
**I REinstall my debian and i installed twint now starts without problem but gives me the same error that give less results**
twint --index-tweets facciamorete -s facciamorete --since 2019-10-01 --until 2019-12-18 --stats --count -es localhost:9200
[+] Indexing to Elasticsearch @ localhost:9200
................................................................................................................................................................................................................................................................................................................................................................................................................CRITICAL:root:twint.run:Twint:Feed:noDataExpecting value: line 1 column 1 (char 0)
................................................................................................................................................................................................................................................CRITICAL:root:twint.run:Twint:Feed:noDataExpecting value: line 1 column 1 (char 0)
........................................................................................................................CRITICAL:root:twint.run:Twint:Feed:noDataExpecting value: line 1 column 1 (char 0)
............................................................CRITICAL:root:twint.run:Twint:Feed:noDataExpecting value: line 1 column 1 (char 0)
............................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................CRITICAL:root:twint.run:Twint:Feed:noDataExpecting value: line 1 column 1 (char 0)

**Anyway i launch a test.py can you find here why im under critical root error?**

python3 test.py 
[+] Beginning vanilla test in <function Following at 0x7f3733b00ae8>
CRITICAL:root:twint.feed:Follow:IndexError
[+] Beginning custom JSON test in <function Following at 0x7f3733b00ae8>
CRITICAL:root:twint.feed:Follow:IndexError
[+] Beginning JSON test in <function Following at 0x7f3733b00ae8>
CRITICAL:root:twint.feed:Follow:IndexError
[+] Beginning custom CSV test in <function Following at 0x7f3733b00ae8>
CRITICAL:root:twint.feed:Follow:IndexError
[+] Beginning CSV test in <function Following at 0x7f3733b00ae8>
CRITICAL:root:twint.feed:Follow:IndexError
[+] Beginning DB test in <function Following at 0x7f3733b00ae8>
[+] Inserting into Database: test_twint.db
CRITICAL:root:twint.feed:Follow:IndexError
[+] Beginning vanilla test in <function Followers at 0x7f3733b00a60>
[+] Inserting into Database: test_twint.db
CRITICAL:root:twint.feed:Follow:IndexError
[+] Beginning custom JSON test in <function Followers at 0x7f3733b00a60>
[+] Inserting into Database: test_twint.db
CRITICAL:root:twint.feed:Follow:IndexError
[+] Beginning JSON test in <function Followers at 0x7f3733b00a60>
[+] Inserting into Database: test_twint.db
CRITICAL:root:twint.feed:Follow:IndexError
[+] Beginning custom CSV test in <function Followers at 0x7f3733b00a60>
[+] Inserting into Database: test_twint.db
CRITICAL:root:twint.feed:Follow:IndexError
[+] Beginning CSV test in <function Followers at 0x7f3733b00a60>
[+] Inserting into Database: test_twint.db
CRITICAL:root:twint.feed:Follow:IndexError
[+] Beginning DB test in <function Followers at 0x7f3733b00a60>
[+] Inserting into Database: test_twint.db
CRITICAL:root:twint.feed:Follow:IndexError
[+] Beginning vanilla test in <function Search at 0x7f3733b00c80>
[+] Beginning custom JSON test in <function Search at 0x7f3733b00c80>
[+] Beginning JSON test in <function Search at 0x7f3733b00c80>
CRITICAL:root:twint.run:Twint:Feed:noDataExpecting value: line 1 column 1 (char 0)
[+] Beginning custom CSV test in <function Search at 0x7f3733b00c80>
[+] Beginning CSV test in <function Search at 0x7f3733b00c80>
[+] Beginning DB test in <function Search at 0x7f3733b00c80>
[+] Inserting into Database: test_twint.db
[+] Beginning vanilla test in <function Profile at 0x7f3733b00bf8>
[+] Inserting into Database: test_twint.db
968243242184491008 2018-02-26 22:55:52 CET <verified> We've paused public submissions for verification.👇 https://twitter.com/TwitterSupport/status/930926225517719552 …
784104327417737216 2016-10-06 20:53:34 CET <verified> If you think your account should be verified – let us know! Check out our article to learn what it takes to apply.  https://support.twitter.com/articles/20174631 …
240862454089920512 2012-08-29 19:24:18 CET <verified> The most important one-pager that every verified Twitter user should read: Keeping Your Account Secure  https://support.twitter.com/articles/76036-safety-keeping-your-account-secure# …
232984451381071872 2012-08-08 01:39:56 CET <verified> Twitter will never, ever ask you for your password. If you receive a verification request asking for your account information, it's false.
232984257734258689 2012-08-08 01:39:10 CET <verified> Verification is not currently open to the general public. Learn more about the types of accounts that are eligible: https://twitter.com/help/verified 
225985823798091776 2012-07-19 18:09:53 CET <verified> Please note: changing your username will result in losing your badge. Questions? File request at  https://support.twitter.com/forms  we'll get to it ASAP!
[!] Twitter does not return more data, scrape stops here.
[+] Beginning custom JSON test in <function Profile at 0x7f3733b00bf8>
[+] Inserting into Database: test_twint.db
968243242184491008 2018-02-26 22:55:52 CET <verified> We've paused public submissions for verification.👇 https://twitter.com/TwitterSupport/status/930926225517719552 …
784104327417737216 2016-10-06 20:53:34 CET <verified> If you think your account should be verified – let us know! Check out our article to learn what it takes to apply.  https://support.twitter.com/articles/20174631 …
240862454089920512 2012-08-29 19:24:18 CET <verified> The most important one-pager that every verified Twitter user should read: Keeping Your Account Secure  https://support.twitter.com/articles/76036-safety-keeping-your-account-secure# …
232984451381071872 2012-08-08 01:39:56 CET <verified> Twitter will never, ever ask you for your password. If you receive a verification request asking for your account information, it's false.
232984257734258689 2012-08-08 01:39:10 CET <verified> Verification is not currently open to the general public. Learn more about the types of accounts that are eligible: https://twitter.com/help/verified 
225985823798091776 2012-07-19 18:09:53 CET <verified> Please note: changing your username will result in losing your badge. Questions? File request at  https://support.twitter.com/forms  we'll get to it ASAP!
[!] Twitter does not return more data, scrape stops here.
[+] Beginning JSON test in <function Profile at 0x7f3733b00bf8>
[+] Inserting into Database: test_twint.db
968243242184491008 2018-02-26 22:55:52 CET <verified> We've paused public submissions for verification.👇 https://twitter.com/TwitterSupport/status/930926225517719552 …
784104327417737216 2016-10-06 20:53:34 CET <verified> If you think your account should be verified – let us know! Check out our article to learn what it takes to apply.  https://support.twitter.com/articles/20174631 …
240862454089920512 2012-08-29 19:24:18 CET <verified> The most important one-pager that every verified Twitter user should read: Keeping Your Account Secure  https://support.twitter.com/articles/76036-safety-keeping-your-account-secure# …
232984451381071872 2012-08-08 01:39:56 CET <verified> Twitter will never, ever ask you for your password. If you receive a verification request asking for your account information, it's false.
232984257734258689 2012-08-08 01:39:10 CET <verified> Verification is not currently open to the general public. Learn more about the types of accounts that are eligible: https://twitter.com/help/verified 
225985823798091776 2012-07-19 18:09:53 CET <verified> Please note: changing your username will result in losing your badge. Questions? File request at  https://support.twitter.com/forms  we'll get to it ASAP!
[!] Twitter does not return more data, scrape stops here.
[+] Beginning custom CSV test in <function Profile at 0x7f3733b00bf8>
[+] Inserting into Database: test_twint.db
968243242184491008 2018-02-26 22:55:52 CET <verified> We've paused public submissions for verification.👇 https://twitter.com/TwitterSupport/status/930926225517719552 …
784104327417737216 2016-10-06 20:53:34 CET <verified> If you think your account should be verified – let us know! Check out our article to learn what it takes to apply.  https://support.twitter.com/articles/20174631 …
240862454089920512 2012-08-29 19:24:18 CET <verified> The most important one-pager that every verified Twitter user should read: Keeping Your Account Secure  https://support.twitter.com/articles/76036-safety-keeping-your-account-secure# …
232984451381071872 2012-08-08 01:39:56 CET <verified> Twitter will never, ever ask you for your password. If you receive a verification request asking for your account information, it's false.
232984257734258689 2012-08-08 01:39:10 CET <verified> Verification is not currently open to the general public. Learn more about the types of accounts that are eligible: https://twitter.com/help/verified 
225985823798091776 2012-07-19 18:09:53 CET <verified> Please note: changing your username will result in losing your badge. Questions? File request at  https://support.twitter.com/forms  we'll get to it ASAP!
[!] Twitter does not return more data, scrape stops here.
[+] Beginning CSV test in <function Profile at 0x7f3733b00bf8>
[+] Inserting into Database: test_twint.db
968243242184491008 2018-02-26 22:55:52 CET <verified> We've paused public submissions for verification.👇 https://twitter.com/TwitterSupport/status/930926225517719552 …
784104327417737216 2016-10-06 20:53:34 CET <verified> If you think your account should be verified – let us know! Check out our article to learn what it takes to apply.  https://support.twitter.com/articles/20174631 …
240862454089920512 2012-08-29 19:24:18 CET <verified> The most important one-pager that every verified Twitter user should read: Keeping Your Account Secure  https://support.twitter.com/articles/76036-safety-keeping-your-account-secure# …
232984451381071872 2012-08-08 01:39:56 CET <verified> Twitter will never, ever ask you for your password. If you receive a verification request asking for your account information, it's false.
232984257734258689 2012-08-08 01:39:10 CET <verified> Verification is not currently open to the general public. Learn more about the types of accounts that are eligible: https://twitter.com/help/verified 
225985823798091776 2012-07-19 18:09:53 CET <verified> Please note: changing your username will result in losing your badge. Questions? File request at  https://support.twitter.com/forms  we'll get to it ASAP!
[!] Twitter does not return more data, scrape stops here.
[+] Beginning DB test in <function Profile at 0x7f3733b00bf8>
[+] Inserting into Database: test_twint.db
968243242184491008 2018-02-26 22:55:52 CET <verified> We've paused public submissions for verification.👇 https://twitter.com/TwitterSupport/status/930926225517719552 …
784104327417737216 2016-10-06 20:53:34 CET <verified> If you think your account should be verified – let us know! Check out our article to learn what it takes to apply.  https://support.twitter.com/articles/20174631 …
240862454089920512 2012-08-29 19:24:18 CET <verified> The most important one-pager that every verified Twitter user should read: Keeping Your Account Secure  https://support.twitter.com/articles/76036-safety-keeping-your-account-secure# …
232984451381071872 2012-08-08 01:39:56 CET <verified> Twitter will never, ever ask you for your password. If you receive a verification request asking for your account information, it's false.
232984257734258689 2012-08-08 01:39:10 CET <verified> Verification is not currently open to the general public. Learn more about the types of accounts that are eligible: https://twitter.com/help/verified 
225985823798091776 2012-07-19 18:09:53 CET <verified> Please note: changing your username will result in losing your badge. Questions? File request at  https://support.twitter.com/forms  we'll get to it ASAP!
[!] Twitter does not return more data, scrape stops here.
[+] Beginning vanilla test in <function Favorites at 0x7f3733b009d8>
[+] Inserting into Database: test_twint.db
CRITICAL:root:twint.feed:Mobile:list index out of range
[+] Beginning custom JSON test in <function Favorites at 0x7f3733b009d8>
[+] Inserting into Database: test_twint.db
CRITICAL:root:twint.feed:Mobile:list index out of range
[+] Beginning JSON test in <function Favorites at 0x7f3733b009d8>
[+] Inserting into Database: test_twint.db
CRITICAL:root:twint.feed:Mobile:list index out of range
[+] Beginning custom CSV test in <function Favorites at 0x7f3733b009d8>
[+] Inserting into Database: test_twint.db
CRITICAL:root:twint.feed:Mobile:list index out of range
[+] Beginning CSV test in <function Favorites at 0x7f3733b009d8>
[+] Inserting into Database: test_twint.db
CRITICAL:root:twint.feed:Mobile:list index out of range
[+] Beginning DB test in <function Favorites at 0x7f3733b009d8>
[+] Inserting into Database: test_twint.db
CRITICAL:root:twint.feed:Mobile:list index out of range
[+] Testing complete!
