### ISSUE TITLE
[QUESTION] Usage of members_list

### ISSUE THREAD

**Issue by nachotp** [twintproject/twint#610]
Greetings

I'm running on Windows 10, python 3.6 and the latest version of twint.

I'm trying to download tweets from a specific date range that were sent by a list of usernames and reading the docs I assumed that members_list was the way to go. and addec this to my search config:

`c.Members_list = "user1/user2/user3"`

but when I run it I get

`CRITICAL:root:twint.run:Twint:Feed:noDataExpecting value: line 1 column 1 (char 0)
CRITICAL:root:twint.run:Twint:Feed:noDataExpecting value: line 1 column 1 (char 0)
CRITICAL:root:twint.run:Twint:Feed:noData'items_html'
CRITICAL:root:twint.run:Twint:Feed:noDataExpecting value: line 1 column 1 (char 0)
CRITICAL:root:twint.run:Twint:Feed:noDataExpecting value: line 1 column 1 (char 0)
CRITICAL:root:twint.run:Twint:Feed:Tweets_known_error:Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0) [x] run.Feed`

wich as far as I am concerned, means that there are no tweets available.

Am I using the correct method or is there a better option?

Thanks!

**Comment by pielco11** [comment]
https://github.com/twintproject/twint/wiki/Other-examples#4---return-tweets-containing-a-specific-keyword-that-have-at-least-5-likes-and-that-are-part-of-a-given-users-list

"Members list" is not a list of usernames, but Twitter's lists. For example if [this](https://twitter.com/manhack/lists/osint) is the list, the argument for it is `manhack/osint`

**Comment by nachotp** [comment]
Thanks! It was exactly what I needed

**Comment by teamdaemons** [comment]
Somehow my twitter list is not working despite creating the list as public. Example here: fashai/worldleaders. Please help

**Comment by defidummy** [comment]
This is interesting cause when I scraped other people's list. It works. For example `"naval/crypto"` but not my own list `"dailydefidummy/demo"`
