### ISSUE TITLE
Twint returning exceptions and timing out after --follower list pull

### ISSUE THREAD

**Issue by PaulWitry** [twintproject/twint#612]
Very new to Twint! Employing it for a specific project. (I apologize for my general lack of knowledge and if things are formatted incorrectly)

`twint -u harrispolicy -followers`

Running this through OSX, verified that my Python is up to date, etc. 

The command starts running fine but returns an initial exception and later on has a timeout exception related to calling for this data. The account only features approx. 10k followers.
I noted in another issue post that there was a limit to how many it could pull down, but is that relative to follows or overall?

Thanks!

**Comment by rlleshi** [comment]
You might want to take a look at [this ](https://github.com/twintproject/twint/issues/340)issue.

**Comment by pielco11** [comment]
Timeout exception means that Twitter stopped giving you data

Also I think that you used `--followers` and not `-followers`

IMO, scraping followers/following reached a dead end. I added some timeouts around, but Twitter still works good

**Comment by PaulWitry** [comment]
Thanks @rlleshi I appreciate the advice! I looked there originally and saw that Pielco11 had said that Twitter was getting more effective at blocking Twint data requests but just wanted an update :)

**Comment by PaulWitry** [comment]
@pielco11 I had a feeling that was the case, I appreciate it. Is it the timing between each data request that they are blocking off of or the size of the request overall?

(I missed the extra tack on the `--followers` when making the initial post haha sorry, noob mistake)

**Comment by tripelix** [comment]
I am tracking a bot army on twitter it currently has over 549 accounts posting spam and phishing links (6584 tweets 2019-12-18) and using --followers or --following I get sporadic: twint.feed:Follow:IndexError on some accounts, from what I can tell there is nothing different just some won't give back any data, this is also true occasionally on tweets. i see them on the platform fine.  i would be happy to share account to look at just don't click on any of the phishing links you will get an FBI visit dm me on twitter for data @trip_elix
