### ISSUE TITLE
[QUESTION] Can't install twint

### ISSUE THREAD

**Issue by ErAle001** [twintproject/twint#614]
###  Command Ran
git clone https://github.com/twintproject/twint/
cd twint
pip3 install -r requirements.txt

### Description of Issue
I cloned the repository, cd into it and installed the requirements. The only weird thing till now is that when I ran the install requirements command, the "Running setup.py bdist_wheel for pandas" took a really long time, I had to let it go like that for like 2 hours over night while I was sleeping.

When I woke up and tried to run twint, I was getting the error that the command was not found. So I ran the requirements.txt once again to make sure that nothing was missing. The only weird thing that stopped appearing after a couple tries is that it showed a (red) message like this: twint has been installed into /.local/bin , please make sure this is in PATH.

But I don't know how to do that, and people explaining that on the internet are really confusing. Maybe that is the problem.

Thanks in advance,
Alejandro

### Environment Details
Kali Linux Light 2019.3-i386     (this version doesn't come with preinstalled tools, I preferred this as I could be adding those which I learn by time). It uses XFCE.
![Captura de pantalla_2019-12-19_10-56-20](https://user-images.githubusercontent.com/59049954/71165933-fc5efb80-2251-11ea-8450-d000cee473c8.png)

**Comment by ErAle001** [comment]
For any reason, I ran once again requirements.txt and it worked. No idea what happened.

**Comment by pielco11** [comment]
Running Twint via `twint` requires you to install it as package, `pip3 install twint`

Doing as you did, instead, gives you the ability to run Twint as module **only** under that directory.
