### ISSUE TITLE
[QUESTION] About gathering information of private accounts

### ISSUE THREAD

**Issue by ErAle001** [twintproject/twint#615]
### Description
So, twint can't gather information from an account that has protected his tweets so the account is private. But I was wondering, "x" person has his account to be private, however, I follow his account with my personal or a fake one that I managed to make them accept it so I can see their tweets. Is there a way of like using that account with twint to gather his twitter info?

It would be like using a proxy which is trusted by the target (not a good comparison but you get what I mean), or is this too much of a crazy idea?

![WhatsApp Image 2019-12-19 at 12 18 44](https://user-images.githubusercontent.com/59049954/71170746-4b119300-225c-11ea-9d50-72c76382b2ce.jpeg)

**Comment by jomorrcode** [comment]
Twint doesn't pass any user credentials so I doubt there's anyway for it to do what you're asking.   It's just doing a generic public search of Twitter without being logged in as any specific user, so it can only see public data.

**Comment by ErAle001** [comment]
> Twint doesn't pass any user credentials so I doubt there's anyway for it to do what you're asking. It's just doing a generic public search of Twitter without being logged in as any specific user, so it can only see public data.

Hmm... Yeah that is exactly how twint is described, maybe the idea can be considered for the future; although it would be right next to the legal border as you would be gathering non-public info, and probably would cross the legal line depending of what you decide to do with it, as sharing to someone for example.

**Comment by pielco11** [comment]
You could edit the way which the requests are crafted, but I'd **not** suggest you to do so since Twitter may recognize your activity as malicious/unusual and thus suspend/block/permanently-ban your account.

I'd consider using the API instead
