### ISSUE TITLE
Twint crashing?

### ISSUE THREAD

**Issue by cad-x2** [twintproject/twint#619]
I'm running the following command to get all tweets from Frankfurt;

twint -g="50.212945,8.715222,10km" --hashtags --csv -o f1.csv --stats -ho  --location &

I periodically get the following in the console: 
CRITICAL:root:twint.run:Twint:Feed:noDataExpecting value: line 1 column 1 (char 0)

I'm running on ubuntu 18.04 and python 3.6

The issue is that the processes dies after a while. Is there anything that I could do to catch all live tweets?

**Comment by pielco11** [comment]
Issue already reported

**Comment by pielco11** [comment]
#604

**Comment by cad-x2** [comment]
I don't think that was the issue, the same problem persists. Oddly, I'm scrapping tweets from various cities around the world, and always twint stops very quickly (after less than 3-4 thousand tweets) in Frankfurt
twint -g="50.212945,8.715222,10km" --hashtags --csv -o f1.csv --stats -ho --location &

**Comment by pielco11** [comment]
May you post here or on PasteBin the content of `twint-last-request.log`, please?
