### ISSUE TITLE
Another installation, another problem with Critical Root

### ISSUE THREAD

**Issue by AldebaranNapoli** [twintproject/twint#624]
Debian, Mint, Ubuntu, Kali lastversione all same error

CRITICAL:root:twint.run:Twint:Feed:noDataExpecting value: line 1 column 1 (char 0)

>Make sure you've checked the following:
Python 3.7.5
Git - cd - install requirement command 
Update
Build setup

**I have searched the issues and there are no duplicates of this issue/question/request BECAUSE I DONT HAVE A SOUTION**

### Command Ran
twint -u liviovarriale --since 2019-01-01 --until 2019-02-01 --stats --count
twint -u liviovarriale --since 2019-01-01 --until 2019-02-01 --stats --count -es localhost:9200

### Description of Issue
**After 4 installs the difference with another coputer is the Nvidia driver installed.
Can be this the problem?**

I have 2 pc one with drivers invidia installed another not(here works good)

### Environment Details
ubunti 19 - twint from terminal - kibana e elastic search actvie.

**Comment by pielco11** [comment]
#604
