### ISSUE TITLE
Fetch Users with a specific description and location

### ISSUE THREAD

**Issue by surbhikakar** [twintproject/twint#631]
Could you tell me how can I fetch users that have a specific keyword in thier Bio and belong to a specific location?

**Comment by pielco11** [comment]
As of now it's not possible to search for specific users

**Comment by surbhikakar** [comment]
Thanks for letting me know. It works for me now. I first searched some tweets using hashtag. Took the distinct users and then scraped these users using LookUp. Checked 
their bio to see if they are the users I wanted. Had to run 2 scripts but it runs anyways.
