### ISSUE TITLE
problem in fetching tweets

### ISSUE THREAD

**Issue by deepalidhaka** [twintproject/twint#632]
### Command Ran
c = twint.Config()
path='/user/test/'
c.Output=path+'tweets.csv'
c.Limit=1000
c.Lang='en'
c.Store_csv=True
c.Search='#hashtag'
twint.run.Search(c)

### Description of Issue
> after running the above code to get 1000 tweets with a particular hashtag, I am getting only few number of tweets (60 tweets or less than that).
Error which i am getting is -
CRITICAL:root:twint.run:Twint:Feed:Tweets_known_error:Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0) [x] run.Feed
[!] if get this error but you know for sure that more tweets exist, please open an issue and we will investigate it!

### Environment Details
>Using Windows 8.1 pro, 64 bit OS ,Running this in Anaconda, spyder.

**Comment by pielco11** [comment]
#604 

The already reported issue is even pinned
