### ISSUE TITLE
Wiki: Wrong tweet attributes

### ISSUE THREAD

**Issue by tibor** [twintproject/twint#634]
I think, it should be `tweet.datestamp` and `tweet.timestamp` instead of `tweet.date` and `tweet.time`:
https://github.com/twintproject/twint/wiki/Tweet-attributes

**Comment by joaociocca** [comment]
`user_id` also doesn't exist anymore, AFAIK

**Comment by pielco11** [comment]
@joaociocca here is what I get

![immagine](https://user-images.githubusercontent.com/17363750/73388498-4368f380-42ca-11ea-8341-8a831d77f701.png)

**Comment by MrMindy** [comment]
> I think, it should be `tweet.datestamp` and `tweet.timestamp` instead of `tweet.date` and `tweet.time`:
> https://github.com/twintproject/twint/wiki/Tweet-attributes

Thx dude, you really saved my life hahahahaha
