### ISSUE TITLE
Resume and input into csv

### ISSUE THREAD

**Issue by Reeyomma** [twintproject/twint#638]
### Command Ran
twint -s "#secondamendment" -o secondamendmentJan152020.csv --csv   ###this command ran fine until it stopped, the resume issue is below.

(venv) C:\Users\lnmar\PycharmProjects\Webscrapers>twint -s "#secondamendment" -resume "secondamendmentJan152020.csv" -o secondamendmentJan152020.csv --csv
usage: python3 twint [options]
twint: error: unrecognized arguments: -resume secondamendmentJan152020.csv

(venv) C:\Users\lnmar\PycharmProjects\Webscrapers>twint -s "#secondamendment" -resume  -o secondamendmentJan152020.csv --csv
usage: python3 twint [options]
twint: error: unrecognized arguments: -resume

### Description of Issue
I am trying to collect tweets into a csv. It will stop giving the error "OSError: [WinError 87] The parameter is incorrect." I then try to use resume to continue the search, but it will not run. I haven't been able to find another example of someone mixing resume and csv, but it seems like something that is likely common. If someone could let me know if I am making a simple error and how to fix it I would appreciate it. 

### Environment Details
>Windows 10, python version 3.6, running in pycharm

**Comment by pielco11** [comment]
Hi @Reeyomma 

to effort the benefits of the resume option, you have to run it first.

`twint -s "#secondamendment" -o secondamendmentJan152020.csv --csv --resume secondamendmentJan152020.session`

Then when it stops, or you stop it, just re-run it.
You can't resume a session if you did not create the `.session` file first

About the error message, the correct argument is `--resume` and not `-resume`

**Comment by Reeyomma** [comment]
Thanks
