### ISSUE TITLE
[QUESTION] How can I get the user profiles of member of a List?

### ISSUE THREAD

**Issue by psanch21** [twintproject/twint#641]
I am wondering how can I get information about the users that are members of a List.

Thank you in advance!

**Comment by pielco11** [comment]
Do you mean information like number of tweets, followers, following, likes, join date, bio...?

**Comment by psanch21** [comment]
Hi,

Not exactly, I meant to say the List feature of Twitter. I refer to the Lists that a user owns and the Lists that a user is subscribed to. Also the information of a List, i.e, the members.

**Comment by pielco11** [comment]
As of now it's not possible to extract the handles of a given list, but you can extract the tweets sent by them

I suggest you to use the browser and extract them from the page, or use the API (not sure if this feature is available)

**Comment by psanch21** [comment]
Great, I'll take a look at it. Thanks for the response!
