### ISSUE TITLE
How to display "Twint response" on html page? As the data is displayed only on command promt

### ISSUE THREAD

**Issue by Jyothsna2795** [twintproject/twint#642]
I am beginner and trying to write API call for displaying Twint response on html page, but the extracted data is displayed in command prompt. Please guide me through this. 

I am using Updated version of twint, Python 3.7, Django 3.0, windows 10

> Below is my code

views.py
```python
class UserName(APIView):
    def get(self,request,format=None):
        return self.username(request,request.query_params)
    def username(self, request, result):
        c = twint.Config()
        asyncio.set_event_loop(asyncio.new_event_loop())
        result = twint.run.Search(c)
        return Response(result)
```

**Comment by pielco11** [comment]
The type of `twint.run.Search` is `void`. Meaning that's a function that returns "nothing"

You may want to save the tweets in a list and then return in, also you may want to have a quiet output (check in the wiki `Hide_output` and `tweets_list`)

**Comment by Jyothsna2795** [comment]
@pielco11  Thank you
