### ISSUE TITLE
Only getting last 26 favorites for a user

### ISSUE THREAD

**Issue by youssefavx** [twintproject/twint#644]
- [] Python version is 3.7.4;
- [] Updated Twint with `pip3 install --user --upgrade -e git+https://github.com/twintproject/twint.git@origin/master#egg=twint`;
- [] I have searched the issues and there are no duplicates of this issue/question/request.

### Command Ran

```
import twint
import os
import time


def downloadfavorites(userfavorites):
    print("Downloading favorites for: " + str(userfavorites))
    fv = twint.Config()
    fv.Username = str(userfavorites.lower())
    fv.Store_csv = True
    fv.Output = "data/" + str(userfavorites) + " favorites.csv"
    while True:
        try:
            twint.run.Favorites(fv)
            break
        except aiohttp.ClientConnectorError:
            print('Cant connect to internet. Retrying in 2 seconds...')
            if os.path.exists('data/' + str(userfavorites) + " favorites.csv"):
                print('Removing the incomplete file ' + str(userfavorites) + " favorites.csv")
                os.remove('data/' + str(userfavorites) + " favorites.csv")
            time.sleep(2)
        except aiohttp.ClientOSError:
            print('Cant connect to internet. Retrying in 2 seconds...')
            if os.path.exists('data/' + str(userfavorites) + " favorites.csv"):
                print('Removing the incomplete file ' + str(userfavorites) + " favorites.csv")
                os.remove('data/' + str(userfavorites) + " favorites.csv")
            time.sleep(2)
        except aiohttp.ServerDisconnectedError:
            print('Cant connect to internet. Retrying in 2 seconds...')
            if os.path.exists('data/' + str(userfavorites) + " favorites.csv"):
                print('Removing the incomplete file ' + str(userfavorites) + " favorites.csv")
                os.remove('data/' + str(userfavorites) + " favorites.csv")
            time.sleep(2)
        except asyncio.TimeoutError:
            print('Cant connect to internet. Retrying in 2 seconds...')
            if os.path.exists('data/' + str(userfavorites) + " favorites.csv"):
                print('Removing the incomplete file ' + str(userfavorites) + " favorites.csv")
                os.remove('data/' + str(userfavorites) + " favorites.csv")
            time.sleep(2)

downloadfavorites(username)

```

### Description of Issue
This function seems to work fine in most cases but for one user with old tweets, for some reason, it stops scraping at the last 26th tweet, and does not go past that. That last tweet was around 2018. The user has 2K likes.

I get a "CRITICAL:root:twint.feed:Mobile:list index out of range" 2 times, but I don't know if that's related or not as it doesn't stop immediately after that.

### Environment Details
> MacOS 10.14 running in Terminal

**Comment by youssefavx** [comment]
I just tried the same user with the twitter API / tweepy, and it also got me only the last 26 favorites.

**Comment by youssefavx** [comment]
I should note that the tweet after the last favorited tweet (which was tweeted in 2018) was tweeted in 2016.

**Comment by pielco11** [comment]
How many favorites for that user? Is 26 an expected count?

**Comment by youssefavx** [comment]
The user has around 2.5K favorites. 26 is unexpected.

**Comment by pielco11** [comment]
Hmm well strange, what do you see if you scroll manually with your browser?

**Comment by youssefavx** [comment]
I see the tweets updating normally

**Comment by pielco11** [comment]
Quite strange, I tried with my profile and I'm able to get a few of them without problems

**Comment by youssefavx** [comment]
Yeah same thing here, I don't know why this user specifically has that problem. Here is the user: paultoo

**Comment by pielco11** [comment]
Well, strange here too

So I suggest you to use the API, this issues seems to be user specific

Maybe Twitter does not allow us to go too back in time

**Comment by youssefavx** [comment]
Will try, thanks!
