### ISSUE TITLE
Header images (background_image) are not returned from a user lookup.

### ISSUE THREAD

**Issue by dotgodly** [twintproject/twint#645]
- [x] Python version is 3.6;
- [x] Updated Twint with `pip3 install --user --upgrade -e git+https://github.com/twintproject/twint.git@origin/master#egg=twint`;
- [x] I have searched the issues and there are no duplicates of this issue/question/request.

### Command Ran
```
import twint

c = twint.Config()
c.Username = "jack"

twint.run.Lookup(c)
```

### Description of Issue
Header images are no longer returned. [It seems like](https://github.com/twintproject/twint/blob/273cd12f20e39fd90b8c51a5f3fc43382622241d/twint/user.py#L136) there is a place to obtain them in the code, however it is likely Twitter has changed it's CSS.

### Environment Details
Linux, Python3

**Comment by pielco11** [comment]
Hmm strange

Here's what I get with my handle

![immagine](https://user-images.githubusercontent.com/17363750/73164260-8029c480-40e9-11ea-86de-55eca876e1d2.png)

**Comment by pielco11** [comment]
And the same with Jack 
![immagine](https://user-images.githubusercontent.com/17363750/73164371-bebf7f00-40e9-11ea-8d34-b4ebd3f80a46.png)

**Comment by dotgodly** [comment]
Actually, running the command and obtaining the header from the CSV also works for me, however when using Twint as a module only returns the profile picture.

**Comment by pielco11** [comment]
The results are the same since the request is the same and handled in the same way

![immagine](https://user-images.githubusercontent.com/17363750/73165242-5a9dba80-40eb-11ea-8e0b-e628b4813c72.png)

Travis-CI is currently pushing to PyPI a little update. You might want to try something like this soon
```python
import twint

c = twint.Config()
c.Username = "jack"
c.Format = "{username} {background_image}"

twint.run.Lookup(c)
```

**Comment by pielco11** [comment]
@dotgodly please update with `pip3 install --upgrade twint` (or similar) and try the snipped that I previously posted

**Comment by dotgodly** [comment]
That worked for me, thank you!
