### ISSUE TITLE
[REQUEST] c.Geo For An Area

### ISSUE THREAD

**Issue by lindsaymahowald1997** [twintproject/twint#649]
Hello! Very new to Python, so sorry if this has already been addressed/is an easy fix. I'm looking to scrape Tweets that were sent out in specific United States counties. However, the Geo feature requests a pinpointed location (lat/long) and a surrounding area, which makes it more difficult to secure data within a county (as compared to being able to use coordinates to set up an area, say). 

Would it be possible to, say, use the googlemaps package such that people with Google API keys could grab the geocodes for specific locations (i.e. counties) using gmaps and subsequently use those in a twint search? Sorry if this question is nonsensical - again, very new to Python here!

**Comment by pielco11** [comment]
Well `c.Geo` accept geocodes, so as you have one, you can filter the results

**Comment by lindsaymahowald1997** [comment]
Hi, thanks for getting back to me! This is a sample the code I'm trying to use right now - it doesn't seem to be taking into account the geocode when running the search:

import twint
import googlemaps

gmaps = googlemaps.Client(key='{my API key}')
alcona_geocode = gmaps.geocode('Alcona County, MI')

c = twint.Config()
c.Search = "#MAGA"
c.Limit = 70000
c.Output = "alcona.csv"
c.Since = "2016-11-01"
c.Until = "2016-11-08"
c.Place = alcona_geocode
c.Images = True
c.Count = True
twint.run.Search(c)

Let me know if I'm doing something wrong here!

**Comment by pielco11** [comment]
The query does not seem wrong, you are searching for tweets in that specific area, between the specified date range and which contain images. If you replicate the search on Twitter, what do you get?

**Comment by lindsaymahowald1997** [comment]
Hi, now when I run that code I'm getting the following error:

Traceback (most recent call last):
  File "/Users/lindsay/Documents/Scrape Attempt 1.py", line 16, in <module>
    twint.run.Search(c)
  File "/Users/lindsay/Documents/twint/run.py", line 290, in Search
    run(config, callback)
  File "/Users/lindsay/Documents/twint/run.py", line 211, in run
    loop.run_until_complete(Twint(config).main(callback))
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/base_events.py", line 612, in run_until_complete
    return future.result()
  File "/Users/lindsay/Documents/twint/run.py", line 149, in main
    await task
  File "/Users/lindsay/Documents/twint/run.py", line 172, in run
    await self.tweets()
  File "/Users/lindsay/Documents/twint/run.py", line 132, in tweets
    await self.Feed()
  File "/Users/lindsay/Documents/twint/run.py", line 49, in Feed
    response = await get.RequestUrl(self.config, self.init, headers=[("User-Agent", self.user_agent)])
  File "/Users/lindsay/Documents/twint/get.py", line 106, in RequestUrl
    _url, params, _serialQuery = await url.Search(config, init)
  File "/Users/lindsay/Documents/twint/url.py", line 92, in Search
    config.Geo = config.Geo.replace(" ", "")
AttributeError: 'list' object has no attribute 'replace'

I'm so sorry if this is too granular for you to figure out! No worries if you're not sure what's wrong.

**Comment by pielco11** [comment]
@lindsaymahowald1997 no worries

So it seems that `gmaps.geocode('Alcona County, MI')` returns a `list` object, while the correct type for `config.Geo` is `string`. So you may want to correctly handle what's returned, and to do this you may need to read the documentation about `googlemaps`

**Comment by lindsaymahowald1997** [comment]
Okay, I think I finally understand what I'm doing enough to ask my question properly!

So the config.Geo function allows you to add a geocode, but what I was hoping to do is use geocodes as bounds for a specific area (in this case, counties). For example, gmaps lists the bounds for Macomb County, MI as:

             northeast: {'lat': 42.897541, 'lng': -82.7059659}, and
             southwest: {'lat': 42.447055, 'lng': -83.102891}

I would like to be able to input bounds (i.e. a northeast and southwest lat and long) into config.Geo - is this possible, and if so, what is the correct syntax for doing so?

**Comment by pielco11** [comment]
`geocode` accepts `lat,long,km/mi`, like `c.Geo = "42.897541,-82.7059659,20km"`, which is a circle

**Comment by lindsaymahowald1997** [comment]
So, to clarify, there is no way to make the argument accept multiple lat/long values to create bounds?

**Comment by pielco11** [comment]
The bound is defined by the radius of the circle. I'm not aware of a way to create rectangular bounds

**Comment by bryanhpchiang** [comment]
I have a similar issue - one solution (takes longer to run) might be to find the center of the bounding box, set the radius to half of the longer diagonal, then filter out all of the tweets that fall outside the bounding box.

**Comment by DerekGrant** [comment]
> c.Geo = "42.897541,-82.7059659,20km"

It works for me. c.Geo = "39.6459604,-99.1227847,1400km"
