### ISSUE TITLE
While scraping a username, is it possible to get the reply/like/retweet count for each tweet? 

### ISSUE THREAD

**Issue by CyrisXD** [twintproject/twint#650]
As title suggests, I'm looking to scrape a specific users tweets, and also get the reply, like and retweet count for each of those tweets. 

I'd like to build my own program to loop over all the tweets and delete the tweets with no interactions as a "Twitter cleanup". 

Any help appreciated. 
Cheers

**Comment by CyrisXD** [comment]
For those also here, I've figured it out by appending --stats to your query.

**Comment by pielco11** [comment]
If you save tweets to `csv` or `json` files (or any other storing option, let it be db or elastic) those counters (likes, replies, retweets) are already reported

![image](https://user-images.githubusercontent.com/17363750/73651410-45d99d80-467c-11ea-97a0-687df158ed7a.png)

`config.Stats` is used to print those counters to stdout
https://github.com/twintproject/twint/blob/81f6c2c516a231136fbd821bd6a53d7959965fee/twint/format.py#L49-L50
