### ISSUE TITLE
[QUESTION] Can i make it faster ?

### ISSUE THREAD

**Issue by apapan08** [twintproject/twint#652]
I use google colaboratory to run the following code:
```python
col_names =  ['from','to',]
my_df  = pd.DataFrame(columns = col_names)

for users in iteration:
  usernames=users
  c = twint.Config()
  c.Username = usernames
  c.Pandas = True
  c.User_full = True  
  twint.run.Followers(c)
  Users_df = twint.storage.panda.User_df['username']
  for i in range(len(Users_df)): 
      my_df.loc[len(my_df)] = [usernames,Users_df[i]]
```
where iteration is a list of twitter name accounts
I want to create a data frame in which the first column will be the usernames of the iteration object and the second column will be the person they follow. For example if a follows b and c my dataframe will have 2 rows [ a ,b] and [a,c]. Although my code is working is very slow ( for 3 users that have 900 followers takes 15 minutes] . I  am assuming that is because for every user it scraps all info about their followers while i only need the name of the followers. Is there a way to make it faster ?
Thanks
# Issue Template
Please use this template!

### Initial Check
> If the issue is a request please specify that it is a request in the title (Example: [REQUEST] more features). If this is a question regarding 'twint' please specify that it's a question in the title (Example: [QUESTION] What is x?). Please **only** submit issues related to 'twint'. Thanks.

>Make sure you've checked the following:

- [] Python version is 3.6;
- [] Updated Twint with `pip3 install --user --upgrade -e git+https://github.com/twintproject/twint.git@origin/master#egg=twint`;
- [] I have searched the issues and there are no duplicates of this issue/question/request.

### Command Ran
>Please provide the _exact_ command ran including the username/search/code so I may reproduce the issue.

### Description of Issue
>Please use **as much detail as possible.**

### Environment Details
>Using Windows, Linux? What OS version? Running this in Anaconda? Jupyter Notebook? Terminal?

**Comment by pielco11** [comment]
To make it faster you may want to run different scripts at the same time, save the data to CSV or the support that you may prefer. And then load each of them into a single script and build your dataframe

**Comment by apapan08** [comment]
thank you for your reply,
When you say different scripts at the same time you mean having multiple
notebooks open and run it right ?

**Comment by pielco11** [comment]
Well, I don't know how Colab exactly works but that sounds reasonable

**Comment by apapan08** [comment]
Okay , Thank you very much for your help
