### ISSUE TITLE
RuntimeError: There is no current event loop in thread 'Thread-61'.

### ISSUE THREAD

**Issue by paras55** [twintproject/twint#655]
run(config, callback)

File "C:\Users\dell\Anaconda3\lib\site-packages\twint\run.py", line 209, in run

get_event_loop().run_until_complete(Twint(config).main(callback))

File "C:\Users\dell\Anaconda3\lib\asyncio\events.py", line 644, in get_event_loop

 [Open an interactive python shell in this frame] % threading.current_thread().name)

**Comment by pielco11** [comment]
May you try with the simple shell? Do you get this issue only with Windows? Version of Python?

Please add more details so that I can understand you environment

**Comment by paras55** [comment]
I tried to make use of twint for fetching tweets and making an SST with them and deploying it with flask . When I opened my local server and entered the keyterm and pressed for result it showed me up with this problem . 
I have python 3.6

**Comment by pielco11** [comment]
So it seems that there's a compatibility issue with that setup
