### ISSUE TITLE
legal?

### ISSUE THREAD

**Issue by heeringa0** [twintproject/twint#659]
Thanks for making available this wonderful tool!

Just a short question: is retrieving tweets by using this tool legal when using it for academic purposes? Somewhere in the developer terms I read:

"_If you provide Twitter Content ... you will only distribute or allow download of Tweet IDs, Direct Message IDs, and/or User IDs. ... You may not do any of the following while accessing or using the Services: (iii) access or search or attempt to access or search the Services by any means (automated or otherwise) other than through our currently available, published interfaces that are provided by Twitter (and only pursuant to the applicable terms and conditions), unless you have been specifically allowed to do so in a separate agreement with Twitter (NOTE: crawling the Services is permissible if done in accordance with the provisions of the robots.txt file, however, scraping the Services without the prior consent of Twitter is expressly prohibited);_"

What to think about this?

**Comment by pielco11** [comment]
What I've to say is that the creator(s), maintainer(s), internal or external collaborator(s) or contributor(s), don't take any possible responsibility for the damage caused by the misuse of this tool

By using it, you accept to take the risk on your own
