### ISSUE TITLE
error: Microsoft Visual C++ 14.0 is required.

### ISSUE THREAD

**Issue by HydroHydro** [twintproject/twint#661]
Issue Template
Please use this template!

### Initial Check
> If the issue is a request please specify that it is a request in the title (Example: [REQUEST] more features). If this is a question regarding 'twint' please specify that it's a question in the title (Example: [QUESTION] What is x?). Please **only** submit issues related to 'twint'. Thanks.

>Make sure you've checked the following:

- [x] Python version is 3.6;
- [x] Updated Twint with `pip3 install --user --upgrade -e git+https://github.com/twintproject/twint.git@origin/master#egg=twint`;
- [x] I have searched the issues and there are no duplicates of this issue/question/request.

### Command Ran
pip3 install twint
pip3 install --user --upgrade -e git+https://github.com/twintproject/twint.git@origin/master#egg=twint

### Description of Issue
I haven't used Twint in a few months. Had it installed fine before and decided to upgrade today. Now I'm getting an error.
When I use "pip3 install twint" I get : error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": https://visualstudio.microsoft.com/downloads/
So I installed that and... I still get the same error.

Tried "pip3 install --user --upgrade -e git+https://github.com/twintproject/twint.git@origin/master#egg=twint" and got: ERROR: Command errored out with exit status 1: git fetch -q --tags Check the logs for full command output.

### Environment Details
Windows 10

**Comment by pielco11** [comment]
Well, I don't run Windows so I don't know why it doesn't work, have you searched on other websites to see if others encountered this problem and found a solution?

**Comment by alexandreteles** [comment]
> "pip3 install twint" I get : error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": https://visualstudio.microsoft.com/downloads/
So I installed that and... I still get the same error.

Some modules like `cchardet` will build native C code on your platform, so make sure that when running the Visual Studio Installer the Build Tools you checked the **C++ Build Tools** and the Microsoft Visual C++ 14.0 components.

> Tried "pip3 install --user --upgrade -e git+https://github.com/twintproject/twint.git@origin/master#egg=twint" and got: ERROR: Command errored out with exit status 1: git fetch -q --tags Check the logs for full command output.

There's a lot of possible reasons for this to happen and without the full logs there's no much I can do to help, but you should be able to install twint following those steps:

1. Make sure you have [Git](https://git-scm.com/download/win) installed;

2. Make sure that you have the latest pip version:

```powershell
python -m pip install --upgrade pip
```

3. Run:

```powershell
pip3 install --user --upgrade -e git+https://github.com/twintproject/twint.git@master#egg=twint
```

or:

```powershell
git clone "https://github.com/twintproject/twint.git" ./twint
pip3 install --user --upgrade -e ./twint
```

When opening issues, make sure to provide the full log ;)

**Comment by reiniervn** [comment]
I had the same issue.
After installing [Visual C++ Build Tools 2015](https://go.microsoft.com/fwlink/?LinkId=691126) and restarting my computer the problem was gone.

**Comment by HydroHydro** [comment]
@alexandreteles That worked! Thank you! Apparently I didn't check all the components on the first install.

Though I didn't have any of that installed when I installed Twint months ago. What changed that required Build Tools?

**Comment by pielco11** [comment]
@HydroHydro well, idk, but the libraries required haven't changed since a while. Maybe it's something about Python, not sure, no proof
