### ISSUE TITLE
[QUESTION] What is the recommended approach for many concurrent scrapers storing in a single database?

### ISSUE THREAD

**Issue by bryanhpchiang** [twintproject/twint#663]
I have many concurrent nodes/processes (e.g. Docker Swarm/K8s/SLURM) running twint -- how do I store my results in single database? 

Is sqlite good enough for this? Thanks!

**Comment by bryanhpchiang** [comment]
Just realized querying by coordinates doesn’t require a search operator.

**Comment by pielco11** [comment]
I don't know if sqlite is the right choice; I use it because it's light and simple to setup

You might want to save your output to csv or json, and after a scraping session, iterate over those files and save into a larger DB

**Comment by bryanhpchiang** [comment]
Thanks for the response -- I think it might be useful for some tutorial/framework for running many concurrent scrapers at low-cost on one of the cloud platforms with K8S and then storing it for easy querying/analysis.

Will look into this later.
