### ISSUE TITLE
[Question] Issue when downloading many tweets

### ISSUE THREAD

**Issue by Jetstarkiller** [twintproject/twint#664]
Hi, I have been having issues recently with downloading tweets that are fairly large for that day (above 10,000). For this particular command ran (see below) it failed between 20,000 and 45,000 which is still less than one day total. The csv file start at 7pm and fail at 9:14am. This is an issue as I really need all the tweets per day... I am not sure what to do as I am not super skilled in coding... Is there a sleep function available to slow down the download or can I restart from the point of failure? I have tries to include the time where the search is supposed to start like shown in the example but it does not seems to work (This is what I tired. c.Until = "2013-05-18 09:15:00")... 

Below is the command ran and the description of the issue.

### Command Ran
import twint
c = twint.Config()
c.Search = "The Great Gatsby"
c.Until = "2013-05-18"
c.Since = "2012-12-20"
c.Store_csv = True
c.Output = "Output.csv"
twint.run.Search(c);

### Description of Issue

CRITICAL:root:twint.run:Twint:Feed:noDataExpecting value: line 1 column 1 (char 0)
CRITICAL:root:twint.run:Twint:Feed:noDataExpecting value: line 1 column 1 (char 0)
CRITICAL:root:twint.run:Twint:Feed:noDataExpecting value: line 1 column 1 (char 0)
CRITICAL:root:twint.run:Twint:Feed:noDataExpecting value: line 1 column 1 (char 0)
CRITICAL:root:twint.run:Twint:Feed:noDataExpecting value: line 1 column 1 (char 0)
CRITICAL:root:twint.run:Twint:Feed:noDataExpecting value: line 1 column 1 (char 0)
CRITICAL:root:twint.run:Twint:Feed:noDataExpecting value: line 1 column 1 (char 0)
CRITICAL:root:twint.run:Twint:Feed:noDataExpecting value: line 1 column 1 (char 0)
CRITICAL:root:twint.run:Twint:Feed:noDataExpecting value: line 1 column 1 (char 0)
CRITICAL:root:twint.run:Twint:Feed:noDataExpecting value: line 1 column 1 (char 0)
CRITICAL:root:twint.run:Twint:Feed:Tweets_known_error:Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0) [x] run.Feed
[!] if get this error but you know for sure that more tweets exist, please open an issue and we will investigate it!

### Environment Details
I am using Mac OS Catalina, Pycharm for the virtual environment. 

Thank you in advance!

**Comment by pielco11** [comment]
Twint version?

Also I guess it's related to #604

**Comment by Jetstarkiller** [comment]
I am on 2.1.12. I just realized I can upgrade which I am about to do. 

I don't think that it is the same issue than 604 because I have consistent results. it just "fails at different times...

**Comment by Jetstarkiller** [comment]
> I am on 2.1.12. I just realized I can upgrade which I am about to do.
> 
> I don't think that it is the same issue than 604 because I have consistent results. it just "fails" at different times...

ok I guess it is probably related to issue 604. I am going to look deeper in that thread see if I can find a solution there.

**Comment by pielco11** [comment]
Ok, so I kindly ask you to post there your findings, just to keep the stuff organized!
