### ISSUE TITLE
failed to search hashtag using SINCE $ UNTIL

### ISSUE THREAD

**Issue by thu07** [twintproject/twint#665]
Hi

I met a problem when running the following code. In the console, it needs me to input a variable. I don't know where is the problem. Thanks.

import twint

c = twint.Config()
c.Search = "#COVID19"
c.Store_csv = True
c.Output = "#COVID19.0201.csv"
c.Username = "thu"
c.Until = "2020-2-1"
twint.run.Search(c)

**Comment by pielco11** [comment]
```
Since                (string) - Filter Tweets sent since date, works only with twint.run.Search (Example: 2017-12-27).
Until                (string) - Filter Tweets sent until date, works only with twint.run.Search (Example: 2017-12-27).
```
https://github.com/twintproject/twint/wiki/Configuration

**Comment by thu07** [comment]
Thanks for the reply. However, I follow the requirements and the problem is still there. Please check. Thanks.
![image](https://user-images.githubusercontent.com/40651520/74782362-49bb1180-5271-11ea-81a9-ff1c2ae723de.png)

![image](https://user-images.githubusercontent.com/40651520/74782290-22fcdb00-5271-11ea-8929-8d82c8ea9339.png)

**Comment by pielco11** [comment]
What have you done to verify that's a Twint's issue? Because a simple Twitter search shows you that no tweets are returned by that search
