### ISSUE TITLE
[ISSUE] Highly inconsistent results at scale

### ISSUE THREAD

**Issue by bryanhpchiang** [twintproject/twint#666]
I'm running a few thousand batch compute jobs with twint, getting wildly inconsistent results that don't line up what the online advanced search gives. Multiple runs of the same query give differing lengths of results.

Common error is Expecting value: line 1 column 1 (char 0) [x] run.Feed 
Seems that Twitter is rate-limiting requests coming from same place? 

Not sure how to get around this, might need to write my own script

**Comment by pielco11** [comment]
Twint handles the data that Twitter provides

**Comment by bryanhpchiang** [comment]
I think this is just another instance of  https://github.com/twintproject/twint/issues/604. Once I run into the error if I wait for a few minutes I can start scraping again?

**Comment by pielco11** [comment]
I think so, you may want to use different source IPs too

**Comment by bryanhpchiang** [comment]
Can you point me in the right direction to set that up?

**Comment by pielco11** [comment]
Get a proxy and configure Twint accordingly it's configuration file https://github.com/twintproject/twint/wiki/Configuration
