### ISSUE TITLE
Can't get retweets

### ISSUE THREAD

**Issue by clarkking** [twintproject/twint#668]
>Make sure you've checked the following:

- [√] Python version is 3.6;
- [√] Updated Twint with `pip3 install --user --upgrade -e git+https://github.com/twintproject/twint.git@origin/master#egg=twint`;
- [√] I have searched the issues and there are no duplicates of this issue/question/request.

### Command Ran
>Please provide the _exact_ command ran including the username/search/code so I may reproduce the issue.

c = twint.Config()
c.Proxy_host = "127.0.0.1"
c.Proxy_port = 9932
c.Proxy_type = "socks5"
#c.Profile_full = True
c.Username = "ProfBrianCox" 
c.Retweets =  True 
twint.run.Profile(c)

### Description of Issue
>Please use **as much detail as possible.**

if i dont use profile_full, it only returns [!] Twitter does not return more data, scrape stops here.
if i use profile_full, it seems that the proxy doesn't work so it returns
root:twint.get:Tweet:Cannot connect to host twitter.com:443 ssl:True [Connect call failed]
or: CRITICAL:root:twint.feed:Mobile:list index out of range

### Environment Details
>Using Windows, Linux? What OS version? Running this in Anaconda? Jupyter Notebook? Terminal?

Using  windows with v2ray

**Comment by clarkking** [comment]
I tried again on a server，using profile_full without proxy ,it works fine. But i still hope there is a way to get retweets with proxy

**Comment by clarkking** [comment]
I tried again on a server， without proxy and using profile_full，it works fine. 
if i don't use profile_full, I still got [!] Twitter does not return more data, scrape stops here.

**Comment by pielco11** [comment]
If Twitter does not return data, there's nothing much that Twint can do

"Get retweets" feature is very limited, and Twitter does not return them that easy
