### ISSUE TITLE
tweet output error

### ISSUE THREAD

**Issue by xiaowei-xw** [twintproject/twint#673]
# Issue Template
Please use this template!

### Initial Check
Python version is 3.6;
Twint version is the newest

### Command Ran
import twint
c=twint.Config()
c.Username='Airbnb'
c.Custom["tweet"]=['id','username','created_at','date','time','timezone','place','tweet','mentions','urls','replies_count','retweets_count','likes_count','hashtags','cashtags','link']
c.Output='Airbnb2.csv'
c.Store_csv=True

twint.run.Search(c)

### Description of Issue
I'd like to output all the tweets since the account was created, but there is the error when running.

CRITICAL:root:twint.run:Twint:Feed:noDataExpecting value: line 1 column 1 (char 0)
CRITICAL:root:twint.run:Twint:Feed:noDataExpecting value: line 1 column 1 (char 0)
CRITICAL:root:twint.run:Twint:Feed:noDataExpecting value: line 1 column 1 (char 0)
CRITICAL:root:twint.run:Twint:Feed:noDataExpecting value: line 1 column 1 (char 0)
CRITICAL:root:twint.run:Twint:Feed:noDataExpecting value: line 1 column 1 (char 0)
CRITICAL:root:twint.run:Twint:Feed:noDataExpecting value: line 1 column 1 (char 0)
CRITICAL:root:twint.run:Twint:Feed:noDataExpecting value: line 1 column 1 (char 0)
CRITICAL:root:twint.run:Twint:Feed:noDataExpecting value: line 1 column 1 (char 0)
CRITICAL:root:twint.run:Twint:Feed:noDataExpecting value: line 1 column 1 (char 0)
CRITICAL:root:twint.run:Twint:Feed:noDataExpecting value: line 1 column 1 (char 0)
CRITICAL:root:twint.run:Twint:Feed:Tweets_known_error:Expecting value: line 1 column 1 (char 0)

Expecting value: line 1 column 1 (char 0) [x] run.Feed
[!] if get this error but you know for sure that more tweets exist, please open an issue and we will investigate it!

### Environment Details
>Using Windows, Running this in Anaconda-- Jupyter Notebook

**Comment by xiaowei-xw** [comment]
also, I only the tweets created by Airbnb, not including the ones which Airbnb is replying to. what is the code? Thanks a lot.

**Comment by pielco11** [comment]
The tweets that Airbnb is replying to, are made by Airbnb since it's replying


Also #604 . The issue is even pinned
