### ISSUE TITLE
Only get non-reply tweets which start a conversation

### ISSUE THREAD

**Issue by NielsRogge** [twintproject/twint#678]
Hello, thank you for this awesome tool!

Question: is it possible to only get **initial** tweets to a specific account? Typically, customers send questions to a Twitter account, and I just want to scrap all questions which customers send to the account (typically, the account then replies and there's a conversation going on with the customer, but I'm not interested in subsequent tweets of a conversation). 

TDLR: how can I get tweets which are not replies.

**Comment by pielco11** [comment]
AFAIK, it does not exist a parameter for such request. For now, you can scrape the tweets and filter them, keeping only the tweets which have `id = conversation_id`
