### ISSUE TITLE
[QUESTION] Help with getting retweets of a specific tweet_id

### ISSUE THREAD

**Issue by shaanchandra** [twintproject/twint#679]
# Issue Template
Please use this template!

### Initial Check
I have searched the issues and there are no duplicates of this issue/question/request.
Issue @199 was similar but not really what I am looking for.

### Command Ran
None

### Description of Issue
Hi,
First of all, great work with the library!

I searched the given examples in the wiki but could not figure out how to get all the retweets of a particular tweet_id (not user)? 
So if I have a list of tweet_ids, how can I get the retweets of each and store the JSON? 
I am particularly interested in just the user_id of of the users who retweeted this particular tweet.
Any pointers could be helpful.

Thanks!
### Environment Details
I am using Windows10 with conda environment and would like to run python script (not CLI) for this.

**Comment by pielco11** [comment]
You might want to search with `--native-retweets` and specifying the text of the tweet as keyword `-s "\"here the text of the tweet\""`

Please consider that there are (Twitter side) limitations to this feature
