### ISSUE TITLE
[QUESTION] Is there a limit on how many tweets can I scrape with twint? My search always stops at 15 mb.

### ISSUE THREAD

**Issue by FeiPower** [twintproject/twint#682]
### Command Ran
$ twint -s "COVID19" --since 2020-08-01 -o covid19.json --json -ho

### Description of Issue
This error happens: 
CRITICAL:root:twint.run:Twint:Feed:noDataExpecting value: line 1 column 1 (char 0)
CRITICAL:root:twint.run:Twint:Feed:noDataExpecting value: line 1 column 1 (char 0)
CRITICAL:root:twint.run:Twint:Feed:noDataExpecting value: line 1 column 1 (char 0)
CRITICAL:root:twint.run:Twint:Feed:noDataExpecting value: line 1 column 1 (char 0)
CRITICAL:root:twint.run:Twint:Feed:noDataExpecting value: line 1 column 1 (char 0)
CRITICAL:root:twint.run:Twint:Feed:noDataExpecting value: line 1 column 1 (char 0)
CRITICAL:root:twint.run:Twint:Feed:noDataExpecting value: line 1 column 1 (char 0)
CRITICAL:root:twint.run:Twint:Feed:noDataExpecting value: line 1 column 1 (char 0)
CRITICAL:root:twint.run:Twint:Feed:noDataExpecting value: line 1 column 1 (char 0)
CRITICAL:root:twint.run:Twint:Feed:noDataExpecting value: line 1 column 1 (char 0)
CRITICAL:root:twint.run:Twint:Feed:noDataExpecting value: line 1 column 1 (char 0)
CRITICAL:root:twint.run:Twint:Feed:Tweets_known_error:Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0) [x] run.Feed
[!] if get this error but you know for sure that more tweets exist, please open an issue and we will investigate it!

I know for sure there are more than 25,000 tweets about COVID19, and this don't just happen with this particular call, it happens with every single search I try to do. It began after I updated to the latest version of twint. 

Please help me 💃 
### Environment Details
I'm running twint in the Anaconda Prompt.

**Comment by pielco11** [comment]
I don't use Twint as social media monitoring tool so Idk. There are discussions and PRs to find out a solution to this. That error simply means that Twitter is blocking the requests

#604
