### ISSUE TITLE
can I collect only a twitter user's self-posting tweets, not including the tweets relying to other users

### ISSUE THREAD

**Issue by xiaowei-xw** [twintproject/twint#690]
- [] Python version is 3.6;
- [] Updated Twint with `pip3 install --user --upgrade -e git+https://github.com/twintproject/twint.git@origin/master#egg=twint`;
- [] I have searched the issues and there are no duplicates of this issue/question/request.

### Command Ran
import twint
c=twint.Config()
c.Username='wimdu'
c.Custom["tweet"]=['id','username','created_at','date','time','timezone','place','tweet','mentions','urls','replies_count','retweets_count','likes_count']
c.Output='wimdu.csv'
c.Store_csv=True

twint.run.Search(c)

### Description of Issue
I have collected all the tweets of a twitter user, but I only want to analyze the tweets of its self-posting, and the tweets replying to other users shouldn't be included. So is it OK? what should I do?

### Environment Details
>Using Windows, Running this in Anaconda, Jupyter Notebook

**Comment by llunn** [comment]
@xiaowei-xw The [configuration](https://github.com/twintproject/twint/wiki/Configuration) wiki page shows you most of the options.  The [Config class](https://github.com/twintproject/twint/blob/master/twint/config.py) has all of the options available, but does not explain how to use them.  You should check out `Retweets`, `Filter_retweets`, and `Replies` options.

**Comment by pielco11** [comment]
You might want to search for tweets sent by your target to itself so that you get its threads, and search for tweets sent by your target and then (once you got them) filter by the condition `id == conversation_id`

**Comment by xiaowei-xw** [comment]
> @xiaowei-xw The [configuration](https://github.com/twintproject/twint/wiki/Configuration) wiki page shows you most of the options. The [Config class](https://github.com/twintproject/twint/blob/master/twint/config.py) has all of the options available, but does not explain how to use them. You should check out `Retweets`, `Filter_retweets`, and `Replies` options.

thanks a lot. but I haven't yet found the finest path.

**Comment by xiaowei-xw** [comment]
> You might want to search for tweets sent by your target to itself so that you get its threads, and search for tweets sent by your target and then (once you got them) filter by the condition `id == conversation_id`

thanks a lot. I have downloaded all the tweets (Username='wimdu'), and saved as in csv. but I don't understand the condition id == conversation_id, the column id is as the follows. can you  say more in detail and specific?
![tweets](https://user-images.githubusercontent.com/57753444/76698732-5bad9a00-66e1-11ea-94e3-1527b38603ef.PNG)

**Comment by pielco11** [comment]
You are not seeing all the columns because you specified specific fields that you want to save 

Here is your current code
```python
import twint
c=twint.Config()
c.Username='wimdu'
c.Custom["tweet"]=['id','username','created_at','date','time','timezone','place','tweet','mentions','urls','replies_count','retweets_count','likes_count'] #### here is the "problem", just remove this row
c.Output='wimdu.csv'
c.Store_csv=True

twint.run.Search(c)
```

**Comment by xiaowei-xw** [comment]
> You are not seeing all the columns because you specified specific fields that you want to save
> 
> Here is your current code
> 
> ```python
> import twint
> c=twint.Config()
> c.Username='wimdu'
> c.Custom["tweet"]=['id','username','created_at','date','time','timezone','place','tweet','mentions','urls','replies_count','retweets_count','likes_count'] #### here is the "problem", just remove this row
> c.Output='wimdu.csv'
> c.Store_csv=True
> 
> twint.run.Search(c)
> ```

Thank you very much, I have recollected the tweets according to your instructions, and sure enough, I find that there is conversation_id, when id==conversation_id, it was indeed the tweets posted by the user itself, rather than replying to other users.

**Comment by pielco11** [comment]
Great, seems to be solved then :)
