### ISSUE TITLE
Expecting value: line 1 column 1 (char 0) [x] run.Feed

### ISSUE THREAD

**Issue by xiaowei-xw** [twintproject/twint#692]
# Issue Template
Please use this template!

### Initial Check
- [] Python version is 3.6;
- [] Updated Twint with `pip3 install --user --upgrade -e git+https://github.com/twintproject/twint.git@origin/master#egg=twint`;
- [] I have searched the issues and there are no duplicates of this issue/question/request.

### Command Ran
import twint
c=twint.Config()
c.Username='Airbnb'

c.Output='Airbnb.csv'
c.Store_csv=True

twint.run.Search(c)

### Description of Issue
CRITICAL:root:twint.run:Twint:Feed:noDataExpecting value: line 1 column 1 (char 0)
CRITICAL:root:twint.run:Twint:Feed:noDataExpecting value: line 1 column 1 (char 0)
CRITICAL:root:twint.run:Twint:Feed:noDataExpecting value: line 1 column 1 (char 0)
CRITICAL:root:twint.run:Twint:Feed:noDataExpecting value: line 1 column 1 (char 0)
CRITICAL:root:twint.run:Twint:Feed:noDataExpecting value: line 1 column 1 (char 0)
CRITICAL:root:twint.run:Twint:Feed:noDataExpecting value: line 1 column 1 (char 0)
CRITICAL:root:twint.run:Twint:Feed:noDataExpecting value: line 1 column 1 (char 0)
CRITICAL:root:twint.run:Twint:Feed:noDataExpecting value: line 1 column 1 (char 0)
CRITICAL:root:twint.run:Twint:Feed:noDataExpecting value: line 1 column 1 (char 0)
CRITICAL:root:twint.run:Twint:Feed:noDataExpecting value: line 1 column 1 (char 0)
CRITICAL:root:twint.run:Twint:Feed:Tweets_known_error:Expecting value: line 1 column 1 (char 0)

Expecting value: line 1 column 1 (char 0) [x] run.Feed
[!] if get this error but you know for sure that more tweets exist, please open an issue and we will investigate it!

this is the error after running the code. I have checked the similar problems #604, and there are these two paths: (1) changing the twint version-2.1.6/2.1.4; (2) change the UserAgent in get.py.

I have tried them, but there exists the above error. So I don't know what to do next? thanks.

### Environment Details
Windows, Anaconda, Jupyter Notebook

**Comment by pielco11** [comment]
As of now a solution about that issue does not exist. Since you are getting the same error messages and the same behavior, I'd close this issue and keep posting in #604 so that we have a single place to keep the discussion organized
