### ISSUE TITLE
[QUESTION] How to remove line breaks in csv output

### ISSUE THREAD

**Issue by unggulwidy** [twintproject/twint#693]
# Issue Template
Please use this template!

### Initial Check
> If the issue is a request please specify that it is a request in the title (Example: [REQUEST] more features). If this is a question regarding 'twint' please specify that it's a question in the title (Example: [QUESTION] What is x?). Please **only** submit issues related to 'twint'. Thanks.

>Make sure you've checked the following:

- [v] Python version is 3.6;
- [v] Updated Twint with `pip3 install --user --upgrade -e git+https://github.com/twintproject/twint.git@origin/master#egg=twint`;
- [v] I have searched the issues and there are no duplicates of this issue/question/request.

### Command Ran
>Please provide the _exact_ command ran including the username/search/code so I may reproduce the issue.

import twint

c = twint.Config()
c.Username = "infoBMKG" 
c.Format = "Username: {username} | Tweet: {tweet} |" 
c.Store_csv = True 
c.Output = "datasetMentahBMKG33.csv" 
c.Since = "2015-1-1" 
c.Until = "2017-1-1" 
c.Search = "tsunami" 

twint.run.Search(c)

### Description of Issue
>Please use **as much detail as possible.**

There is some problems in the csv file produced. When twint scrapped tweets that use line-breaks, the csv output write it as a line-break too. So, the output of one tweet become two or more lines, not just one straight line in that csv file. Is there any problem with my setup? Or I just need to process that csv file outside twint? How to change that-two-or-more-lines to become just one line?
![line breaks](https://user-images.githubusercontent.com/49548061/76868570-b7228800-6899-11ea-91c4-c1d3180d970f.png)
Please help me, thank you.

### Environment Details
>Using Windows, Linux? What OS version? Running this in Anaconda? Jupyter Notebook? Terminal?

I am using Windows 10, no Anaconda, I am running the code with PyCharm and Python IDLE, it provides the same result.

**Comment by pielco11** [comment]
Output files are `utf-8` encoded, I'd suggest to use something like Libreoffice to read `.csv` files

**Comment by unggulwidy** [comment]
> Output files are `utf-8` encoded, I'd suggest to use something like Libreoffice to read `.csv` files

Thank you, I am using WPS Office and its working fine now.
