### ISSUE TITLE
How can i used twint's CLI on the centos7?

### ISSUE THREAD

**Issue by wooyunwang** [twintproject/twint#696]
# Issue Template
Please use this template!

### Initial Check
> If the issue is a request please specify that it is a request in the title (Example: [REQUEST] more features). If this is a question regarding 'twint' please specify that it's a question in the title (Example: [QUESTION] What is x?). Please **only** submit issues related to 'twint'. Thanks.

>Make sure you've checked the following:

- [] Python version is 3.8;

### Command Ran
>
pip3 install --user --upgrade -e git+https://github.com/twintproject/twint.git@origin/master#egg=twint

### Description of Issue
>
![image](https://user-images.githubusercontent.com/15990552/77226353-a718ea00-6bb2-11ea-8b7f-8630bdaf5fbb.png)

### Environment Details
>
centos7   50G

**Comment by llunn** [comment]
You likely need to install a missing library `libffi-dev`.

**Comment by wooyunwang** [comment]
still the same error.

WARNING: Did not find branch or tag 'origin/master', assuming revision or ref.
  Running command git reset --hard -q origin/master
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/root/yxzh/src/twint/setup.py'"'"'; __file__='"'"'/root/yxzh/src/twint/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info
         cwd: /root/yxzh/src/twint/
    Complete output (11 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/usr/local/python38/lib/python3.8/site-packages/setuptools/__init__.py", line 20, in <module>
        from setuptools.dist import Distribution, Feature
      File "/usr/local/python38/lib/python3.8/site-packages/setuptools/dist.py", line 35, in <module>
        from setuptools import windows_support
      File "/usr/local/python38/lib/python3.8/site-packages/setuptools/windows_support.py", line 2, in <module>
        import ctypes
      File "/usr/local/python38/lib/python3.8/ctypes/__init__.py", line 7, in <module>
        from _ctypes import Union, Structure, Array
    ModuleNotFoundError: No module named '_ctypes'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by wooyunwang** [comment]
What is it mean about this error?↓↓↓
WARNING: Did not find branch or tag 'origin/master', assuming revision or ref.

**Comment by wooyunwang** [comment]
Did you delete some branches?

**Comment by pielco11** [comment]
Hmmm strange because `origin/master` exists for sure

**Comment by llunn** [comment]
> Did not find branch or tag 'origin/master', assuming revision or ref

You are getting this warning because there is indeed no tag or branch called `origin/master`;  `https://github.com/twintproject/twint.git` ***is*** the origin.

The source should be: `git+https://github.com/twintproject/twint.git@master#egg=twint`

I think this will not address your error message though and it is likely related to not having a library in your PATH environment variable or a missing library.

What version of python are you using?

**Comment by wooyunwang** [comment]
But your course command is “pip3 install --user --upgrade -e git+https://github.com/twintproject/twint.git@origin/master#egg=twint”

**Comment by wooyunwang** [comment]
Well, when i use the new commond ”pip3 install --user --upgrade -e git+https://github.com/twintproject/twint.git@master#egg=twint“, it will not display the yellow warming, but still display the red error.
My python's version is 3.8.2.

**Comment by wooyunwang** [comment]
and python also 64bit

**Comment by pielco11** [comment]
@wooyunwang so I tested and that command does not seem to work anyone. My bad for not checking it.

May you run this and let me know, please?
 `python3.7 -m pip install --user --upgrade git+https://github.com/twintproject/twint.git#egg=twint`

(Doing `python3.7 -m pip` is the same as doing `pip3`)

**Comment by wooyunwang** [comment]
cause my python is 3.8.2, so i type this command
"python3 -m pip install --user --upgrade git+https://github.com/twintproject/twint.git#egg=twint"
and then, system display the same error ↓↓↓

    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-xe9tc9qs/twint/setup.py'"'"'; __file__='"'"'/tmp/pip-install-xe9tc9qs/twint/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-xe9tc9qs/twint/pip-egg-info
         cwd: /tmp/pip-install-xe9tc9qs/twint/
    Complete output (11 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/usr/local/python38/lib/python3.8/site-packages/setuptools/__init__.py", line 19, in <module>
        from setuptools.dist import Distribution
      File "/usr/local/python38/lib/python3.8/site-packages/setuptools/dist.py", line 34, in <module>
        from setuptools import windows_support
      File "/usr/local/python38/lib/python3.8/site-packages/setuptools/windows_support.py", line 2, in <module>
        import ctypes
      File "/usr/local/python38/lib/python3.8/ctypes/__init__.py", line 7, in <module>
        from _ctypes import Union, Structure, Array
    ModuleNotFoundError: No module named '_ctypes'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by pielco11** [comment]
Yeah I'm running python3.7, but it work too with python3 or python3.8. To be sure you can run `python3 --version` and then you see which version is called.

That said, it seems that you are missing the `_ctypes` module. Searching around it seems that some users resolved as @llunn suggested, but others not.

May you try with python3.7?

**Comment by wooyunwang** [comment]
i install libffi-dev under pythton3.8 just now, but still the same error.
Well, i must to go home now,  decide to try 3.7 tomorrow

**Comment by wooyunwang** [comment]
python3.7 on centos still fail.
When i try debian9 & python3.7.5 , the CLI can run now!!!
But...emmn....i find some new questions, i will create a new issue soom.
