### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by icrnomarkovic** [twintproject/twint#700]
- Python version is 3.6.10

### Command Ran
> pip3 install twint
OR
> git clone https://github.com/twintproject/twint.git
> cd twint
> pip3 install . -r requirements.txt

### Description of Issue

![image](https://user-images.githubusercontent.com/62644318/77526135-66f38900-6e8a-11ea-9421-3d5c14d779a7.png)

### Environment Details
> Linux Ubuntu - running in Anaconda

**Comment by pielco11** [comment]
As you may see the problem is related to the installation of pandas, not twint itself.

That said, are you using a compatible version of Python?
