### ISSUE TITLE
[REQUEST] Displaying date, time and time zone as one datestring

### ISSUE THREAD

**Issue by ilanb1996** [twintproject/twint#702]
### Description of Issue
Hey i've started using twint (awesome library!) and i've run into an issue.
When I save the data to a file with json format the time, date and time zone are all different fields.
I would like to have an option in the config that would make all 3 of them one datestring field.

### Environment Details
Using windows 10 with python 3.8.2 version

**Comment by pielco11** [comment]
You can save the data in a temporary json file, and as the scraping session ends you just create a new file with the format of your choice. This is really really easy to achieve and even for tons of tweets it will be done in a few ms

**Comment by juliobguedes** [comment]
Hi guys! I just ran into an issue by thinking that `timestamp` would return the entire date + time + timezone, and I'm having to run every single query again. It was an error in my understanding, but I think that this is a valid issue and it would be implemented quite easily. May I?

**Comment by ilanb1996** [comment]
> 
> 
> You can save the data in a temporary json file, and as the scraping session ends you just create a new file with the format of your choice. This is really really easy to achieve and even for tons of tweets it will be done in a few ms

I'm having trouble implementing this solution. Is it done with the `twint.Config.custom` field? if so i dont understand how it works at all.
Could you please help me understand it a little bit better?

**Comment by juliobguedes** [comment]
Hi, @ilanb1996. Since @pielco11 has not yet answered your question, let me explain what I understood from what he said:
When you are saving the data as a `.json` file, you can always process it one more time after saving it for the first time. The library already provides you every information that you would need to create your own field that contains the date, time and timezone all together, and you would only need to concatenate the three strings or something like this.

Lets say that the .json file that you saved the tweets follows this format:
```json
{
    "tweets": [{
        "id": 01234,
        "username": "bbcnews",
        "datestamp": "2020-01-22",
        "timestamp": "16:50:25",
        "timezone": "GMT -0300"
    },
    "Other tweets here...",
    ]
}
```

You would need to write a Python program that opens this json file and modifies each object adding another field. The program would be something like this:

```python
import json

filename = 'my_awesome.json'
with open(filename, 'r') as json_file:
    my_json = json.load(json_file)

num_tweets = len(my_json['tweets'])
for i in range(num_tweets):
    current_tweet = my_json['tweets'][i]
    complete_time = current_tweet['datestamp'] + " " + current_tweet['timestamp'] + " " + current_tweet['timezone']
    current_tweet['completeTime'] = complete_time
    my_json['tweets'][i] = current_tweet

with open(filename, 'w') as json_file:
    json.dump(my_json, json_file)
```

You can read more about loading json files [in this website](https://www.programiz.com/python-programming/json). Feel free to ask more questions.

**Comment by ilanb1996** [comment]
> 
> 
> Hi, @ilanb1996. Since @pielco11 has not yet answered your question, let me explain what I understood from what he said:
> When you are saving the data as a `.json` file, you can always process it one more time after saving it for the first time. The library already provides you every information that you would need to create your own field that contains the date, time and timezone all together, and you would only need to concatenate the three strings or something like this.
> 
> Lets say that the .json file that you saved the tweets follows this format:
> 
> ```json
> {
>     "tweets": [{
>         "id": 01234,
>         "username": "bbcnews",
>         "datestamp": "2020-01-22",
>         "timestamp": "16:50:25",
>         "timezone": "GMT -0300"
>     },
>     "Other tweets here...",
>     ]
> }
> ```
> 
> You would need to write a Python program that opens this json file and modifies each object adding another field. The program would be something like this:
> 
> ```python
> import json
> 
> filename = 'my_awesome.json'
> with open(filename, 'r') as json_file:
>     my_json = json.load(json_file)
> 
> num_tweets = len(my_json['tweets'])
> for i in range(num_tweets):
>     current_tweet = my_json['tweets'][i]
>     complete_time = current_tweet['datestamp'] + " " + current_tweet['timestamp'] + " " + current_tweet['timezone']
>     current_tweet['completeTime'] = complete_time
>     my_json['tweets'][i] = current_tweet
> 
> with open(filename, 'w') as json_file:
>     json.dump(my_json, json_file)
> ```
> 
> You can read more about loading json files [in this website](https://www.programiz.com/python-programming/json). Feel free to ask more questions.

Thank you for the detailed reply @juliobguedes 
That's what I was afraid of, but I did find a better solution (IMO). I saw I can actually overwrite the JSON parsing method of twint and then ill get the tweets in a form of a python object and I could format them as I want in before I would save them to a file.

Closing the issue since I found a solution.
Thank you everybody
