### ISSUE TITLE
[QUESTION] How to get follower / following user ids instead of screen names 

### ISSUE THREAD

**Issue by s2t2** [twintproject/twint#704]
### Command Ran

```py
    config = twint.Config()
    config.Username = SCREEN_NAME
    config.Limit = 20
    config.Hide_output = True
    config.Store_object = True
    #config.User_full = True # seems to be a lot slower
    config.Store_object_follow_list = []
    print(config)

    twint.run.Following(config)
    # takes a few requests
    # seeing the occasional "CRITICAL:root:twint.feed:Follow:IndexError"

    print("FOLLOWS LIST:", twint.output.follows_list) #> []
    print("USERS LIST:", twint.output.users_list) #> []
    print("STORED OBJECT FOLLOWS LIST:", config.Store_object_follow_list) #> yay, a list of screen names!
```

### Description of Issue

The code above provides a list of screen names who the user follows in the `config.Store_object_follow_list`, but is there a way to return their user ids instead?

I tried a few approaches setting `config.User_full = True`, but it seems to be a lot slower. And I was hoping to use the faster approach.

### Environment Details

Mac OS, inside anaconda environment with Python 3.7

**Comment by s2t2** [comment]
I also tried a few approaches using `config.Custom` like `config.Custom = ['id']` and `config.Custom["user"] = ['id']` but neither seems to work.

**Comment by llunn** [comment]
Retrieving only the user id's is not currently possible without retrieving the full profile of the users being followed by or are following the user specified in your search.  

The technical reason behind this is that Twitter returns permalinks for these lists.  Specifying `User_full = True` will instruct twint to retrieve those permalinks and populate the `output.users_list` list with the profiles.
