### ISSUE TITLE
[QUESTION] Where is the .csv file saved to in Windows 10?

### ISSUE THREAD

**Issue by AlyeskaBear** [twintproject/twint#705]
I just came across this wonderful tool today and like it very much. But after I tried the following code in Commend Prompt in Windows 10
 `twint -u CDCgov --since "2020-03-01 22:00:01" --limit 20 --followers --stats -o aa.csv --csv `

I have no idea which folder the "aa.csv" file is saved into. I searched by the file name in my local machine but did not find it. I also tried to find the answer online but nothing comes out. Can someone please help me on this simple (maybe, naive) question? I will greatly appreciate it.

**Comment by llunn** [comment]
In this example, it should exist in the same directory that you executed twint from.

**Comment by AlyeskaBear** [comment]
> In this example, it should exist in the same directory that you executed twint from.

Thank you! It turns out that I ran the code in a server drive. That is why I could not find it in my local drive. A really obvious mistake. :-(
