### ISSUE TITLE
[QUESTION] Critical error on high-volume twint -s query

### ISSUE THREAD

**Issue by ghostbeagle** [twintproject/twint#706]
### Command Ran

`twint -s "hydroxychloroquine" -o try2_hc.csv --csv`

### Description of Issue

Hello - I ran the command above on 04/01/2020 and the script consistently throws an error once the tweets reach back to 03/30/2020. 

> [!] if get this error but you know for sure that more tweets exist, please open an issue and we will investigate it!

I assume this may be an issue with searching for a query that returns a high volume of tweets, but would appreciate any insight you could lend. I'm running this from a terminal on Mac OSx.

**Comment by pielco11** [comment]
This issue has been already reported #603 

As of now, Twint is not suggested for SNA
