### ISSUE TITLE
twint -u uname --followers stopped working after Twitter starts to need login to see followers

### ISSUE THREAD

**Issue by JunhaoWang** [twintproject/twint#708]
# twint -u uname --followers stopped working after Twitter starts to need login to see followers

### Command Ran
>twint -u wjhtomwjh --followers 

### Description of Issue
>twint -u uname --followers stopped working after Twitter starts to need login to see followers

### Environment Details
>Linux Ubuntu Python3.7 Terminal

**Comment by llunn** [comment]
I just ran the command you posted using a fresh install of twint:

```bash
python -m venv venv
source venv/bin/activate
pip install twint
twint -u wjhtomwjh --followers
```

Output:
<img width="571" alt="image" src="https://user-images.githubusercontent.com/35606856/78386517-14b21680-75b4-11ea-9f3b-2929628a9dc7.png">

Actual twitter page:
![image](https://user-images.githubusercontent.com/35606856/78386631-4e831d00-75b4-11ea-9485-379692c47111.png)

**Comment by BonfaceKilz** [comment]
@JunhaoWang I also ran the same and I got what @llunn is getting that is:
```
CRITICAL:root:twint.feed:Follow:IndexError
UMichEIM
ilynn0802
MichiganTray
GoShmacked
CreditZippo
CRITICAL:root:twint.feed:Follow:IndexError
```
Perhaps it's a geographical thing? That's a very wild guess.

**Comment by pielco11** [comment]
I'm CET, got the same results

**Comment by BonfaceKilz** [comment]
I think @pielco11 we should go ahead and close this unless @JunhaoWang can provide more info. Wdyt?
