### ISSUE TITLE
[QUESTION] How to scrap tweets with two (or more) hashtag (or word) used in the same tweet?

### ISSUE THREAD

**Issue by eliasbitencourt** [twintproject/twint#709]
# [QUESTION] How to scrap tweets with two (or more) hashtag (or word) used in the same tweet?
Hello every body, I'm trying to scrap only tweets that contain two words (or hashtags) used together (eg. extract tweets that contain 'covid' and 'fitbit'). I've already tried this syntax bellow without success. You guys know any kind of way out to this situation?

>twint  -s fitbit; -s COVID -l en --since 2020-01-01 --until 2020-04-02 --count --stats  --o fitbir_covid.csv --csv

>twint  -s fitbit, -s COVID -l en --since 2020-01-01 --until 2020-04-02 --count --stats  --o fitbir_covid.csv --csv

>twint  -s fitbit -s COVID -l en --since 2020-01-01 --until 2020-04-02 --count --stats  --o fitbir_covid.csv --csv

Im using Mac OS Sierra, running twint in PyCharm terminal

thanks in advance,
keep safe.

**Comment by llunn** [comment]
You can specify boolean based search strings.

Try: `"#fitbit AND #covid" or `"fitbit AND covid"`

**Comment by AlyeskaBear** [comment]
I have the same question. But when I tried 

`twint -search "fitbit AND covid" --stats --since "2020-01-01 00:00:01" --until "2020-03-26 00:00:01" --limit 10`

an error message was returned as 

> twint: error: unrecognized arguments: fitbit AND covid

**Comment by Shanuchauhan** [comment]
try twint -s "fitbit covid"
It will give you the correct results.I have checked it.

**Comment by twollnik** [comment]
Hi @llunn @Shanuchauhan @eliasbitencourt 

I have a similar question and would love to get your answer. I would like to find all tweets that contain a substring consisting of multiple words. For example, find all tweets that contain the substring "Donald Trump". Is this possible with `twint`?

As far as I understand `-s "Donald Trump"` will yield all tweets containing "Donald" and "Trump" without taking into account if the words occur right behind each other.

I would really appreciate your help on this.

Kind regards, Tom

**Comment by llunn** [comment]
I am not sure how to do this using the command line, but by code you simply include the term as a string inside your search criteria (I.e a nested string). You may was to try that from the command line with and without escape characters

**Comment by twollnik** [comment]
Thanks!
