### ISSUE TITLE
List error memory to obtain followers, duplicate objects

### ISSUE THREAD

**Issue by MrHereric** [twintproject/twint#711]
# Issue Template
Please use this template!

### Initial Check
> If the issue is a request please specify that it is a request in the title (Example: [REQUEST] more features). If this is a question regarding 'twint' please specify that it's a question in the title (Example: [QUESTION] What is x?). Please **only** submit issues related to 'twint'. Thanks.

>Make sure you've checked the following:

- [x] Python version is 3.6;
- [x] Updated Twint with `pip3 install --user --upgrade -e git+https://github.com/twintproject/twint.git@origin/master#egg=twint`;
- [X] I have searched the issues and there are no duplicates of this issue/question/request.

### Command Ran
>Please provide the _exact_ command ran including the username/search/code so I may reproduce the issue.

import twint
c = twint.Config()
c.Username = "testing"
c.Store_object = True
c.User_full = True

#Extract followers
twint.run.Followers(c)

#Save it to a list
target_followers = twint.output.users_list

with open('@'+c.Username+'-Seguidores.csv','w') as output:
    output.write('usuario,username,name,followers, following, tweets, creacion cuenta\n')
    for u in target_followers:
        output.write('{},{},{},{},{},{},{}\n'.format(c.Username,u.username, u.name, u.followers, u.following, u.tweets, u.join_date))

### Description of Issue
>Please use **as much detail as possible.**

It show 2 times the same object in the list, BUT I install the version 2.1.15 and it works normal (no duplicates)

### Environment Details
>Using Windows, Linux? What OS version? Running this in Anaconda? Jupyter Notebook? Terminal?

Mac OS X Catalina (10.15.4)
Visual Studio Code (1.44.0)
Terminal
Python 3.5

Attached Error with version 2.1.18 and without error (twint version 2.1.15)

<img width="1480" alt="Without Error" src="https://user-images.githubusercontent.com/55793553/78994462-8295a980-7b83-11ea-999a-9ae3a30dcddf.png">
<img width="1457" alt="With Error" src="https://user-images.githubusercontent.com/55793553/78994466-84f80380-7b83-11ea-8055-0aa746a54189.png">

**Comment by pielco11** [comment]
Hi, I saw your message around, I guess you are still the same guy. Sorry for the late but really busy days

Anyway, pushed a fix and now pushing to Pip the new version (v.2.1.19)
