### ISSUE TITLE
[REQUEST] Getting additional information while searching for tweets using a particular hashtag.

### ISSUE THREAD

**Issue by Sudhandar** [twintproject/twint#713]
While searching for tweets using a particular hashtag, is it possible to get information about the users who had the highest engagement or retweets or likes  in that hashtag.

eg: Im scraping tweets under the hashtag #covid 

- Can I get a list of top 20 users having the highest number of retweets while using the hashtag #covid 

The number of retweets is just an example. Can we get information similar to that like users with  most number of likes or must number of tweets using that particular hashtag.

It will be very useful for doing exploratory data analysis.

**Comment by pielco11** [comment]
First you should get the tweets, do some statistics (sum of # of retweets for each user), and then sort
