### ISSUE TITLE
Unable to save User object returned from Followers method into a json file

### ISSUE THREAD

**Issue by Sakshimakkar** [twintproject/twint#716]
l='some_user'
c = twint.Config()
c.Store_object = True
c.User_full = True
c.Username = l

twint.run.Followers(c)
foll = twint.output.users_list

with open(os.path.join(l+'.json'), 'w') as F:
    F.write(json.dumps(foll))

I am unable to save this as JSON. It is giving error as "TypeError: Object of type user is not JSON serializable".

**Comment by pielco11** [comment]
`twint.output.users_list` is a list, so you should iterate over it with a for loop

**Comment by Sakshimakkar** [comment]
> `twint.output.users_list` is a list, so you should iterate over it with a for loop

On printing the elements of that list, I am getting "<twint.user.user object at 0x7f1f7f1bfeb8>" as output. I need the exact values that get printed on screen when we call the function.

**Comment by SanketDG** [comment]
FYI, this is because `user.py` doesn't have a `__repr__` method.

**Comment by pielco11** [comment]
@Sakshimakkar here are the attributes https://github.com/twintproject/twint/wiki/User-attributes#attributes

You call attributes with the dot notation

**Comment by Sakshimakkar** [comment]
> @Sakshimakkar here are the attributes https://github.com/twintproject/twint/wiki/User-attributes#attributes
> 
> You call attributes with the dot notation

That Worked. Thank You :)

**Comment by mspanish** [comment]
Calling values with dot notation is a miserable way to do this. I find it hard to believe there is not a more efficient way!
