### ISSUE TITLE
[QUESTION] How can I limit the search query using today's date?

### ISSUE THREAD

**Issue by danieleperera** [twintproject/twint#728]
- [ok] Python version is 3.6;

- [ok] Updated Twint with `pip3 install --user --upgrade -e git+https://github.com/twintproject/twint.git@origin/master#egg=twint`;
- [ok] I have searched the issues and there are no duplicates of this issue/question/request.

I'm trying to scrape twitter daily, so I thought of creating a cronjob which collects tweets regarding a certain keyword. As it's a daily cronjob I don't want to see the tweets from yesterday's cronjob. 
I was wondering if there is a way to limit the search only for today's date or do I have to parse the datetime?

Thanks

**Comment by Aaronzinhoo** [comment]
The arg `since` should be what you are looking for. You can find an example in the README.

**Comment by danieleperera** [comment]
Thanks
