### ISSUE TITLE
[Question] Search Only Tweets

### ISSUE THREAD

**Issue by scraperhelp** [twintproject/twint#729]
When I am searching using #Hashtags then it pulls tweets with that Hashtag. BUT if I use a term as a keyword it is pulling names with that term as well... How can I limit it so it only searches the Tweets for that search term? 
Ex. "#burger" pulls #burger related tweets only. but with "burgers" its also pulling user with name burger. Any way to limit it so that "burger" only searches for tweets with #burger or burger in their tweets.

**Comment by pielco11** [comment]
You should get the tweets, first, and then iterate over them and do some "filtering" to exclude the ones that don't match
