### ISSUE TITLE
Min_Tweets configuration is not working

### ISSUE THREAD

**Issue by Sudhandar** [twintproject/twint#731]
I want to get top 100 tweets for the hashtag #KimJongUn filtered based on minimum number of likes say 1000. I ran the following commands,

Python 3.7
twint  updated from master
Have searched issues without finding anything

Commands run>

`c= twint.Config() `
`c.Search = "#KimJongUn"`
`c.Min_Likes = 1000`
`c.Pandas = True`
`c.Limit = 100`
`twint.run.Search(c)`
`Tweets_df = twint.storage.panda.Tweets_df
`
But instead of getting tweets filtered by the number of likes, Im getting last 100 tweets tweeted using this hashtag, sorted based on time and not filtered based on minimum number of likes. Its not required in my case to get all the 50k tweets for a particular hashtag.What if there are 9M tweets. Its impossible for me to scrape all of them. Please let me know the fix for this issue.

**Comment by pielco11** [comment]
`c.Min_likes`
