### ISSUE TITLE
I want to only crawl English tweets, how to filter other types of language

### ISSUE THREAD

**Issue by RachelLYY** [twintproject/twint#758]
# Issue Template
### Description of Issue
I want to crawl only English tweets, and I see twitter provides api of detect language, can twint use twitter api, or detect language?

### Environment Details
>Using Windows, Running this in Anaconda.

**Comment by benzaked** [comment]
you can just do it with c.Lang = "en"
for example : 
import twint
c = twint.Config()
c.Lang = "en"
twint.run.Search(c)

**Comment by RachelLYY** [comment]
> you can just do it with c.Lang = "en"
> for example :
> import twint
> c = twint.Config()
> c.Lang = "en"
> twint.run.Search(c)

Thanks a lot!
