### ISSUE TITLE
[QUESTION] Is it possible to get a tweet object from just its id?

### ISSUE THREAD

**Issue by aksub99** [twintproject/twint#771]
I know just the id of a tweet. Is there any way I can get the twint tweet object corresponding to this tweet? I don't know the username of the user beforehand.

**Comment by aksub99** [comment]
To explain my use case a bit further,

I have **tweet 1**. Suppose **tweet 1** is a reply to **tweet 2**. I am trying to obtain information about **tweet 2** from just **tweet 1**.

I've managed to get the conversation_id of **tweet 1** and am trying to obtain **tweet 2** using this. Hope this explains my use case a bit better.

**Comment by neon-ninja** [comment]
Sounds like you want to hydrate tweets - you can use twarc for that https://github.com/DocNow/twarc

**Comment by aksub99** [comment]
@neon-ninja Thanks for your response. Yes, that should do it!
Closing the issue.
