### ISSUE TITLE
No user information is received with LookUp function [Urgent]

### ISSUE THREAD

**Issue by DenizDalkilic10** [twintproject/twint#772]
Running on Twint 2.1.20 and Python 3.7.5

Twint does not return any info about a user with LookUp function. Both storing as dataframe and as user object gives empty results. I am on Windows, everything was fine yesterday but today no user information can be received, although tweets can be fetched...

**Comment by SpencerFlow** [comment]
@calebglawson Committed a fix yesterday to scrape data by Usernamed - I was able to leverage his solution to issue #767.

In get.py change line 183 to the following:
`response = await Request(url, headers={"X-Requested-With": "XMLHttpRequest"}, connector=_connector)`

I don't fully understand why this works but this works for me!

**Comment by DenizDalkilic10** [comment]
Thanks for your reply! But you mean 182 right? Because there is a variable called soup in line 183...

**Comment by elamje** [comment]
I think that's what he meant. After you update that line of code, how do you build a fresh version and bind it to the "twint" cli command?

**Comment by SpencerFlow** [comment]
> I think that's what he meant. After you update that line of code, how do you build a fresh version and bind it to the "twint" cli command?

I'm just using the twint library but you should be able to do ```python setup.py install``` from the twint repo directory after making your changes.

**Comment by aksub99** [comment]
I got this fixed by adding:
```
elif hasattr(config.Store_object_users_list, 'append'):
            config.Store_object_users_list.append(user)
```
below line 196 in `output.py`.

**Comment by pielco11** [comment]
Please update your local package with `pip3 install --user --upgrade git+https://github.com/twintproject/twint.git@origin/master#egg=twint`

I'll push a new version to PyPI soon, in the mean time please do as suggested above
