### ISSUE TITLE
Still cannot get user info after editing the get.py following #769

### ISSUE THREAD

**Issue by Cheryl520** [twintproject/twint#775]
I'm getting user information these days but i noticed it suddenly gave error messgages of 
**"CRITICAL:root:twint.get:User:'NoneType' object is not subscriptable"** this morning. And i noticed that there's change on the twitter end and there's change in the 'get.py'.

I followed the modification by deleting:
`    r = await Request(url)`
and adding:
`    r = await Request(url, headers={"X-Requested-With": "XMLHttpRequest"})`
by editing the 'get.py' manually.

But it still doesn't work since **"CRITICAL:root:twint.get:User:'NoneType' object is not subscriptable"** still comes out.

**Comment by kijames653** [comment]
Getting the same issue this morning :(

**Comment by bulucemonkey** [comment]
twitter's page which about use "user_id" to get user info   is change ,maybe twint need to change the way, 'soup.find("a", "fn url alternate-context")["href"].replace("/", "")' need to fix,it isn't worked.

**Comment by Cheryl520** [comment]
I have solved this problem by editing two places in the 'get.py' :

**change line 163 to :**
`r = await Request(url, headers={"X-Requested-With": "XMLHttpRequest"})`
(refer to #769 )

**change line 182 to :**
`response = await Request(url, headers={"X-Requested-With": "XMLHttpRequest"}, connector=_connector)`
(refer to #772 )

**Comment by bulucemonkey** [comment]
thanks , your answer is rigtht

**Comment by kijames653** [comment]
This is solved the issue; **however**, getting the same error when using with other options like "twint -u account_name --profile-full"

Any thought please !

**Comment by pielco11** [comment]
Patch merged, please update with `pip3 install --user --upgrade git+https://github.com/twintproject/twint.git@origin/master#egg=twint`

**Comment by mikaelyh** [comment]
It was working until yesterday,
but something else has been broken.

Someone having an idea ?

**Comment by pielco11** [comment]
@mikaelyh solution in #863
