### ISSUE TITLE
-u "username" no longer works while -s "something" still works.

### ISSUE THREAD

**Issue by PascalLeDeveloppeur** [twintproject/twint#780]
# Issue Template
Please use this template!

### Initial Check
> If the issue is a request please specify that it is a request in the title (Example: [REQUEST] more features). If this is a question regarding 'twint' please specify that it's a question in the title (Example: [QUESTION] What is x?). Please **only** submit issues related to 'twint'. Thanks.

>Make sure you've checked the following:

- [] Python version is 3.6;
- [] Updated Twint with `pip3 install --user --upgrade -e git+https://github.com/twintproject/twint.git@origin/master#egg=twint`;
- [] I have searched the issues and there are no duplicates of this issue/question/request.

### Command Ran
twint -u "LocksyBe"

### Description of Issue
Absolutely nothing happened

### Environment Details
Using Linux mint

python version: 3.8.2

**Comment by PascalLeDeveloppeur** [comment]
Oops!
Updated with :
pip3 install --user --upgrade -e git+https://github.com/twintproject/twint.git@origin/master#egg=twint;

Now it works

**Comment by kijames653** [comment]
> Oops!
> Updated with :
> pip3 install --user --upgrade -e git+https://github.com/twintproject/twint.git@origin/master#egg=twint;
> 
> Now it works

I have tried this one but still not working. I am using python 3.7.6 
btw, last week was working perfectly.

Any help please!
