### ISSUE TITLE
Favorites does not work

### ISSUE THREAD

**Issue by yunusemrecatalcam** [twintproject/twint#805]
I have checked the followings
- Python version is 3.6;
- Updated Twint with `pip3 install --user --upgrade -e git+https://github.com/twintproject/twint.git@origin/master#egg=twint`;
- I have searched the issues and there are no duplicates of this issue/question/request.

I checked previous issues and found #781 but it was the time twitter user profiles couldn't be reached after a UI update and it allready solved.

### Command Ran
twint -u tk_tr --favorites

### Description of Issue
twint doesn't return favorites with the command above, it prints the log below; 
CRITICAL:root:twint.feed:Mobile:list index out of range
CRITICAL:root:twint.feed:Mobile:list index out of range

### Environment Details
Using linux, Ubuntu 18.04. Also checked with the source code and got the same error.

I checked and saw that twitter website doesn't allow to see favorites without login. And I am thinking that these two are related to each other.

Thankss!

**Comment by tarungog** [comment]
seconding this. twint favorites sometimes works, but rarely. 

Get same error:
`CRITICAL:root:twint.feed:Mobile:list index out of range`

**Comment by yunusemrecatalcam** [comment]
I am developing a patch for this and I'll make a pull request soon

**Comment by yunusemrecatalcam** [comment]
Now it's done! We can fetch tweet id, tweet texts and dates now. 
@pielco11 can you give me permission to push a new branch?

**Comment by inactivist** [comment]
> Now it's done! We can fetch tweet id, tweet texts and dates now.
> @pielco11 can you give me permission to push a new branch?

Why not submit a pull request for review?

**Comment by yunusemrecatalcam** [comment]
Sorry, my bad. I've submitted the pull request. [](https://github.com/twintproject/twint/pull/826)

**Comment by pielco11** [comment]
Just merged, thank you a lot for this! :heart:

**Comment by yunusemrecatalcam** [comment]
Happy to contribute!
