### ISSUE TITLE
CRITICAL:root:twint.get:User:'NoneType' object is not subscriptable appears again

### ISSUE THREAD

**Issue by Cheryl520** [twintproject/twint#806]
### Initial Check
> If the issue is a request please specify that it is a request in the title (Example: [REQUEST] more features). If this is a question regarding 'twint' please specify that it's a question in the title (Example: [QUESTION] What is x?). Please **only** submit issues related to 'twint'. Thanks.

>Make sure you've checked the following:

- [] Python version is 3.7;
- [] Updated Twint with `pip3 install --user --upgrade -e git+https://github.com/twintproject/twint.git@origin/master#egg=twint`;
twint-2.1.20
- [] I have searched the issues and there are no duplicates of this issue/question/request.

### Command Ran
```
u = twint.Config()
u.Username = 'boyblu_monkey'
u.User_full=True
user_filename = 'username1_profile.csv'
u.Output = user_filename
u.Store_csv = True

twint.run.Lookup(u)

```
(Just give an example for one username however actually im running this in a for loop.)
### Description of Issue
'CRITICAL:root:twint.get:User:'NoneType' object is not subscriptable'  appears again.
1 week or so before it still works fine. 
However i found the twitter-scraper package : https://github.com/bisguzar/twitter-scraper still can work. Since I want to make my previously scrapped file consistent, I would like to stick to twint to scrape user profile information.

Is the twitter end changing again?

### Environment Details
>Using Windows, Running this in Anaconda Jupyter Notebook

**Comment by YikSanChan** [comment]
@Cheryl520 Hi I run into the same issue, did you address it? If so, do you mind sharing how?

**Comment by Cheryl520** [comment]
> @Cheryl520 Hi I run into the same issue, did you address it? If so, do you mind sharing how?

Hello! I changed to another computer and it works now. Not quiet sure what happened.

**Comment by Sue-Fwl** [comment]
I have the same problem and couldn't find a solution, and I'm running the example provided by twint:

import twint

# Configure
c = twint.Config()
c.Username = "realDonaldTrump"
c.Search = "I hate you"

#First run returned with 2 tweets, second run I get the same error in this issue! and no matter what I clear or restart in the program nothing changes.
