### ISSUE TITLE
c.Search doesnot work in for loop for multiple words

### ISSUE THREAD

**Issue by Poohi5** [twintproject/twint#811]
# I have a list of events and I need to scrape tweets for these events. But c.Search is not working with for loop. 
> Here is my code, please have a look at it

```
for event in tqdm(event_list):
    c = twint.Config()
    c.Search = event
    c.Lang = "en"
    c.Pandas = True
    c.Near = "San Jose"
    c.Hide_output = True
    twint.run.Search(c)
    #Datatframe   
    df = twint.storage.panda.Tweets_df    

```

### Environment Details
>Using Windows,

@pielco11

**Comment by xxristoskk** [comment]
@Poohi5 
Yes, I was having some troubles with this as well. It used to work just fine, but I think Twitter has made some changes that limit what Twint can actually scrape. The only way I got it to work with limited results, is to search one item at a time, saving the results for each search. It is tedious, but you could wrap all the operations in a while loop and create a prompt to run another search. For example:

`running = True
while running:
    c = twint.Config()
    c.Search = event
    c.Lang = "en"
    c.Pandas = True
    c.Near = "San Jose"
    c.Hide_output = True
    twint.run.Search(c)
    #Datatframe   
    df = twint.storage.panda.Tweets_df

    exit_prompt = input("Do another search?(y/n): "
    if exit_prompt == "n":
        running = False
    else:
        continue`

Unfortunately that is not effective if you are searching for a lot of events. Please let me know if you find any other work around for this issue!

**Comment by Poohi5** [comment]
> @xxristoskk, I think the problem is while passing the events/any term to c.Search, only the words are passed and the quotes enclosing the word is not passed. 
> c.search requires the term to be searched to be included in quotes and maybe that is the reason it is not working.
> For example, c.Search = "twint" will work but c.Search = twint (without quotes) won't work
> @pielco11 could you please look into this issue?

**Comment by Poohi5** [comment]
@xxristoskk 
I found a work around for this. Just append quotes to the list of terms to be searched. 

```
df = []
for value in tqdm(event_list):
    #valuenew = ("'" + value + "'")
    #print(valuenew)
    #value2 = "'{0}'".format(value)
    print(value)
    c = twint.Config()
    c.Search = value
    c.Lang = "en"
    c.Pandas = True
    c.Near = "San Jose"
    c.Debug = True
    c.Hide_output = True
    twint.run.Search(c)    

    #twint.run.Search(c)
    #Datatframe 
    tf = twint.storage.panda.Tweets_df
    tf["searchString"] = value
    df.append(tf)

df = pd.concat(df)
```

**Comment by Poohi5** [comment]
I think it has nothing to do with the quotes. 
It was just that I did not append my results into a dataframe and the last term in my list had no tweets, that is the reason why I always got empty dataframe.

```
dataframe = []
    for value in tqdm(dfevents.name.values):
        print(value)
        c = twint.Config()
        c.Search = value
        c.Lang = "en"
        c.Popular_tweets = True
        c.Pandas = True
        c.Near = "San Jose"
        c.Debug = True
        c.Hide_output = True
        twint.run.Search(c) 
        

        #Save output in pandas dataframe
        try:
            df = twint_to_df(['date', 'username', 'tweet', 'hashtags', 'nlikes', 'link'])
        except (KeyboardInterrupt, SystemExit):
            raise
        except:
            print("No Tweets for this event")
        df["searchString"] = value
        dataframe.append(df)

    dataframe = pd.concat(dataframe)
```


This code worked for me. @xxristoskk
