### ISSUE TITLE
Cannot import name "SocksConnector"

### ISSUE THREAD

**Issue by TianshuangQiu** [twintproject/twint#833]
Code was completed and tested on my windows machine and ran smoothly. I tried porting it to Google Colab, but experienced this crash.
I have tried both `!pip install twint` and `!pip3 install --user --upgrade -e git+https://github.com/twintproject/twint.git@origin/master#egg=twint`
Both ended up with the error below.
I have found that this is a possible duplicate, but the solutions that fixed them do not appear to be working in my situation.

Google Colab runs Python 3.6 if that helps.
<img width="1393" alt="Screen Shot 2020-07-16 at 9 02 46 PM" src="https://user-images.githubusercontent.com/41294301/87738221-dfb88100-c7aa-11ea-851b-1f4d47d7b3ae.png">

**Comment by june1994** [comment]
Clone the repo.
Change the requirement as discussed previously

**Comment by TianshuangQiu** [comment]
https://github.com/TianshuangQiu

**Comment by TianshuangQiu** [comment]
`pip install --upgrade aiohttp_socks==0.4.1
`
Thank you for the help
