### ISSUE TITLE
Search banned profiles return nothing

### ISSUE THREAD

**Issue by Bl4Cc4t** [twintproject/twint#843]
- [x] Python version is 3.6;
- [x] Updated Twint with `pip3 install --user --upgrade -e git+https://github.com/twintproject/twint.git@origin/master#egg=twint`;
- [x] I have searched the issues and there are no duplicates of this issue/question/request.

### Command Ran
`twint -u MuffinMajima` (nsfw profile)

### Description of Issue
Search banned profiles do not return tweets anymore. This worked about a month ago (2020-06-30).
Checked with [shadowban.eu](https://shadowban.eu/MuffinMajima)

### Environment Details
Tested on macOS 10.13.6 and Debian WSLv1 @ Windows 10 v2004

**Comment by pielco11** [comment]
That's because Twitter does not return a thing
