### ISSUE TITLE
It was working until yesterday, but something else has been broken.

### ISSUE THREAD

**Issue by mikaelyh** [twintproject/twint#864]
https://github.com/twintproject/twint/issues/775  was working until yesterday, but something else has been broken.

**********************************************************************
From https://github.com/twintproject/twint/issues/775  

**change line 163 to :**
`r = await Request(url, headers={"X-Requested-With": "XMLHttpRequest"})`
(refer to #769 )

**change line 182 to :**
`response = await Request(url, headers={"X-Requested-With": "XMLHttpRequest"}, connector=_connector)`
(refer to #772 )

_Originally posted by @Cheryl520 in https://github.com/twintproject/twint/issues/775#issuecomment-637300558_

**Comment by andywalden** [comment]
https://github.com/twintproject/twint/issues/863
