### ISSUE TITLE
[REQUEST] Output a list of authors for a search

### ISSUE THREAD

**Issue by hudmb** [twintproject/twint#90]
For the search option it would also be super useful to have an option to output a list of de-duplicated authors for all the matching tweets (lowercase ideally) together with follower counts and any other stats about them you are able to obtain.

**Comment by haccer** [comment]
@hudmb Can you give me an example of how you would want this outputted?

**Comment by haccer** [comment]
Thanks for elaborating @hudmb 

That'd be easy to implement

**Comment by pielco11** [comment]
Hi @hudmb ,

it depends on how deep you want to go. 
Options:
- write a "post-processing" tool to load scraped tweets from saved files (not so good);
- store in RAM the authors of every tweet and filter them out (good way).

While the first case is quite easy, in the second case might not be. 

You could create a new function in `twint/output.py` that's called from `_output`, this would pass `obj` arg to your new function, and that stores in a global variable the `obj.username` attribute, then this new function would do some kind of remove-duplicate-authors. 

When the whole scraping process is done, call from `twint.run.Search` a function that writes to a file (unique for every search) your `unique_list_of_authors`

**Comment by pielco11** [comment]
## Usage
```python
import twint

c = twint.Config()
c.Search = "something here"

twint.run.Search(c)

author_list = twint.output.author_list
```
