### ISSUE TITLE
[BUG] crash - Twint silent exception due to using invalid parameter for aiohttp-socks ProxyConnector

### ISSUE THREAD

**Issue by lmeyerov** [twintproject/twint#913]
### Command Ran

`twint -u realDonaldTrump --user-full --proxy-type Socks5 --proxy-port 9050 --proxy-host localhost`

from https://github.com/twintproject/twint/issues/847 

### Environment

```
FROM python:3.7
RUN apt-get update \
    && apt-get install -y --no-install-recommends git vim tor \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

RUN pip install prefect==0.10.1 aiohttp==3.5.4 aiohttp_socks==0.4.1 simplejson twarc neo4j boto3==1.12.39 \
    pandas  pyarrow urlextract 
```

Test:

```
service tor start && twint -u realDonaldTrump --user-full --proxy-type Socks5 --proxy-port 9050 --proxy-host localhost
```

### Description of Issue

Twint's tor mode is broken due to incomplete fix https://github.com/twintproject/twint/commit/0871376b7fb8b69886decdaca402d646abb015be . It results in a failure due to passing the wrong arguments to aiohttp-socks's  new `ProxyConnector`.

The initial issue seems to be:

1. Twint's tor call `ProxyConnector(socks_ver=ProxyType.SOCKS5, ...`

https://github.com/twintproject/twint/blob/87b5b6637e47848e41d3cfbbebb8db9bc2f0d94a/twint/get.py#L54

2. Should instead be `ProxyConnector(proxy_type=ProxyType.SOCKS5, ...`

For reference, see their deprecated internal call:  https://github.com/romis2012/aiohttp-socks/blob/67821e3f9913129604c2b4cb216a2ea181e2e570/aiohttp_socks/_deprecated.py#L30

This *might* fix use of tor ( https://github.com/twintproject/twint/issues/847  ),  or at least one blocker for it

**Comment by lmeyerov** [comment]
+ @webcoderz

**Comment by lmeyerov** [comment]
Fixed: https://github.com/twintproject/twint/pull/914

Until upstream merge, you can do pip install git+https://github.com/lmeyerov/twint.git@patch-1#egg=twint`

**Comment by pielco11** [comment]
Just merged. My bad for not checking that.

Thanks

**Comment by LinqLover** [comment]
@lmeyerov Can you confirm that your setup still works for you? If I try to reproduce your configuration, twint gives me an error:

```
root@e1a60d3653e6:/# twint -u realDonaldTrump --user-full --proxy-type Socks5 --proxy-port 9050 --proxy-host localhost
CRITICAL:root:twint.get:User:'NoneType' object is not subscriptable
```
