### ISSUE TITLE
consistent sleeping for a long time and no response

### ISSUE THREAD

**Issue by Muhammad4hmed** [twintproject/twint#926]
I am trying to scrap using following 

```
import twint

# Configure
c = twint.Config()
c.Username = "realDonaldTrump"
c.Search = "great"

# Run
twint.run.Search(c)
```

but it keep outputting, 
sleeping for (seconds) seconds.

**Comment by akshaykalucha3** [comment]
Ref: https://github.com/twintproject/twint/issues/918#issuecomment-695807117

Maybe Twitter has deleted the https://twitter.com/i/search/timeline

twint is not the only Twitter scraper having the same problem. See: https://github.com/jonbakerfish/TweetScraper/issues/92
