### ISSUE TITLE
No data is being retrieved if geo config is set !!!

### ISSUE THREAD

**Issue by Manoj15** [twintproject/twint#947]
Below is the code ran : 

import twint
c = twint.Config()

c.Limit = 100
c.Search = "apple"
c.Store_json = True
c.Output = "tweets.json"
c.Geo = "36.055121,-119.01595,10mi"

twint.run.Search(c)

**Comment by Manoj15** [comment]
[](url)

**Comment by Manoj15** [comment]
#944

**Comment by Manoj15** [comment]
There is space issue in the string in "url.py" at Line 126. 
Please replace "q += f"{config.Search}"" with "q += f" {config.Search}"".
Its working perfectly now 💯

**Comment by himanshudabas** [comment]
> There is space issue in the string in "url.py" at Line 126.
> Please replace "q += f"{config.Search}"" with "q += f" {config.Search}"".

Thanks for letting me know. I've fixed this and will push a commit later today with some more fixes and functionality.
