### ISSUE TITLE
How to include number of like and number of comment in the output.

### ISSUE THREAD

**Issue by yangyangdotcom** [twintproject/twint#948]
This might be a dumb question but I really can't figure it out.

I am using Twint as a module but I can't get the number of comment and number of likes This is my code:

```
import twint
from datetime import timedelta, datetime
import time
import os
import json
import glob
import argparse
import logging as logme

c = twint.Config()

c.Search = "black army matter"
c.Limit = 50
c.Stats = True
c.Count = True
c.Lang = "en"
c.Output = "a.csv"
c.Format = True
t1 = time.time()
twint.run.Search(c)

obj = c.search_tweet_list
print(obj)

```

Please help!

**Comment by himanshudabas** [comment]
1. Format doesn't take a **_boolean_** value.
2. You didn't set `c.Store_csv = True` so the final output won't be saved to csv file.
3. I don't think there is something like `search_tweet_list` in _twint_.

try this :

`c = twint.Config()

c.Search = "black army matter"
c.Limit = 50
c.Stats = True
c.Count = True
c.Lang = "en"
c.Output = "a.csv"
c.Store_csv = True
twint.run.Search(c)`

This will create a file named **a.csv** in the directory where you run the script from. and you'll find all your tweets in that.

**Comment by yangyangdotcom** [comment]
Thanks for helping me! Really appreciate it! Once I run the script, where should I find the a.csv? Is it storing in the twint file? Because I can't find it. Thank you!

**Comment by himanshudabas** [comment]
You are running your python file (file which contains the above code) from terminal?
So whatever your terminal's current working directory is (i.e. the directory your terminal is opened in), you'll find your a.csv file there.
So if your terminal says c:/users , you'll find a.csv in c:/users

**Comment by yangyangdotcom** [comment]
Thanks a lot!

**Comment by kristoDev** [comment]
> Thanks a lot!

Hello, did you manage to figure out a way to get the number of likes and comments in the output?
