### ISSUE TITLE
[Question] Can't get user information

### ISSUE THREAD

**Issue by edmangog** [twintproject/twint#970]
### Initial Check

- [] Python version is 3.8.3;
- [] Updated Twint with `pip3 install --user --upgrade -e git+https://github.com/twintproject/twint.git@origin/master#egg=twint`;
- [] I have searched the issues and there are no duplicates of this issue/question/request.

### Command Ran
```
import twint
c = twint.Config()
c.Username = "realDonaldTrump"
c.Custom["user"] = ["id", "username"]
c.Output = "username.csv"
c.Store_csv = True

twint.run.Lookup(c)
```

### Description of Issue
I try to scrape specific user information and follow the code in user attribute in [wiki](https://github.com/twintproject/twint/wiki/User-attributes). But I got the following errors:

> ERROR:root:twint.run:Lookup:Unexpected exception occured.
> Traceback (most recent call last):
>   File "c:\users\user\src\twint\twint\run.py", line 393, in Lookup
>     get_event_loop().run_until_complete(get.User(url, config, db.Conn(config.Database)))
> TypeError: User() missing 2 required positional arguments: 'bearer_token' and 'guest_token'
> Traceback (most recent call last):
>   File "C:/Users/user/Desktop/project/SN0-0.py", line 9, in <module>
>     twint.run.Lookup(c)
>   File "c:\users\user\src\twint\twint\run.py", line 393, in Lookup
>     get_event_loop().run_until_complete(get.User(url, config, db.Conn(config.Database)))
> TypeError: User() missing 2 required positional arguments: 'bearer_token' and 'guest_token'

### Environment Details
>Occurred in Terminal and PyCharm 2020.1.2

**Command in Terminal:**
> C:\Users\user\AppData\Local\Programs\Python\Python38\Scripts>twint -u "realDonaldTrump" --user-full

**Comment by AiswaryaSrinivas** [comment]
Facing this same issue.

**Comment by elig0n** [comment]
same with --user-full

**Comment by mesutgurlek** [comment]
+1 same issue

**Comment by alirezaafzalaghaei** [comment]
I solved the problem by adding `bearer_token` and `guest_token` arguments to line 393 of the `run.py` file but the problem will occur in other lines. The `bearer_token` should be defined in the Config variable `c`, but it was set to None by default. Unfortunately, there is no documentation that explains what does this variable means. There is only a global `bearer` variable in the `run.py` which can be used. 

The second problem is the `guest_token` variable which is not defined anywhere in the codes. By analyzing the project, I found we should use the `token.py` file to get a guest token. So the test example should be like

```
c = twint.Config()
twint.token.Token(c).refresh()
c.Bearer_token= twint.run.bearer
c.Username = 'myusername'
c.Custom["user"] = ["id", "username"]
c.Output = "username.csv"
c.Store_csv = True
twint.run.Lookup(c)
```
By running this code you will get an error on 19 of the `user.py` file. Because the function is recursively called without necessary argument. I think this is not a recursive function and the user class in the `_usr = User()`, is a container for the retrieved user info, as the `User` class is defined in the 5th line of the file. So, I changed the function name to `UserM` and also edited the name of this function in the `output.py` file (lines 5 and 186).  Also, in line 15 of the `user.py` file you should change `and` operator to `or`.

After doing these changes, I ran the example and get:
```
KeyError: 'malformed json! cannot be parsed to get user data'
```
because the `ur` variable which passed to the `UserM` function is:

```
{'data': {}, 'errors': [{'message': 'Not found', 'path': ['user'], 'locations': [{'line': 126, 'column': 3}], 'source': 'Server', 'code': 50, 'kind': 'NonFatal', 'extensions': {'source': 'Server', 'code': 50, 'kind': 'NonFatal'}}]}
```

I think this is because of Twitter changes and project contributors should update the project...

**Comment by seonake** [comment]
Same issue :(

**Comment by micaelamaria** [comment]
Hi! I am facing the same issue (kubuntu 20.4) - it works just fine on my mac though

**Comment by micaelamaria** [comment]
Does anyone know what the guest token refers to?

**Comment by himanshudabas** [comment]
Yeah,
Guest Token is required to make requests to `Twitter`.
It hasn't been implemented in `Lookup` yet,
So try to use `Search` instead for now.
_Lookuo_ is broken right now.
I might fix it later. But I am a bit occupied at the moment.

**Comment by seonake** [comment]
Ok, but Seach can not be used for the same purpose I think.
How can I check account location for example?

**Comment by himanshudabas** [comment]
@seonake 
yes, you are right. `Search` cannot be used in stead of `Lookup`.

I had some free time, so I put up a fix for this issue.
Try installing from my [master branch](https://github.com/himanshudabas/twint) and let me know if your issue gets resolved.

Note: Some things might still be broken, or perhaps some new things might have broken. Bear with me a little, I'll try to fix things as soon as I can. :)

**Comment by micaelamaria** [comment]
Following up on this one, now there is a new error indeed: KeyError: 'url'

**Comment by himanshudabas** [comment]
@micaelamaria 
Could you share the script you ran & the entire error that you got?

**Comment by micaelamaria** [comment]
@himanshudabas  yes!! I paste it below

mik@prisma-ds:~$ twint -u MaraRoller2 --user-full
CRITICAL:root:twint.get:User:'url'
ERROR:root:twint.run:Twint:Lookup:Unexpected exception occurred.
Traceback (most recent call last):
  File "/home/mik/.local/lib/python3.8/site-packages/twint/run.py", line 307, in Lookup
    await get.User(self.config.Username, self.config, db.Conn(self.config.Database))
  File "/home/mik/.local/lib/python3.8/site-packages/twint/get.py", line 228, in User
    await Users(j_r, config, conn)
  File "/home/mik/.local/lib/python3.8/site-packages/twint/output.py", line 177, in Users
    user = User(u)
  File "/home/mik/.local/lib/python3.8/site-packages/twint/user.py", line 31, in User
    _usr.url = ur['data']['user']['legacy']['url']
KeyError: 'url'
Traceback (most recent call last):
  File "/home/mik/.local/bin/twint", line 8, in <module>
    sys.exit(run_as_command())
  File "/home/mik/.local/lib/python3.8/site-packages/twint/cli.py", line 339, in run_as_command
    main()
  File "/home/mik/.local/lib/python3.8/site-packages/twint/cli.py", line 326, in main
    run.Lookup(c)
  File "/home/mik/.local/lib/python3.8/site-packages/twint/run.py", line 386, in Lookup
    run(config)
  File "/home/mik/.local/lib/python3.8/site-packages/twint/run.py", line 329, in run
    get_event_loop().run_until_complete(Twint(config).main(callback))
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/mik/.local/lib/python3.8/site-packages/twint/run.py", line 235, in main
    await task
  File "/home/mik/.local/lib/python3.8/site-packages/twint/run.py", line 270, in run
    await self.Lookup()
  File "/home/mik/.local/lib/python3.8/site-packages/twint/run.py", line 307, in Lookup
    await get.User(self.config.Username, self.config, db.Conn(self.config.Database))
  File "/home/mik/.local/lib/python3.8/site-packages/twint/get.py", line 228, in User
    await Users(j_r, config, conn)
  File "/home/mik/.local/lib/python3.8/site-packages/twint/output.py", line 177, in Users
    user = User(u)
  File "/home/mik/.local/lib/python3.8/site-packages/twint/user.py", line 31, in User
    _usr.url = ur['data']['user']['legacy']['url']
KeyError: 'url'

**Comment by micaelamaria** [comment]
@himanshudabas have you been able to look at this one?> Just asking in case I should openanother thread!
