### ISSUE TITLE
[Error]CRITICAL:root:twint.run:Twint:Feed:noData'tweet'

### ISSUE THREAD

**Issue by babysbreathElin** [twintproject/twint#997]
# Issue Template
Please use this template!

### Initial Check
> If the issue is a request please specify that it is a request in the title (Example: [REQUEST] more features). If this is a question regarding 'twint' please specify that it's a question in the title (Example: [QUESTION] What is x?). Please **only** submit issues related to 'twint'. Thanks.

>Make sure you've checked the following:

- [] Python version is 3.6;
- [] Updated Twint with `pip3 install --user --upgrade -e git+https://github.com/twintproject/twint.git@origin/master#egg=twint`;
- [] I have searched the issues and there are no duplicates of this issue/question/request.

### Command Ran
>Please provide the _exact_ command ran including the username/search/code so I may reproduce the issue.
c = twint.Config()
c.Username = 'realDonaldTrump'
twint.run.Search(c)

### Description of Issue
>Please use **as much detail as possible.**
CRITICAL:root:twint.run:Twint:Feed:noData'tweet'
sleeping for 1.0 secs
CRITICAL:root:twint.run:Twint:Feed:noData'tweet'
sleeping for 8.0 secs
CRITICAL:root:twint.run:Twint:Feed:noData'tweet'
sleeping for 27.0 secs
CRITICAL:root:twint.run:Twint:Feed:noData'tweet'
sleeping for 64.0 secs
CRITICAL:root:twint.run:Twint:Feed:noData'tweet'
sleeping for 125.0 secs
CRITICAL:root:twint.run:Twint:Feed:noData'tweet'
sleeping for 216.0 secs
CRITICAL:root:twint.run:Twint:Feed:noData'tweet'
sleeping for 343.0 secs
CRITICAL:root:twint.run:Twint:Feed:noData'tweet'
sleeping for 512.0 secs
CRITICAL:root:twint.run:Twint:Feed:noData'tweet'
sleeping for 729.0 secs
CRITICAL:root:twint.run:Twint:Feed:noData'tweet'
CRITICAL:root:twint.run:Twint:Feed:Tweets_known_error:'tweet'
'tweet' [x] run.Feed[!] if get this error but you know for sure that more tweets exist, please open an issue and we will investigate it!

### Environment Details
>Windows 10 Python3.7.0

**Comment by rohanrajpal** [comment]
facing the same issue

**Comment by coreyryanhanson** [comment]
It might be related to this:
https://github.com/twintproject/twint/issues/992

Does your search url look like it has no spaces between the username and the search term?

**Comment by babysbreathElin** [comment]
> It might be related to this:
> #992
> 
> Does your search url look like it has no spaces between the username and the search term?

Thanks for your reply. But may have nothing to do with spaces. As I described above, I do not use other configurations except Username. And I also ran this code and got many users' tweets successfully.

**Comment by himanshudabas** [comment]
I've put up a patch for this in my [master branch](https://github.com/himanshudabas/twint).
@babysbreathElin @rohanrajpal try installing from my branch and see if your issue is resolved.

@coreyryanhanson It's actually a different issue and not related to _spaces_.
you can find more details about it's cause [here](https://github.com/himanshudabas/twint/commit/1309820ff306d53491e3ee762f03f9c534624d4b).

**Comment by babysbreathElin** [comment]
> I've put up a patch for this in my [master branch](https://github.com/himanshudabas/twint).
> @babysbreathElin @rohanrajpal try installing from my branch and see if your issue is resolved.
> 
> @coreyryanhanson It's actually a different issue and not related to _spaces_.
> you can find more details about it's cause [here](https://github.com/himanshudabas/twint/commit/1309820ff306d53491e3ee762f03f9c534624d4b).

It works for me. Thank you so much!

**Comment by Luna0815** [comment]
how do you solve the problem? I have the same one too.
